### ISSUE TITLE
Window fill not shrinking on vertical

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#1008]
Dim.Fill for Windows Height works for expansion of the Window but not for contraction. This can be seen in the example program as well. 

![fill](https://user-images.githubusercontent.com/1786698/99196627-99c0f900-275b-11eb-9f70-d5d954ca969f.gif)

My program doesn't have any text at the bottom but the same thing is happening.

**Comment by BDisp** [comment]
That is limitation on `WindowsDriver`. It would be great if there are any resolution for that.

**Comment by tig** [comment]
Dupe of #335
