### ISSUE TITLE
Parameterless constructors

### ISSUE THREAD

**Issue by MihaMarkic** [migueldeicaza/gui.cs#102]
Can we have parameterless constructors?

**Comment by migueldeicaza** [comment]
Sure, it is a matter of time and fixing.

**Comment by Slesa** [comment]
So should the controls and views be converted into fluent interfaces?

**Comment by tig** [comment]
I definitely want to get rid of all constructors with parameters. Been making some progress.

I think fluent interfaces are neat too. But I'd make that a separate topic.
