### ISSUE TITLE
GridView like control

### ISSUE THREAD

**Issue by tsgiannis** [migueldeicaza/gui.cs#1023]
Hello to everybody,
I must say ...wow..great toolkit...
I would like to ask if there is some kind of thought implementing a gridiview like control to present data.
If this is not possible is it possible to somehow embedd a table like BetterConsoleTables :https://github.com/douglasg14b/BetterConsoleTables
maybe embedded in a panel or something similar.
I am seeing a lot about tabular data so should we expect something like this

**Comment by BDisp** [comment]
See this PR #1015

**Comment by tsgiannis** [comment]
Ok thanks

**Comment by migueldeicaza** [comment]
Closing as there is a PR in progress that does that
