### ISSUE TITLE
Pass the information about whether the view is focused to the method Render of ListView

### ISSUE THREAD

**Issue by Matihood1** [migueldeicaza/gui.cs#1032]
I tried to make a ListView where different items were displayed in different colors, using a class that inherits the IListDataSource interface. Everything works great, except for the fact that I don't have access to the bool that keeps the information about whether the view is currently focused or not and so I can't modify how elements are displayed when the ListView isn't focused.

It would be great if that bool was passed to the method Render so that it could be used when inheriting IListDataSource.

**Comment by BDisp** [comment]
The `SelectedItem `property is the current item selected. It isn't enough? Otherwise can you share a little example about what you are need to achieve, please.

**Comment by Matihood1** [comment]
I was trying to achieve a similiar effect to how the `Redraw` method sets the color:
`var newcolor = focused ? (isSelected ? ColorScheme.Focus : ColorScheme.Normal) : (isSelected ? ColorScheme.HotNormal : ColorScheme.Normal);`
Unfortunately, the `Render` method in `IListDataSource` doesn't receive the `focused` variable and I can't get the desired effect without it.

**Comment by BDisp** [comment]
But you can check if it's focused through the `ListView container` parameter of the `Render `method, like this way:
`var focused = container.HasFocus;`

**Comment by Matihood1** [comment]
Oh yea, you are right... I somehow completely missed the `container` parameter. My bad. Issue solved.
