### ISSUE TITLE
CJK chars display as ▯▯▯▯▯

### ISSUE THREAD

**Issue by qdwang** [migueldeicaza/gui.cs#1039]
Lastest Terminal.Gui with .NET 5 in Windows 10.

<img width="209" alt="1" src="https://user-images.githubusercontent.com/403616/102166004-a81f4380-3ec6-11eb-8fd5-4f84b1736ce1.png">
<img width="89" alt="2" src="https://user-images.githubusercontent.com/403616/102166035-a9e90700-3ec6-11eb-87c7-818e2446071b.png">

**Comment by BDisp** [comment]
What font type you are using?

**Comment by qdwang** [comment]
@BDisp I've tried all kinds of fonts(both fonts with only western chars and fonts with cjk chars).  And I've tired to use `chcp` to change the code page to 437(us), 936(chinese) or 45001(utf-8).  None of them works.

**Comment by tznind** [comment]
Have you tried creating a text file with those characters in it and printing it to the console with a normal dos/ps command?

**Comment by qdwang** [comment]
@tznind Adding `Console.WriteLine("テスト");` to the program can correctly display the chars in terminal after exiting the gui.

**Comment by BDisp** [comment]
@tznind of course you can. You need to deal with the `Rune.ColumnWidth` to check if the char occupies two columns and consider it as only one column, on the Redraw method. See what I did in the `TextField`.  But I was talking about only change the `Attribute `color when you print the '+' char :-)

**Comment by BDisp** [comment]
@qdwang you have to change the console to support unicode 65001 (UTF-8) in the regional settings.

**Comment by qdwang** [comment]
@BDisp 

yeah, I've done that.  

"Beta: Use Unicode UTF-8 for worldwide language support" checked.

**Comment by BDisp** [comment]
What driver are you using, `WindowsDriver`, `CursesDriver `or `NetDriver`?

**Comment by qdwang** [comment]
`WindowsDriver`, how can I the driver?

**Comment by BDisp** [comment]
If you are running with the `Application.UseSystemConsole = true` then the app is using the `NetDriver `on all `SO`.
If you are running with the `Application.UseSystemConsole = false` then the app is using the `WindowsDriver `if you are running on a `Windows 10 OS` or using the `CursesDriver `if you are running on a `Linux `or `macOS` `OS`.

**Comment by BDisp** [comment]
And of course you have to use a font type that supports CJK, like KaiTi.

With `Application.UseSystemConsole = true`:
![usc-true](https://user-images.githubusercontent.com/13117724/102238864-28a56a80-3eee-11eb-8ade-29f7e9c626ed.png)

With `Application.UseSystemConsole = false`:
![usc-false](https://user-images.githubusercontent.com/13117724/102238888-2e9b4b80-3eee-11eb-8040-7837b1c828c9.png)

**Comment by qdwang** [comment]
Thanks, but the issue still happens on my both desktop pc and laptop.

**Comment by BDisp** [comment]
Did you try with the` GUI Example` project only replacing the `File `menu with chinese characters and I thing you already have the chinese language installed, of course. If it doesn't work to you, then I have no idea what is going on.

**Comment by qdwang** [comment]
Good news. The package in `master` branch works fine with displaying CJK fonts. 
It seems the issue comes from the nuget version `0.90.3`

**Comment by migueldeicaza** [comment]
Closing the bug then
