### ISSUE TITLE
Application.CurrentView looks unused

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#1052]
The `Application.CurrentView` looks like it was used at some point, but does not seem to serve any purpose anymore.

**Comment by BDisp** [comment]
Yes you are right. It not needed anymore.

**Comment by tig** [comment]
How do you know it's unused? How do you know no client app has used it and depends on it?

We committed to have a very high bar for breaking API changes. If you are confident nobody has used this API then let's delete it. But if we don't know, then we should do something else (e.g. change the API documentation to state it's deprecated and will be removed in a future version, but leave it in place).

**Comment by BDisp** [comment]
I know because was me who created it to deal with `AddRune `in the `ConsoleDriver `but with your solution with the clipped region it was not needed anymore.
