### ISSUE TITLE
Support for ScrollBars on TextView for large results

### ISSUE THREAD

**Issue by dynamoRando** [migueldeicaza/gui.cs#1058]
In reference to [this ](https://github.com/migueldeicaza/gui.cs/discussions/1049)discussion, I am filing a request to have Textview support scrollbars for very large results that are outside the area/window.

Please let me know if there are any additional details I should provide in this issue.

**Comment by tig** [comment]
Fixed with https://github.com/migueldeicaza/gui.cs/pull/1081
