### ISSUE TITLE
ComputerLayout scenario does not drawn correctly.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1061]
The `X` and `Y` computed settings are not also respected on dragging.

![computed-layout](https://user-images.githubusercontent.com/13117724/103182414-f9eea300-48a2-11eb-9a6a-affd7096dce8.gif)

**Comment by tig** [comment]
I think another of your recent PRs broke clipping again.

**Comment by BDisp** [comment]
The `Toplevel `redraw method always redraws his subviews, even not necessary. After I submit a long time a PR to fix it, naturally breaked that but that changes are alwright. In this case is a `Window `with another `Window `inside, as subview and so the `Window` `Redraw` method must handle that. It really redrawns but it was not cleaning the `LayoutNeeded`.
About the dragging I only handled the `Width `and `Height `settings and forgot to handle the `X` and `Y` settings.
