### ISSUE TITLE
UI Catalog is not filling console (at least on Windows)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1065]
VS 2019 debug:
![image](https://user-images.githubusercontent.com/585482/103229943-fbdb5500-48e8-11eb-8452-e389cd956784.png)

Cmd.exe
![image](https://user-images.githubusercontent.com/585482/103229853-ca628980-48e8-11eb-9104-eaaaff418886.png)

conemu:
![image](https://user-images.githubusercontent.com/585482/103229990-17466000-48e9-11eb-99c8-0e76ac843f60.png)

Windows Terminal:
(hangs)

**Comment by BDisp** [comment]
In `cmd.exe` and `ConEmu `I confirm. The strange thing is happening to you in the VS 2019 debug which is the one I use the most and in my is filling well. What code page do you use? I use 65001 (UTF-8). Unfortunately, WindowPlacement does not have column and row dimensions and I have to make the conversion. The others consoles may being calculating other dimensions values.
Maybe is better using Application.HeightAsBuffer=true as default?

**Comment by tig** [comment]
I haven't run a new build in a while. This used to work fine. We need to figure out what broke and revert it.

The worst part is the app doesn't show at all under Windows Terminal. 

![](https://i.imgur.com/AH5cNy3.gif)

**Comment by tig** [comment]
I'm really confused now. Why did you change things so the system console was not default?

I just saw this code 

![image](https://user-images.githubusercontent.com/585482/103246550-b898da80-4918-11eb-8a87-f946fa3203e2.png)

If I run UICatalog with -usc It works fine AND *MOUSE WORKS*!
![](https://i.imgur.com/hfNVX6k.gif)

**Comment by tig** [comment]
Now I can't get the incorrect size thing to reproduce. Ugh.

**Comment by BDisp** [comment]
I didn't make the use system console as default because it works slower than `WindowsDriver `and `CursesDriver`, but at least the `NetDriver `works better on others consoles with exception on ConEmu.

**Comment by BDisp** [comment]
@tig if you use the arg -usc it use the `NetDriver `on all SO and the mouse works like on the Linux using sequence escapes.

**Comment by tig** [comment]
> I didn't make the use system console as default because it works slower than `WindowsDriver `and `CursesDriver`, but at least the `NetDriver `works better on others consoles with exception on ConEmu.

I confused myself. Nevermind. I was thinking System Console == WindowsDriver/CursesDriver.

It is confusing that `Application.UseSystemConsole` is named as it is. Because the driver that gets selected is `NetDriver`. 

Regardless, it seems to be sometime recently WindowsDrivder got seriously broken.

**Comment by BDisp** [comment]
> Regardless, it seems to be sometime recently WindowsDrivder got seriously broken.

Yes I think the calculation is made incorrect, but on the `VS 2019` debug console it filling fine on my PC.

**Comment by BDisp** [comment]
> It is confusing that `Application.UseSystemConsole` is named as it is. Because the driver that gets selected is `NetDriver`.

Yes you are right. I think it should named like `Application.UseNetDriver`.

**Comment by tig** [comment]
Very weird.

Even if I change `demo.cs` to not use system console, it fills screen correctly. But `UICatalog` does not:
![image](https://user-images.githubusercontent.com/585482/103247514-fea36d80-491b-11eb-9db4-2af2de9f9ab2.png)

![image](https://user-images.githubusercontent.com/585482/103247532-12e76a80-491c-11eb-8d78-9be88ad73029.png)

**Comment by tig** [comment]
Vertical is always wrong. Depending on the font, horizontal is sometimes correct. 

It does this in `VS 2019` and in `cmd.exe`.
![image](https://user-images.githubusercontent.com/585482/103247725-c3ee0500-491c-11eb-88d3-532316f86bc7.png)

**Comment by BDisp** [comment]
I would like that my `VS 2019` debugger to have the same console as your. Did you some specific configuration?

VS 2019:
![vs2019](https://user-images.githubusercontent.com/13117724/103248318-100f6880-4962-11eb-9445-0192eb09fb2f.png)

cmd.exe:
![cmd](https://user-images.githubusercontent.com/13117724/103248330-17367680-4962-11eb-960c-ffdcefd9221a.png)

**Comment by BDisp** [comment]
@tig I already figured out the weird behaviour why on my `VS 2019` was filling right. In `VS 2019` the `Consolas `font size is 17 and in the `cmd.exe` is 16. So, the solution to fix this is take on account the font size to calculate the correct `Cols `and `Rows `size. That is not very easy and any help would be welcome.

**Comment by BDisp** [comment]
> 
> 
> > It is confusing that `Application.UseSystemConsole` is named as it is. Because the driver that gets selected is `NetDriver`.
> 
> Yes you are right. I think it should named like `Application.UseNetDriver`.

I take back what I said and really the named `Application.UseSystemConsole` is a good choice, because it meaning that is using the `System.Console` from the `dotnet API` and not the system console of the `OS` (Operating System).

**Comment by tig** [comment]
Fiexed.
