### ISSUE TITLE
[PowerShell] Object initialiser does not work for Label but does for Window

### ISSUE THREAD

**Issue by mrboring** [migueldeicaza/gui.cs#1067]
Hi

I'm investigating Terminal.Gui in PowerShell. I found that I can create a `Label` using the constructor, but not using object initialisation. I get no errors, but the label is not displayed. However, object initialisation works for `Window`. What am I doing wrong?

Sample code (please excuse the quality, it's my first attempt):

```PowerShell
using namespace Terminal.Gui

Add-Type -Path 'C:\Users\<removed>\.nuget\packages\terminal.gui\1.0.0-pre.99.1\lib\net5.0\Terminal.Gui.dll'
Add-Type -Path 'C:\Users\<removed>\.nuget\packages\nstack.core\0.16.0\lib\netstandard2.0\NStack.dll'

[Application]::Init()

$top = [Application]::Top

# This object initialiser works for Window
$mainWindow = [Window] @{
    Title  = 'Testing'
    X      = 0
    Y      = 1
    Width  = [Dim]::Fill()
    Height = [Dim]::Fill()
}

$top.Add($mainWindow)

# Using the constructor works. Label is displayed
$testLabel1 = [Label]::new(0, 0, 'Test1')

# Using object initialiser does not work for Label
# No errors, but the label is not displayed
$testLabel2 = [Label] @{
    X    = 0
    Y    = 1
    Text = 'Test2'
}

$mainWindow.Add($testLabel1)
$mainWindow.Add($testLabel2)

$menu1 = [MenuBar]::new(
    @(
        [MenuBarItem] @{
            Title    = '_File'
            Children = @(
                [MenuItem] @{
                    Title  = '_Quit'
                    Action = {[Application]::RequestStop()}
                }
            )
        }
    )
)

$top.Add($menu1)

[Application]::Run()
[Application]::Shutdown()
```

**Comment by BDisp** [comment]
That is already fixed. Try the last version on master.

**Comment by mrboring** [comment]
Not sure if this was what you were suggesting, but this is what I did:

1. Cloned master 
2. Built it using `dotnet build -c Release`. 
3. In the sample code above, updated the `Add-Type` to point at the newly built `bin\Release\net5.0\Terminal.Gui.dll`.
4. Ran the sample code.

I got a blank screen. If I comment out the last two lines (`[Application]::Run()` and `[Application]::Shutdown()`) and run it, I get this error:

```PowerShell
Line |
  36 |  $menu1 = [MenuBar]::new(
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert the "System.Collections.Hashtable" value of type "System.Collections.Hashtable" to type "Terminal.Gui.MenuItem".
```

This is slightly misleading as the error is on line 41: `[MenuItem @{`

This looks like the object initialiser on `MenuItem` isn't working now (it did with the original dll). I used a constructor and did not get an error. However, regardless of the menu, I'm only getting a blank screen now.

Any ideas on what I'm doing wrong?

**Comment by BDisp** [comment]
I have a project with the `ps1` files and configured to "`Copy if newer`". In the `Debug `or `Release `folder where is the `Terminal.Gui.dll` I run the ps1 file. I can run and see the label's text. At the begin of the file I write the following:
```
using namespace Terminal.Gui
import-module .\Terminal.Gui.dll
```
I also having the same error as you on the `MenuItem`:
`Cannot convert the "System.Collections.Hashtable" value of type "System.Collections.Hashtable" to type "Terminal.Gui.MenuItem".`
I don't know why.

**Comment by mrboring** [comment]
If I replace:

```PowerShell
# Object initialiser
[MenuItem] @{
    Title  = '_Quit'
    Action = {[Application]::RequestStop()}
}
```

With:

```PowerShell
# Constructor
[MenuItem]::new('_Quit', '', {[Application]::RequestStop()})
```

I don't get an error. That's why I think it's related to object initialisation. 

But, as I said, nothing is displayed. 

If I revert back to using:

`C:\Users\<removed>\.nuget\packages\terminal.gui\1.0.0-pre.99.1\lib\net5.0\Terminal.Gui.dll`

Everything, apart from `$testLabel2` is displayed OK, and I get no errors.

![image](https://user-images.githubusercontent.com/5991977/103308986-bebbb380-4a0b-11eb-81ca-7b0965494ae9.png)

**Comment by BDisp** [comment]
Ah ok I get it. In the "`Windows Terminal`" is not displaying nothing and I don't know why. But try with PowerShell 7 and you'll see it work. There is something that I've not already discover why that not working on the `Windows Terminal` and it could be also a WT issue.
![powershell7](https://user-images.githubusercontent.com/13117724/103309755-d7c56400-4a0d-11eb-9f46-86bb6419bc0a.png)

**Comment by mrboring** [comment]
`PowerShell 7` and latest master works:

![image](https://user-images.githubusercontent.com/5991977/103310130-c92b7c80-4a0e-11eb-9df8-03721c82075a.png)

Hopefully there is a solution to it working in `Windows Terminal`.

**Comment by BDisp** [comment]
If you figure out about the menu please share.

**Comment by BDisp** [comment]
I only could make it working with this code:

```
$menu1 = [MenuBar]::new(
    @(
        [MenuBarItem]::new('_File',
            @(
                [MenuItem]::new('_Quit', '',
                    {[Application]::RequestStop()}
                )
            )
        )
    )
)

```
![powershell-menu](https://user-images.githubusercontent.com/13117724/103313658-a8682480-4a18-11eb-9320-fc70272f66cb.png)

If you don't need this issue open anymore, please close it. Thanks.
