### ISSUE TITLE
Toplevel.GetTopLevelSubviews ()

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#1071]
This method is intended to return a list in the order it was found (I am guessing from the requirement to get an "isForward") parameter.   This is called during the focus processing systems, and if the value is true, the items are reversed.

HashSet does not seem to guarantee the order in which the elements were added.

Pinging, as this was part of a bug fix, and not sure what the intent was, but this does look strange

**Comment by BDisp** [comment]
This method is used on two cases in the `Toplevel.ProcessKey` method:
- One on the `Key.Tab` and if it wasn't found any focused view then it will search forwards for the next subview for a focused view.
- Another on the `Key.BackTab` and if it wasn't found any focused view then it will search backwards for the prevoiw subview for a focused view.

So I think it do the actions which it need to do.

**Comment by migueldeicaza** [comment]
Yes, I agree that those actions need to take place

But today the data is being collected into a "HashSet", which does not guarantee the order in which the data was added is the order in which it will be returned.   So the return value is random, and reverse-random, rather than the order in which they were added, or the reverse order in which they were added :-)

**Comment by BDisp** [comment]
Ok I know what you mean. I thook after I implemented the `TabIndex` this would not be a problem, but you are right. I'll change to an `IList<View>`.
