### ISSUE TITLE
[PowerShell] Problem with ScrollView and keyboard navigation

### ISSUE THREAD

**Issue by mrboring** [migueldeicaza/gui.cs#1073]
Hi

Environment:

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I want the window (and sub-components) to be resizable. So, widths and heights are set to `[Dim]::Fill()`. `ScrollView.ContentSize` is set to: longest line length, total number of lines. I did this after reading [Question: ScollViewer ContentSize / Width / Height confusion](https://github.com/migueldeicaza/gui.cs/issues/859).

Eventually there will be two side-by-side FrameViews. 

I'm having the following issues:

* When I run the script the cursor is at the beginning of line 0. This is as expected.

* If I press `Page Down` the cursor is placed at the bottom of `mainWindow`. I expected it to be on line 17.

* Pressing the `Up Arrow` does nothing. `Page Up` takes me back to line 0.

* Pressing `End` puts the cursor at the right of the `mainWindow`. I expected it to scroll the line within the `scrollView`.

* Though keyboard navigation is not working as expected, mouse navigation using the scroll bars is working OK. With the exception that the cursor can end up outside the `scrollView`. 

*  Finally, a question: How do I make `ScrollView.ContentSize` resizable based on the `FrameView` it is inside of?

Here's a video of the issues:

![ScrollView](https://user-images.githubusercontent.com/5991977/103547764-bdbbd380-4e9c-11eb-8626-e9ab39eaa582.gif)

Here's the code I'm using:

```PowerShell
using namespace Terminal.Gui

# Latest release version
# Add-Type -Path 'C:\Users\<remove>\.nuget\packages\terminal.gui\1.0.0-pre.99.1\lib\net5.0\Terminal.Gui.dll'

# Latest pull of master
Add-Type -Path 'C:\Data\CSharp\gui.cs\Terminal.Gui\bin\Release\net5.0\Terminal.Gui.dll'

Add-Type -Path 'C:\Users\<remove>\.nuget\packages\nstack.core\0.16.0\lib\netstandard2.0\NStack.dll'

$host.ui.RawUI.WindowTitle = 'Testing ScrollView'

$stringBuilder = [System.Text.StringBuilder]::new()

for ($i = 0; $i -lt 150; $i++) {
    $line = ('dummy ' * 10).Trim()
    $null = $stringBuilder.Append("Line: $i - $line`r`n")
}

$text = $stringBuilder.ToString()
$textLongestLine = ($text -split "`r`n" | Measure-Object -Property Length -Maximum).Maximum

[Application]::Init()

$top = [Application]::Top

$mainWindow = [Window] @{
    X      = 0
    Y      = 0
    Width  = [Dim]::Fill()
    Height = [Dim]::Fill()
}

$frameView = [FrameView] @{
    X      = [Pos]::Center()
    Y      = 0
    Width  = 30
    Height = [Dim]::Fill()
}

$scrollView = [ScrollView] @{
    KeepContentAlwaysInViewport   = $true
    ShowVerticalScrollIndicator   = $true
    ShowHorizontalScrollIndicator = $true
    ContentSize                   = [Size]::new($textLongestLine, 150)
    X                             = 0
    Y                             = 0
    Width                         = [Dim]::Fill()
    Height                        = [Dim]::Fill()
}

$textView = [TextView] @{
    Text   = $text
    Width  = [Dim]::Fill()
    Height = [Dim]::Fill()
}

$scrollView.Add($textView)
$frameView.Add($scrollView)
$top.Add($mainWindow)
$mainWindow.Add($frameView)

[Application]::Run()
[Application]::Shutdown()
```

**Comment by BDisp** [comment]
The `TextView `should be:

```
$textView = [TextView] @{
    Text   = $text
    Width  = $textLongestLine
    Height = 150
}

```
Since the `PageDown `and `PageUp `is related to the height and it is 150 it going to the last item. You must override the textView `ProcessKey `method to only move the scrollView frame height and updating the` ScrollView.ContentOffset` for both, vertical and horizontal. The `ScrollView.ContentSize` is already set. It isn't an easy thing to do. You'll need a hard job to get it working.

**Comment by mrboring** [comment]
> The TextView should be:

```
$textView = [TextView] @{
    Text   = $text
    Width  = $textLongestLine
    Height = 150
}
```

Trying the above resulted in this exception:

```PowerShell
InvalidArgument: C:\Data\PowerShell\Miscellaneous\Issues\Terminal.Gui\ScrollView problem\ScrollView problem.ps1:55
Line |
  55 |  $textView = [TextView] @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot create object of type "Terminal.Gui.TextView". Cannot convert the "71"
     | value of type "System.Double" to type "Terminal.Gui.Dim".
```

> Since the PageDown and PageUp is related to the height and it is 150 it going to the last item. You must override the textView ProcessKey method to only move the scrollView frame height and updating the ScrollView.ContentOffset for both, vertical and horizontal. The ScrollView.ContentSize is already set. It isn't an easy thing to do. You'll need a hard job to get it working.

It looks like `ScrollView` does support `Computed Layout`, but `ScrollView.ContentSize` doesn't. Does this not mean that, effectively, `ScrollView` does not really support `Computed Layout`?

**Comment by BDisp** [comment]
Sorry, I made a test `C#` parallel testing and I didn't test in the `ps1` file. Like `F#` we can't assign a variable to a `Dim `object directly and we have to use the `Sized `method.

```
$textView = [TextView] @{
    Text   = $text
    Width  = [Dim]::Sized($textLongestLine)
    Height = 150
}

```
`ScrollView `does really support `Computed Layout`. You need to understand how `ScrollView `work. Firstly, you don't need to use a `ScrollView `to work with a `TextView `because it already deal with scrolling. If you insist using you have to derive from a `TextView `and override the `ProcessKey `to change the behavior of the `PageDown `and `PageUp `to scroll only the `ScrollView `height.

Here an image how both work together. As you can see the `TextView `width and height is already setup when is created and the `ScrollView `only have to scroll it on any direction. If the `TextView `is focused it process all the keystroke.

![scrollView-sample](https://user-images.githubusercontent.com/13117724/103902657-bd1c7a80-50f2-11eb-9ba7-2af589a1f367.png)

**Comment by mrboring** [comment]
Thank you for the explanation, I appreciate you taking the time.

I've just tested removing the `ScrollView` and just using a `TextView`. It works, but does not have scrollbars. Scrollbars are an indicator of more data, and also a quick way to navigate around the data.

I was guessing that `ScrollView` was a way of giving scrollbars to all components. Based on your explanation I think `ScrollView` has limited usage scenarios for non-resizable applications. I'm no expert, but when I create `WinForms` applications, I don't have the issues related to `ScrollView`. If needed components scroll and provide scrollbars. 

Just my opinion, but I think `ScrollView` should use Computed Layout, or scrolling should be built into each component.  Also, `ScrollView` should make sure the cursor stays inside it. Basically, components should act as we are used to in `WinForms` and other frameworks. I appreciate that it's easy for me to say this, but might be hard to do. I certainly couldn't do it.

**Comment by tig** [comment]
We agree `TextView` should have scrollbars. Here's the issue for that: https://github.com/migueldeicaza/gui.cs/issues/1058

Wanna help? ;-)

**Comment by mrboring** [comment]
Wish I had the skills to help. I'm a very basic C# programmer. However, I could contribute as a tester.

What about scrollbars on other components such as `ListView`? Should I create an issue similar to the one you referenced for `TextView`?

**Comment by BDisp** [comment]
Yes, the solution for this kind of feature is using the `ScrollBarView `and not the `ScrollView`. But adding a `ScrollBarView `in any view isn't magic and need to be properly implemented. However, the more sophisticated it is the better it will be to implement.
