### ISSUE TITLE
Debian issues, Unhandled exception

### ISSUE THREAD

**Issue by peterbaumert** [migueldeicaza/gui.cs#1074]
Hi All,

i have a console Application which is running fine on windows. Now i built it for linux-x64 and wanted it to run on my debian 10 machine. I get the following error and have no clue where to look for issues.

`Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Value is beyond the supplementary range!')
at System.Rune..ctor(UInt32 rune)
at System.Rune.op_Implicit(UInt32 value)
at Terminal.Gui.CursesDriver.Init(Action terminalResized)
at Terminal.Gui.Application.Init(Func1 topLevelFactory, ConsoleDriver driver, IMainLoopDriver mainLoopDriver)
at Terminal.Gui.Application.Run[T]()
at my.Program.Main()
Aborted`

Sorry in advance if this is a easy fix but i couldnt find anything related yet.

KR
Pete

**Comment by BDisp** [comment]
Can you provide some code that reproduces that issue?

**Comment by BDisp** [comment]
I guess you get the error on the `Application.cs` at line 707 on the Run method, which throw any unhandled error in the app.

**Comment by peterbaumert** [comment]
> Can you provide some code that reproduces that issue?

Yes sure.

Program.cs
`namespace hzauto
{
    static class Program
    {
        static void Main()
        {
            Application.Run<HzAuto>();
        }
    }
}`

hzauto.cs

`
public HzAuto() {

            Application.Init();
            _top = Application.Top;
            _menu = new MenuBar();
            _top.Add(_menu);

            instance = this;

            _leftPane = new FrameView("Main")
            {
                X = 0,
                Y = 1, // for menu
                Width = 25,
                Height = Dim.Fill(1),
                CanFocus = false
            };
            _leftPane.Title = $"{_leftPane.Title}";

            _rightPane = new FrameView("hzAuto")
            {
                X = 25,
                Y = 1, // for menu
                Width = Dim.Fill(),
                Height = Dim.Fill(1),
                CanFocus = true
            };
            _rightPane.Title = $"{_rightPane.Title}";

            Home();

            _capslock = new StatusItem(Key.CharMask, "Caps", null);
            _numlock = new StatusItem(Key.CharMask, "Num", null);
            _scrolllock = new StatusItem(Key.CharMask, "Scroll", null);

            _statusBar = new StatusBar()
            {
                Visible = true,
            };
            _statusBar.Items = new StatusItem[] {
                _capslock,
                _numlock,
                _scrolllock,
                new StatusItem(Key.F10, "~F10~ Hide/Show Status Bar", () => {
                    _statusBar.Visible = !_statusBar.Visible;
                    _leftPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
                    _rightPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
                    _top.LayoutSubviews();
                }),
            };

            _top.KeyDown += KeyDownHandler;
            _top.Add(_leftPane);
            _top.Add(_rightPane);
            _top.Add(_statusBar);

            ReadConfig();

            server = new UdpServer();

            Application.Run(_top);
            Application.Shutdown();
        }
`

Is this enought already?

KR
Pete

**Comment by BDisp** [comment]
Since you are using the generic `Application.Run<T>` you don't have to call `Application.Init()` and `Application.Run (_top)` in the `Toplevel `derived class. This class only have to create the subviews and assigned to it. If you analise carefull it is already calling the `Init `and `Run` methods.

```
		public static void Run<T> (Func<Exception, bool> errorHandler = null) where T : Toplevel, new()
		{
			Init (() => new T ());
			Run (Top, errorHandler);
		}

```

**Comment by peterbaumert** [comment]
`using Terminal.Gui;

namespace hzauto
{
    static class Program
    {
        static void Main()
        {
            Application.Run<HzAuto>();
        }
    }
}` < Program.cs

`partial class HzAuto : Window
    {
        public HzAuto()
        {
            _leftPane = new FrameView("Main")
            {
                X = 0,
                Y = 1, // for menu
                Width = 25,
                Height = Dim.Fill(1),
                CanFocus = false
            };
            _leftPane.Title = $"{_leftPane.Title}";

            _rightPane = new FrameView("hzAuto")
            {
                X = 25,
                Y = 1, // for menu
                Width = Dim.Fill(),
                Height = Dim.Fill(1),
                CanFocus = true
            };
            _rightPane.Title = $"{_rightPane.Title}";

            _capslock = new StatusItem(Key.CharMask, "Caps", null);
            _numlock = new StatusItem(Key.CharMask, "Num", null);
            _scrolllock = new StatusItem(Key.CharMask, "Scroll", null);

            _statusBar = new StatusBar()
            {
                Visible = true,
            };
            _statusBar.Items = new StatusItem[] {
                _capslock,
                _numlock,
                _scrolllock,
                new StatusItem(Key.F10, "~F10~ Hide/Show Status Bar", () => {
                    _statusBar.Visible = !_statusBar.Visible;
                    _leftPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
                    _rightPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
                    this.LayoutSubviews();
                }),
            };

            this.KeyDown += KeyDownHandler;
            this.Add(_leftPane);
            this.Add(_rightPane);
            this.Add(_statusBar);


        }
}` < hzauto.cs

This is what i have and if i try to run this remote via ssh on my server i get the error from up.
Cant get the Code formatting here right somehow, sorry for that.

KR
and thanks for the help!

**Comment by BDisp** [comment]
After the PR #1063 was merged all the most unhandled exceptions will throw by the `Application.Run` method and will bring more difficulty to debug and caught exceptions where they take place.
In this case you are now deriving the `HzAuto `from a `Window `which create the views and using the `Application.Run` on the Program class without using the generic. The error you get is because `Application.Top` is null and you must create it first, using `Application.Init()`, then call the `HzAuto` class to create the views and lastely call `Application.Run()`.

**Comment by BDisp** [comment]
On your first sample with HzAuto derived from `Toplevel`:
```
	static class Program { static void Main () { Application.Run<HzAuto> (); } }

	public class HzAuto : Toplevel {
		private Toplevel _top;
		private MenuBar _menu;
		private HzAuto instance;
		private FrameView _leftPane;
		private FrameView _rightPane;
		private StatusItem _capslock;
		private StatusItem _numlock;
		private StatusItem _scrolllock;
		private StatusBar _statusBar;

		public HzAuto ()
		{
			//Application.Init ();
			//_top = Application.Top;
			Width = Dim.Fill ();
			Height = Dim.Fill ();
			_top = this;
			_menu = new MenuBar ();
			_top.Add (_menu);

			instance = this;

			_leftPane = new FrameView ("Main") {
				X = 0,
				Y = 1, // for menu
				Width = 25,
				Height = Dim.Fill (1),
				CanFocus = false
			};
			_leftPane.Title = $"{_leftPane.Title}";

			_rightPane = new FrameView ("hzAuto") {
				X = 25,
				Y = 1, // for menu
				Width = Dim.Fill (),
				Height = Dim.Fill (1),
				CanFocus = true
			};
			_rightPane.Title = $"{_rightPane.Title}";

			//Home ();

			_capslock = new StatusItem (Key.CharMask, "Caps", null);
			_numlock = new StatusItem (Key.CharMask, "Num", null);
			_scrolllock = new StatusItem (Key.CharMask, "Scroll", null);

			_statusBar = new StatusBar () {
				Visible = true,
			};
			_statusBar.Items = new StatusItem [] {
			    _capslock,
			    _numlock,
			    _scrolllock,
			    new StatusItem(Key.F10, "~F10~ Hide/Show Status Bar", () => {
				_statusBar.Visible = !_statusBar.Visible;
				_leftPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				_rightPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				_top.LayoutSubviews();
			    }),
			};

			//_top.KeyDown += KeyDownHandler;
			_top.Add (_leftPane);
			_top.Add (_rightPane);
			_top.Add (_statusBar);

			//ReadConfig ();

			//server = new UdpServer ();

			//Application.Run (_top);
			//Application.Shutdown ();
		}
	}

```
On your second sample with HzAuto derived from `Window`:
```

	static class Program {
		static void Main ()
		{
			Application.Init ();
			var top = Application.Top;
			var win = new HzAuto ();
			top.Add (win);
			Application.Run ();
		}
	}

	partial class HzAuto : Window {
		private FrameView _leftPane;
		private FrameView _rightPane;
		private StatusItem _capslock;
		private StatusItem _numlock;
		private StatusItem _scrolllock;
		private StatusBar _statusBar;

		public HzAuto ()
		{
			_leftPane = new FrameView ("Main") {
				X = 0,
				Y = 1, // for menu
				Width = 25,
				Height = Dim.Fill (1),
				CanFocus = false
			};
			_leftPane.Title = $"{_leftPane.Title}";

			_rightPane = new FrameView ("hzAuto") {
				X = 25,
				Y = 1, // for menu
				Width = Dim.Fill (),
				Height = Dim.Fill (1),
				CanFocus = true
			};
			_rightPane.Title = $"{_rightPane.Title}";

			_capslock = new StatusItem (Key.CharMask, "Caps", null);
			_numlock = new StatusItem (Key.CharMask, "Num", null);
			_scrolllock = new StatusItem (Key.CharMask, "Scroll", null);

			_statusBar = new StatusBar () {
				Visible = true,
			};
			_statusBar.Items = new StatusItem [] {
			    _capslock,
			    _numlock,
			    _scrolllock,
			    new StatusItem(Key.F10, "~F10~ Hide/Show Status Bar", () => {
				_statusBar.Visible = !_statusBar.Visible;
				_leftPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				_rightPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				this.LayoutSubviews();
			    }),
			};

			//this.KeyDown += KeyDownHandler;
			this.Add (_leftPane);
			this.Add (_rightPane);
			this.Add (_statusBar);
		}
	}

```

**Comment by peterbaumert** [comment]
@BDisp thanks again for your help but i changed now everything to be as in your second example and still get the error:

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Value is beyond the supplementary range!')
at System.Rune..ctor(UInt32 rune)
at System.Rune.op_Implicit(UInt32 value)
at Terminal.Gui.CursesDriver.Init(Action terminalResized)
at Terminal.Gui.Application.Init(Func 1 topLevelFactory, ConsoleDriver driver, IMainLoopDriver mainLoopDriver)
at Terminal.Gui.Application.Init(ConsoleDriver driver, IMainLoopDriver mainLoopDriver)
at hzauto.Program.Main()
```

**Comment by BDisp** [comment]
Obviously you are using some other code which is causing a `Rune `error. You only can use a valid `Rune `and you are using a rune which is greater than the maximum allowed rune which is `0x10ffff`. That error is from the `NStack `API.

**Comment by BDisp** [comment]
Is preferable this sample:

```
	static class Program {
		static void Main ()
		{
			new HzAuto ();
		}
	}

	public class HzAuto {
		private Toplevel _top;
		private MenuBar _menu;
		private FrameView _leftPane;
		private FrameView _rightPane;
		private StatusItem _capslock;
		private StatusItem _numlock;
		private StatusItem _scrolllock;
		private StatusBar _statusBar;

		public HzAuto ()
		{
			Application.Init ();
			_top = Application.Top;

			_menu = new MenuBar (new MenuBarItem [] {
				new MenuBarItem ("_File", new MenuItem [] {
					new MenuItem ("_Quit", "", () => Application.RequestStop(), null, null, Key.Q | Key.CtrlMask)
				})
			});

			_leftPane = new FrameView ("Main") {
				X = 0,
				Y = 1, // for menu
				Width = 25,
				Height = Dim.Fill (1),
				CanFocus = false
			};
			_leftPane.Title = $"{_leftPane.Title}";

			_rightPane = new FrameView ("hzAuto") {
				X = 25,
				Y = 1, // for menu
				Width = Dim.Fill (),
				Height = Dim.Fill (1),
				CanFocus = true
			};
			_rightPane.Title = $"{_rightPane.Title}";

			_capslock = new StatusItem (Key.CharMask, "Caps", null);
			_numlock = new StatusItem (Key.CharMask, "Num", null);
			_scrolllock = new StatusItem (Key.CharMask, "Scroll", null);

			_statusBar = new StatusBar () {
				Visible = true,
			};
			_statusBar.Items = new StatusItem [] {
			    _capslock,
			    _numlock,
			    _scrolllock,
			    new StatusItem(Key.F10, "~F10~ Hide/Show Status Bar", () => {
				_statusBar.Visible = !_statusBar.Visible;
				_leftPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				_rightPane.Height = Dim.Fill(_statusBar.Visible ? 1 : 0);
				_top.LayoutSubviews();
				_top.SetChildNeedsDisplay();
			    }),
			};

			//this.KeyDown += KeyDownHandler;
			_top.Add (_menu);
			_top.Add (_leftPane);
			_top.Add (_rightPane);
			_top.Add (_statusBar);

			Application.Run ();
		}
	}

```

**Comment by tig** [comment]
> After the PR #1063 was merged all the most unhandled exceptions will throw by the `Application.Run` method and will bring more difficulty to debug and caught exceptions where they take place.

I don't think this is right. PR #1063 uses `throw` inside the handler, and thus the original exception should be passed up, right?

**Comment by peterbaumert** [comment]
> Obviously you are using some other code which is causing a `Rune `error. You only can use a valid `Rune `and you are using a rune which is greater than the maximum allowed rune which is `0x10ffff`. That error is from the `NStack `API.

At least not to my knowledge, is a Rune "used" by something else or i have to call it explicitly?

![rune](https://user-images.githubusercontent.com/1212934/103882453-1e851f00-50dc-11eb-85c5-9d4bceef3a21.png)

I use exactly the code from up which generates this error. I commented everything else out, so only this part of the code would be executed. Sorry for the inconveniences and thx for all the help.

**Comment by BDisp** [comment]
> I don't think this is right. PR #1063 uses `throw` inside the handler, and thus the original exception should be passed up, right?

Yes you are right. I didn't meaning it. What I had mean is the needed of tracking the origin of the exception, which can make more confusing for some users. The PR does well what it is meant to do.

**Comment by BDisp** [comment]
Since you said that only happens with `Debian `and not on `Windows`, please try on the `WSL `or other `Linux `device too see if you get the same error.

**Comment by peterbaumert** [comment]
> Since you said that only happens with `Debian `and not on `Windows`, please try on the `WSL `or other `Linux `device too see if you get the same error.

On WSL (also Debian) I am getting the same error. Will try another distro soon too. I am still using Terminal gui 0.9 can that be an issue?

**Comment by BDisp** [comment]
> On WSL (Debian and Ubuntu) I am getting the same error. Will try another distro soon too. I am still using Terminal gui 0.9 can that be an issue?

I really don't know as I'm using the latest master version. Please try with this version and then say anything.

**Comment by peterbaumert** [comment]
> > On WSL (Debian and Ubuntu) I am getting the same error. Will try another distro soon too. I am still using Terminal gui 0.9 can that be an issue?
> 
> I really don't know as I'm using the latest master version. Please try with this version and then say anything.

I tried all and didnt work. I ended up copying all my code to a new solution.. this worked.. i dunno what fucked up my old one.

Sorry for all the inconveniences and thank you for your help!

KR
Pete
