### ISSUE TITLE
Textview Newline Bug

### ISSUE THREAD

**Issue by deaddlocust** [migueldeicaza/gui.cs#1076]
Hello. It's my first time opening an issue so please forgive me if I do anything wrong.

I have this issue, when attempting to set the Text value to a string, theres an question mark box in every newline. For example with this code:

```
string text = @"yes
yes
yes";

editor.Text = text;
```
Is there a fix for this or is this a bug or something? It is similar to [this](https://github.com/migueldeicaza/gui.cs/pull/1025) but i am unsure if it's fixed or not.

**Comment by tznind** [comment]
I have encountered this with windows line endings (CR LF).  Try replacing "\r\n" with "\n" in your string i.e.

```csharp
string text = @"yes
yes
yes";

editor.Text = text.Replace("\r\n","\n");
```

**Comment by deaddlocust** [comment]
> I have encountered this with windows line endings (CR LF). Try replacing "\r\n" with "\n" in your string i.e.
> 
> ```cs
> string text = @"yes
> yes
> yes";
> 
> editor.Text = text.Replace("\r\n","\n");
> ```

Thank you, it fixed the problem for me.

**Comment by BDisp** [comment]
This was already fixed in the preview version.
