### ISSUE TITLE
Textview ctrl+v paste

### ISSUE THREAD

**Issue by deaddlocust** [migueldeicaza/gui.cs#1077]
Hey so errrr this is my second issue today but if i can solve both issues i have in one day, i wont ever have to get frustrated over this library ever again.

Basically, ctrl+v doesnt work for textview for me.

Is it possible to use the shortcut in textview? Or does the shortcut go under a different key combination in this library?

If not, is there any way to implement this? I have been doing a lot of searching and I still cant find a solution

**Comment by tznind** [comment]
I don't think this is implemented in TextView.  There is a `Clipboard` class but it doesn't interact with the system clipboard of the OS.  You might be able to find a NuGet package somewhere for cross platform clipboard.

```csharp
            textView.KeyPress += (k)=>
            {
                if(k.KeyEvent.Key == Key.ControlC)
                    Clipboard.Contents = textView.Text;
                if(k.KeyEvent.Key == Key.ControlV)
                    textView.Text = Clipboard.Contents;
            };
```

Note that this is code for the current release of gui, I think in 1.0 it will change to `Key.C | Key.CtrlMask` instead of `Key.ControlC`

**Comment by deaddlocust** [comment]
> I don't think this is implemented in TextView. There is a `Clipboard` class but it doesn't interact with the system clipboard of the OS. You might be able to find a NuGet package somewhere for cross platform clipboard.
> 
> ```cs
>             textView.KeyPress += (k)=>
>             {
>                 if(k.KeyEvent.Key == Key.ControlC)
>                     Clipboard.Contents = textView.Text;
>                 if(k.KeyEvent.Key == Key.ControlV)
>                     textView.Text = Clipboard.Contents;
>             };
> ```
> 
> Note that this is code for the current release of gui, I think in 1.0 it will change to `Key.C | Key.CtrlMask` instead of `Key.ControlC`
> 
> I also don't think TextView has a notion of selected areas... (although I could be wrong)

Alright thanks. I am not too worried about ctrl+a so this is fine by me.

**Comment by BDisp** [comment]
These features aren't already implemented yet in `TextView `like in the `TextField`.
Indeed it is a good solution the `Clipboard `class could interact with the system clipboard of the `OS`.

**Comment by deaddlocust** [comment]
Nevermind. Turns out the clipboard works, but the key detection seems to be off. Opened a new issue regarding that.
