### ISSUE TITLE
View.ColorScheme setter should likely call setNeedsDisplay ()

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#1078]
So it triggers a re-display.

**Comment by BDisp** [comment]
I agree.

**Comment by BDisp** [comment]
Although I had agreed, now I have some doubts. On cases where the user are setting some configurations and only want apply on exit or on a reinitialization, the changes is immediately apply, which the user maybe don't want. In this case is better the user call the `SetNeededDisplay `later.

**Comment by migueldeicaza** [comment]
Generally, I don't think that gui.cs is modeled after a reinitialization - generally, the properties have an immediate effect.
