### ISSUE TITLE
up/down keys not working to move across buttons?

### ISSUE THREAD

**Issue by agonzalezm** [migueldeicaza/gui.cs#108]
I am trying to create this console app that present 4 options/button but when i start the app:

1. keys up/down are not working to move accross the buttons. I see in the demo that you can use up/down to move accross components.
2. I want the first button (Install) to be the selected/highlited one but the selected/highlited one on start is Exit button.

Any idea how can i get what i want? Thanks!

```
        static void Main(string[] args)
        {
            Application.Init();     
            var top = Application.Top;
            
            var menu = new Dialog("Options",50,20, new Button("Exit"))
            {
                new Button(10, 5, "Install") { Clicked = () => { Install(); } },
                new Button(10, 6, "Uninstall") { Clicked = () => { Uninstall(); } },
                new Button(10, 7, "Check for updates") { Clicked = () => { Updates(); } },
                new Button(10, 8, "Exit") { Clicked = () => { Application.RequestStop (); } },
            };

            Application.Run(menu);
        }
```

**Comment by migueldeicaza** [comment]
I tried reproducing this problem, but it works for me, left/right/up/down do move as intended.

To focus the first view, call "menu.SetFocus (...)" with the first parameter as your button, so you will want to save that into a variable and pass that to SetFocusm
