### ISSUE TITLE
Help with KeyDown in TextView?

### ISSUE THREAD

**Issue by deaddlocust** [migueldeicaza/gui.cs#1082]
Hi im sorry if this is considered something "too stupid" or that "I didnt read the documentation" but I have this problem and after a ton of searching, I can't seem to find a fix for it.

Is there a way to detect when letter keys are pressed in textview? Textview always seems override it and just display the letter in the textview instead.

References, explanations or code would be appreciated.

**Comment by tznind** [comment]
This seems to work for me (with latest stable package).  The key is probably setting e.Handled to true if you are doing something special?

```csharp
var tv = new TextView();
            
            tv.KeyPress += (e) =>
            {
                if(e.KeyEvent.KeyValue == 'p')
                {
                    e.Handled = true;
                    MessageBox.Query("You pressed P","","Ok");
                }
            };
```

**Comment by BDisp** [comment]
@tznind with the master version this is working. Everytime the 'p' key is pressed the `MessageBox `is displayed and doesn't display the letter in the `TextView` or does nothing as your sample.

```c#
			var tv = new TextView () {
				Width = Dim.Fill (),
				Height = Dim.Fill ()
			};

			tv.KeyPress += (e) =>
			{
				if (e.KeyEvent.KeyValue == 'p') {
					MessageBox.Query ("You pressed P", "", "Ok");
					e.Handled = true;
				}
			};

```

**Comment by deaddlocust** [comment]
Thanks for the help
