### ISSUE TITLE
Pos.right, pos.bottom cause the view to disappear 

### ISSUE THREAD

**Issue by evanAndersonDigipen** [migueldeicaza/gui.cs#1083]
`var QuitB = new Button("Quit")
            {
                Y = yBot,
                X = Pos.Right(menu)
            };`
The button doesnt appear anymore when added to menu `var menu = new Window();`
Same happens if I ever set the y to Pos.Bottom(menu)
also, yBot is just Pos.At(7) for now

Am I using this wrong or is this just broken?

**Comment by BDisp** [comment]
On both cases the `Button `is placed outside of `Window `frame.
In the first case it must be `X = Pos.Right(menu) - "Quit".Length` and in the second case it must be `Y = Pos.Bottom(menu) - 1`
I didn't tested but I think it is the issue.

**Comment by evanAndersonDigipen** [comment]
Well! That made it so it was at least slightly on the screen, ill keep messing around with it, thank you for your quick response

**Comment by BDisp** [comment]
You right, I didn't considered the `Window `margin.
