### ISSUE TITLE
Application.Shutdown() does not return to original SynchronizationContext

### ISSUE THREAD

**Issue by angelobreuer** [migueldeicaza/gui.cs#1084]
When running the following code the synchronization context is still set to an instance of `Terminal.Gui.Application.MainLoopSyncContext` after a shutdown. This causes any async/await code to block indefinitely as the main loop does not run anymore. I think this behavior ***may be unintended*** (I am new to using gui.cs).

```cs
using System;
using System.Threading.Tasks;
using Terminal.Gui;

Application.Run<A>();
Application.Shutdown();

// main loop suspended, call async
await Task.Yield();

// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context which will not work as the main 
// loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false);

Console.WriteLine("should print but does not"); // will never come to this point

internal class A : Window
{
    public A()
    {
        var button = new Button("Request Stop");
        button.Clicked += Application.RequestStop;

        Add(button);
    }
}
```

**Additional details**

I am using gui.cs for setting up my application itself, after the setup completed the application will use mainly async/await to resume. The easiest workaround for this issue is simply returning to the original synchronization context using  `SynchronizationContext.SetSynchronizationContext(..)`.

I am also available to grab this issue, if this is unintended behavior.

Thank you for reading.

**Comment by BDisp** [comment]
The `button.Clicked` handler is not correctly set.
The solution for what you want is possible as follow:

```
	static class Program {
		static async Task Main ()
		{
			Application.Run<A> ();
			Application.Shutdown ();

			// main loop suspended, call async
			//await Task.Yield ();
			Task.Yield ().GetAwaiter ();

			// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context which will not work as the main 
			// loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false); Get an error with this.

			Console.WriteLine ("should print but does not"); // will never come to this point with await Task.Yield ();

			Console.WriteLine ("Now is printing."); // Comment "await Task.Yield ();" to see print this.
		}

		internal class A : Window {
			public A ()
			{
				var button = new Button ("Request Stop");
				button.Clicked += () => Application.RequestStop ();

				Add (button);
			}
		}
	}

```

**Comment by angelobreuer** [comment]
Thank you for your quick response, @BDisp!

> The button.Clicked handler is not correctly set.
> The solution for what you want is possible as follow:

The button.Clicked event handler is correctly set, as `() => Application.RequestStop()` is the same as passing the method itself, both result in a similar delegate instantiation (similar because `() => Application.RequestStop()` wraps another time in a method). Both approaches should behave the same. In further examples, I will use your example to re-wrap the delegate (``() => Application.RequestStop()``).

> Task.Yield ().GetAwaiter ();

You changed the call to be non-awaiting, the call to `GetAwaiter()` should post the task onto the synchronization context, but it will not await it, so this may produce invalid results.

To be sure that the asynchronous method is awaited, I prepared a code snippet, which will show what is awaited and whatnot:

```cs
using System;
using System.Threading.Tasks;
using Terminal.Gui;

Application.Run<A>();
Application.Shutdown();

// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context
// which will not work as the main loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false);
TestAsync().GetAwaiter();

Console.WriteLine("This is the INNER body of the `<Program>$.<Main>$` method.");

async Task TestAsync()
{
    // use delay/yield/any async method to force-recapture the synchronization context after the
    // yield, which forces the method to run on the main loop (which is suspended)
    await Task.Delay(500);

    Console.WriteLine("This is the INNER body of the `TestAsync()` method.");
}

internal class A : Window
{
    public A()
    {
        var button = new Button("Request Stop");
        button.Clicked += () => Application.RequestStop();

        Add(button);
    }
}
```

In the above, you see that only `This is the INNER body of the <Program>$.<Main>$` method. is printed out. This is because the TestAsync() method is not awaited (because the main thread exits before the task completes).

Now, I've changed the call to `GetResult()`, see following example: 

<details>
  <summary>Click to expand!</summary>
  
```cs
using System;
using System.Threading.Tasks;
using Terminal.Gui;

Application.Run<A>();
Application.Shutdown();

// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context
// which will not work as the main loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false);
TestAsync().GetAwaiter().GetResult(); // here <--

Console.WriteLine("This is the INNER body of the `<Program>$.<Main>$` method.");

async Task TestAsync()
{
    // use delay/yield/any async method to force-recapture the synchronization context after the
    // yield, which forces the method to run on the main loop (which is suspended)
    await Task.Delay(500);

    Console.WriteLine("This is the INNER body of the `TestAsync()` method.");
}

internal class A : Window
{
    public A()
    {
        var button = new Button("Request Stop");
        button.Clicked += () => Application.RequestStop();

        Add(button);
    }
}

```
</details>

You will see that nothing is printed in the console because of the task blocks. This is because the main loop of the application has been suspended and does not do anything anymore.

This is where my problem begins: You will see that if I remove any code concerning `gui.cs` the code works fine:


<details>
  <summary>Click to expand!</summary>
  
```cs
using System;
using System.Threading.Tasks;

// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context
// which will not work as the main loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false);
TestAsync().GetAwaiter().GetResult();

Console.WriteLine("This is the INNER body of the <Program>$.<Main>$ method.");

async Task TestAsync()
{
    // use delay/yield/any async method to force-recapture the synchronization context after the
    // yield, which forces the method to run on the main loop (which is suspended)
    await Task.Delay(500);

    Console.WriteLine("This is the INNER body of the `TestAsync()` method.");
}

```
</details>

In the console, there are the following lines written:
```
This is the INNER body of the `TestAsync()` method.
This is the INNER body of the `<Program>$.<Main>$` method.
```

Which I think should be the behavior.

Then let's move on why the code is not being executed when gui.cs ran:

- `Application.Run<A>();` sets the synchronization context of an instance of `Terminal.Gui.Application.MainLoopSyncContext`, which is made because users should be able to use gui.cs and async/await. The method blocks until the application stops have been **requested**.
- Now `Application.Shutdown();` shutdowns the application **without resetting the SynchronizationContext**.
- You can observe this when you call `Console.WriteLine(SynchronizationContext.Current);`
- Now, an asynchronous task starts, which is then posted to gui.cs's synchronization context, which does not process any tasks anymore!
- The program is dead.

So, my fix for this is to put a `SynchronizationContext.SetSynchronizationContext(syncContext: null);` after shutting down the application.

<details>
  <summary>Click to expand!</summary>
  
```cs
using System;
using System.Threading;
using System.Threading.Tasks;
using Terminal.Gui;

Application.Run<A>();
Application.Shutdown();
SynchronizationContext.SetSynchronizationContext(syncContext: null);

// without calling .ConfigureAwait(false) the task tries to recapture the synchronization context
// which will not work as the main loop is suspended (running = false), e.g., await Task.Yield().ConfigureAwait(false);
TestAsync().GetAwaiter().GetResult();

Console.WriteLine("This is the INNER body of the `<Program>$.<Main>$` method.");

async Task TestAsync()
{
    // use delay/yield/any async method to force-recapture the synchronization context after the
    // yield, which forces the method to run on the main loop (which is suspended)
    await Task.Delay(500);

    Console.WriteLine("This is the INNER body of the `TestAsync()` method.");
}

internal class A : Window
{
    public A()
    {
        var button = new Button("Request Stop");
        button.Clicked += () => Application.RequestStop();

        Add(button);
    }
}
```
</details>

Now the code works as expected. I am opening this issue because I think it was unintended to retain the synchronization context set by `gui.cs` after the application shutdown.

Thank you.

**Comment by BDisp** [comment]
You are right, it run synchronously. Only call `Application.Shutdown();` if you really want to exit. So, if you have awaitable tasks you must ensure that all tasks are completed before shutdown.
About the `button.Clicked`, you are right. I only changed it to set a breakpoint inside.
You are right too, it was unintended to retain the synchronization context set by `gui.cs` after the application shutdown. It must be disposed on the `Application.Shutdown` method.
You may could submit a PR to fix this if you are comfortable.
