### ISSUE TITLE
How do you get TextView text changed to work

### ISSUE THREAD

**Issue by duolingo9939** [migueldeicaza/gui.cs#1095]
Hello!
I want to add syntax Highlighting to my TextView and i made a prototype to detect if text has changed. I tried using `editor.TextChanged` but that didn' work. Do you guys have another idea how to accomplish my goal? Anyways,
Here is the code i tried it with 
```cs
editor.TextChanged += () =>
{
      System.Windows.Forms.MessageBox.Show("Text Changed");
};
```

This does not work. 
I would appreciate help, thank you.

UPDATE: Pressing CTRL will bring the MessageBox to show and it pastes `using System.Windows.Forms;` in the TextView then

**Comment by BDisp** [comment]
`TextChanged `only fires if the `Text `property is changed and not when you are typing, because you don't want to save the changes. But there must be a `Changed `event just to notify the user that they can get the changes with get method `Text`.

**Comment by tznind** [comment]
If you want to do syntax highlighting you might want to inherit from TextView and override `ReDraw`?

**Comment by deaddlocust** [comment]
I think it would be better to ask about possible ways to pull off syntax highlighting instead.
