### ISSUE TITLE
Syntax Highlighting in TextView control

### ISSUE THREAD

**Issue by 0x788** [migueldeicaza/gui.cs#1096]
Hello, is it possible to add syntax highlighting to my TextView control? Can I color certain words or change the color after a character stuff like that. Without changing the whole foreground color of the entire text.

**Comment by BDisp** [comment]
I think @tznind has already answered here https://github.com/migueldeicaza/gui.cs/issues/1095#issuecomment-765001514.
In `Redraw`, you will print the text however you want, using the `ColorScheme `attributes. For this you do not need the event because the legacy `TextView `will always be handling changes whenever you are typing.

**Comment by duolingo9939** [comment]
> I think @tznind has already answered here [#1095 (comment)](https://github.com/migueldeicaza/gui.cs/issues/1095#issuecomment-765001514).
> In `Redraw`, you will print the text however you want, using the `ColorScheme `attributes. For this you do not need the event because the legacy `TextView `will always be handling changes whenever you are typing.

Where can I read about Redraw?

**Comment by BDisp** [comment]
`Redraw `is a `View `class virtual method. So see in the `TextView `class how it is implemented the override `Redraw `method. You must be a little skill to deal with that.

**Comment by tznind** [comment]
Just looked into this as its quite interesting idea.  I overided Redraw and copied the current code out of the base implementation (as a starting point) but it uses a lot of `private` variables.  Would it be worth making some of those `protected`? 

https://github.com/migueldeicaza/gui.cs/blob/287d2c1b059af5ce932b20969eaa7ab913dd08bb/Terminal.Gui/Views/TextView.cs#L388-L394

**Comment by BDisp** [comment]
I agree. In my PR #1081 I did changes to the `TextView `by adding public properties to get their values, but I think we could make them `protected `variables. Another suggestion is to create custom characteres color attributes which could be manipulated before printed.
