### ISSUE TITLE
List View rendering: a ilist<t> to a IList with IListDataSource.ToList()

### ISSUE THREAD

**Issue by Impdevil** [migueldeicaza/gui.cs#1098]
I'm trying to use the IListDataSource for my own definition but I'm hitting a road block with IListDataSource.ToList, its asking me to return the list but when i try to return the list it says its unable to convert from IList<t> to an IList. what is the way of doing this that I'm not understanding. im just using the example in the views/listview.cs for more context. 

Im trying to render a 2d array, and i know there is no grid view for listview, so I'm basically going to try and render each column as their own listview within the same frameview.

**Comment by BDisp** [comment]
Maybe something like this:

```cs
var a = new ustring [5, 2];
List<ustring> lst = new List<ustring> ();
foreach (var item in a) {
	lst.Add (item);
}

```

**Comment by Impdevil** [comment]
your literally just telling me how to add items from an array to a list, i think you might be focusing on the wrong part of my issue.  thank you for replying so quickly though

**Comment by BDisp** [comment]
As you said that you had a two-dimensional array (2d array), I thought you were having problems because of that. It would be better to give an example of what you want to do to help you better.

**Comment by Impdevil** [comment]
my apologizes, I'm using a FrameView to to hold an array of listviews[], these listviews gain there items from a 2d array that has a string within it. I'm trying to show the first letter of the string but its not displaying at all within the listview, Im only trying to get one column to work right now. 
`




    public class UI_t_Map : FrameView
    {
        ListView column;
        public UI_t_Map(int x, int y, Map map) : base(new Rect(x, y,map.G_MapSize+2,map.G_MapSize+2),"map")
        {
            column = new ListView();
            for (int i = 0; i < 1 i++)
            {
                List<string> xtilecolumn = new List<string>();

                for (int j = 0; j < map.G_MapSize; j++)
                {
                    xtilecolumn.Add( map.G_Map[i,j].Get_LandType.ToString()[0]+"");
                }

                column.Source =new MapRenderer(xtilecolumn);

            }
            
        }
        public void AddCol()
        {
            for (int i = 0; i < 1; i++)
                this.Add(column);
        }
    }


`


MapRenderer refers to a IListDataSource class though this is basically the same code as the one from [here](https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Views/ListView.cs) line 755 


my current issue is i cant even get one item from one column of the 2d array to show up

**Comment by BDisp** [comment]
Don't forget to set the `ListView `size and use this:

```cs
column.Source = new ListWrapper (new MapRenderer(xtilecolumn));
```

**Comment by BDisp** [comment]
Here is the code I used to test:

```cs
static class Program {
	static void Main ()
	{
		Application.Init ();
		var top = Application.Top;

		var rows = 5;
		var cols = 10;
		var array = new string [rows, cols];

		for (int i = 0; i < rows; i++) {
			for (int j = 0; j < cols; j++) {
				array [i, j] = $"Item{i}-{j}";
			}
		}

		var map = new UI_t_Map (0, 0, new Size (80, 25), array, rows, cols);
		top.Add (map);

		Application.Run ();
	}

	public class UI_t_Map : FrameView {
		ListView column;
		public UI_t_Map (int x, int y, Size map, string [,] array, int rows, int cols) : base (new Rect (x, y, map.Width + 2, map.Height + 2), "map")
		{
			column = new ListView () {
				Width = Dim.Fill (),
				Height = Dim.Fill ()
			};

			List<string> xtilecolumn = new List<string> ();

			for (int i = 0; i < rows; i++) {
				for (int j = 0; j < cols; j++) {
					xtilecolumn.Add (array [i, j]);
				}

				column.Source = new ListWrapper (xtilecolumn);
				AddCol ();
			}
		}

		public void AddCol ()
		{
			for (int i = 0; i < 1; i++)
				this.Add (column);
		}
	}
}

```

**Comment by Impdevil** [comment]
Thank you so much, its now showing the one column, I'm sure from here I can get the other Columns working. Again thankyou
