### ISSUE TITLE
UI Catalog doesn't work on Windows Terminal

### ISSUE THREAD

**Issue by abiratur** [migueldeicaza/gui.cs#1099]
when running UICatalog.exe from windows terminal there is an empty screen.
after some investigation it appears that this commit breaks the windows terminal: 
94f58acecf70a7b1bfa6be1906b7f7cb91d1f1ef (Trying fix #335)

**Comment by tznind** [comment]
I have also had difficulty on Windows with screen height:

In c0540b5de6b37a15ec15714bdbcbf737dad3a223 it works:

![image](https://user-images.githubusercontent.com/31306100/105707168-6d1f1f80-5f0a-11eb-9444-091dd89b8024.png)

In 94f58acecf70a7b1bfa6be1906b7f7cb91d1f1ef the screen height is halved:

![image](https://user-images.githubusercontent.com/31306100/105707248-8d4ede80-5f0a-11eb-9351-e12aaf011415.png)

**Comment by BDisp** [comment]
Can you test with my PR #1066, please?

**Comment by tznind** [comment]
> Can you test with my PR #1066, please?

Yup that seems to fix it, thanks

**Comment by BDisp** [comment]
I changed the `_heightAsBuffer` field to false in the `UICatalog` to always use the window size. Still not the best solution because I can't always fit completely all the window size. Please check when you have the time. Thanks.

**Comment by BDisp** [comment]
It's seems that `Windows Terminal's cmd` is rendering different than the `cmd.exe`.

**Comment by BDisp** [comment]
On the `cmd.exe` when the height is equal to 0 the windows disappear but `UICatalog` is still running. It seems that is related with the `"No process is on the other end of the pipe"` error. But with the `Visual Studio Debugger Console` this doesn't happens.

**Comment by abiratur** [comment]
> Can you test with my PR #1066, please?

Works perfect
thanks !
