### ISSUE TITLE
redraws while app is not focused on windows.

### ISSUE THREAD

**Issue by tlemmons** [migueldeicaza/gui.cs#1105]
I am using this to create a console app that will have several Views that are showing ssh/telnet data.  I created a new view based on ScrollView.  I seem to have problems with the redraw getting called enough to show the flowing data.  I added a task that checked for new data every XX ms and called SetNeedsDisplay when needed.  This seems to work although if there is better way please let me know.  The issue I have not is that when the console window is not active/focused in Windows it does not update even though I am still calling SetNeedsDisplay .  Am I doing something wrong or what can I do to override and get draws during un focused time.

**Comment by BDisp** [comment]
See the `UICatalog Scrolling` scenario which has some views in it and is redrawn as needed.

**Comment by tlemmons** [comment]
Thanks, I will look into that and see if it works for me.

**Comment by tlemmons** [comment]
I just looked at it but nothing on the scrolling scenario moves or changes when out of focus either.  Even the mouse position does not update unless the window has focus.   Do you have any examples that show long running updates of the text that might happen without user involvement?

**Comment by BDisp** [comment]
You have to handle the scroll yourself when the focus has changed. Maybe take the current focused view's frame and change the scroll offset to reflect the new coordinates. It's not very easy indeed.

**Comment by tlemmons** [comment]
I am doing that and it works fine when the console window is active or focused on Windows, but when a different app has the Window focus it stops updating, but will update when focus is once again received.  I have tried going through the code but cannot find where the loss of Windows focus stops updates.  I have not tried this yet on Linux or mac but I plan to build for both.

**Comment by BDisp** [comment]
Try the `Application.MainLoop.AddTimeout` to update periodicaly your view.

```cs
		bool timer (MainLoop caller)
		{
			yourView.Redraw(yourView.Bounds);
			return true;
		}

		Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (300), timer);

```

**Comment by tlemmons** [comment]
That seemed to work.  Thanks.  I will keep checking it out but I think it is fixed.

**Comment by tig** [comment]
@tlemmons can you confirm this is no longer an issue for you?

**Comment by tlemmons** [comment]
I will as soon as I can get back to that project.  Busy life right now but thanks for letting me know.

**Comment by tlemmons** [comment]
Yes.  It is full window now.  Thanks!
