### ISSUE TITLE
Blank lines at bottom of window

### ISSUE THREAD

**Issue by tlemmons** [migueldeicaza/gui.cs#1106]
I have the following
Top
>Menu
>Window
                X = 0,
                Y = 1, // Leave one row for the toplevel menu
                Width = Dim.Fill(),
                Height = Dim.Fill(),

When I run the app, the main window initially shows up full height of the console but quickly redraws to leaving 5 or so blank lines under the window boarder.  I ran the UICatalog app and it has same issue.  Is this a known bug or something on my computer?

![image](https://user-images.githubusercontent.com/6530302/107070644-d6235480-67a0-11eb-9a10-9622dfdbf981.png)

**Comment by BDisp** [comment]
Yes, it's a bug. Test with this PR #1066, please.

**Comment by tig** [comment]
This should now be fixed in `master`. @tlemmons, can you please confirm?
