### ISSUE TITLE
Terminal modes are not properly restored on exit for Linux.

### ISSUE THREAD

**Issue by nmacholl** [migueldeicaza/gui.cs#1114]
I am observing that on Linux (MXLinux 19.3) my terminal modes are not restored when my application closes. Most notably is the noecho. This is fixed with a simple reset. I have tested this on Terminator and Xfce.

My application is exiting gracefully, I am closing my application using:
```
Application.RequestStop();
```

**Comment by BDisp** [comment]
This related with the #931 issue. There is no fix for that yet.

**Comment by nmacholl** [comment]
Ah thank you; I did not see this issue in my search. I will close this issue and monitor that one. Thanks!
