### ISSUE TITLE
Question marks.

### ISSUE THREAD

**Issue by BaRRaKudaRain** [migueldeicaza/gui.cs#1115]
Hi everyone!
Having the following issue. I created the messagebox and see the "Yes" button with question marks.
![image](https://user-images.githubusercontent.com/29839832/108591822-b2a10200-737b-11eb-98b7-4674f372ec21.png)
Is there some missing or unsupported symbol?

**Comment by BDisp** [comment]
> Is there some missing or unsupported symbol?

Do you are using this statement in the` main` of the app?
`Console.OutputEncoding = System.Text.Encoding.Default;`

**Comment by tig** [comment]
What font are you using in your console?
