### ISSUE TITLE
OpenDialog result

### ISSUE THREAD

**Issue by scemino** [migueldeicaza/gui.cs#112]
How do I get the result of an `OpenDialog`, if the user clicks on the Cancel button, what happens ?
Here is my code:
```c#
var dialog = new OpenDialog("Open", "Open a pack")
{
  FilePath = "ThimbleweedPark.ggpack1",
  AllowedFileTypes = new string[] { ".ggpack1", ".ggpack2" }
};
Application.Run(dialog);
```
I cannot test FilePath which is not null and I didn't find documentation about another property.

Thank you

**Comment by migueldeicaza** [comment]
You are correct, this could be improved.

In the meantime, the FilePaths property should be an empty list.
