### ISSUE TITLE
Broken link in articles docs

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1130]
The link for 'TreeView Deep Dive' seems wrong (gives 404) in https://migueldeicaza.github.io/gui.cs/articles/index.html

It leads to:
 `https://migueldeicaza.github.io/gui.cs/articles/articles/treeview.md` 

but should be:
 `https://migueldeicaza.github.io/gui.cs/articles/treeview.html`

It would be great if there was also a link to the table view article:
https://migueldeicaza.github.io/gui.cs/articles/tableview.html

Appologies if this is something I did wrong in my PRs

**Comment by tig** [comment]
I'm fixing some other things too...
