### ISSUE TITLE
Reactive sample should not pull Terminal.Gui from nuget

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1132]
This

```
 <PackageReference Include="Terminal.Gui" Version="1.0.0-pre.*" />
```

Should be

```
        <ProjectReference Include="..\Terminal.Gui\Terminal.Gui.csproj" />
```

But I can't get that to work. I get  these errors, which make no sense to me:

![image](https://user-images.githubusercontent.com/585482/110528508-7557a680-80d5-11eb-823e-910f7581d3ee.png)

There has got to be a way to have this sample build correctly without having to refer to the nuget.

@worldbeater can you help?

**Comment by worldbeater** [comment]
Worth noting that there is `ObservableEventsSourceGenerator` https://github.com/reactivemarbles/ObservableEventsSourceGenerator That is planned to be a successor for Pharmacist in the future, it won't do such stuff as NuGet processing. So one option would be to wait until that new tool is out.

Another option would be to reference locally built packages from a local NuGet package feed specified either via `nuget.config` or via `<RestoreSources>` MSBuild directive.

**Comment by tig** [comment]
Removing as a requirement for 1.0

**Comment by worldbeater** [comment]
[Pharmacist](https://github.com/reactiveui/Pharmacist) has been reimplemented as [ObservableEvents](https://github.com/reactivemarbles/observableevents) .NET 5 source generator, so I guess if we replace the former package with the latter, we'll no longer need to pull `Terminal.Gui` from NuGet in the reactive sample.

**Comment by BDisp** [comment]
I already changed to not use the NuGet package and using the `Terminal.Gui` project, but the virus alert kill me.

**Comment by worldbeater** [comment]
@BDisp what do you mean by a "virus alert"?
Is Windows treating .NET 5 source generators as viruses? o_o
Just replaced  [Pharmacist](http://github.com/reactiveui/pharmacist) with [ReactiveMarbles.ObservableEvents](https://github.com/reactivemarbles/observableevents) in https://github.com/migueldeicaza/gui.cs/pull/1440 and it all works fine on my Linux (Ubuntu 18.04 KDE) machine using the latest .NET SDK (`5.0.302`). Worth noting that the observable events generator is open source so you can check for viruses manually.

**Comment by BDisp** [comment]
See here #1412 and #1415. The virus is inside the compiled `ReactiveExample.dll`. I think the virus is inside the `ReactiveUI`, `ReactiveUI.Fody`, or both. The virus is detected on `Windows 10`.

**Comment by worldbeater** [comment]
Probably worth removing the dependency on `ReactiveUI.Fody`, there is an opinion that Fody has been picked up as a virus. @BDisp could you please try removing [`ReactiveUI.Fody`](https://github.com/migueldeicaza/gui.cs/blob/main/ReactiveExample/ReactiveExample.csproj#L7) (and the related attributes from `ReactiveExample` so the sample app compiles), in order to see if Norton complains about the newly compiled dll? I suppose we can safely remove `ReactiveUI.Fody` and replace this dependency with [manually written getters and setters](https://www.reactiveui.net/docs/handbook/view-models/#read-write-properties)

**Comment by BDisp** [comment]
So I was right of my mistrust. Anyway, it stopped giving the virus alert in the last update of Dependabot.

**Comment by worldbeater** [comment]
Hmm, probably they've just hot-fixed something. [Fody](https://github.com/Fody/Fody) is known for its heavy use of low-level stuff while performing assembly weaving and code generation, so probably the cause of the heuristic virus detection was similar to the issue in the C/C++ worlds

**Comment by BDisp** [comment]
But you can see there that is 100% C#, so there are no C++ code, unless they are embedded in C# code.

**Comment by tig** [comment]
This is fixed.
