### ISSUE TITLE
Flaw in LayoutSubviews/TopologicalSort

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#1133]
Hello,

I just realized that the code in LayoutSubviews that collects the dependencies is incomplete:

```
                        foreach (var v in InternalSubviews) {
                                nodes.Add (v);
                                if (v.LayoutStyle == LayoutStyle.Computed) {
                                        if (v.X is Pos.PosView vX)
                                                edges.Add ((vX.Target, v));
                                        if (v.Y is Pos.PosView vY)
                                                edges.Add ((vY.Target, v));
                                        if (v.Width is Dim.DimView vWidth)
                                                edges.Add ((vWidth.Target, v));
                                        if (v.Height is Dim.DimView vHeight)
                                                edges.Add ((vHeight.Target, v));
                                }
                        }
```

The issue is that this is not taking into account the Dim and Pos subclasses that combine two views, so we only do the proper job of topologically sorting when there is a direct dependency, not when there is something like view + 1 (when we create a combined pos/dim)

The code needs to handle PosCombine/DimCombine and recursively add the elements to it.

**Comment by BDisp** [comment]
Can you explain better, please. The `edges` is of type `HashSet<(View, View)>` but the `PosCombine/DimCombine` only return an `int` from the `Anchor` method.

**Comment by migueldeicaza** [comment]
Yes.

Topological sort needs to get all the view dependencies.  Currently, this is not tracking dependencies for these compound dim/pos, so the dependencies break when you use them.

What is needed is to add a check for those types and if it is one of those types, extract the dependency.

This is how I solved it in Swift:

https://github.com/migueldeicaza/TermKit/blob/master/Sources/TermKit/Core/View.swift#L1195

**Comment by BDisp** [comment]
Thanks for point me in the right direction. I also had to add recursive method inside each subviews, because the `UICatalog` have three scenarios that use the `Dim.Height` equal to sum of other `Dim.Height` views. Is the case of the `Dialogs`, `MessageBoxes` and `Progress` scenarios.
The `Application.Top` can't be referenced on another view with `Pos/Dim` class.

**Comment by tig** [comment]
marking as a 1.0 bug.

**Comment by BDisp** [comment]
I think I just fix it now.

**Comment by migueldeicaza** [comment]
Beautiful!
