### ISSUE TITLE
Unwanted characters

### ISSUE THREAD

**Issue by GladCypress3030** [migueldeicaza/gui.cs#1140]
Hello

There is appearing unwanted "␍" characters
![image](https://user-images.githubusercontent.com/65029993/111598385-fd822e00-87f0-11eb-9c47-4ff0eeefd4d7.png)
There is my write code:
```
Sub WriteLine(a As String)
        a = uncolor(a)
        Dim lines As List(Of String) = chatlog.Text.ToString.Split(vbLf).ToList
        If lines.Count > 17 Then
            lines.RemoveAt(0)
        End If
        lines.Add(a)
        chatlog.Text = String.Join(vbLf, lines)
End Sub
```
I tried to use Environment.NewLine and vbLf, vbCrLf
But "␍"characters not disappereared

**Comment by GladCypress3030** [comment]
Okay, I solved this by adding
```
For i = 0 To lines.Count - 1
        lines(i) = lines(i).Replace(vbCr, "").Replace(vbLf, "")
Next
```

**Comment by BDisp** [comment]
In the preview version this is already fixed.

**Comment by GladCypress3030** [comment]
> In the preview version this is already fixed.

okay thanks
