### ISSUE TITLE
TextFormatter.Format does not keep the end spaces on wrapped text.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1148]
I need this to be able to control TextView navigation.

**Comment by tig** [comment]
You mean TextView resizing?

**Comment by BDisp** [comment]
> You mean TextView resizing?

Yes. If I don't have all the right information of the wrapped text it is impossible to get the correct `TextView `cursor position.

**Comment by tig** [comment]
Makes total sense to me now.
