### ISSUE TITLE
FileDialog blank constructor results in unstable window

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1154]
The blank constructor `new FileDialog()` generates a window with an empty 'ok' button

![image](https://user-images.githubusercontent.com/31306100/112354308-76d3c200-8cc4-11eb-98df-8b403d0252ea.png)

Tabbing to this button crashes the application (with `IndexOutOfRangeException`).

**Comment by jmperricone** [comment]
Hi,
I think title and prompt must default to one of this: 
1) (title: "File", prompt: "Ok")
2) (title: "Open", prompt: "Open")
