### ISSUE TITLE
MoveForward/MoveBackward not bound on Text controls

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#1155]
Alt-F, and Alt-B for forward-word and backward-word do not seem to be hooked up anymore in both controls.

On TextView, it seems like backward has the wrong semantics, I suspect that when the code was moved from indexes to col/row manipulation we lost one line of code that did a "i++" after the two loops.  The equivalent would be to remember the last col/row before MoveBack is attempted and then restore that value.

**Comment by tig** [comment]
Note these fixes break the use of the Alt key for menu shortcuts. E.g. "Alt-F" will no longer open the File menu.

**Comment by BDisp** [comment]
Yes, only when a TextView has the focus. For me we can use other keys combinations.

**Comment by migueldeicaza** [comment]
There are two issues, one is the behavior of the move forward/backward which is slightly off, and the second is the keybinding.

The second could probably be solved in the presence of a menu by having the menu process the top level hot keys during the hot key phase of event dispatching, before the Text controls get a chance to see it.

**Comment by BDisp** [comment]
@migueldeicaza, please see my PR #1156 where I fixed the issue for forward/backward.
The problem as @tig said, is due the fact that the TextView/TextField key binding conflict with mouse keys binding. If letting the Menu process first the TextView will not function well. In my opinion we must avoid using the same keys bindings for Menu and other views. We must use more functions keys, Alt, Ctrl+Alt for the Menu and using the Ctrl, Shift+Ctrl for others views. The main problem is on Unix where not all combinations are caught.
We should discussing better about this.
