### ISSUE TITLE
File Open Dialog should disable 'Open' if file is blank (or not valid)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1158]
1. Run Editor in UI Catalog
2. Change directory
3. Note Open: field is empty
4. Press Open

Crash.

Instead, Open should be disabled until a filename is selected.

**Comment by BDisp** [comment]
> Instead, Open should be disabled until a filename is selected.

Or don't return until on entry is selected or press cancel button. I think this is preferable.

**Comment by BDisp** [comment]
Another question. Should this control be in the `Filedialog` base class or in the derived classes?

**Comment by tig** [comment]
> Remember that the errors after open a file must be handled by the developer who is using the dialogs and not in the bases classes. The dialogs only must return a non empty object or a cancel notification, I think.

I agree. I still think Open should be disabled until there is something to return to the caller.

**Comment by BDisp** [comment]
Done @tig. Thanks.
