### ISSUE TITLE
Text of TextField/Label only change when mouse is moving?

### ISSUE THREAD

**Issue by raiytu4** [migueldeicaza/gui.cs#116]
```
            // total page downloaded label
            var tdpLabel = new Label("TPD")
            {
                X = Col10Pos,
                Y = 1,
                Width = 30,
                Height = 1
            };
            win.Add(tdpLabel);
            new Thread(() =>
            {
                Task.Delay(3000).Wait();
                tdpLabel.Text = $"123";
            }).Start();
            Application.Top.Add(win, menu);
            Application.Run();
```

The text in tdpLabel should change to "123" after the application running for 3 seconds. But only when the mouse is in the console and moving. If the mouse is outside of the console, nothing changes. 

Any idea about this?

**Comment by migueldeicaza** [comment]
Yes, you are not supposed to do that, the API is not thread safe :-)

If you need to update the UI from a background thread, you need to use `Application.MainLoop.Invoke (Action)` to trigger the code to run on the main UI.

In your case:

```
Application.MainLoop.Invoke (() => tdpLabel.Text = "123");
```
