### ISSUE TITLE
container.RemoveAll();

### ISSUE THREAD

**Issue by winkmichael** [migueldeicaza/gui.cs#118]
When trying to remove all the previous objects via container.RemoveAll(); the process dies

                var menu = new MenuBar(new MenuBarItem[] {
                new MenuBarItem ("_Settings", new MenuItem [] {
                new MenuItem ("_Network", "", () => Network (win))};

        static void Network(View container)
        {
                container.RemoveAll();
       }

**Comment by winkmichael** [comment]
Is this related to this item?
https://github.com/migueldeicaza/gui.cs/pull/117

**Comment by IKoshelev** [comment]
Also getting this issue.
Actually, if you simply call win.RemovewAll() in example from main page before adding UI elements - the app won't load.

` Application.Init ();
        var top = Application.Top;

	// Creates the top-level window to show
        var win = new Window (new Rect (0, 1, top.Frame.Width, top.Frame.Height-1), "MyApp");
        top.Add (win);

	// Creates a menubar, the item "New" has a help menu.
        var menu = new MenuBar (new MenuBarItem [] {
            new MenuBarItem ("_File", new MenuItem [] {
                new MenuItem ("_New", "Creates new file", NewFile),
                new MenuItem ("_Close", "", () => Close ()),
                new MenuItem ("_Quit", "", () => { if (Quit ()) top.Running = false; })
            }),
            new MenuBarItem ("_Edit", new MenuItem [] {
                new MenuItem ("_Copy", "", null),
                new MenuItem ("C_ut", "", null),
                new MenuItem ("_Paste", "", null)
            })
        });
        top.Add (menu);

////////////////////////////////////////////////////////////////////////////////////////
 win.RemoveAll();                           //this kills it
///////////////////////////////////////////////////////////////////////////////////////
	
// Add some controls
	win.Add (
            new Label (3, 2, "Login: "),
            new TextField (14, 2, 40, ""),
            new Label (3, 4, "Password: "),
            new TextField (14, 4, 40, "") { Secret = true },
            new CheckBox (3, 6, "Remember me"),
            new RadioGroup (3, 8, new [] { "_Personal", "_Company" }),
            new Button (3, 14, "Ok"),
            new Button (10, 14, "Cancel"),
            new Label (3, 18, "Press ESC and 9 to activate the menubar"));

        Application.Run ();
`

**Comment by IKoshelev** [comment]
Update, `win.RemoveAll(); ` is sort of expected, to clear up the window one should call RemoveAll() on the content subview of window.

`win.Subviews[0].RemoveAll(); //your precise index may warry`

P.S. RemoveAll seems to have an issue in latest nuget, you may need to build from source.

**Comment by winkmichael** [comment]
IKoshelev: thanks for that feed back, that somewhat helps me a fair bit. Any way to determine your index?

**Comment by migueldeicaza** [comment]
Window should have overwritten `RemoveAll` to remove the contents of the containerView.

**Comment by migueldeicaza** [comment]
Fixed
