### ISSUE TITLE
View.Remove

### ISSUE THREAD

**Issue by dbuzz111** [migueldeicaza/gui.cs#119]
The correct way to use view.remove() seems unclear. When passing a view to a new method I cannot see any exposure of the objects that exist in this view. In addition it appears at RemoveAll is currently broken.

Any suggestions on a clear way to call .Remove and be aware of the content of the view?

Thanks
D

**Comment by migueldeicaza** [comment]
You pass to a container the view that you want to remove:

```
window.Remove (label_inside_the_window);
```
