### ISSUE TITLE
ListView.ProcessKey() Key.Enter handler

### ISSUE THREAD

**Issue by obender12** [migueldeicaza/gui.cs#1196]
Currently Key.Enter handler in ListView.ProcessKey() breaks from switch rather than returning true after calling OnOpenSelectedItem (). This results in multiple OnOpenSelected events (I counted 7) after a single Enter press.

**Comment by obender12** [comment]
(possible duplicate of https://github.com/migueldeicaza/gui.cs/issues/1183)

**Comment by BDisp** [comment]
Yes it is :-)
