### ISSUE TITLE
Wrong horizontal frame border on Linux (WSL/Ubuntu 18.04)

### ISSUE THREAD

**Issue by odalet** [migueldeicaza/gui.cs#121]
The frame borders seem to render incorrectly - but only the horizontal ones - when using WSL/Ubuntu 18.04. 

I couldn't reproduce the issue neither in a Debian VM nor in my WSL/Debian 9.3 instance... I suppose it is related to Ubuntu 18.04...

See screenshots below:

Windows: 
![wingui](https://user-images.githubusercontent.com/79333/44104464-40a69b86-9fef-11e8-9bb8-75c83a16c5f9.png)

WSL/Debian 9.3:
![wsldebgui](https://user-images.githubusercontent.com/79333/44106339-ad5ff628-9ff4-11e8-8752-75143f7fa2dd.png)

Debian 9 (VM):
![virtualbox_debian_14_08_2018_18_53_23](https://user-images.githubusercontent.com/79333/44105992-a856dea4-9ff3-11e8-9d32-8896fc66f13b.png)

WSL/Ubuntu 18.04:
![wslgui](https://user-images.githubusercontent.com/79333/44104489-4b61f7b4-9fef-11e8-96c8-5ef448f849a6.png)

**Comment by odalet** [comment]
OK, so I've dug a bit. Here is what I came to:
* The weird behavior only happens with Ubuntu 18.04 / WSL  when the application is run from a Windows Command box; it runs just fine when launched from a gui terminal (I tested xterm and konsole)
* It is not limited to the horizontal line, but happens each time a character sent to addch is the same as the previous one (tried with a line of dashes or 'a'... all the same: only one character is output)

I reproduced the same behavior with a C program by directly targetting ncursesw

By looking at some other source code, and reading in the ncurses documentation, it appeard that one should call `setlocale(LC_ALL, "");` before any use of ncurses. I did just that and it worked. I ported this to my C# code (with interop), and was able to have the windows draw correctly.

Here is the repro code (just comment out the call to `UbuntuHack` to verify the wrong behavior):

```csharp
using System;
using System.Runtime.InteropServices;
using System.Threading;
using Terminal.Gui;

namespace TerminalUbuntuRepro
{
    internal static class Program
    {
        private static class UbuntuHack
        {
            private const int LC_ALL = 6;

            public static void Execute()
            {
                // Should do this if platform is MacOSX as well?
                if (Environment.OSVersion.Platform == PlatformID.Unix) 
                    setlocale(6, "");
            }

            [DllImport("libc.so.6")]
            private extern static IntPtr setlocale(int category, [MarshalAs(UnmanagedType.LPStr)]string locale);

        }

        private static void Main(string[] args)
        {
            UbuntuHack.Execute();

            Application.UseSystemConsole = false;
            Application.Init();

            var win = new Window("Test");
            Application.Top.Add(win);

            var state = Application.Begin(win);

            DrawTest(Application.Driver);

            Thread.Sleep(3000);
            Application.End(state);
        }

        private static void DrawTest(ConsoleDriver driver)
        {
            driver.SetAttribute(Colors.Base.Normal);

            driver.Move(13, 2);
            for (var i = 0; i < 10; i++)
                driver.AddRune((uint)('0' + i));

            driver.Move(13, 3);
            driver.AddRune(driver.ULCorner);
            for (var i = 1; i < 9; i++)
                driver.AddRune(driver.HLine);
            driver.AddRune(driver.URCorner);

            driver.Refresh();
        }
    }
}
```

Maybe the call to `setlocale` should be part of the initialization steps for the Curses drviers... the bottom line is I don't know why this is needed in my Ubuntu/WSL case, and there may be a cleaner solution; however, it just works in my case.

**Comment by migueldeicaza** [comment]
This makes sense, let me look into baking this in.

**Comment by odalet** [comment]
Thanks!

**Comment by odalet** [comment]
Well, 2y after this issue and having checked the new version works correctly even in my Ubuntu/WSL setup, I suppose I can close this. You have work enough with the other open issues :)
