### ISSUE TITLE
How Tab and Shift+Tab keys should be performed on TextView?

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1210]
- In my opinion `Tab` should insert the `char 9` and the `Shift+Tab` should retreat the `char 9` to the previous column, because on a multiline editor is normal to press the tab key to insert spaces and and Shift+Tab to remove spaces. So, if it goes to the next view, forces us to go to the `TextView` again causing stressing.
- Another solution is replacing the tabs to spaces, but if the original text has tabs it should be maintained. Perhaps an option to convert to spaces or vice-versa.
- For navigation `Ctrl+Tab` should go to the next view and `Ctrl+Shift+Tab` should go to the previous view.
- Please, give your opinions to makes this definitively clear. Thanks in advance.

**Comment by tig** [comment]
I'm a Windows user. Windows has very a very clear, and very consistent model for this. 

- Tab moves forward through the hierarchy of controls that can be selected (*)
- Shift-tab moves backwards through the hierarchy of controls that can be selected
- Ctrl-Tab moves forward between windows or tabs in a list of open windows or tabs (e.g. in a web browser)
- Ctrl-Shift-Tab moves backwards through the same

(*) The exception is when the control that has focus is an edit control that has declared that the user can enter tabs. In this case, tab enters the `tab` (`char 9`) into the text field. Shift-tab continues to work to navigate backwards.

I do not know if this is consistent on Mac or Linux. 

The vast majority of the time when a user is using a Terminal.Gui app they ARE NOT TYPING IN A TEXT VIEW THAT NEEDS TO ACCEPT TABS. Thus I think the most common case is using tab for navigation and thus tab/shift-tab should navigate. Only in the rare case when the user is using a text view THAT REQUIRES/ALLOWS tabs should this behavior change. 

That's my opinion.

**Comment by BDisp** [comment]
I agree and that exception is  the case of TextView which is allowed to editt with tabs and Shift + tabs

**Comment by tznind** [comment]
In WinForms there is a boolean property for this `AcceptsTab` and also `AcceptsReturn` (both default to false).  Not sure if that helps just thought I'd add another perspective.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textboxbase.acceptstab?view=net-5.0

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textbox.acceptsreturn?view=net-5.0

**Comment by BDisp** [comment]
Thanks for the links. Since T`erminal.Gui` already have two text edit views, one for single line (`TextField`) and other for multiple line (`TextView`), there is no need to both the views have the same features.
So, `AcceptsReturn` don't justify to use in the `TextView` because it's already a multiline view and need the return key to edit, but if you think is better to activates the default button for the superview, if it's false, please say your opinions.
The `AcceptsTab` I've thought already to use it and set it to true by default to edit the text.
About the properties names do you think we can use the same as winforms or our own names?

**Comment by tznind** [comment]
> So, `AcceptsReturn` don't justify to use in the `TextView` because it's already a multiline view and need the return key to edit, but if you think is better to activates the default button for the superview, if it's false, please say your opinions.

Yeah I think you are right we don't need an `AcceptsReturn` that was my mistake.  I meant to bring it up as precedent for giving the API user control of these types of things (not that we should add it).

> The `AcceptsTab` I've thought already to use it and set it to true by default to edit the text.
> About the properties names do you think we can use the same as winforms or our own names?

That makes sense.  Using the same names as other APIs is almost always a good idea since it helps establish a standard.  So unless this function exists in a bunch of other APIs under a different name I'd say go with `AcceptsTab`.

**Comment by BDisp** [comment]
- Although it's not very difficult to add single line feature to the `TextView`, I won't waste time with that.
- So, I decided to use these two features and with the following names. If anyone don't agree please say something:

> `AllowsReturn` - `true` (default ) if the `Key.Enter` creates a new line of text and `false` if the `Key.Enter` key activates the default button for the superview.

> `AllowsTab` - `true` (default) if users can enter tabs in a `TextView` using the `Key.Tab` and `false` if pressing the `Key.Tab` moves the focus to next view. If `true`, the `Shift + Key.Tab` will delete the previous `tab`, if if there is any, and if `false` the `Shift + Key.Tab` moves the focus to previous view.

PS: I opted for the `Allows` word because we have some APIs started with that word and none for `Accepts`. The majority win :-)

**Comment by BDisp** [comment]
`AllowsReturn = false` makes the `TextView` a single line text edit box :-)

**Comment by tig** [comment]
I think this is a good plan.
