### ISSUE TITLE
TextField uses large amounts of memory relative to text entered

### ISSUE THREAD

**Issue by antijingoist** [migueldeicaza/gui.cs#1213]
Versions tested: 1.0.0-beta.8, 0.90.3
When entering large amounts of text into a TextField, memory usage seems to increase by megabytes, first noticed when entering 500 characters of text. The same text entered into a TextView does show the any noticeable increase in memory usage. 

Tested by creating a new .net core console application in visual studio 2019 on Windows. Added Terminal.gui via nuget, and added a single Window with one TextField. Text pasted was a randomized string containing only alphanumeric characters.
The test was repeated with a TextView to see if it was also affected, but there was no noticeable memory increase.

Approximate Memory usage increased by character count: 
- 1,000 / 5mb
- 10,000 / 53mb
- 20,000 / 330mb

**Comment by BDisp** [comment]
That is because of the history text features it uses for undo/redo.

**Comment by tig** [comment]
Closing as by-design.
