### ISSUE TITLE
How to run on Debian Linux?

### ISSUE THREAD

**Issue by VoIPTools** [migueldeicaza/gui.cs#123]
When I try to run the examples on Windows everything works fine.  When I try to run on Debian I get this error:

Curses failed to initialize, the exception is: System.EntryPointNotFoundException: Unable to find an entry point named 'dlopen' in DLL 'libc'.
   at Unix.Terminal.Curses.libc_dlopen(String file, Int32 mode)
   at Unix.Terminal.Curses.DlOpen(String path)
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Window' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'dlopen' in DLL 'libc'.
   at Unix.Terminal.Curses.libc_dlopen(String file, Int32 mode)
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Unix.Terminal.Curses.Window..cctor()
   --- End of inner exception stack trace ---
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init()
   at Demo.Main() in C:\Users\morr\Downloads\gui.cs-master\gui.cs-master\StandaloneExample\Program.cs:line 172
Aborted

**Comment by philcarbone** [comment]
Error message is similar and stacktrace is identical in Ubuntu...
Curses failed to initialize, the exception is: System.EntryPointNotFoundException: Unable to find an entry point named 'dlopen' in shared library 'libc'.
   at Unix.Terminal.Curses.libc_dlopen(String file, Int32 mode)
   at Unix.Terminal.Curses.DlOpen(String path)
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)

**Comment by philcarbone** [comment]
I fixed my issue by installing the ncurses development package:
`sudo apt-get install libncurses5-dev`

then I was able to run my .net core app:
`dotnet run`

All is working well now, in Ubuntu (in regard to this problem). 

I have a frame border issue now, but there is already an open issue for that here: https://github.com/migueldeicaza/gui.cs/issues/121

**Comment by VoIPTools** [comment]
Philcarbone, your suggestion got me 99% of the way there.  But I was getting goofy line drawing characters.  I found when running directly on the Debian desktop everything looked fine, but when running in putty I got goofy characters.  This clued me in that it was a putty issue not a Terminal.Gui issue.  I Googled and tinkered for a bit and discovered if I changed the putty settings everything looked fine.  The setting I changed in putty was:  Window --> Translation --> Remote character set -->  Use font encoding.

**Comment by migueldeicaza** [comment]
I think we need to add a call to setlocale, see:

https://github.com/migueldeicaza/gui.cs/issues/121

The library issue with Debian is a known problem.   While there is a mono-specific solution, we need one solution that also works for .NET Core and that just happens to be tedious to write :-(

**Comment by migueldeicaza** [comment]
I have done some of the work now on in the `dynamic-library-loader` branch

**Comment by migueldeicaza** [comment]
Work is completed, I will merge tomorrow.

**Comment by migueldeicaza** [comment]
I have now pushed a fix, Nuget version 0.18  should work out of the box on Debian,

**Comment by VoIPToys** [comment]
I'm running 0.19 and have installed libncurses5 libraries.  I still have border issues (funky characters rather than line-draw characters) when running on Debian using putty.
