### ISSUE TITLE
Multi_Thread_Toplevels unit tests fails if run standalone or in different order

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1238]
I just discovered that `Multi_Thread_Toplevels` in `UnitTests/ViewTests.cs` fails if it is run as a standalone test or if the order of what tests run before it change.

![image](https://user-images.githubusercontent.com/585482/115580310-d0a3b980-a27b-11eb-8cc0-494f9e93bbab.png)

I discovered this when I was re-factoring how the unit tests are organized. 

This test has some dependency from prior running tests that allow it to succeed. Or there is actually a bug in `MainLoop` that is HIDDEN because of another unit test.

If all of the tests in the `ViewTests.cs` are run, it does not fail. So the dependency is likely in there.

@BDisp I think I will need you help debugging this!

**Comment by BDisp** [comment]
> If all of the tests in the `ViewTests.cs` are run, it does not fail. So the dependency is likely in there.

It fail when run all tests at once.

**Comment by tig** [comment]
I've found that simply changing the name of the method (e.g. to `zMulti_Thread_Toplevels`) can change whether it works or not when run with the other tests!

**Comment by BDisp** [comment]
Starting with an 'a' fail lol. Damn.

**Comment by tig** [comment]
Did you write this test cas or did I? I don't remember!

I also, clearly, don't remember what it was exactly supposed to be testing. Fail.

**Comment by tig** [comment]
you did:

![image](https://user-images.githubusercontent.com/585482/115586190-2dee3980-a281-11eb-8273-c0759aeba98c.png)

**Comment by BDisp** [comment]
Yes I did. I have to review it again. But why changing to 'z' it work lol.

**Comment by tig** [comment]
I'm going to comment it out in my code coverage PR. When you figure it out and fix, please uncomment that. Thanks!

**Comment by BDisp** [comment]
I already fixed. How to uncomment that and fix?

**Comment by tig** [comment]
I'll just update my pr.

What was the problem and what was the fix?

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by BDisp** [comment]
> What was the problem and what was the fix?

On line 947 replace to this:

`if (count1 > 12 && count < 15) `

**Comment by tig** [comment]
That doesn't explain what the problem was. I'd like to understand the root cause.

Can you please explain?

**Comment by BDisp** [comment]
Something in your configuration changes the `MainLoop` timer. Before when count  was less than 15 and count1 greater than 13, or equal to 14 it pass. Now when count is equal to 14 the count1 is equal to 13. I haven't an explanation for this, sorry.

**Comment by tig** [comment]
We should not feel satisfied with this test until we can explain it!

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by BDisp** [comment]
I agree. I'm comparing in both to see if I can find it out.

**Comment by BDisp** [comment]
@tig it should be like this.
`count` it's one more than the others two and `count1` it's one more than the `count2` which stopped at 10.

```cs
		public void Multi_Thread_Toplevels ()
		{
			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));

			var t = Application.Top;
			var w = new Window ();
			t.Add (w);

			int count = 0, count1 = 0, count2 = 0;
			bool log = false, log1 = false, log2 = false;
			bool fromTopStillKnowFirstIsRunning = false;
			bool fromTopStillKnowSecondIsRunning = false;
			bool fromFirstStillKnowSecondIsRunning = false;

			Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (100), (_) => {
				count++;
				if (count1 == 5) {
					log1 = true;
				}
				if (count1 == 14 && count2 == 10 && count == 15) { // count2 is already stopped
					fromTopStillKnowFirstIsRunning = true;
				}
				if (count1 == 7 && count2 == 7 && count == 8) {
					fromTopStillKnowSecondIsRunning = true;
				}
				if (count == 30) {
					Assert.Equal (30, count);
					Assert.Equal (20, count1);
					Assert.Equal (10, count2);

					Assert.True (log);
					Assert.True (log1);
					Assert.True (log2);

					Assert.True (fromTopStillKnowFirstIsRunning);
					Assert.True (fromTopStillKnowSecondIsRunning);
					Assert.True (fromFirstStillKnowSecondIsRunning);

					Application.RequestStop ();
					return false;
				}
				return true;
			});

			t.Ready += FirstDialogToplevel;

			void FirstDialogToplevel ()
			{
				var od = new OpenDialog ();
				od.Ready += SecoundDialogToplevel;

				Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (100), (_) => {
					count1++;
					if (count2 == 5) {
						log2 = true;
					}
					if (count2 == 4 && count1 == 5 && count == 5) {
						fromFirstStillKnowSecondIsRunning = true;
					}
					if (count1 == 20) {
						Assert.Equal (20, count1);
						Application.RequestStop ();
						return false;
					}
					return true;
				});

				Application.Run (od);
			}

			void SecoundDialogToplevel ()
			{
				var d = new Dialog ();

				Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (100), (_) => {
					count2++;
					if (count < 30) {
						log = true;
					}
					if (count2 == 10) {
						Assert.Equal (10, count2);
						Application.RequestStop ();
						return false;
					}
					return true;
				});

				Application.Run (d);
			}

			Application.Run ();
			Application.Shutdown ();
		}

```

**Comment by BDisp** [comment]
> 
> We should not feel satisfied with this test until we can explain it!
> 

Well, I think the explanation is that before `MainLoop` did not immediately run the `Appication.Top` timer. Therefore, it does not make sense the counter of the second `MainLoop` has been previously equal to the first.
`count1 > 13 && count < 15` == `14`

**Comment by tig** [comment]
Fixed
