### ISSUE TITLE
Add multi-step Wizard view

### ISSUE THREAD

**Issue by GaikwadPratik** [migueldeicaza/gui.cs#124]
Hi,
This is an awesome library. I like it very much. I am trying to create an application based on form wizard for initial setup but in Linux. Regarding that I have few questions.
I am thinking of adding a `window` as `container` in the `Application.Top`. This container will load the `View` dynamically. I am also adding two buttons `Next` and `Previous` in the `Top` outside `container`. 
Here are my questions:

1. My first form has really long text that I need to display along with `scroll bar` and `radio button`. Which view should I choose? `ScrollView`, `ScrollBarView`, `TextView`?
2. Can the `TextView` be rendered with `readonly` attribute?
3. `Previous` and `Next` button are rendered outside of `Top` frame. Since those are going to remain static, how do I render them inside `Top` but outside `container`?

![screenshot from 2018-09-12 06-03-40](https://user-images.githubusercontent.com/36861239/45418992-014afd80-b654-11e8-9e55-c556fcf81300.png)

4. `tab` key navigates between only `views` inside `container`. i.e. in the above image, `tab` will switch focus between `textview` and `radio button`. Control doesn't focus on either `Previous` or `Next` buttons at all.
5. `Window.removeAll()` doesn't seem to remove the `view`s immediately. I have to focus somewhere manually. Since I would like to keep one container for various forms, how do I solve this?

Here is my code:
`Program.cs`

```using System;
using System.Threading.Tasks;
using Terminal.Gui;

namespace hive_appliance_console
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Application.Init();
            var top = Application.Top;

            //Create top level window to show
            var _formContainer = new Window("Hive Appliance Console")
            {
                X = 0,
                Y = 1,
                // Width = top.Frame.Width, 
                // Height = top.Frame.Height - 1
                Width = Dim.Fill(),
                Height = Dim.Fill() - 1
            };

            var menu = new MenuBar(new MenuBarItem [] 
            {
                new MenuBarItem("_Menu", new MenuItem [] 
                {
                    new MenuItem ("_Quit", "", () => 
                    { 
                        if (Quit ()) 
                        {
                            Application.RequestStop(); 
                        }
                    })
                })
            });

            var _eula = new Eula();
            _eula.LoadView(_formContainer);

            var _btnNext = new Button("Next") 
            { 
                X = Pos.Center() + 4,
                Y = Pos.Bottom(_formContainer),
                // Clicked = () => {
                //     _formContainer.RemoveAll();
                // }
            };
            var _btnPrevious = new Button("Previous") { X = Pos.Center() - 10, Y = Pos.Bottom(_formContainer)};

            top.Add(
                menu,
                _formContainer,
                _btnPrevious,
                _btnNext
            );
            Application.Run();
        }

        static bool Quit ()
        {
            var n = MessageBox.Query (50, 7, "Quit setup", "Are you sure you want to quit setup process?", "Yes", "No");
            return n.Equals(0);
        }
    }
}
```

and `Eula.cs`

```
using System;
using System.Collections.Generic;
using Terminal.Gui;

namespace hive_appliance_console
{
  public class Eula
  {
    private string _eulaFilePath = @"/home/pratik/hive/code/hive-appliance-console/eula.txt";

    public void LoadView(View container)
    {
        var _window = new Window("EULA");
        var _textView = new TextView()
        {
            X = 2,
            Y = 1,
            Width = Dim.Fill(),
            Height = Dim.Fill() - 2
        };
        _textView.LoadFile(_eulaFilePath);
        _window.Add(_textView);
        
        var _consent = new RadioGroup(new [] {"I accept", "I decline"}, 0)
        {
            X = Pos.Center(),
            Y = Pos.Bottom(_textView)
        };
        _window.Add(_consent);
        container.Add(_window);
    }
  }
}
```
Since you are in the process of creating document, I am asking this long question here. I feel like once this is resolved, I can work on my own.

**Comment by migueldeicaza** [comment]
This is a good feature request, a read-only textview, I should add that.   Alternatively, you can create a `ReadOnlyTextView : TextView` that essentially ignores any keyboard commands.

**Comment by migueldeicaza** [comment]
I will take a look at your EULA example tomorrow hopefully, just implemented the readonly capability.

**Comment by GaikwadPratik** [comment]
@migueldeicaza Thank you for implementing the `ReadOnly` feature. It wasn't processing `Tab` key because `Readonly` feaure. I have modified the code for that. I have also added code to process `Page Up` and `Page Down` keys. Can you please take a look at https://github.com/migueldeicaza/gui.cs/pull/129 ?

**Comment by tig** [comment]
Wizard: #469

**Comment by GaikwadPratik** [comment]
@tig ,

I'm wondering, after seeing so many changes in the library, if we can work this up. It has been almost 2 years, I think I am at the point where I really need to replace the text based UI that we have, mainly because it _sucks_. 

Can we work together and create a demo project that would be implement wizard structure? I'll update https://github.com/GaikwadPratik/TerrminalWizard to use latest nuget. We can use that as a demo project.

Waiting for your thoughts...

**Comment by tig** [comment]
Bring it on!

I think it'd be a great way to start for to share the user flow you have in mind. What are each wizard step? What are the transitions? Etc...

**Comment by GaikwadPratik** [comment]
@tig,

Awesome to know that you are onboard...

I've collected some initial flow that we can start with. I'll then extend it as per my needs. This should cover most of the elements in GUI.CS library. 

[Appliance Console.docx](https://github.com/migueldeicaza/gui.cs/files/6875346/Appliance.Console.docx)

I can add you as contributor to the repo, if you are okay with it. Once finished we can merge the repo in `Examples` collection

I'm wondering if we can use some sort of DM application, else this comment section will be too big.

Awaiting for your response...

**Comment by GaikwadPratik** [comment]
@tig,

any suggestions as to how should I start?

**Comment by GaikwadPratik** [comment]
@tig ,

I apologize for tagging you _again_ but can we please pick this up? I want to be able to change the inner screen based on button click(s)

**Comment by tig** [comment]
> I've collected some initial flow that we can start with. I'll then extend it as per my needs. This should cover most of the elements in GUI.CS library.
> 
> [Appliance Console.docx](https://github.com/migueldeicaza/gui.cs/files/6875346/Appliance.Console.docx)
> 

* Wizard Framework 
  * The wizard UI has the following elements:
    * `Wizard` - A class derived from `Dialog`
      * The title should just be the Window `Title`/`Text`
      * Default size TBD - Your pics show it being full screen. I don' think that's a good idea as some users use very large terminal windows. I suggest a requirement of the framework be "By default works as a pop-up/non-full-screen window with an intelligent default size."
    * ControlPane - The pane where the developer adds controls for the wizard step the user is on. 
      * Goes on the left, using `Dim.Percent(50)`, by default.
      * If this could just be a hosted `Dialog` it would be ideal; that way all of the logic currently in `Dialog` is re-used.
    * separator - a vertical `LineView`
    * HelpPane - The pane where the developer provides help text for the step for the user. 
      * Goes on the right, using `Dim.Percent(50)` (therefore equally sized with the Controls). 
      * Just a `TextView` and the API to set it is `HelpPane.Text = ...`. 
    *  ActionPane - The pane where the `Reset`, `Next`, etc.... buttons go. 
      *  3 rows tall (same as height of `Button`)
      * `Width = Dim.Percent(100)`
      * Includes two `Button` by default
        * `Back` - Aligned left (default `Text = "Back")
          * If `wizard.ActiveStep == wizard.Steps[0] then wizard.ActionPane.Back.Visible = false else wizard.ActionPane.Back.Text = "Next..."`
        * `Next` - Aligned right.
          * If `wizard.ActiveStep == wizard.Steps[wizard.Steps.Length] then wizard.ActionPane.Next.Text = "Finish" else Wizard.ActionPane.Next.Text = "Next..."`
          * If user presses ENTER at anytime `Next` does Clicked`.
    * `Finished` property - Set to `true` to indicate user has done everything required of the wizard
    * Keys
      * ESC cancels wizard. If `wizard.Finished == false` a message box asking for confirmation is shown.
      * ENTER does `Clicked` on `Next` button. 
    * Events - Calling app can just wire up to events of the embedded views (e.g. `wizard.ActionPane.Next.OnClicked += ...`. 
      * Probably need `StepChanged`

> I can add you as contributor to the repo, if you are okay with it. Once finished we can merge the repo in `Examples` collection
> 

You have two 'r' in `GaikwadPratik/TerrminalWizard` btw...

> I'm wondering if we can use some sort of DM application, else this comment section will be too big.

Let's just use this Issue. 

> I've no idea how to start. Current code in that repo is based on status of the GUI.CS at the time. I think that is not the correct way to proceed. So I'll need your thorough guidance initially
> 
> Awaiting for your response...

This shows basic usage:

```csharp
// Create Wizard
            var btnWizard = new Button(text: "Launch Wizard") 
            { 
                Id = "btnWizard",
                X = Pos.Center(),
                Y = Pos.Center()
            };

            btnWizard.Clicked += () => 
            {
                var backBtn = new Button("Back");
                var nextBtn = new Button("Next");
                nextBtn.IsDefault = true;
                var wizard = new Wizard("Demo Wizard", new Button[]{ backBtn, nextBtn });
                nextBtn.Clicked += () => {
                    Application.RequestStop ();
                };                

                wizard.Steps.Add(new Wizard.WizardStep("First Step"));
                wizard.Steps[0].HelpPane.Text = "This is the help text for the First Step.";
                var editLbl = new Label() { Text = "Edit: ", AutoSize = true, X = 1, Y = 10 };

                var edit = new TextField() {
                    Text = "hello world",
                    X = Pos.Right(editLbl),
                    Y = Pos.Top(editLbl),
                    Width = 40,

                };
                wizard.Steps[0].ControlPane.Add(editLbl, edit);

                wizard.Add(wizard.Steps[0]);
                Application.Run(wizard);

            };
```

Here's the start of the `Wizard` class:

```csharp
using System.Collections.Generic;
using NStack;

namespace Terminal.Gui {
	/// <summary>
    /// Provides a step-based Wizard.
	/// </summary>
	/// <remarks>
	/// </remarks>
	public class Wizard : Dialog {
        /// <summary>
        /// One step for the Wizard.
        /// </summary>
        /// <remarks>
        /// </remarks>
        public class WizardStep : View {
            public ustring Title;
            public View ControlPane = new View();
            public TextView HelpPane = new TextView();

            /// <summary>
            /// Initializes a new instance of the <see cref="Wizard"/> class using <see cref="LayoutStyle.Computed"/> positioning.
            /// </summary>
            /// <param name="title">Title for the Step. Will be appended to the containing Wizard's title as 
            // "Wizard Title - Wizard Step Title" when this step is active.</param>
            /// <remarks>
            /// </remarks>
            public WizardStep (ustring title) {
                Title = title;
                Height = Dim.Fill(2); // for button frame
                Width = Dim.Fill();

                ControlPane.ColorScheme = Colors.Dialog;
                ControlPane.Height = Dim.Fill();
                ControlPane.Width = Dim.Percent(50);

                HelpPane.ColorScheme = Colors.Dialog;
                HelpPane.X = Pos.Right(ControlPane) + 1;
                HelpPane.Height = Dim.Fill();
                HelpPane.Width = Dim.Fill();

                this.Add(ControlPane);

                var separator = new LineView(Graphs.Orientation.Vertical);
                separator.X = Pos.Right(ControlPane);
                separator.Height = Dim.Fill();
                this.Add(separator);

                this.Add(HelpPane);
            }
        }

        public List<WizardStep> Steps = new List<WizardStep>();

		/// <summary>
		/// Initializes a new instance of the <see cref="Wizard"/> class using <see cref="LayoutStyle.Computed"/> positioning.
		/// </summary>
		/// <param name="title">Title for the Wizard.</param>
		/// <param name="buttons">Optional buttons for the bottom of the Wizard.</param>
		/// <remarks>
		/// The Wizard will be vertically and horizontally centered in the container and the size will be 85% of the container. 
		/// After initialization use <c>X</c>, <c>Y</c>, <c>Width</c>, and <c>Height</c> to override this with a location or size.
		/// </remarks>
		public Wizard (ustring title, params Button [] buttons) : base (title: title, width: 0, height: 0, buttons: buttons) {
            if (buttons.Length > 0) { 
                buttons[buttons.Length-1].IsDefault = true;
            }
        }

    }
}
```

**Comment by GaikwadPratik** [comment]
@tig 
I can't find `WizardClass` in the [Terminal.Gui](https://github.com/migueldeicaza/gui.cs) library. Are we going to keep it as a separate class in my project temporarily till it is fully baked and then move it to this library?

P.S. I added you as a collaborator.

**Comment by tig** [comment]
It’s not there yet. If you are willing to help, use the starter code I pasted to add it (in the Terminal.gui/Windows folder), add a UI Catalog scenario, and unit tests. Then do a PR.


-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by tig** [comment]
I had some time this afternoon and dove into coding the wizard up further. I'm about to take off on a 12 hour flight may make more progress. No internet on flight so it'll be a day before I can share the work.

**Comment by tig** [comment]
@GaikwadPratik - Please check out the new `Wizard` in main. I hope it works for your use cases!

Please submit new Issues if you would like to see changes.

**Comment by BDisp** [comment]
After clicking in the `TextView` the buttons don't respond to clicks anymore.

**Comment by GaikwadPratik** [comment]
@tig, 

How do I use that commit in my project? You will need to release 1.6.5 in nugget for me to consume it, right?

**Comment by tig** [comment]
Clone gui.cs, ‘dotnet build’, and change your projects .csproj to point to Terminal.Gui/bin/…/Terminal.gui.dll.

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by tznind** [comment]
> @tig,
> 
> How do I use that commit in my project? You will need to release 1.6.5 in nuget for me to consume it, right?

The method @tig suggests is the simplest.  But if your code is already in a GitHub repo you could also set 'gui.cs' as a submodule.  That would let you pull any updates from gui.cs as they are merged without having to wait for a nuget release.  To do that you can see here:

https://www.pluralsight.com/guides/using-git-submodules-to-reference-one-git-repository-from-another
