### ISSUE TITLE
Refactor TreeView to reduce surface area

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1240]
@tznind Before we ship 1.0 I'd like us to consider a breaking API change for TreeView to encapsulate the auxiliary types better.

Ideally (not sure if this is possible) we'd have a single class `TreeView` that had `TreeBuider`, `ITreeView`, `Treestyle`, etc... all as nested types. 

I think there should be a `TreeView` sub-folder of `Views` that includes `Tree*.cs`. 

Note you can use `partial` to still keep the various classes in their own files. https://stackoverflow.com/questions/9143046/nested-partial-class

Can you investigate the cleanest way to do this?

**Comment by tznind** [comment]
Hmn so `TreeView` inherits from `TreeView<T>`

Many of the auxiliary classes are also generic which would complicate things:

https://stackoverflow.com/questions/8765211/how-do-i-get-an-inner-class-to-inherit-enclosing-class-generic-type

Would a namespace be an acceptable solution?

The use of generics is so the user can create:

- `TreeView<People>`  and implement an `TreeBuilder<People>` 
- The `TreeView` (non generic) is just an `TreeBuilder<ITreeNode>` with a default builder set up

The goal is to avoid the user having to wrap every instance of their data class `People` with a tree node wrapper when it is easier for them just to implement the builder that tells the tree how to find children itself.

**Comment by tig** [comment]
Fixed in #1246
