### ISSUE TITLE
Update README.md to point to TextValidateField API docs

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1245]
.

**Comment by jmperricone** [comment]
They are not generated yet. Its ok ?

**Comment by tig** [comment]
Actually I already did this.  We can close this issue

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by jmperricone** [comment]
Oh, I didn't see that you just added it.

**Comment by tig** [comment]
Yeah, i tagged this in my pr, expecting it to close automatically, but for some reason it didn't.

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by BDisp** [comment]
404 File not found
Not working.

**Comment by BDisp** [comment]
In the md file:
https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.TextValidateField.html

In the API Reference:
https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.TextValidateField-1.html

**Comment by tig** [comment]
Oops. I guessed wrong.

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by tig** [comment]
I've fixed this in the `V1_0_0_0` branch.
