### ISSUE TITLE
TextValidateField has XML doc errors

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1255]
![image](https://user-images.githubusercontent.com/585482/116285217-c7669100-a742-11eb-9cd5-73db07dd5e96.png)

@jmperricone, please fix by adding `///<inheritdoc/>` as appropriate.

**Comment by jmperricone** [comment]
I saw that now the class definition is 
```csharp
public class TextValidateField<T> : View, ITextValidateProvider where T : class {
```

TextValidateField dosen't realy need to implement ITextValidateProvider. and T must to be of type ITextValidateProvider

**Comment by jmperricone** [comment]
I explain this because the error is because now TextValidateField must implement `Fixed` Property, that dosen't have the summary.
But Fixed is really a provider property so TextValidateField knows if it is a fixed length input (mask) or if ot grows as a normal input.

**Comment by BDisp** [comment]
@jmperricone sorry for making changes to this, but is was breaking the `All View Tester` and this seems to fixed it. But you are right, is better to implement each validator in his own class, like the `TreeView` and `TreeView<T>`. Can you that, please?

**Comment by BDisp** [comment]
But I tried to fix it without changing the class definition but the constructor is never called, but it is important that the `All View Tester` runs without breaking.

**Comment by jmperricone** [comment]
Im new to the project, what is All View Tester, because it passed all tests. Or it is a test outside the solution?

**Comment by tig** [comment]
> Im new to the project, what is All View Tester, because it passed all tests. Or it is a test outside the solution?

Run UICatalog and try the "All View Tester".

**Comment by BDisp** [comment]
> 
> 
> Im new to the project, what is All View Tester, because it passed all tests. Or it is a test outside the solution?

It run all test because I fixed your `TextFieldValidation`. Try to remove the recents updates and try again. You will check that your control throws a `NullException`.

**Comment by tig** [comment]
see #1260

**Comment by jmperricone** [comment]
@BDisp  Yes, exception.

Why the generic can't have a constraint to a specific interface. Why that is bad ?

**Comment by BDisp** [comment]
It's only to ensure that all the views don't throws with default constructor, even it depend on other objects and do nothing.
Imaging the `Terminal.Gui` have an IDE and you add a view that will throw an error to it. You don't have the chance of adding it.
Now, if it don't throw, you can adding properties and other dependents to it and construct the view.

**Comment by tig** [comment]
It also enables more automated testing.

**Comment by jmperricone** [comment]
Just to clarify, something like this will not be good for the project.

```csharp
foreach (var arg in type.GetGenericArguments ()) {
	var ctypes = arg.GetGenericParameterConstraints ();
	if (ctypes.Length == 0) {
		typeArguments.Add (typeof (object));
	} else {
		typeArguments.Add (ctypes [0]);
	}
}
```

**Comment by jmperricone** [comment]
Im thinking how to reimplement becasue, 
```csharp
var field = new TextValidateField<int>();
```
What should be the behavior ? Throw ?

**Comment by BDisp** [comment]
We can restrict only to the classes that implement `ITextValidateField`.

**Comment by jmperricone** [comment]
Yes, but will be at runtime.

I think that we need no remove the generic and pass the provider via constructor or via Property after construction.
In case the provider is not set, show an error message just like you did, and treeview does too.

Because if it also work with generic, will make any sense to have also the constructor o the setter property.

```csharp
var provider = new TextRegexProvider();
var field = new TextValidateField<NetMaskedTextProvider>(provider);
field.Provider = new AnotherProvider();
```
That will be worst I think.

**Comment by jmperricone** [comment]
Without the generic makes more sense to change the provider at runtime. 

```csharp
var provider = new TextRegexProvider();

var field = new TextValidateField(provider);

field.Provider = new AnotherProvider();
```

**Comment by BDisp** [comment]
I think you should maintain the generic that will allow others implementations. You can add another non generic `TextValidateField` class with default behavior as `TreeView` did.

**Comment by jmperricone** [comment]
Other implementation will keep working, because the providers are the implementation. The only diff is that we passit via contructor, and not its created with the activator.
```csharp
public class MyProvider : ITextValidateProvider{}

var field = new TextValidateField(new MyProvider{});
```

**Comment by jmperricone** [comment]
TreeView, does this too i think. You have to pass the builder with a constructor or via property later. The generic its only to constrain the type.

**Comment by BDisp** [comment]
> You have to pass the builder with a constructor or via property later

True.

**Comment by jmperricone** [comment]
@BDisp  Thanks!!. I will change it, send PR and then we see.

**Comment by tznind** [comment]
> 
> Just to clarify, something like this will not be good for the project.
> 
> ```cs
> foreach (var arg in type.GetGenericArguments ()) {
> 	var ctypes = arg.GetGenericParameterConstraints ();
> 	if (ctypes.Length == 0) {
> 		typeArguments.Add (typeof (object));
> 	} else {
> 		typeArguments.Add (ctypes [0]);
> 	}
> }
> ```

We do have something quite like that actually in the `AllViewsTester`:

https://github.com/migueldeicaza/gui.cs/blob/26cb2007372670aaf6b0acf97985893c694f44f7/UICatalog/Scenarios/AllViewsTester.cs#L345-L362

I agree it is a bit of a kludge.  At the time TreeView was the only generic View and this enabled compatiblity with the `AllViewsTester` and I was thinking that `object` would always be supported by a template view (which of course is not true).

Any thoughts on this? should we change it to just handle each generic explicitly `TreeView<T>` explicitly e.g.

```csharp
View CreateClass (Type type)
{	
	View view;

	if(type == typeof(TreeView<>)) {
		view = new TreeView<object> ();
	} else {
		view = (View)Activator.CreateInstance (type);
}

```

**Comment by BDisp** [comment]
> Any thoughts on this? should we change it to just handle each generic explicitly e.g.
> 
> ```cs
> View CreateClass (Type type)
> {	
> 	View view;
> 
> 	if(type == typeof(TreeView<>)) {
> 		view = new TreeView<object> ();
> 	} else {
> 		view = (View)Activator.CreateInstance (type);
> 	}
> ```

The problem is if it has a bunch of generic types  later, it needs to changes for each of them.

**Comment by jmperricone** [comment]
"We do have something quite like that actually in the AllViewsTester"

Yes, I change that code , adding the generic contraint .life the e.g.

**Comment by jmperricone** [comment]
> > Any thoughts on this? should we change it to just handle each generic explicitly e.g.
> > 
> > ```cs
> > View CreateClass (Type type)
> > {	
> > 	View view;
> > 
> > 	if(type == typeof(TreeView<>)) {
> > 		view = new TreeView<object> ();
> > 	} else {
> > 		view = (View)Activator.CreateInstance (type);
> > 	}
> > ```
> 
> The problem is if it has a bunch of generic types  later, it needs to changes for each of them.
> 

With the code I send , it works for any generic with a constraint

​foreach​ (​var​ ​arg​ ​in​ ​type​.​GetGenericArguments​ ()) {
        ​var​ ​ctypes​ ​=​ ​arg​.​GetGenericParameterConstraints​ ();
        ​if​ (​ctypes​.​Length​ ​==​ ​0​) {
                ​typeArguments​.​Add​ (​typeof​ (​object​));
        } ​else​ {
                ​typeArguments​.​Add​ (​ctypes​ [​0​]);
        }
}

**Comment by jmperricone** [comment]
Works with class A<T> where T : class  , or any other interface, class
