### ISSUE TITLE
ListView's ProcessKey returns true even if the SelectedItem event isn't handled

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1257]
ProcessKey implementations should return true only if the processing of the key actually did something. 

OnSelectedItem returns true even if the event isn't handled; Instead, it should return `false` if no action has been defined.

Proposed fix:

Before:
```c#
public virtual bool OnOpenSelectedItem ()
{
	if (source.Count <= selected || selected < 0) return false;
	var value = source.ToList () [selected];


	OpenSelectedItem?.Invoke (new ListViewItemEventArgs (selected, value));

	return true;
}
```

After:
```c#
public virtual bool OnOpenSelectedItem ()
{
	if (source.Count <= selected || selected < 0 || OpenSelectedItem == null) {
		return false;
	}

	var value = source.ToList () [selected];

	OpenSelectedItem?.Invoke (new ListViewItemEventArgs (selected, value));

	return true;
}

```

Then, have `ProcessKey` utilize the return value from `OnOpenSelectedItem`:

```c#
public override bool ProcessKey (KeyEvent kb)
		{
...
			case Key.Enter:
				return OnOpenSelectedItem ();
				break;

...
			default:
				return false;
			}

			return true;
		}
```

**Comment by BDisp** [comment]
@tig sometimes a view that handle some keystroke need to check if it's necessary to do something or not, but need to set it to true because it has the focus and don't want another view take another action for that keystroke. Think well :-)
