### ISSUE TITLE
Ctrl+Tab not registering in xterm

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1266]
Is there a key combination that gets you out of TextView when AcceptsTab is true (default)?

I am testing in Linux and finding that in `Notepad` and `Tab View` Scenarios,  once you tab into a TextView you can't get out (without using mouse).

No combination of Ctrl/Alt/Shift + Tab are moving focus.

**Comment by tig** [comment]
I don't think so.

**Comment by BDisp** [comment]
That was working before, damn. I' ll check.

**Comment by tznind** [comment]
> That was working before, damn. I' ll check.

Could be OS specific (have not tried on Windows).  I am using xterm-256color

**Comment by BDisp** [comment]
In `Windows` is working. Is `Ctrl+Tab` for forwarding and `Ctrl+Shift+Tab` for backwarding.

**Comment by tznind** [comment]
Hmn looking at `Scenario Keys` it seems like its something to do with my console.  Ctrl+Key works but Ctrl+Tab just sends Tab:

![ctrlTab](https://user-images.githubusercontent.com/31306100/116453497-de96a300-a856-11eb-8953-f86c75a6e05d.gif)
_Pressing Ctrl+D followed by Ctrl+Tab (which just registers as Tab)_

**Comment by BDisp** [comment]
Yes, in WSL the tab is not caught anymore with the Tab key too.

**Comment by BDisp** [comment]
Please try with the -usc for the NetDriver. It don't work too.

**Comment by BDisp** [comment]
Oh damn, it always open with CursesDriver and not NetDriver.

**Comment by BDisp** [comment]
I found that the ResetState is setting the UseSystemConsole to false,

**Comment by BDisp** [comment]
@tig on `NetDriver` it's working but it's need to comment the `UseSystemConsole = false;` in the `ResetState` method

**Comment by BDisp** [comment]
> Hmn looking at `Scenario Keys` it seems like its something to do with my console. Ctrl+Key works but Ctrl+Tab just sends Tab:

No it's not with your terminal. Is that because `nCurses` always only send `Tab` or `Shift+Tab`. This is a bad notice.

**Comment by BDisp** [comment]
@tznind what terminal do you use? Mine is not printing the last key press as your is in red. It's blank.

**Comment by BDisp** [comment]
I found this:
https://superuser.com/questions/787280/ctrltab-is-not-working-in-vim-with-gnome-terminal

**Comment by BDisp** [comment]
> 
> 
> @tznind what terminal do you use? Mine is not printing the last key press as your is in red. It's blank.

Never mind it doesn't happen anymore.

**Comment by tznind** [comment]
> @tznind what terminal do you use? 

My terminal is:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
thomas@mx:~
$ echo $TERM
xterm-256color

```

**Comment by tznind** [comment]
Are there any workarounds for TextView specifically like maybe pressing Left when the cursor is at 0,0 (i.e. the beginning of the text) could move focus back or pressing Right when at the end of the text moves focus forward?  

Would that feel like natural behavior? You can't go back any more so you go back out of the control?

**Comment by BDisp** [comment]
The Shift+CursorLeft and CursorRight are used to select the text backward and forward. I think the Ctrl+B for backward and Ctrl+F for forward is better but will break the current funcionality.

**Comment by tznind** [comment]
That could collide with other shortcuts if a user of the library has registered something else for those combinations?  Also probably wouldn't be something a user would try for getting out of the control.

Would defaulting AcceptsTab to false preserve previous behavior? In the changelog we can highlight the new ability to handle tabs by setting this to true and explain this limitation?

**Comment by BDisp** [comment]
The solution cannot being breaking the current feature that works perfect on Windows. We have to add another combinations that will work twice on Windows and only once on Linux. Can you put on practice?

**Comment by BDisp** [comment]
I am not even a `Linux` user, so I will leave Linux users to make that decision. Only I would not want someone break the functionality with `Windows`, please.

**Comment by tznind** [comment]
I will have a play around.  I definetly don't want to break anything!  There are other scenarios where an alternative to Ctrl+Tab could be nice for example using remote desktop through Guacamole (or similar technology) where the web browser might intercept Ctrl+Tab.

**Comment by BDisp** [comment]
Thanks. I now you will found a good solution.

**Comment by BDisp** [comment]
Thanks. @tznind I forgot to remember that you must apply the same fix to the `Toplevel` process key to allow navigation between windows, see the `Windows & FrameViews` scenario, please.
