### ISSUE TITLE
Creating Attributes/ColourSchemes before initializing the Application

### ISSUE THREAD

**Issue by EternalClickbait** [migueldeicaza/gui.cs#1269]
I'm trying to use default field initializers to initialize colour schemes used in my app like so:
```
public static readonly ColorScheme DefaultColourScheme = new ColorScheme
{
		Disabled = new Attribute(Color.DarkGray, Color.Gray),
		Focus = new Attribute(Color.White, Color.BrightBlue),

		HotFocus = new Attribute(Color.White, Color.Blue),

		Normal = new Attribute(Color.Gray),
		HotNormal = new Attribute(Color.White, Color.DarkGray)
};
```

Unfortunately, as the class that holds these ColourSchemes is initialized before the `Terminal.Gui,Application` is initialized, I get `System.TypeInitializationExceptions`:
```
System.TypeInitializationException: The type initializer for 'Core.Console.CommandLineConsoleManager' threw an exception. ---> System.InvalidOperationException: The Application has not been initialized
   at Attribute Terminal.Gui.Attribute.Make(Color foreground, Color background)
   at new Terminal.Gui.Attribute(Color foreground, Color background)
   at static Core.Console.CommandLineConsoleManager()
```

I had a look and this is because  ` new Attribute()` internally calls `Attribute.Make()` which requires access to the `Application.Driver`, which hasn't been set because the app isn't set up yet.

Is there any way to get around this somehow without pre-initializing the application? I'm assuming the answer is no because of some sort of platform-specific colours or something, but I'd like to check just in case.

**Comment by BDisp** [comment]
Yes is platform specific which return different values.

**Comment by tznind** [comment]
Where in your program do you call `Application.Init()`?  You could populate your static readonly variable from a static constructor?

```csharp
class MyClass {

	public static readonly ColorScheme DefaultColourScheme;
	
	static MyClass ()
	{
		Application.Init ();
		DefaultColourScheme = new ColorScheme {
			Disabled = new Attribute (Color.DarkGray, Color.Gray),
			Focus = new Attribute (Color.White, Color.BrightBlue),

			HotFocus = new Attribute (Color.White, Color.Blue),

			Normal = new Attribute (Color.Gray),
			HotNormal = new Attribute (Color.White, Color.DarkGray)
		};
	}
}
```

**Comment by BDisp** [comment]
Without the attribute value the foreground and background colors are useless per si, because each driver has his own algorithm to convert the value to the respective colors.
So I think this can be closed.
