### ISSUE TITLE
Application with multiple screens 

### ISSUE THREAD

**Issue by GaikwadPratik** [migueldeicaza/gui.cs#127]
@migueldeicaza, can you please create an example of application with multiple screens such that one screen can be loaded after the other on an event?

**Comment by IKoshelev** [comment]
I've spent some time trying to do the same thing. You will need Terminal.Gui.dll built from source (or wait till NuGet refresh), to avoid error in .RemoveAll(). Otherwise, here is a code sample that worked for me:


```
	    Application.Init();
	    var top = Application.Top;

	    // Creates the top-level window to show
	    var win = new Window(new Rect(0, 1, top.Frame.Width, top.Frame.Height - 1), "MyApp");
	    top.Add(win);

	    Window windowA = new Window(new Rect(0, 0, win.Frame.Width - 2, win.Frame.Height - 2), "A");
	    windowA.Add(
		new TextField(14, 2, 40, "1"),
		new TextField(14, 4, 40, "2")
		);

	    Window windowB = new Window(new Rect(0, 0, win.Frame.Width - 2, win.Frame.Height - 2), "B");
	    windowB.Add(
		new TextField(14, 2, 40, "3"),
		new TextField(14, 4, 40, "4")
		);

	    var lastIsA = true;

	    var menu = new MenuBar(new MenuBarItem[] {
	    new MenuBarItem ("_File", new MenuItem [] {
		new MenuItem ("_Swap window", "", () => {

		    var subView = win.Subviews[0];
		    subView.RemoveAll();
		    if(lastIsA) {
			win.Add(windowB);
			lastIsA = false;
			windowB.FocusFirst();
			windowB.LayoutSubviews();
		    } else {
			win.Add(windowA);
			lastIsA = true;
			windowA.FocusFirst();
			windowA.LayoutSubviews();
		    }

		}),
		new MenuItem ("_Quit", "", () => { top.Running = false; })
	    })
	});

	    top.Add(menu);
	    win.Add(windowA);

	    Application.Run(); 
```

**Comment by GaikwadPratik** [comment]
@IKoshelev , Thank you for replying. I never did the last part that you suggested i.e. calling `LayoutSubviews` on `View`. Let me try that. One question though, where are you removing either `windowA` or `windowB` from main `win`. As per code above, the instances are just added again and again to main `win` object. Do you want to call `FocusFirst` and `LayoutSubviews` if the instance are already present? or `remove` from `win` object and then add the other `window`?

**Comment by IKoshelev** [comment]
@GaikwadPratik I start by removing all child views and then adding the one I want to see at the moment. Normally, only one child window will be present, i.e. windowB is show => everything is removed (and so windowB is removed) => windowA is added.

I've done more testing, and it looks like .LayoutSubviews() is not necessary, at least in this case. What really made it work is setting explicit child window size by passing a Rect: `new Window(new Rect(0, 0, win.Frame.Width - 2, win.Frame.Height - 2), "A");
`

**Comment by GaikwadPratik** [comment]
@IKoshelev , Instead of `window` I am using `FrameView` for children control because I need `tab` navigation functionality. For some reason, even though I have set child `Frame` using `rect` it wasn't painted. I have to call `LayoutSubview()` explicitly. Only then new child window was actually displayed on the UI.

**Comment by migueldeicaza** [comment]
I do not understand what the exact request is.

What you want sounds like you want to create two toplevels (Windows are toplevels) and run one after the other:

```
var w = new Window () {...};
var w2 = new Window () {...};

Application.Run (w);
Application.Run (w2);
```

**Comment by GaikwadPratik** [comment]
@migueldeicaza no, That won't do. Can you please try to run https://github.com/GaikwadPratik/TerrminalWizard? On click of `Next` Button it doesn't show(paint) new form.

**Comment by IKoshelev** [comment]
@GaikwadPratik I found a hack around the problem with width and height not recalculating. Here is a version of code with FrameView, please see if it works for you (just remember to use Terminal.Gui.dll built from source to have the latest bugfixes).

```
	    Application.Init();
	    var top = Application.Top;

	    // Creates the top-level window to show
	    var win = new Window("MyApp") 
	    {
		X = 0,
		Y = 1,
		Width = Dim.Fill(),
		Height = Dim.Fill()
	    };
	    top.Add(win);

	    FrameView windowA = new FrameView("A"); 
	    windowA.Add(
		new TextField(14, 2, 40, "1"),
		new TextField(14, 4, 40, "2")
		);

	    FrameView windowB = new FrameView("B");
	    windowB.Add(
		new TextField(14, 2, 40, "3"),
		new TextField(14, 4, 40, "4")
		);

	    var menu = new MenuBar(new MenuBarItem[] {
	    new MenuBarItem ("_File", new MenuItem [] {
		new MenuItem ("_Swap to window B", "", () => {

		    var subView = win.Subviews[0];
		    subView.RemoveAll();
		    win.Add(windowB);
		    windowB.FocusFirst();

		    typeof(Application)
			.GetMethod("TerminalResized", BindingFlags.NonPublic | BindingFlags.Static)
			.Invoke(null, new object[0]);

		}),
		new MenuItem ("_Quit", "", () => { top.Running = false; })
	    })
	});

	    top.Add(menu);
	    win.Add(windowA);

	    Application.Run();
```

**Comment by pratikgaikwadhive** [comment]
@IKoshelev,  I see you are invoking `TerminalResized`. Can you check my comment in https://github.com/migueldeicaza/gui.cs/issues/128?

**Comment by GaikwadPratik** [comment]
@IKoshelev, can you check my comment in https://github.com/migueldeicaza/gui.cs/issues/128?

**Comment by migueldeicaza** [comment]
Some other observations: Dim.Percent(99) is not really going to work most of the time, as screen sizes can be as small as 80 columns (or even less in some configurations), so you are not making your life easy.

The percentages are useful for things like "20% or 50%", not to add one or two spaces.   For that, instead use Dim.Fill() and subtract the value you need, like: `Dim.Fill() - 2` will give you the dimension and two spaces to spare.

**Comment by GaikwadPratik** [comment]
If I run the Eula and Hostname forms modally i.e. in a window then I can't use `Tab` key to navigate to `Previous` and `Next` buttons. The application that I am trying to create will be running in a server console  without mouse support. Hence I need `Tab` as well as `Shift+Tab` keys to be functioning. Hence I am working with `Frame` instead of `Window`.

**Comment by migueldeicaza** [comment]
Additionally, you do not need to use patterns like `LoadView`, you can just instantiate the various views inside your constructor.

**Comment by migueldeicaza** [comment]
The Previous/Next buttons need to be part of the window that you run modally.

You can avoid code duplication by having some method add the previous/next buttons for you and handle the Applciation.RequestStop () method on the Click handler for example and set the proper "previous"/"back" flag.

**Comment by migueldeicaza** [comment]
The mouse support is completely optional, and everything should work without mouse.

There is no need to use FrameView instead of Window, that is just because you are trying to force the UI to behave differently and calling LayoutSubviews on your own - yes, this can be done, but then you are signing up to study the event system and make sure you get it right, which is going to be a lot more work than just using the system the way I described it

**Comment by migueldeicaza** [comment]
There is an action for me here given that this is a common scenario: 

(a) Better document how to create these compound views.

(b) Provide an example of how something like this would work, to avoid others the same pain of trying to recreate the setup and going behind the toolkit's back for it.

**Comment by migueldeicaza** [comment]
I did not clean up everything, but addressed some of the layout issues, used the idiom I described here:

https://gist.github.com/migueldeicaza/15308acfe824ff94009e95486612c919

It is all in a single file, it was easier for me to do it that way.

**Comment by IKoshelev** [comment]
@migueldeicaza Thanks for clarification regarding Application.Run();

How does this look to you:

```
	    Application.Init();

	    Window windowA = new Window("A");
	    windowA.Add(
		new TextField(14, 2, 40, "1"),
		new TextField(14, 4, 40, "2")
		);

	    Window windowB = new Window("B");
	    windowB.Add(
		new TextField(14, 2, 40, "3"),
		new TextField(14, 4, 40, "4")
		);

	    void switchViewToWindowB()
	    {
		Application.RequestStop();
		var newTop = CreateFreshTopLevel(switchViewToWindowB, windowB);
		Application.Run(newTop);
	    }

	    var firstTop = CreateFreshTopLevel(switchViewToWindowB, windowA);
	    Application.Run(firstTop);

	    Toplevel CreateFreshTopLevel(Action onSwithToWindowBMenuInvoked, params View[] children)
	    {
		var top = new Toplevel();

		// Creates the top-level window to show
		var win = new Window("MyApp") {
		    X = 0,
		    Y = 1,
		    Width = Dim.Fill(),
		    Height = Dim.Fill()
		};
		top.Add(win);

		var menu = new MenuBar(new MenuBarItem[] {
		    new MenuBarItem ("_File", new MenuItem [] {
			new MenuItem ("_Switch to window B", "", onSwithToWindowBMenuInvoked),
			new MenuItem ("_Quit", "", () => { top.Running = false; })
		    })
		});

		top.Add(menu);
		win.Add(children);

		return top;
	    }
```

**Comment by GaikwadPratik** [comment]
@migueldeicaza , I think I understand what you are saying but I am still a bit confused. Here is yet another question, how Calling `Application.RequestStop()` and then making call to `Application.Begin(windowB)` is different than making below 4 calls or invoking `TerminalResized`?

```
_formWindow.RemoveAll();
 _formWindow.Add(_childFormContainer);
_formWindow.FocusFirst();
_formWindow.SetNeedsDisplay();
_formWindow.LayoutSubviews();
```
Computationally how is that different? I went through the source code, calling `Application.Begin` makes the same call in the same order. I would really appreciate if you would help me understand.

**Comment by worksofliam** [comment]
I actually have a requirement for this to be fixed also. I have code to recreate it here:

```csharp
    public class Display : Window
    {
        public Display(string text) : base(text)
        {
        }
        public override bool ProcessColdKey(KeyEvent keyEvent)
        {
            Application.RequestStop();
            return true;
        }
    }
```

```csharp
        static void Main(string[] args)
        {
            Application.Init ();

            Application.Run(getNewWindow("Screen 1"));
            Application.Run(getNewWindow("Screen 2"));
        }

        static Window getNewWindow(string sometext) {
            var win = new Display ("") {
                X = 0,
                Y = 0,
                Width = 80,
                Height = 24
            };

            var label = new Label (sometext) {
                X = 5,
                Y = 5,
                Width = 20,
                Height = 1
            };
            win.Add (label);

            return win;
        }
```
