### ISSUE TITLE
Linux hangs was fixed but created another issue which is terminal not being refreshed on resizing.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1272]
Since the cursor is set to the application the `Curses.CheckWinChange` method always return the same values for the `LINES` and `COLS`, not detecting windows resizing.

On WSL:
![linux-resizing](https://user-images.githubusercontent.com/13117724/116541681-aee1ac80-a8e3-11eb-9f6d-8391918095e0.gif)

On Ubuntu:
![linux-ubuntu-resizing](https://user-images.githubusercontent.com/13117724/116582764-971f1e00-a90d-11eb-84f1-f8e055264348.gif)

On macOS:
![macos-resizing](https://user-images.githubusercontent.com/13117724/116585029-e2d2c700-a90f-11eb-83eb-89c7f9ec59d8.gif)

**Comment by BDisp** [comment]
Since the cursor is set to the application the `Curses.CheckWinChange` method always return the same values for the `LINES` and COLS, not detecting windows resizing.

**Comment by BDisp** [comment]
The main problem is even I can set the lines and columns to the right sizes, the `Curses.refresh` will always uses the the initial values. Any thoughts about this?

**Comment by tig** [comment]
Fixed with #1272
