### ISSUE TITLE
Window dimensions are not recalculated when it is added to display hierarchy.

### ISSUE THREAD

**Issue by IKoshelev** [migueldeicaza/gui.cs#128]
I've spent some time poking the code, and can't seem to find a way to force Window dimension to be recalculated. The only way I found to force Window to have a height is to make sure it is part of display hierarch when App.Run() is invoked, even if many windows are stacked together one on top of each-other. How do I force Window dimensions recalculation after it has been added? 

```
	public static void Main(string[] args)
	{
	    Application.Init();
	    var top = Application.Top;

	    // Creates the top-level window to show
	    var win = new Window(new Rect(0, 1, top.Frame.Width, top.Frame.Height - 1), "MyApp");
	    top.Add(win);

	    Window windowA = new Window("A");
	    windowA.Add(
		new TextField(14, 2, 40, "1"),
		new TextField(14, 4, 40, "2")
		);

	    Window windowB = new Window("B");
	    windowB.Add(
		new TextField(14, 2, 40, "3"),
		new TextField(14, 4, 40, "4")
		);

	    var lastIsA = true;

	    var menu = new MenuBar(new MenuBarItem[] {
	    new MenuBarItem ("_File", new MenuItem [] {
		new MenuItem ("_Swap window", "", () => {

		    var subView = win.Subviews[0];
		    subView.RemoveAll();
		    if(lastIsA) {
			win.Add(windowB);
			lastIsA = false;
			windowB.FocusFirst();
		    } else {
			win.Add(windowA);
			lastIsA = true;
			windowA.FocusFirst();
		    }

		}),
		new MenuItem ("_Quit", "", () => { top.Running = false; })
	    })
	});

	    top.Add(menu);

	    //if windowB is not present when Application.Run() is called,
	    //its dimension will be 0
	    //win.Add(windowB);
	    win.Add(windowA);

	    Application.Run();
	}
```

**Comment by GaikwadPratik** [comment]
This is true for all the `View`s. I am sure, when you press `Tab` it focuses on `TextField` on both `Window`, right?

**Comment by migueldeicaza** [comment]
In the sample above, you are forcing the size of the window by calling the Window constructor with a `Rect` parameter - this tells the library that you desire the size to be fixed.

If you want a layout that automatically grows, you must set the X, Y, Width and Height properties individually so you can anchor them.   This is described here:

https://migueldeicaza.github.io/gui.cs/articles/overview.html#layout

A simple way would be to do:

```
var win = new Window () { X = 0, Y = 1, Width = Dim.Fill (), Height = Dim.Fill ()-1 }
```

The above starts one line below the top, and the height is just -1 from the full height.

**Comment by IKoshelev** [comment]
The problem is not in "MyApp" window, which is constructed with a Rect, it is in windowA and windowB. When app starts, only windowA has been added as child to "MyApp", and it shows ok: 

![image](https://user-images.githubusercontent.com/5594348/45779859-7e7e0000-bc5c-11e8-98e9-b595ff603820.png)

Then we call "Swap window":
![image](https://user-images.githubusercontent.com/5594348/45779933-abcaae00-bc5c-11e8-92e2-64e83fbe7e91.png)

which roughly comes down to removing windowA from main window children and adding windowB instead:
```
var subView = win.Subviews[0];
subView.RemoveAll();
win.Add(windowB);
windowB.FocusFirst();
windowB.LayoutSubviews();
```

I expect to see windowB shown, but I don't:
![image](https://user-images.githubusercontent.com/5594348/45780110-1ed42480-bc5d-11e8-8c59-6d1ea0fa5b6c.png)

Investigation lead me to believe, that this is because it has 0 width and 0 height, despite both A and B being created in the same way. 

**With the change you suggested, this still happens, BUT when I resize the whole Windows 10 console - windowB is drawn properly:**

![image](https://user-images.githubusercontent.com/5594348/45780445-e7b24300-bc5d-11e8-85a2-41f83d54841d.png)

So, the question is: how do I trigger this full size recalculation and redraw without resizing console window?

Here is updated demo code:

```
	    Application.Init();
	    var top = Application.Top;

	    // Creates the top-level window to show
	    var win = new Window("MyApp") 
	    {
		X = 0,
		Y = 1,
		Width = Dim.Fill(),
		Height = Dim.Fill()
	    };
	    top.Add(win);

	    Window windowA = new Window("A"); 
	    windowA.Add(
		new TextField(14, 2, 40, "1"),
		new TextField(14, 4, 40, "2")
		);


	    Window windowB = new Window("B");
	    windowB.Add(
		new TextField(14, 2, 40, "3"),
		new TextField(14, 4, 40, "4")
		);


	    var menu = new MenuBar(new MenuBarItem[] {
	    new MenuBarItem ("_File", new MenuItem [] {
		new MenuItem ("_Swap to window B", "", () => {

		    var subView = win.Subviews[0];
		    subView.RemoveAll();
		    win.Add(windowB);
		    windowB.FocusFirst();
		    windowB.LayoutSubviews();

		}),
		new MenuItem ("_Quit", "", () => { top.Running = false; })
	    })
	});

	    top.Add(menu);
	    win.Add(windowA);

	    Application.Run();
```

**Comment by IKoshelev** [comment]
I have achieved desired result by making ` Application.TerminalResized` method public and calling it after adding windowB. 

```
		    var subView = win.Subviews[0];
		    subView.RemoveAll();
		    win.Add(windowB);
		    windowB.FocusFirst();
		    Application.TerminalResized();
```

**Comment by GaikwadPratik** [comment]
@IKoshelev can you try compiling https://github.com/GaikwadPratik/gui.cs? I have added a fix in https://github.com/migueldeicaza/gui.cs/pull/129 with one small below change in the code:
```var subView = win.Subviews[0];
		    subView.RemoveAll();
		    win.Add(windowB);
		    windowB.FocusFirst();
                    windowB.SetNeedsDisplay();
		    windowB.LayoutSubviews();```

**Comment by IKoshelev** [comment]
Are your commits in a branch? I don't think I see them when I download the project.

**Comment by GaikwadPratik** [comment]
@IKoshelev https://github.com/GaikwadPratik/gui.cs
