### ISSUE TITLE
Linux/Mac - Text is hidden in "Text Alignment and Direction" scenario

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1281]
Colors of the TextView and centered and justified Label are hiding the text in the "Text Alignment and Direction" scenario on Linux and Mac.

![hiden-text](https://user-images.githubusercontent.com/13117724/116943802-345eb700-ac6c-11eb-9c0a-2683df83b657.png)

**Comment by tig** [comment]
I edited the bug title and description to make the title more terse. It is hard to process bug lists with long/wordy titles.

**Comment by BDisp** [comment]
The main problem is because of this:
```cs
var color1 = new ColorScheme { Normal = Application.Driver.MakeAttribute (Color.Black, Color.Gray) };
var color2 = new ColorScheme { Normal = Application.Driver.MakeAttribute (Color.Black, Color.DarkGray) };

```
Unix don't have a `DarkGray `but only a `COLOR_CYAN`. So, `Gray `and `Dark Gray` is the same color for the `Unix`.

**Comment by BDisp** [comment]
I made a basic color scenario and I found that there is a large bug in color management in the` CursesDriver`. Whenever I leave and re-enter the scenario, the colors are shown in a randomly and uncontrolled way.
Because of this I think that after all it can be possible to stop and restart the driver, as you wanted to do at the beginning @tig, and maybe not only a singleton.

![curses-color-bug](https://user-images.githubusercontent.com/13117724/117113023-d3c19e00-ad81-11eb-8010-c494b807e89d.gif)

**Comment by BDisp** [comment]
Another repro related with the `CursesDriver` color issue. While doing a tabbing (in this case with `Ctrl+PageDown` using my PR #1266) the masked text colors are always changed.

![curses-color-bug2](https://user-images.githubusercontent.com/13117724/117309649-870dbe00-ae7a-11eb-9518-6b23879fb7c2.gif)

**Comment by tznind** [comment]
I have noticed this issue in the past (many months ago).  I thought maybe it was to do with the color (`Attribute`) structs going out of scope and getting garbage collected (despite there being references to them).  Which doesn't make much sense but it was my best guess.  I think in the end I did some workaround that involved constantly redeclaring colors or declaring them at the top of my program (can't quite remember).

It does seem to take a while to kick in like you can see that it holds the (red) color for a while then looses it.

**Comment by BDisp** [comment]
I'm glad I could have fixed this annoying bug.
