### ISSUE TITLE
Text is cropped when using not english characters

### ISSUE THREAD

**Issue by alexxonline** [migueldeicaza/gui.cs#130]
When used non english character (in my case, I speak Spanish) the text in labels or message box (I think they use labels internally) is cropped:

I tested the following sentence: "Se iniciará el análisis" and without non-english characters "Se iniciara el analisis"

I attached a picture of the results below

The code to add the label that I'm using is:

```
            window.Add(new Label(2, 2, message));
```
![guics_01](https://user-images.githubusercontent.com/1951024/45824998-9b035200-bcc7-11e8-8da5-80b8c97e0718.PNG)
![guics_02](https://user-images.githubusercontent.com/1951024/45824999-9b035200-bcc7-11e8-8b76-2261429ec9be.PNG)

Any thoughts on this?

**Comment by migueldeicaza** [comment]
very good catch, let me fix this right away.

I bet this is because I used a lame count, rather than RuneCount.

**Comment by migueldeicaza** [comment]
Fixed in 4fcaf39, will release tomorrow.

**Comment by alexxonline** [comment]
Sorry to bother you with this but are you going to release soon?
