### ISSUE TITLE
Need propper sample of application where individual windows are plugins (how to swap them propperly)

### ISSUE THREAD

**Issue by IKoshelev** [migueldeicaza/gui.cs#131]
I'm looking to make a plugin-based application, where initial screen is a list of available plugins, choosing one plugin switches screen to its respective view, and when user is done, top menu is used to get back to list. Here is an example with two plugins: 

![windows-powershell-9_21_2018-12_02_09-am](https://user-images.githubusercontent.com/5594348/45849695-4a294300-bd33-11e8-9458-ef7a524f9fca.gif)

I came up with a version of such architecture (as shown by gif above), based on discussion in  https://github.com/migueldeicaza/gui.cs/issues/127 , but @migueldeicaza mentioned, it may be working against the framework design. Can someone please clarify, what the correct approach would be?  To clarify, I specifically need to know, what is the proper way to hide one window and show another in its place.

**Comment by tig** [comment]
I think `UI Catalog` does what you are asking. 

If you still have issues re-open this Issue.
