### ISSUE TITLE
The setting for the OS clipboard on Linux is not fully guaranteed.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1318]
I detected this when I was trying to do unit tests to getting the clipboard content from the OS and also setting the OS clipboard.

**Comment by tznind** [comment]
Theres probably windows distributions that don't come with powershell or where it is disabled by admins too.  Should try to keep the clipboard interaction as extensible as possible and code defensively in this area.

**Comment by BDisp** [comment]
But it is only for the effects of unit tests. You can verify that the `Linux` clipboard is the only that is using the same application (`xclip`), both in unit tests and in the driver. Therefore, whoever performs unit tests is usually a developer who will probably have these tools. Of course, I'm also considering version `Windows 8` and above .
