### ISSUE TITLE
StatusBar Multiple Instances

### ISSUE THREAD

**Issue by rmorales87atx** [migueldeicaza/gui.cs#1320]
I'm starting to work with Terminal.Gui and right now have implemented several instances of `Toplevel` for different "screens" in my program. *(I don't want borders/title drawn as would happen with a `Window`, but I do want a `StatusBar` for each `Toplevel`.)*

The first `Toplevel` that gets created with a `new StatusBar()` looks fine, but **all subsequent `Toplevel` views do not have a visible `new StatusBar()`**; additionally, hot-key functions *are* usable even without a *visible* `StatusBar`.

I see there's `StatusBar` property on the `Toplevel`. If I try assigning a `new StatusBar()` to this property, all views get a visible `StatusBar` **but the first view has an "extra" blank line** which ends up with a "ghost" `StatusBar` when the views are switched.

**Comment by BDisp** [comment]
> The first `Toplevel` that gets created with a `new StatusBar()` looks fine, but **all subsequent `Toplevel` views do not have a visible `new StatusBar()`**; additionally, hot-key functions _are_ usable even without a _visible_ `StatusBar`.

You can create many `Toplevel` you want, but you only can assign  one each time to the `Application.Top`. So, before you assign a new `Toplevel` you must disposing, removing all subviews, from the last one, otherwise the last hotkeys used are still avaiable.

**Comment by rmorales87atx** [comment]
`... the last hotkeys are still available` doesn't seem to be my issue. The hotkeys are reacting correctly for each `Toplevel` (e.g., F2 being a delete command in one `Toplevel` and a different command in another), they just aren't visible on-screen.

In the program I've written so far, the "main" `Toplevel` contains a `ListView` where the user can double-click/press `Enter` to activate the screen for a selected option (`ListView.OpenSelectedItem`). Each of these screens has its own encapsulating class that essentially does this:
``` C#
var nextView = new Toplevel();
// ... create appropriate widgets for the screen ...
// ... now create StatusBar ...
var sb = new StatusBar(new[] {
	new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop())
});
nextView.Add(sb);
// run the view
Application.Run(nextView);
```

Only the "main" `Toplevel` has a visible StatusBar. All other `Toplevel` screens don't have a visible status bar but the assigned hotkeys do work correctly within each view.

**Comment by BDisp** [comment]
> You can create many `Toplevel` you want, but you only can assign one each time to the `Application.Top`.

This is the basis for the new `Toplevel` to work properly. All the news `Toplevel` must be assigned to the main `Toplevel`. So, before `Application.Run(nextView);` you must assign `nextView` to the `Application.Top`.
Instead using `var nextView = new Toplevel();`
Try using the following:
```cs
var nextView = Application.Top;
nextView = new Toplevel();
```

**Comment by tznind** [comment]
So I have done a little experimenting with how to switch top views.  This seems to be about what you are looking for? I've used `View` for the sub windows and just edited the contents of Top rather than trying to load a new `TopLevel`.

```csharp
using System;
using Terminal.Gui;

namespace console
{

    class Program
    {
        private static View[] views = new View[3];
        private static StatusBar[] bars = new StatusBar[3];
        private static int current = 0;
        
        static void Main(string[] args)
        {
            Application.Init();

            
            views[0] = new View(){
                Width = Dim.Fill(),
                Height = Dim.Fill() -1
            };
            views[0].Add(new Label("Window1"));

            bars[0] = new StatusBar(new[] {
	new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
	new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(current+1))
});

         views[1] = new View(){
                Width = Dim.Fill(),
                Height = Dim.Fill() -1
            };
            views[1].Add(new Label("Window2"));

            bars[1] = new StatusBar(new[] {
	new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
	new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(current-1)),
	new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(current+1))
});

         views[2] = new View(){
                Width = Dim.Fill(),
                Height = Dim.Fill() -1
            };
            views[2].Add(new Label("Window3"));

            bars[2] = new StatusBar(new[] {
	new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
	new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(current-1))
});


            Application.Top.Add(bars[0]);
            Application.Top.Add(views[0]);
            Application.Run();
        }

        private static void Load(int next)
        {
            
            Application.Top.Remove(views[current]);
            Application.Top.Remove(bars[current]);

            current = next;

            Application.Top.Add(views[current]);
            Application.Top.Add(bars[current]);
    
            // Not sure why this is needed, I tried SetNeedsDisplay but that alone didn't cut it        
            Application.Run();
        }
    }
}

```

**Comment by BDisp** [comment]
> ```cs
> // Not sure why this is needed, I tried SetNeedsDisplay but that alone didn't cut it        
>             Application.Run();
> ```

Because a `Toplevel` is only running through `Application.Run`, be modal or not.

Another way to do this:

```cs
class Program {
	static void Main (string [] args)
	{
		Load (MainTop ());

		Application.Shutdown ();
	}

	private static Toplevel MainTop ()
	{
		Application.Init ();

		var top = Application.Top;

		top.Add (new Label ("Window1"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
			new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(SecondTop()))
		});
		top.Add (sb);

		return top;
	}

	private static Toplevel SecondTop ()
	{
		Application.Init ();

		var top = Application.Top;

		top.Add (new Label ("Window2"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
			new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(MainTop())),
			new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(ThirdTop()))
		});
		top.Add (sb);

		return top;
	}

	private static Toplevel ThirdTop ()
	{
		Application.Init ();

		var top = Application.Top;

		top.Add (new Label ("Window3"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
				new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(SecondTop()))
		});
		top.Add (sb);

		return top;
	}

	private static void Load (Toplevel top)
	{
		Application.Run (top);
	}
}

```

**Comment by tznind** [comment]
Ok cool so `Application.Init ();` will clear out the old system state and make it ready to set up a new top?

**Comment by BDisp** [comment]
> 
> 
> Ok cool so `Application.Init ();` will clear out the old system state and make it ready to set up a new top? (or am I misunderstanding your code example).

You are right. See the `demo.cs` in the `Example` project which has a similar approach.

**Comment by BDisp** [comment]
> You are right. See the `demo.cs` in the `Example` project which has a similar approach.

Sorry @tznind. I gave you wrong information. `Application.Init ();` doesn't do nothing to acquire the needed behavior, because the driver and `Appliaction.Top` are already setup. It's the `var top = Application.Top;` who do what it's intended to do, because only the `Application.Top` can have a `MenuBar` and a `StatusBar`. But we must be careful to cleanup all the `Application.Top` subviews, before assign it to a new `Toplevel`. So, here is a changed example:

```cs
class Program {
	static void Main (string [] args)
	{
		Application.Init ();

		Load (MainTop ());

		Application.Shutdown ();
	}

	private static Toplevel MainTop ()
	{
		var top = NewTop ();

		top.Add (new Label ("Window1"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
			new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(SecondTop()))
		});
		top.Add (sb);

		return top;
	}

	private static Toplevel SecondTop ()
	{
		var top = NewTop ();

		top.Add (new Label ("Window2"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
			new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(MainTop())),
			new StatusItem(Key.CtrlMask | Key.T, "~^T~ Next", () => Load(ThirdTop()))
		});
		top.Add (sb);

		return top;
	}

	private static Toplevel ThirdTop ()
	{
		var top = NewTop ();

		top.Add (new Label ("Window3"));

		var sb = new StatusBar (new [] {
			new StatusItem(Key.CtrlMask | Key.Q, "~^Q~ Exit", () => Application.RequestStop()),
				new StatusItem(Key.CtrlMask | Key.P, "~^P~ Previous", () => Load(SecondTop()))
		});
		top.Add (sb);

		return top;
	}

	private static void Load (Toplevel top)
	{
		Application.Run (top);
	}

	private static Toplevel NewTop ()
	{
		Application.Top.RemoveAll ();
		return Application.Top;
	}
}

```

**Comment by rmorales87atx** [comment]
Thank you all for the code samples! This looks decent 👍
