### ISSUE TITLE
On linux mouse input is being ignored when clicking on the right half side of the terminal.

### ISSUE THREAD

**Issue by AtomicJeff** [migueldeicaza/gui.cs#1325]
When clicking too far right on the terminal the mouse will no longer register and the terminal goes into a "SELECT" state, and mouse input no longer registers until hitting the return key (highlighted in the upper left hand of the image). Things on the left side of the red line in the image register, and on the right side don't and cause the terminal to drop into "SELECT".

Additonally, under SSH, the terminal still rejects input on the right side of the terminal, but does NOT drop into the "SELECT " state.

Running under wsl2: Ubuntu 20.04 LTS.
Terminal.GUI v1.0.0

![image](https://user-images.githubusercontent.com/45468813/119861524-58f52a00-becc-11eb-8ee8-9d2b5a6207a5.png)

**Comment by BDisp** [comment]
If you are using `WSL`  (that is the case) and run the command `echo $TERM` you probably will have this result `xterm-256color`, which is the same on a real `Linux` (with `DISPLAY`). So, it is a `WSL` limitation and in this case you have to open an issue on the https://github.com/microsoft/WSL/issues

**Comment by AtomicJeff** [comment]
yes, I do get the result xterm-256 color, but other mouse enabled  console apps work as expected under wsl, such as Midnight Commander.

**Comment by BDisp** [comment]
You are right, sorry. I mean, it is a `WSL` limitation using with `ncurses` library. If you run your app using `Application.UseSystemConsole = true`, before the `Application.Init()`, it will run with the `NetDriver` and the mouse works properly. Unfortunately, it runs much slower.

**Comment by AtomicJeff** [comment]
Ok, so on the UICatalog example, setting the UseSystemConsole flag to true works, and mouse registers everywhere, but the nuget package of terminal.gui 1.0.0 the flag doesn't have any effect, Application.Driver.ToString resolves to Termin.Gui.CursesDriver on linux, and Terminal.Gui.WindowsDriver on windows.

![image](https://user-images.githubusercontent.com/45468813/119880073-babf8f00-bee0-11eb-9b7a-1a98f893f1cc.png)

**Comment by BDisp** [comment]
You must use the main from the github, because that was already fixed by the PR #1267.

**Comment by AtomicJeff** [comment]
Check, that worked. Anecdotally, NetDriver is much slower on windows, but is actually more responsive on Linux...

thanks so much for the help!

**Comment by BDisp** [comment]
Ah, yes it's true, I forgot to mention that is only slower on `Windows`. You welcome.

**Comment by DrMiaow** [comment]
If that is the first 96 characters then it might be an issue with the application not using 'extended mouse reporting' where X/Y (-32) are encoded as UTF-8.  

I have noticed a strange issue in that at column 120 I get an empty mouse report packet, which is how I ended up at this issue.  Related, being fixed or new?
