### ISSUE TITLE
mouse input printing to terminal after exiting from application while using netdriver

### ISSUE THREAD

**Issue by AtomicJeff** [migueldeicaza/gui.cs#1340]
Mouse input is being written to terminal after application shutdown, any tips here?

environment: Ubuntu 20.04
driver: NetDriver
version v1.1.1

![image](https://user-images.githubusercontent.com/45468813/122460360-e1fcff80-cf66-11eb-919c-6f521f17965d.png)

**Comment by tznind** [comment]
Do you have the issue with UICatalog (in this repo)?

Have you called `Application.Shutdown ();`

**Comment by AtomicJeff** [comment]
@tznind Looks like I was only calling Application.RequestStop(). Application.Shutdown() resolved my issue.

Thanks so much!
