### ISSUE TITLE
Setting ShowBothScrollIndicator in ScrollBarView constructor to false causes exception

### ISSUE THREAD

**Issue by melance** [migueldeicaza/gui.cs#1344]
If you set the ShowBothScrollIndicator in the Constructor to false, refresh throws an Object null exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Terminal.Gui
  StackTrace:
   at Terminal.Gui.ScrollBarView.CheckBothScrollBars(ScrollBarView scrollBarView, Boolean pending)
   at Terminal.Gui.ScrollBarView.ShowHideScrollBars()
   at Terminal.Gui.ScrollBarView.Refresh()
   at Randomizer.Generator.UITerminal.Views.GeneratorListFrameView.<>c__DisplayClass10_0.<.ctor>b__0(Rect e) in C:\Users\me_la\source\repos\Randomizer.Generator\Randomizer.Generator.Terminal\Views\GeneratorListFrameView.designer.cs:line 47
```

**Comment by BDisp** [comment]
There is no `ShowBothScrollIndicator` but only a read only `showBothScrollIndicator` that has the following sintax:
```cs
bool showBothScrollIndicator => OtherScrollBarView != null && OtherScrollBarView.showScrollIndicator && showScrollIndicator;

```

**Comment by melance** [comment]
It's an optional parameter in the constructor:
      
`public ScrollBarView(View host, Boolean isVertical, Boolean showBothScrollIndicator = true);`

**Comment by melance** [comment]
Works for Horizontal but if IsVertical == true it still throws the exception.

**Comment by BDisp** [comment]
> Works for Horizontal but if IsVertical == true it still throws the exception.

I don't think so. I already had added an unit test for `IsVertical == true` and now in the PR #1355 I added an unit test for `IsVertical == false`. So, @melance please be more specific.

**Comment by melance** [comment]
I had deleted my comment because I realized I still had the old version.  Sorry about that.
