### ISSUE TITLE
Setting Label text using Text doesn't work

### ISSUE THREAD

**Issue by maloo** [migueldeicaza/gui.cs#1347]
When creating a label like `var label = new Label { Text = "test", X = 1, Y = 1 }` the label text is not visible. Creating it like `var label = new Label("test") { X = 1, Y = 1 }` works.

**Comment by BDisp** [comment]
Because on the first created you forgot to using the default Label constructor. It should be:
`var label = new Label() { Text = "test", X = 1, Y = 1 }`

**Comment by maloo** [comment]
How is that any different? An object initializer should call the default constructor.

**Comment by tznind** [comment]
> Because on the first created you forgot to using the default Label constructor. It should be:
> `var label = new Label() { Text = "test", X = 1, Y = 1 }`

The brackets are optional when using a property list combined with a blank constructor.  Both have identical behaviour:

```
// result in exactly the same code and constructors being called
new MyClass(){SomeVar =1};
new MyClass{SomeVar =1};
```

**Comment by BDisp** [comment]
> 
> 
> How is that any different? An object initializer should call the default constructor.

Sorry you are right. I didn't try it before and I confirm the first is working fine, too.

**Comment by BDisp** [comment]
> That said this may have already been fixed In the current main branch. I am just trying to reproduce it at the moment.

Yes, this was fixed along with the `AutoSize` fixes.

**Comment by maloo** [comment]
Ok, so if I understand it the bug is confirmed and fixed and merged to main, but not released yet. Do you have a reference to the "AutoSize issue" so I can track the release of it?

**Comment by tznind** [comment]
> Ok, so if I understand it the bug is confirmed and fixed and merged to main, but not released yet. Do you have a reference to the "AutoSize issue" so I can track the release of it?

I think this is the PR that fixed it: 
https://github.com/migueldeicaza/gui.cs/pull/1333

@BDisp can you confirm?

**Comment by BDisp** [comment]
I confirm @tznind .

**Comment by BDisp** [comment]
> // result in exactly the same code and constructors being called
> new MyClass(){SomeVar =1};
> new MyClass{SomeVar =1};

I did a little change to prove the above.

```cs
[Theory]
[InlineData (1)]
[InlineData (2)]
[InlineData (3)]
public void LabelChangeText_RendersCorrectly_Constructors (int choice)
{
	var driver = new FakeDriver ();
	Application.Init (driver, new FakeMainLoop (() => FakeConsole.ReadKey (true)));

	try {
		// Create a label with a short text 
		Label lbl;
		var text = "test";

		if (choice == 1) {
			// An object initializer should call the default constructor.
			lbl = new Label { Text = text };
		} else if (choice == 2) {
			// Calling the default constructor followed by the object initializer.
			lbl = new Label () { Text = text };
		} else {
			// Calling the Text constructor.
			lbl = new Label (text);
		}
		lbl.ColorScheme = new ColorScheme ();
		lbl.Redraw (lbl.Bounds);

		// should have the initial text
		Assert.Equal ('t', driver.Contents [0, 0, 0]);
		Assert.Equal ('e', driver.Contents [0, 1, 0]);
		Assert.Equal ('s', driver.Contents [0, 2, 0]);
		Assert.Equal ('t', driver.Contents [0, 3, 0]);
		Assert.Equal (' ', driver.Contents [0, 4, 0]);
	} finally {
		Application.Shutdown ();
	}
}

```

**Comment by tig** [comment]
Closing as it appears this is a non issue.
