### ISSUE TITLE
TableView cell color

### ISSUE THREAD

**Issue by marceln** [migueldeicaza/gui.cs#1356]
Hey,

Is there a way to change the color of certain cells in a table view based on their value? Is there any other customization possible othen than through the RepresentationGetter?

Thanks,
Marcel

**Comment by tznind** [comment]
At the moment you can only change the text that is displayed (and text alignment) and it can only occupy a single console row.  The reason for this design is to allow rapid scrolling around large tables (e.g. 100,000 rows / 50 columns) without having to calculate the full table representation of every cell.

The rendering process will instead start at the scrolled to part of the `DataTable` and use the `RepresentationGetter` to measure and draw that bit of the table until it runs out of space in the console.  It also measures the representations returned to avoid showing half a cell where possible (e.g. where content spills off the right hand side do to many/large columns).

We could definetly add colored cell support though! The current draw code that would need updated is:

https://github.com/migueldeicaza/gui.cs/blob/7f27d78cc732c3155995ada06096a0748687605b/Terminal.Gui/Views/TableView.cs#L394-L433

We would need a corresponding member in `ColumnStyle`.  Something like:

```csharp
/// <summary>
/// Defines a delegate for returning custom color values for cells in the table. 
/// </summary>
public Func<object, ColorScheme?> ColorGetter;
```
