### ISSUE TITLE
Redirect standard input output

### ISSUE THREAD

**Issue by ektorasd** [migueldeicaza/gui.cs#1361]
Hi,
I am trying an application using Terminal.GUI from a telnet server and I am getting:
`Failed to get input console mode, error code: 6.
   at Terminal.Gui.NetWinVTConsole..ctor()
   at Terminal.Gui.NetDriver..ctor()
   at Terminal.Gui.Application.Init(Func`1 topLevelFactory, ConsoleDriver driver, IMainLoopDriver mainLoopDriver)
   at Terminal.Gui.Application.Run[T](Func`2 errorHandler)
   at ConsoleTest.Program.Main(String[] args) in C:\projects\labs\ConsoleTest\ConsoleTest\Program.cs:line 20`
As far as I understand GetConsoleMode does not support redirection. Do you have any ideas how this could be accomplished?

**Comment by tznind** [comment]
When you say you are redirecting input/output do you mean like:

```csharp
Console.SetOut(someStreamWriter);
Console.SetIn(someStreamReader);
```
What OS is the server you are connecting to and what OS and terminal are you using to open the connection?

I don't know about telnet but it seems to work as expected over SSH.

**Comment by BDisp** [comment]
It looks like you are trying to create a console on a `Windows OS`, but without a real console terminal. That also will happens if you try to run a unit test with the `NetDriver` on a `Windows OS`.

**Comment by ektorasd** [comment]
> When you say you are redirecting input/output do you mean like:
> 
> ```cs
> Console.SetOut(someStreamWriter);
> Console.SetIn(someStreamReader);
> ```
> 
> What OS is the server you are connecting to and what OS and terminal are you using to open the connection?
> 
> I don't know about telnet but it seems to work as expected over SSH.
> 
> Can you share some code that you are using for your ConsoleTest program and how you are running/accessing it via telnet?

I was trying from windows 10. And it did work with SSH, thanks

**Comment by ektorasd** [comment]
> It looks like you are trying to create a console on a `Windows OS`, but without a real console terminal. That also will happens if you try to run a unit test with the `NetDriver` on a `Windows OS`.
> `Terminal.Gui.NetWinVTConsole` is only used on `Windows OS`.

You are right, that was the case.
