### ISSUE TITLE
listen for window ready or displayed.

### ISSUE THREAD

**Issue by adrwh** [migueldeicaza/gui.cs#1363]
Hi, I am writing a PowerShell UI and want to run some powershell comes as soon as the Window is "ready", ie, before the user starts interacting with the console, however i don't want the background task to delay the window from running until its finished.

Im doing something like this, where i am trying to listen for a Ready event then run this code.

```
...
$Top.add_Ready{
    $UIDs = Get-ADUser -Properties uidnumber,gidnumber -LDAPFilter '(|(uidnumber=*)(gidnumber=*))'
    $UIDs.count
} 

$Top = [Application]::Top
$Top.Add($Window)
[Application]::Run()
[Application]::Shutdown()
```

**Comment by tznind** [comment]
Is there a reason not to just start a normal Thread right before calling `Run()`?

**Comment by adrwh** [comment]
That sounds logical, can you point me to an example of what you mean?

**Comment by BDisp** [comment]
You can use the `Application.Top.Ready` action which is fired on the first instance, before interacting with the console.

.```
..
$Top = [Application]::Top

$Top.Ready += {
    $UIDs = Get-ADUser -Properties uidnumber,gidnumber -LDAPFilter '(|(uidnumber=*)(gidnumber=*))'
    $UIDs.count
} 

$Top.Add($Window)
[Application]::Run()
[Application]::Shutdown()
```

**Comment by BDisp** [comment]
Another option is the `Loaded` event which is fired before the `Ready` event.

**Comment by tznind** [comment]
> however i don't want the background task to delay the window from running until its finished.

I'm not used to the syntax of powershell but it looks like you can create a new thread/task using these commands (see below).  That would prevent the callback from blocking user input while it completes.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/start-job?view=powershell-7.1

https://docs.microsoft.com/en-us/powershell/module/threadjob/start-threadjob?view=powershell-7.1
