### ISSUE TITLE
I want to draw horizontal line (HLine)

### ISSUE THREAD

**Issue by ichan-akira** [migueldeicaza/gui.cs#1367]
I want to draw horizontal line (U+2500), just like the border of `Window`/`FrameView`, I use following code (shortened for brevity):

```C#
    private Label _topSeparatorLabel;

    public Window Win { get; private set; }

    public void Init( Toplevel top )
    {
      Win = new Window( "Application Name Setup" )
      {
        X = 0,
        Y = 0,
        Width = Dim.Fill(),
        Height = Dim.Fill() - 1
      };
    }

    public void Setup()
    {
      _topSeparatorLabel = new Label()
      {
        X = 0,
        Y = 5,
        Width = Dim.Width( Win ) - 2,
        Height = 1
      };
      _topSeparatorLabel.DrawContent += TopSeparatorLabel_DrawContent;

      Win.Add( _topSeparatorLabel );
    }

    private void TopSeparatorLabel_DrawContent( Rect obj )
    {
      _topSeparatorLabel.Text = new string( '\u2500', _topSeparatorLabel.Bounds.Width );
    }
```

The idea is I need some kind of `Line` control which I can put anywhere to separate content in `Window`.
Since there is none, I think to simply use `Label` and give its `Text` with repeated value of `\u2500`.

![Screenshot 2021-07-15 200151](https://user-images.githubusercontent.com/18476854/125792701-ade3cb30-c718-4001-83fe-863e43f2a8d6.png)

Is this a good approach, or there will be a problem here?
Thanks in advance.

**Comment by BDisp** [comment]
Another solution is the use of `FrameView `to separate contents.

**Comment by ichan-akira** [comment]
I thought about `FrameView` as well but I don't want the left and right border to be displayed, can it be turned off?

**Comment by BDisp** [comment]
No, sorry.

**Comment by ichan-akira** [comment]
Awww, ok...

Thanks, I guess if my approach might not cause any problem, I will go on with it.

**Comment by BDisp** [comment]
I think your approach is good.

**Comment by tznind** [comment]
Changing the labels text is the kind of thing that could result in a redraw though (if not now possibly in future) so I would worry about the possibility of getting into a loop? You think that is worth worrying about @BDisp ? 

Should be pretty easy to write a HorizontalLine class and implement the Redraw method, might be cleaner?

**Comment by BDisp** [comment]
> Changing the labels text is the kind of thing that could result in a redraw though (if not now possibly in future) so I would worry about the possibility of getting into a loop? You think that is worth worrying about @BDisp ?

You are right, managing in the `DrawContent `event can ran in a loop. The text should only be changed if the window were resized.


> Should be pretty easy to write a HorizontalLine class and implement the Redraw method, might be cleaner?

Much better, I agree.

**Comment by ichan-akira** [comment]
> > Changing the labels text is the kind of thing that could result in a redraw though (if not now possibly in future) so I would worry about the possibility of getting into a loop? You think that is worth worrying about @BDisp ?
> 
> You are right, managing in the `DrawContent `event can ran in a loop. The text should only be changed if the window were resized.

Ah, you both are right! I have not realized that, thanks for pointing it out. Unfortunately I seems cannot find `Window` `Resize` event. So I thought I can only use `DrawContent` event for this purpose.

**Comment by tznind** [comment]
```csharp
public class HorizontalLineView : View {

	public HorizontalLineView ()
	{
		CanFocus = false;
		Width = Dim.Fill ();
		Height = 1;
	}
	public override void Redraw (Rect bounds)
	{
		base.Redraw (bounds);

		Move (0, 0);
		Driver.SetAttribute (ColorScheme.Normal);

		var hLineWidth = Math.Max(1,Rune.ColumnWidth (Driver.HLine));

		for (int x = 0; x< bounds.Width;x += hLineWidth) {
			Move (x, 0);
			Driver.AddRune (Driver.HLine);
		}
	}
}
```

Heres some code to test it:

```csharp
Application.Init ();

var window = new Window () { Width = Dim.Fill (), Height = Dim.Fill () };

window.Add (new Label ("hey, I'm above") { X = 0, Y = 0 });
window.Add (new HorizontalLineView () { X = 0, Y = 1 });
window.Add (new Label ("And I'm below") { X = 0, Y = 2 });

Application.Run (window);
Application.Shutdown ();
```

![image](https://user-images.githubusercontent.com/31306100/125920881-5c481069-8fbf-448c-b8da-33ad1cb7f550.png)

**Comment by ichan-akira** [comment]
Oh! Thanks so much @tznind I am also thinking to use this "_rune_" thing, but when I digging in the Terminal.Gui code, I cannot really understand how to use it.

After I see your example, I finally know that `Driver.AddRune (Driver.HLine);` can be used within `View.Redraw()` method. I will try it right away!

**Comment by tznind** [comment]
Good luck, one gotcha is that `Driver.Move(x,y)` (static) is not the same as `View.Move(x,y)` (non-static).  The former moves to a screen position in the console while the `View.Move(x,y)` moves to the area within the control (i.e. it's client area).

**Comment by BDisp** [comment]
> Ah, you both are right! I have not realized that, thanks for pointing it out. Unfortunately I seems cannot find `Window` `Resize` event. So I thought I can only use `DrawContent` event for this purpose.

The resize event is in the `Application `class. `Application.Resized`

**Comment by ichan-akira** [comment]
It works very perfectly, I really like the concept of user defined custom view we can create such as `HorizontalLineView`!
Thanks so much @tznind I have incorporated your `HorizontalLineView` class in my project! 👍 

Also thanks for explaining `Driver.Move()` vs `View.Move()` as well.

**Comment by ichan-akira** [comment]
> The resize event is in the `Application `class. `Application.Resized`

Ah no wonder I cannot find it, thanks @BDisp!

I will close this issue, the given solution is work perfectly!

**Comment by BDisp** [comment]
@tznind can I propose to you make a `LineView `which can be horizontal or vertical, based on the alignment property?

**Comment by BDisp** [comment]
@ichan-akira if @tznind accept my challenge, please reopens this issue again. Thanks.

**Comment by ichan-akira** [comment]
> @ichan-akira if @tznind accept my challenge, please reopens this issue again. Thanks.

Sure! I prefer to use Terminal.Gui generic control/view as well! That will be excellent 👍 
(For time being I will use the custom made view by @tznind 😸 )
