### ISSUE TITLE
UICatalog doesn't build without git (on command line)

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1377]
The MinVer package has a dependency on command line git.  So building without it causes a quite unclear error message.  See half way down this discussion for a user that had this exact problem https://github.com/migueldeicaza/gui.cs/discussions/1376:

See also the accepted answer on this StackOverflow post: https://stackoverflow.com/a/60233394

```bash
thomas@mx:~/gui.cs/UICatalog
$ dotnet run
thomas@mx:~/gui.cs/UICatalog
$ sudo apt-get remove git
[sudo] password for thomas: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  git-man liberror-perl liblept5 libtesseract4 libvapoursynth
  libvapoursynth-script0 libzimg2 mpv python3-pyxattr rtmpdump
  vapoursynth-python3
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  git
0 upgraded, 0 newly installed, 1 to remove and 39 not upgraded.
After this operation, 36.2 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 388567 files and directories currently installed.)
Removing git (1:2.20.1-2+deb10u3) ...
thomas@mx:~/gui.cs/UICatalog
$ dotnet run
/home/thomas/.nuget/packages/minver/2.5.0/build/MinVer.targets(39,5): error MSB3073: The command "dotnet "/home/thomas/.nuget/packages/minver/2.5.0/build/../minver/MinVer.dll" "/home/thomas/gui.cs/Terminal.Gui" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --tag-prefix "v" --verbosity "" --version-override """ exited with code 134. [/home/thomas/gui.cs/Terminal.Gui/Terminal.Gui.csproj]

The build failed. Fix the build errors and run again.
thomas@mx:~/gui.cs/UICatalog
```

If it is an unavoidable dependency we should highlight this  in our README.md build instructions

**Comment by BDisp** [comment]
> If it is an unavoidable dependency we should highlight this in our README.md build instructions

I agree. I think you would be a good candidate to add these instructions to the README.md file.  👍

**Comment by tznind** [comment]
Does visual studio build/run UICatalog without git installed on command line? (I know vs has it's own version of git embedded).

I don't know the history of the MinVer dependency but I notice you can disable it for Debug builds, that might be nicer than trusting that every user will read the build instructions carefully:

https://github.com/adamralph/minver#can-i-disable-minver

**Comment by BDisp** [comment]
> Does visual studio build/run UICatalog without git installed on command line? (I know vs has it's own version of git embedded).

Since a long time ago for pull requests effects, I had to install it with the creation of certificates keys.. I never uninstall because it gives some hard work to reinstall and to enable again.
