### ISSUE TITLE
Setting AllowsTab in TextView disables Multiline

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1380]
It seems that turning off 'AllowsTab' setting in `TextView` also disables `Mutliline`.  Is this a bug or is there a there a reason why we can't have a multi line editor where tab insertion is disabled?

```csharp
[Fact]
public void TextView_MultiLineButWithoutTabs()
{
	var view = new TextView ();
	
	// the default for TextView
	Assert.True (view.Multiline);

	view.AllowsTab = false;
	Assert.False (view.AllowsTab);

	Assert.True (view.Multiline); // crashes here
}
```

To me `AllowsTab` should be whether when the user presses TAB a tab gets inserted.  So the rendering/layout would be standard regardless of this setting (e.g. `\t` is tabWidth spaces).

**Comment by BDisp** [comment]
> To me `AllowsTab` should be whether when the user presses TAB a tab gets inserted. So the rendering/layout would be standard regardless of this setting (e.g. `\t` is tabWidth spaces).

Thats a bug. The intention was if `AllowsTab `is setting to true and `Multiline `is false, then the `Multine `must be set to true.

**Comment by BDisp** [comment]
The culprit is here:

```
				if (!allowsTab && multiline) {
					Multiline = false;
				}
```
I will delete it. Do you have more suggestions or do you want to make the changes yourself?

**Comment by tznind** [comment]
Happy for you to make this change :) 1 less bug in the world is a good thing

**Comment by BDisp** [comment]
> To me `AllowsTab` should be whether when the user presses TAB a tab gets inserted. So the rendering/layout would be standard regardless of this setting (e.g. `\t` is tabWidth spaces).

I also fixed this.

![editor-allows-tab](https://user-images.githubusercontent.com/13117724/126171904-ba95b3f9-3ef2-43a9-b609-07f5579f202d.gif)

**Comment by BDisp** [comment]
@tznind how to avoid the `Quit `method being executed by pressing `Ctrl+Y` on `Editor `scenario?

**Comment by tznind** [comment]
> @tznind how to avoid the `Quit `method being executed by pressing `Ctrl+Y` on `Editor `scenario?

Ctrl+Y doesn't do anything special on `main` branch just pastes as expected.  But I am using linux terminal.  Conversely Ctrl+C immediately terminates the app.

Maybe it is a console shortcut that is overriding for you?

**Comment by BDisp** [comment]
Sorry I forgot to mention that the changes is in this PR #https://github.com/migueldeicaza/gui.cs/pull/1364/files

**Comment by BDisp** [comment]
I know the reason. Enum flags values should be factor of two. But for the Key.A to Key.Z enum it have values from 65 to 90, equals to the Ascii code. But how can I differentiate them?

**Comment by BDisp** [comment]
I found a solution for this by using `Equals`.

`e.KeyEvent.Key.Equals (Key.Q | Key.CtrlMask)`

**Comment by BDisp** [comment]
For sure there is a lot of bugs because of this.

**Comment by tznind** [comment]
> For sure there is a lot of bugs because of this.

Yes having turned a pure enum into [Flags] like this sounds dangerous.  Can you do a minimum repro unit test of how we are currently checking the property and how it results in ambiguity? Maybe as a new issue?

**Comment by BDisp** [comment]
>
> Maybe as a new issue?

No worth.

>
> Yes having turned a pure enum into [Flags] like this sounds dangerous.

There is not much difference. Without [Flags] does not work well with bitwise and so the ToString () method returns a different value.


> Can you do a minimum repro unit test of how we are currently checking the property and how it results in ambiguity?

If you change the value of Last = 5 the test will fail, so it is only valid if one of the bit is high value.

```
		enum SimpleEnum { One = 1, Two = 2, Three = 3, Four = 4, Last = 0x40000000 }

		[Flags]
		enum FlaggedEnum { One = 1, Two = 2, Three = 3, Four = 4, Last = 0x40000000 }

		[Fact]
		public void Simple_Enum_And_Flaged_Enum ()
		{
			var simple = SimpleEnum.Three | SimpleEnum.Last;

			Assert.True (simple.HasFlag (SimpleEnum.One | SimpleEnum.Last));
			Assert.True (simple.HasFlag (SimpleEnum.Two | SimpleEnum.Last));
			Assert.True (simple.HasFlag (SimpleEnum.Three | SimpleEnum.Last));
			Assert.False (simple.HasFlag (SimpleEnum.Four | SimpleEnum.Last));
			Assert.True ((simple & (SimpleEnum.One | SimpleEnum.Last)) != 0);
			Assert.True ((simple & (SimpleEnum.Two | SimpleEnum.Last)) != 0);
			Assert.True ((simple & (SimpleEnum.Three | SimpleEnum.Last)) != 0);
			Assert.True ((simple & (SimpleEnum.Four | SimpleEnum.Last)) != 0);
			Assert.Equal ("1073741827", simple.ToString ());
			Assert.False (simple == (SimpleEnum.One | SimpleEnum.Last));
			Assert.False (simple == (SimpleEnum.Two | SimpleEnum.Last));
			Assert.True (simple == (SimpleEnum.Three | SimpleEnum.Last));
			Assert.False (simple == (SimpleEnum.Four | SimpleEnum.Last));

			var flagged = FlaggedEnum.Three | FlaggedEnum.Last;

			Assert.True (flagged.HasFlag (FlaggedEnum.One | FlaggedEnum.Last));
			Assert.True (flagged.HasFlag (FlaggedEnum.Two | FlaggedEnum.Last));
			Assert.True (flagged.HasFlag (FlaggedEnum.Three | FlaggedEnum.Last));
			Assert.False (flagged.HasFlag (FlaggedEnum.Four | FlaggedEnum.Last));
			Assert.True ((flagged & (FlaggedEnum.One | FlaggedEnum.Last)) != 0);
			Assert.True ((flagged & (FlaggedEnum.Two | FlaggedEnum.Last)) != 0);
			Assert.True ((flagged & (FlaggedEnum.Three | FlaggedEnum.Last)) != 0);
			Assert.True ((flagged & (FlaggedEnum.Four | FlaggedEnum.Last)) != 0);
			Assert.Equal ("Three, Last", flagged.ToString ());
			Assert.False (flagged == (FlaggedEnum.One | FlaggedEnum.Last));
			Assert.False (flagged == (FlaggedEnum.Two | FlaggedEnum.Last));
			Assert.True (flagged == (FlaggedEnum.Three | FlaggedEnum.Last));
			Assert.False (flagged == (FlaggedEnum.Four | FlaggedEnum.Last));
		}

```

**Comment by BDisp** [comment]
>  Can you do a minimum repro unit test of how we are currently checking the property and how it results in ambiguity?

I will open a discussion and not an issue because I will not fix this, as this would result in a breaking changes in the users code. I will only explain why this happens and advise on how to make the right comparison.

```cs
		[Fact]
		public void Key_Ambiguity_Check ()
		{
			var key = Key.Y | Key.CtrlMask;

			// This will not be well compared.
			Assert.True (key.HasFlag (Key.Q | Key.CtrlMask));
			Assert.True ((key & (Key.Q | Key.CtrlMask)) != 0);

			// This will be well compared, because the Key.CtrlMask have a high value.
			Assert.False (key == (Key.Q | Key.CtrlMask));
			switch (key) {
			case Key.Q | Key.CtrlMask:
				// Never goes here.
				break;
			case Key.Y | Key.CtrlMask:
				Assert.True (key == (Key.Y | Key.CtrlMask));
				break;
			default:
				// Never goes here.
				break;
			}
		}

```
