### ISSUE TITLE
When calling Focus on another ListView from inside the Select event of a ListView, the 2nd list's Select also gets triggered

### ISSUE THREAD

**Issue by liviu-marinescu** [migueldeicaza/gui.cs#1391]
From what I investigated this happens because the first ListView calls it's Select function but doesn't return true, so the event keeps propagating.

I was able to fix this by adding a return true after the OnSelect?.Invoke in the ProcessKey function inside SelectableView.cs.
I am not sure if this is the correct way to fix this.

```C#
        public override bool ProcessKey(KeyEvent keyEvent)
        {
            if (keyEvent.Key == Key.Enter)
            {
                OnSelect?.Invoke(SelectedItem);
                return true;
            }
            return base.ProcessKey(keyEvent);
        }
```

**Comment by BDisp** [comment]
If you don't want it propagating to other view, you are doing right by returning true;

**Comment by tznind** [comment]
Are you able to reproduce this on the main branch of the repo?  It looks like `OnOpenSelectedItem` is returning true correctly after invoking?

https://github.com/migueldeicaza/gui.cs/blob/bbffac8f23ba9abeddfd055f5c38556ff77c402e/Terminal.Gui/Views/ListView.cs#L653-L664

**Comment by BDisp** [comment]
I think he's inherit on a new ListView.

**Comment by liviu-marinescu** [comment]
> Are you able to reproduce this on the main branch of the repo? It looks like `OnOpenSelectedItem` is returning true correctly after invoking?
> 
> https://github.com/migueldeicaza/gui.cs/blob/bbffac8f23ba9abeddfd055f5c38556ff77c402e/Terminal.Gui/Views/ListView.cs#L653-L664
> 
> Looks like it was fixed around [26cb200#diff-f7e7cfdef83e80b88b150ed4239c1d684ae109ea833b995091d1bd85bc5dd810](https://github.com/migueldeicaza/gui.cs/commit/26cb2007372670aaf6b0acf97985893c694f44f7#diff-f7e7cfdef83e80b88b150ed4239c1d684ae109ea833b995091d1bd85bc5dd810) so might not be in live nuget package yet.

The problem I described is referring to the event handling function ProcessKey in the SelectableView class. From what I see it just fires the OnSelect and then continues and if I focus another control which is after the current one (in the list of controls) it will also receive the OnSelect because the previous one didn't consume it.

PS: I cloned the latest live version.

**Comment by BDisp** [comment]
This is a bit confused. If a view returns true in a `ProcessKey` event it never propagates for another view even changing the focus. I do not know what you mean by referring to the `SelectableView` class. Is it some class you're creating? If this is and you return true after the event processing it should not propagate to other views. If this happens, then please make the code available to check.

**Comment by liviu-marinescu** [comment]
> This is a bit confused. If a view returns true in a `ProcessKey` event it never propagates for another view even changing the focus. I do not know what you mean by referring to the `SelectableView` class. Is it some class you're creating? If this is and you return true after the event processing it should not propagate to other views. If this happens, then please make the code available to check.

Maybe I didn't explain it properly :) the original code doesn't include a "return true" statement after OnSelect?.Invoke(SelectedItem);

It looks like this:
```C#
        public override bool ProcessKey(KeyEvent keyEvent)
        {
            if (keyEvent.Key == Key.Enter)
            {
                OnSelect?.Invoke(SelectedItem);
            }
            return base.ProcessKey(keyEvent);
        }
```

I was able to fix the issue by adding a return true after the OnSelect invoke.

**Comment by BDisp** [comment]
But the original code is now as @tznind already said above, in the current main. You probably are seeing the NuGet package code. Please, always checkout the current main branch.

**Comment by liviu-marinescu** [comment]
Yes, I re-downloaded the project and seems something went wrong on my side the first time (I suspect a file merge).
