### ISSUE TITLE
Question about Thread Safety

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#1398]
I am running Termina.Gui on one thread and other code on another thread.

My question is how do I know which functions in Terminal.Gui are "thread safe" (I want to call Terminal.Gui functions across 2 different threads)?

**Comment by BDisp** [comment]
Look at the `Threading` category in the `UICatalog`.

**Comment by valkyrienyanko** [comment]
Okay thank you.

**Comment by valkyrienyanko** [comment]
I'm not sure where to look for threading examples in UICatalog.

For dequeuing a concurrentqueue I know I need a while loop but I also know that Application.Run() needs to be executed but once Application.Run() is executed the dotnet app seems to hang up here. So if I were to add a while(true) before Application.Run(), then Application.Run() would be unreachable code.

This is how I did it last time https://github.com/Kittens-Rise-Up/client/blob/abaf999f1184200edd97b4431f4757f9287805d1/Assets/Scripts/Netcode/ENetClient.cs#L78-L89

**Comment by valkyrienyanko** [comment]
It would be helpful to know if `View` is thread safe but I doubt it.

**Comment by BDisp** [comment]
I mean you have to look at the current main branch and not in the NuGet package. In the UICatalog project on the left pane, there are a Threading category which have various samples files.

**Comment by BDisp** [comment]
> It would be helpful to know if `View` is thread safe but I doubt it.

Is safe if you don't close it before the returns. But you also can create a thread which can open a View to show the results.  See in the BackgroundCollection example.

**Comment by BDisp** [comment]
If you put in a while statement is a high PC consumer. Use appropriate background threads.

**Comment by tznind** [comment]
> I'm not sure where to look for threading examples in UICatalog.

https://github.com/migueldeicaza/gui.cs/blob/main/UICatalog/Scenarios/Threading.cs

**Comment by BDisp** [comment]
> I'm not sure where to look for threading examples in UICatalog.

If you want to see they running, run the `UICatalog` project.

![threading-categories](https://user-images.githubusercontent.com/13117724/127304848-20a3c174-3117-453e-8104-dc620fb6399c.png)

**Comment by valkyrienyanko** [comment]
> Is safe if you don't close it before the returns.

Not sure what you mean by this.

> Here is a minimum representation of what I think it is you are wanting to do?

This example does not show how to dequeue a Concurrent queue while letting Application.Run() do its thing.

> I would suggest using ListView

If I remember correctly this limited the control I had over the view with what I wanted to do.

> If you want to see they running, run the UICatalog project.

I had a quick look, it all looks very alien to me sorry.

I am trying to mimic Minecraft's server console where they have log output and they allow you to type commands like `ban player`, you can get more an idea of what I'm trying to do by looking at the GIF posted in this previous issue https://github.com/migueldeicaza/gui.cs/issues/631

Thank you for all of your help, this is going way over my head right now, I won't bother you guys any further.
