### ISSUE TITLE
Label class no longer has TextColor property

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#1399]
![image](https://user-images.githubusercontent.com/6277739/127234740-e5acb4c5-d725-478a-a227-e0d22ead6b89.png)

In the API overview it says TextColor is a property of Label but this is not the case anymore for some reason.

**Comment by BDisp** [comment]
I think you mean about https://github.com/jsuarezruiz/xamarin-forms-gui.cs which uses the `Terminal.Gui` as base library.
With the `Terminal.Gui` you have to use the `ColorScheme` property.

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/127239988-e01d6bc9-c562-4da2-a1e9-a887cf25cbcd.png)

I am confused, I installed this NuGet package. Is this not the right Termina.Gui package? I found the the screenshot code above 
```cs
var myColor = Application.Driver.MakeAttribute (Color.Blue, Color.Red);
var label = new Label (...);
label.TextColor = myColor
``` 
from the Termina.GUI API Overview near the bottom of the page, just do Ctrl+F search for "TextColor" and you'll find it.

I try to access TextColor from Label but intellisense does not find it.

Are you saying I'm using https://github.com/jsuarezruiz/xamarin-forms-gui.cs instead?

I am trying to use Termina.Gui with my dotnet C# console app. Here is my [code](https://github.com/Kittens-Rise-Up/server/blob/main/src/Logger/Logger.cs)

I happened to stumble upon ColorScheme property before and I know how to use it I am just confused with what I said above.

**Comment by valkyrienyanko** [comment]
This is the project I used last time and if I remember correctly I had no issues finding TextColor property https://github.com/The-MMORPG-Project/game-server

**Comment by valkyrienyanko** [comment]
The old project uses 
```cs
<PackageReference Include="Terminal.Gui" Version="0.81.0" />
```
and the new project uses
```cs
<PackageReference Include="Terminal.Gui" Version="1.1.1" />
```
I believe that is the only difference, so I think something changed between versions.

**Comment by BDisp** [comment]
Ups sorry. Maybe was removed from the old l

**Comment by tznind** [comment]
You are using the correct package.  `ColorScheme` is what you need.  You use it as follows:

```csharp
var newLabel = new Label ("Label");
newLabel.ColorScheme = new ColorScheme () {
    Normal = Application.Driver.MakeAttribute (Color.Blue, Color.Red)
};
```

`ColorScheme` allows you to define what color a control should have under all states (disabled, normal, focused etc).
