### ISSUE TITLE
Label not visible on View

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#1400]
I created a new `View` and added it to `Application.Top`, then I created a `Label` and added it to the `View`. I was expecting to see the label but I did not. The label is only visible if I add it directly to `Application.Top`?

```cs
var loggerView = new View();
Application.GrabMouse(loggerView);
Application.Top.Add(loggerView);
loggerView.Add(label); // can't see
```

```cs
Application.Top.Add(label); // can see
```

Update: Tried doing the same thing with a `ScrollView`, same thing, can't see the label.

**Comment by BDisp** [comment]
You have to initialize the `View` with position and length to accommodate the `Label`. First add the `Label` to the `View` and lastly add the `View` to the `Application.Top`.

**Comment by valkyrienyanko** [comment]
Thank you
