### ISSUE TITLE
Do we dispose views when we are done with them?

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#1401]
I noticed `View` imeplements `IDisposable`, does that mean we do `view.dispose()` when we are done with them or is this handled somewhere I do not know about? 
![image](https://user-images.githubusercontent.com/6277739/127236362-8a750a39-a435-4251-8a87-9ec6b1eb8afa.png)

**Comment by BDisp** [comment]
If you add Views dynamically after `Application.Run` and you close it without exit the application, it is recommended to remove them first. If you are terminating the application with the `Shutdown` method he handles with that.

**Comment by valkyrienyanko** [comment]
Thank you
