### ISSUE TITLE
Expose public property in TextView for model.GetLine(int line).

### ISSUE THREAD

**Issue by bureto** [migueldeicaza/gui.cs#1405]
Usage would be for allowing user to get how long a particular row/line is. 
Or is there another way?

**Comment by BDisp** [comment]
If you select the line you want through the mouse or keyboard, you will get the text on the `SelectedText` property.

**Comment by BDisp** [comment]
You can also select by using the properties the `SelectionStartColumn` and `SelectionStartRow`.

**Comment by bureto** [comment]
Okay thanks. Here's a hacky way I'm doing it now:

```
var initialCursorPosition = CursorPosition;

CursorPosition = new Point(Maxlength, CurrentRow);
var afterCurrentColumn = CurrentColumn;
CursorPosition = initialCursorPosition;

if (afterCurrentColumn == initialCursorPosition.X)
    return true;
```

**Comment by BDisp** [comment]
> It relies on CursorPosition properties' setter checking the line's length.

Yes is true, sorry I had forgot for to mention that.

**Comment by BDisp** [comment]
@tznind I think your PR #1406 fixes this, but to automatically close this issue, you must reference it in a commit.

**Comment by tznind** [comment]
> 
> @tznind I think your PR #1406 fixes this, but to automatically close this issue, you must reference it in a commit.

I have added to the description that it closes the issue, that should trigger it when merged :)

**Comment by BDisp** [comment]
I'm not sure. Pay attention when it being merged. If it say close via #id, then it worked, but I think this id is a commit.

**Comment by tznind** [comment]
Ok will do, at least GitHub thinks it will be closed by the PR ;) 

![image](https://user-images.githubusercontent.com/31306100/129036937-db0386fd-1e59-4910-bd86-69381c51cd44.png)

**Comment by BDisp** [comment]
Ok, sorry, I did not notice it :-)
