### ISSUE TITLE
I think there is a BUG

### ISSUE THREAD

**Issue by deivid1** [migueldeicaza/gui.cs#1407]
//I didn't have this problem in old versions. When adding a few ListView the text color changes when clicking/changing selection. Weird. Am I missing something? Sample code shows the error:

           Application.Init();
            var top = Application.Top;

            // Creates the top-level window to show
            var win = new Window("test")
            {
                X = 0,
                Y = 0,
                Width = Dim.Fill(),
                Height = Dim.Fill()
            };
            top.Add(win);

            List<string> t1_str = new List<string>();
            t1_str.Add("xxxxx");
            t1_str.Add("xxxxx");
            var t1 = new ListView(new Rect(110, 2, 8, 6), t1_str);
            win.Add(t1);
            List<string> t2_str = new List<string>();
            t2_str.Add("bbbb");
            t2_str.Add("bbbb");
            var t2 = new ListView(new Rect(120, 2, 8, 6), t2_str);
            win.Add(t2);

            Application.Run();

**Comment by BDisp** [comment]
It's a normal behavior. If the `ListView` is being focused then the selected item will be black on gray. If the `ListView` is not being focused then the selected item will be dark cyan on dark blue.

**Comment by deivid1** [comment]
ohhh I see thx, it is the last one selected. Is there any way of disable it? to look like in old versions

**Comment by BDisp** [comment]
> 
> 
> ohhh I see thx, it is the last one selected. Is there any way of disable it? to look like in old versions

No there isn't. I think this is the desired for the most users, but if it's much requestable maybe a flag property could be created to maintain or nor the last selected item.

**Comment by deivid1** [comment]
Please, this is not working anymore. How could I adapt it to new versions? :
mylist.SelectedChanged += () =>
                                {//my stuff
                                };

**Comment by BDisp** [comment]
It's `SelectedItemChanged` now. If you use the IDE intelligence it will be appear on the list.

**Comment by tznind** [comment]
> ohhh I see thx, it is the last one selected. Is there any way of disable it? to look like in old versions

The line that determines color in `ListView` is:
```
var newcolor = focused ? (isSelected ? ColorScheme.Focus : ColorScheme.Normal) : (isSelected ? ColorScheme.HotNormal : ColorScheme.Normal);
```
So I think changing the ColorScheme so that `HotNormal` and `Focus` were the same colors for the `ListView`  it would have the same colors regardless of being focused.  But it might make it harder to see what is going on for users.

**Comment by BDisp** [comment]
> So I think changing the ColorScheme so that `HotNormal` and `Focus` were the same colors for the `ListView` it would have the same colors regardless of being focused. But it might make it harder to see what is going on for users.

I think is not need to do any changes, as setting a custom `ColorScheme` at a `ListView` instance can have what you needs.
Yes, it will be harder to the users to view where they had navigate. In the `UICatalog` we can know what was the last category and the last scenario opened. Thanks @tznind .

**Comment by BDisp** [comment]
Maybe this can be closed.

**Comment by deivid1** [comment]
yes plz, thx

**Comment by BDisp** [comment]
You can close it yourself.
