### ISSUE TITLE
TableView.Style - RowColorGetter & InvertSelectedCellFirstCharacter missing

### ISSUE THREAD

**Issue by CDE-College** [migueldeicaza/gui.cs#1409]
In UICatalog, both:

    RowColorGetter & InvertSelectedCellFirstCharacter 

are available as Properties and have their delegates called.

**NOT AVAILABLE IN V1.1.1**

**Comment by tznind** [comment]
These were added [10 days ago](https://github.com/migueldeicaza/gui.cs/pull/1357).  Version 1.1.1 was released back in May.  They will be in the next nuget released package.

**Comment by CDE-College** [comment]
Superb! Thanks for the Quick Reply! 

I am really digging this package, just discovered it 1 week ago. Good job guys!

I had seen your commit @tznind, but I thought it was a change more than an addition. Good work!
