### ISSUE TITLE
Quitting the application causes cursor location to be printed.

### ISSUE THREAD

**Issue by HFDan** [migueldeicaza/gui.cs#1423]
If i quit the application, the cursor location (i think) starts being printed to the console like this:
![image](https://user-images.githubusercontent.com/58553089/129761631-28baa691-749e-43f7-8cb9-0a9d7d7eee09.png)

This only happens when using gui.cs.

The command i used to run is:
`dotnet run -r:linux-x64`

**Comment by BDisp** [comment]
Do you are using the current main `Terminal.Gui` https://github.com/migueldeicaza/gui.cs branch?

**Comment by tznind** [comment]
Also make sure to call `Application.Shutdown();` before exiting.

**Comment by HFDan** [comment]
> Do you are using the current main `Terminal.Gui` https://github.com/migueldeicaza/gui.cs branch?

Installed using `dotnet add package Terminal.Gui`

**Comment by HFDan** [comment]
> Also make sure to call `Application.Shutdown();` before exiting.

Dosen't ctrl+Q call that?

**Comment by BDisp** [comment]
> Installed using `dotnet add package Terminal.Gui`

The package version is not updated with the last version from the main branch. So, it's a bug that already was fixed on the main branch.

**Comment by BDisp** [comment]
On the worker folder type.
`git clone https://github.com/migueldeicaza/gui.cs.git`

**Comment by tznind** [comment]
> 
> 
> > Also make sure to call `Application.Shutdown();` before exiting.
> 
> Dosen't ctrl+Q call that?

No, you have to add it.  Add `Application.Shutdown();` as the last line in your program (after Application.Run() - literally the very last line in your entire program to run) and see if that fixes it.

**Comment by tznind** [comment]
See https://github.com/migueldeicaza/gui.cs/issues/1340 where adding shutdown fixed the problem

**Comment by HFDan** [comment]
Thank you to everyone who helped. Issue is now fixed!
