### ISSUE TITLE
Exiting the application from Linux causes the terminal input to disappear afterward

### ISSUE THREAD

**Issue by breadbyte** [migueldeicaza/gui.cs#1428]
Related: #931 and #1114

## Steps to reproduce:
1. Install .NET 5.0 on Linux.
2. Clone the repo. I used commit 618714cc69ac6e0c1641076bd3c535c32cfe78fd, which is latest as of when this issue was written.
3. Build and open UICatalog. 

     - Alternatively, use [this minimal repro](https://gist.github.com/breadbyte/b2cf55fbe90b5a2dcfc2c89e174709f4) with a reference to the Terminal.Gui project within the repo.

4. Exit UICatalog.
     - To exit the minimal repro, select the textbox at the bottom of the screen and press F1.
5. Type reset. Nothing will show up.
6. Press Enter. the console should have reset and typed characters will now appear.

## Expected outcome (commit https://github.com/migueldeicaza/gui.cs/commit/666912c046f8af1212b48df83e699f7b8bb73e83 on netcoreapp3.1)
![4MRAHV0azj](https://user-images.githubusercontent.com/14045257/130350385-ea50cd33-5d8c-4008-a376-7fa50309a0af.gif)

## Actual outcome (commit https://github.com/migueldeicaza/gui.cs/commit/d90072151982a2499d3cf2df4776bb89a2fbb6f0 onwards on net5.0)
![bsLiAQAWy9](https://user-images.githubusercontent.com/14045257/130350113-b2122b85-fbaa-478e-8a40-6703c5079b25.gif)

Tested on the following machines:
`Linux localhost 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 21.04)
`Linux localhost 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux` (Debian 10)

I took a few minutes to run `git bisect` and returned with commit https://github.com/migueldeicaza/gui.cs/commit/d90072151982a2499d3cf2df4776bb89a2fbb6f0
I don't think this commit is useful, however, since it just moves the build target from netcoreapp3.1 to .net 5.0.

Using the workaround listed in #931 to toggle `Application.UseSystemConsole` does indeed fix this issue, but at the cost of usability (the application becomes way too slow to be reasonably usable).

**Comment by BDisp** [comment]
This PR #1420 already fix this. Test please.

**Comment by breadbyte** [comment]
> This PR #1420 already fix this. Test please.

Hello, I have tested this branch and I can confirm that it is fixed. Thank you for your work!
