### ISSUE TITLE
Can anyone ncurses expertise explain why this happens with CursesDriver?

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1445]
This is caused by the use of this line `reset_shell_mode ();` in the `binding.cs` file. This avoid writing `reset` every time when quitting the `UICatalog`. Running the `Editor` scenario the first time and open the `Find/Replace` dialog corrupts the output. Pressing `Ctrl+Q` to quit and running again the `Editor`, this corruption doesn't happens anymore. I want some help to try fix this issue, please.

![cursesdriver-issue](https://user-images.githubusercontent.com/13117724/131190319-f7949e46-0e75-4d50-9f75-76bf0aee967e.gif)

**Comment by tznind** [comment]
Not sure I can help but it looks related that when using the Down cursor to move focus around in the Find/Replace dialog then the cursor jumps to the left of the screen.  Again it is only with the Curses driver (running with `-usc` makes problem go away).  Also when CtrlQ out and going back into editor it doesn't show.

![oddcursor](https://user-images.githubusercontent.com/31306100/131211867-dbb4ad08-7d24-425b-954a-38501663a44b.gif)

**Comment by BDisp** [comment]
> Not sure I can help but it looks related that when using the Down cursor to move focus around in the Find/Replace dialog then the cursor jumps to the left of the screen.

Due the output corruption all works badly, including cursor position.



> Again it is only with the Curses driver (running with `-usc` makes problem go away).

Of course because it is using `NetDriver` and is a `CursesDriver` related issue.



> Also when CtrlQ out and going back into editor it doesn't show.

Because the driver is restarted in the `UICatalog`, using the `Application.Shutdown` and running the `Application.Init` again. My curiosity is why it stop giving the corruption behavior, if it is executed the same code as the first time.

**Comment by tznind** [comment]
Any idea what commit this first started happening on?

**Comment by BDisp** [comment]
> This is caused by the use of this line `reset_shell_mode ();` in the `binding.cs` file.
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/Terminal.Gui/ConsoleDrivers/CursesDriver/binding.cs#L107

If comment out this, the issue would stop, but if you start the application through the terminal, you have no cursor and you have to typing `reset`, with no output, to restore it.

**Comment by BDisp** [comment]
@tznind can you confirm if it works for you too, please? The test errors maybe are caused by the clipboard tests, but since I only tested on Windows I received no errors. I have to test it on Linux.

**Comment by tznind** [comment]
> @tznind can you confirm if it works for you too, please? The test errors maybe are caused by the clipboard tests, but since I only tested on Windows I received no errors. I have to test it on Linux.

Can confirm that the rendering/cursor corruption does not seem to be present on the above branch of your fork.  Good stuff!

**Comment by BDisp** [comment]
Well, the problem is the fix I made causes error on `FakeDriver`, as obvious because it uses `Curses.Raw`. The main problem, is that I can't debug unit tests on `VS Code` to try a workaround. Gives the "`Cannot destructure property 'debugEventListener' of '(intermediate value)' as it is undefined.`" error.

**Comment by BDisp** [comment]
For the first time I used the `.devcontainer\devcontainer.json` in the `VS Code` and was very useful.
