### ISSUE TITLE
Question about window SSH tool color

### ISSUE THREAD

**Issue by 625781186** [migueldeicaza/gui.cs#1451]
![image](https://user-images.githubusercontent.com/30521429/131628096-922909c2-4be1-4e16-a4bc-1a34243e0cf1.png)

I use xshell ssh on win10  run ubuntu1804 server command , 
But xshell color system will replace gui.cs color system , 
and I don't know xshell color system  how to set , 

Different color schemes will cause different effects. Figure 1 is incomplete and Figure 2 cannot be highlighted.

![image](https://user-images.githubusercontent.com/30521429/131628364-49bd3ed4-1ada-4e76-8904-99e591ca38a6.png)
![image](https://user-images.githubusercontent.com/30521429/131628373-4f4a625f-5fa3-44aa-9e9f-1352c6ea6572.png)

Are there any recommended SSH tools ?

**Comment by tznind** [comment]
What does it look like if you set it to XTerm?

**Comment by 625781186** [comment]
> What does it look like if you set it to XTerm?

![image](https://user-images.githubusercontent.com/30521429/131629879-439e10ad-6654-4141-a1ea-40543d0c0948.png)

But I use `TopLevel` , cannot be highlighted (when selected item change) and Menu can't show  incomplete .

![image](https://user-images.githubusercontent.com/30521429/131630209-7a9a87e4-0f4b-4e17-a268-f68032d460b0.png)

![image](https://user-images.githubusercontent.com/30521429/131630457-4c1cfed3-8849-42aa-a1ca-9de90eb64c55.png)

**Comment by tznind** [comment]
What is the output of:

```
echo $TERM
```

**Comment by 625781186** [comment]
```shell
root@lin:/www/gui.cs/UICatalog# echo $TERM
xterm
```

`dotnet run -usc` , But mouse click and scroll failure ,  becomes a `select`
![image](https://user-images.githubusercontent.com/30521429/131631200-c42eaf59-9cce-4579-a7ba-07ee2e55f7d1.png)

**Comment by tznind** [comment]
> But mouse click and scroll failure , becomes a select

Can you elaborate more on what is/isn't working in `-usc` mode? 

When running in `-usc` are all the colors usable including in the Scenarios 'Basic Colors' and 'Invert Colors'?
Are you able to use the application correctly with keyboard navigation only?
What is the problem with the mouse? is it just dragging or also clicking in general?

**Comment by 625781186** [comment]
> > But mouse click and scroll failure , becomes a select
> 
> Can you elaborate more on what is/isn't working in `-usc` mode?
> 
> When running in `-usc` are all the colors usable including in the Scenarios 'Basic Colors' and 'Invert Colors'?
> Are you able to use the application correctly with keyboard navigation only?
> What is the problem with the mouse? is it just dragging or also clicking in general?

![jdfw2](https://user-images.githubusercontent.com/30521429/131632853-cd271bf8-a8a9-4eaa-8559-b89119c741c7.gif)

**Comment by tznind** [comment]
Thanks for the video that is very helpful.  From the screenshot it looks like the click and drag is possibly being directly handled by the terminal client itself so probably doesn't even reach the Terminal.Gui code. There is a scenario 'Mouse' that you can use to see the events as Terminal.Gui sees them.

**Comment by 625781186** [comment]
> Thanks for the video that is very helpful. From the screenshot it looks like the click and drag is possibly being directly handled by the terminal client itself so probably doesn't even reach the Terminal.Gui code. There is a scenario 'Mouse' that you can use to see the events as Terminal.Gui sees them.
> 
> I would look in the xShell settings to see if there is a way to disable the mouse selecting / copy / paste features that it ships with and pass the mouse events direct to the other end.

OK , 
Thank you for your efforts ,
and look forward to your good news.

**Comment by 625781186** [comment]
There is also a problem about the fluency of the mouse, I will issue another issue

**Comment by BDisp** [comment]
I think changing the TERM environment to `xterm-256color` could make some difference. Try change and restart.
`export TERM=xterm-256color`

**Comment by tznind** [comment]
For the mouse issue I think that it is a side effect of the xshell client.  From the docs (https://cdn.netsarang.net/docs/Xshell6_manual.pdf):

> Terminal > Advanced 

> Set advanced terminal options. 

> Restrict Mouse Use at Terminal with Shift Key 
> Some  applications  such  as  ‘vi’  and  ‘mc’  can  use  mouse  click  and  drag  to  make  a  selection  or  
> change the directory. When this option is selected, press the Shift key while using the mouse and 
> Xshell uses the mouse input to perform actions such as making selection on the screen.   

Can you check the Settings and see if 'Restrict Mouse Use at Terminal with Shift Key' exists in your version of xShell and if so tick it.

**Comment by 625781186** [comment]
@tznind 

![image](https://user-images.githubusercontent.com/30521429/131660693-d8141ec7-bdc6-4006-b413-ba8b07036af3.png)
this setting all open , but use `-usc` still just select ,

I use  this method , https://github.com/migueldeicaza/gui.cs/issues/1451#issuecomment-910118796 , 
and run `dotnet run`  without -ucs , 
It's right show , But  mouse scroll failure , I will try ubuntu20.04 ,

![image](https://user-images.githubusercontent.com/30521429/131661194-2518ff06-101f-4c40-977b-7e5133ab838e.png)

**Comment by BDisp** [comment]
> Now , mouse click is right But mouse scroll failure , I will try ubuntu20.04

Yes. do please.
The `Xshell` might send his own coded escape sequence, that may differ with `Terminal.Gui` handles, or `Ubuntu 18.04` doesn't handles the scroll the same way the `20.04` version.

**Comment by 625781186** [comment]
ubuntu 20.04 scroll bar mouse wheel can scroll , 
but drag scroll can
