### ISSUE TITLE
Window control without border

### ISSUE THREAD

**Issue by phspies** [migueldeicaza/gui.cs#1453]
Do you have a way to create a window control without a border and also have a 0 border at the same time?

**Comment by BDisp** [comment]
Yes. Just set the `BorderStyle.None` and `DrawMarginFrame` to false.

**Comment by phspies** [comment]
I don't see any attribute that supports that in the Window class

`public class View : Responder, ISupportInitializeNotification, ISupportInitialize`

**Comment by phspies** [comment]
> Yes. Just set the `BorderStyle.None` and `DrawMarginFrame` to false.
> 
> ![window-no-border](https://user-images.githubusercontent.com/13117724/131872442-c5be8017-9169-4f5f-8e47-4e845c49d2e0.gif)

I see, but where do I get this in the Class?

**Comment by BDisp** [comment]
Tat is a wrapper to using with a Toplevel. Use the Window itself.

**Comment by phspies** [comment]
> Tat is a wrapper to using with a Toplevel. Use the Window itself.

When I create a new Window object, I don't see this attribute in the new object.

`static Window NewWindow = new Window() { };`

**Comment by BDisp** [comment]
> I don't see any attribute that supports that in the Window class

The `Border` is in the base class `View`.

**Comment by phspies** [comment]
> That is a wrapper to using with a `Toplevel`. Use the `Window` itself.
> 
> ```cs
> var win = new Window () {
> 	Border = new Border () {
> 		BorderStyle = BorderStyle.None,
> 		DrawMarginFrame = false,
> 		Effect3D = false,
> 	}
> };
> ```

Ok maybe I'm not running the code you using. I'm using "Terminal.Gui" v 1.2.1 in my console project. Is this the correct one?

**Comment by phspies** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'Window' does not contain a definition for 'Border'
```

**Comment by BDisp** [comment]
> Ok maybe I'm not running the code you using. I'm using "Terminal.Gui" v 1.2.1 in my console project. Is this the correct one?

I think it is only on the main branch.

**Comment by phspies** [comment]
> That is a wrapper to using with a `Toplevel`. Use the `Window` itself.
> 
> ```cs
> var win = new Window () {
> 	Border = new Border () {
> 		BorderStyle = BorderStyle.None,
> 		DrawMarginFrame = false,
> 		Effect3D = false,
> 	}
> };
> ```

**Comment by phspies** [comment]
Ok the NuGet package version number is not in sync with your Github version. I cloned the code and dropped it into my project and now it works.
