### ISSUE TITLE
Backspace stoped working with latest branch on OSX

### ISSUE THREAD

**Issue by phspies** [migueldeicaza/gui.cs#1456]
After updating to the latest build on Github the backspace/delete keystroke no longer works on OSX. Windows and Lunux (Ubuntu) is fine. Any ideas why?

**Comment by BDisp** [comment]
On the `Key` scenario what key event is print?

**Comment by phspies** [comment]
> On the `Key` scenario what key event is print?

Could you elaborate?

**Comment by BDisp** [comment]
![keys-scenario](https://user-images.githubusercontent.com/13117724/131920933-cb431c03-b7cb-4d4e-8cf4-6b3dccb48c53.gif)

**Comment by phspies** [comment]
![Screen Shot 2021-09-02 at 5 59 20 PM](https://user-images.githubusercontent.com/4684625/131921790-d16c5074-3221-48d9-b45e-eae41adaa2fe.png)

**Comment by phspies** [comment]
https://user-images.githubusercontent.com/4684625/131922216-2312e7c0-e862-4be4-9ab5-aacc77e3a8de.mov

**Comment by BDisp** [comment]
Mac running `CursesDriver` interprets somes keys differently. Please run with the `-usc` and see if the keys are right.

**Comment by phspies** [comment]
> Mac running `CursesDriver` interprets somes keys differently. Please run with the `-usc` and see if the keys are right.

That worked. How do I make this permanent without using the command line switch?

**Comment by BDisp** [comment]
Before call the `Application.Init` call `Application.UseSystemConsole` first.

**Comment by phspies** [comment]
Thank you, that worked!

**Comment by tig** [comment]
@BDisp does this issue describe bugs you think we can fix in `CursesDriver` that will allow it to work well on Mac. I think `-usc` is a short-term fix, right? 

Should we re-open this issue as a place holder for those bugs, or do you think there are already other issues filed that we are tracking? thanks.

**Comment by BDisp** [comment]
This can be done by comparing the operating system where is running and invoking the right event.
We could maintain this issue open.
