### ISSUE TITLE
INotifyPropertyChanged Capability

### ISSUE THREAD

**Issue by phspies** [migueldeicaza/gui.cs#1459]
Looking for a way to use a data model with the TableView and then fire an event to the TableView control once data inside the model has changed. In WPF you would use a NotifyPropertyChanged event. Do you have something similar in gui?

**Comment by tznind** [comment]
This should be very possible.  The discussion below shows how to present a list of data model objects (in the discussion it is the `Process` class.  Assuming you implement it as described then you should be able to refresh the data just using `SetNeedsDisplay()` 

https://github.com/migueldeicaza/gui.cs/issues/1285

**Comment by BDisp** [comment]
You can also use the `INotifyPropertyChanged`. See the `DynamicMenuBar.cs`  and `DynamicStatusBar.cs` scenarios implementation.

The model class:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L1004

The binding class:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L1056

The converter interface:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L1052

The converter class:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L1106

The data context property;
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L73

The bindings declarations:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L501-L503

The converters declarations:
https://github.com/migueldeicaza/gui.cs/blob/8bfa2f042509138dbcd5c904fe94912f1e344949/UICatalog/Scenarios/DynamicMenuBar.cs#L499

**Comment by phspies** [comment]
> This should be very possible. The discussion below shows how to present a list of data model objects (in the discussion it is the `System.Diagnostics.Process` class. Assuming you implement it as described then you should be able to refresh the data just using `SetNeedsDisplay()` as at render time the `RepresentationGetter` will be called for each cell and the data will be served up out of your class.
> 
> Discussion: #1285
> 
> If after reading the discussion you still have questions please just say so and if possible provide some more details of your data model and I can advise more.

Thank you for the feedback. I think I'm maybe set is what I do when I use WPF, so you could maybe let me know how I could achieve the same in GUI.CS.

WPF would enable me to attached a List<T> as a source to the WPF control. This enables me to fire the INotifyPropertyChanged event if anything changed within the model which in turns updates the display.

In GUI.cs it seems the acceptable approach would be to use a DataTable which is fine but I don't see any example to exposing the INotifyPropertyChanged event with in this object type.

**Comment by tznind** [comment]
Ok here is a fully worked example:

```csharp
Application.Init();

// create some demo customers
var customers = new List<DemoCustomer>();
customers.Add(DemoCustomer.CreateNewCustomer());
customers.Add(DemoCustomer.CreateNewCustomer());
customers.Add(DemoCustomer.CreateNewCustomer());
customers.Add(DemoCustomer.CreateNewCustomer());

Random r = new Random();

// every 2 seconds change a customers name
Application.MainLoop.AddTimeout(TimeSpan.FromSeconds(2),
	(a) =>
	{
		var idx = r.Next(4);
		customers[idx].CustomerName = "Customer" + r.Next(9);
		return true;
	}
	);

var dt = new DataTable();
var id = dt.Columns.Add("ID",typeof(int));
var name = dt.Columns.Add("CustomerName", typeof(int));
var number = dt.Columns.Add("PhoneNumber", typeof(int));

// for each customer add a row to the table
for(int i=0;i<customers.Count;i++)
{
	// BUT don't store the actual values only store the index of the 
	// list that the customer appears
	dt.Rows.Add(i, i, i);
}


// create a table view and the data source of the view to the DataTable we created (that has the indexes)
var tv = new TableView(dt)
{
	Width = Dim.Fill(),
	Height = Dim.Fill(),
};

// when rendering the cell convert the index into the current value of the property
tv.Style.GetOrCreateColumnStyle(id).RepresentationGetter = (i) => customers[(int)i].ID.ToString();

// Same for customer name
tv.Style.GetOrCreateColumnStyle(name).RepresentationGetter = (i) => customers[(int)i].CustomerName;

// Same for phone number
tv.Style.GetOrCreateColumnStyle(number).RepresentationGetter = (i) => customers[(int)i].PhoneNumber;

// register PropertyChanged event to refresh table
foreach (var customer in customers)
{
	customer.PropertyChanged += (s,e)=> tv.SetNeedsDisplay();
}

var w = new Window()
{
	Width = Dim.Fill(),
	Height = Dim.Fill(),
};

w.Add(tv);

Application.Run(w);

Application.Shutdown();
```

It uses the DemoCustomer class from the [Microsoft INotifyPropertyChanged demo](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=net-5.0).  I have copied the DemoCustomer class below for convenience.

```csharp
// This is a simple customer class that 
// implements the IPropertyChange interface.
public class DemoCustomer : INotifyPropertyChanged
{
    // These fields hold the values for the public properties.
    private Guid idValue = Guid.NewGuid();
    private string customerNameValue = string.Empty;
    private string phoneNumberValue = string.Empty;

    public event PropertyChangedEventHandler PropertyChanged;

    // This method is called by the Set accessor of each property.
    // The CallerMemberName attribute that is applied to the optional propertyName
    // parameter causes the property name of the caller to be substituted as an argument.
    private void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
    {
        if (PropertyChanged != null)
        {
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    // The constructor is private to enforce the factory pattern.
    private DemoCustomer()
    {
        customerNameValue = "Customer";
        phoneNumberValue = "(312)555-0100";
    }

    // This is the public factory method.
    public static DemoCustomer CreateNewCustomer()
    {
        return new DemoCustomer();
    }

    // This property represents an ID, suitable
    // for use as a primary key in a database.
    public Guid ID
    {
        get
        {
            return this.idValue;
        }
    }

    public string CustomerName
    {
        get
        {
            return this.customerNameValue;
        }

        set
        {
            if (value != this.customerNameValue)
            {
                this.customerNameValue = value;
                NotifyPropertyChanged();
            }
        }
    }

    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberValue;
        }

        set
        {
            if (value != this.phoneNumberValue)
            {
                this.phoneNumberValue = value;
                NotifyPropertyChanged();
            }
        }
    }
}
```

**Comment by phspies** [comment]
Wow, ok let me give this a try. Thank you for taking the time to put this out in the clear manner you did!

**Comment by phspies** [comment]
Just to confirm, how would this change if I want to fire a addition event when I add to the List?

**Comment by tznind** [comment]
> Just to confirm, how would this change if I want to fire a addition event when I add to the List?

So given the above solution and the fact that you are only adding new rows you would just have to add a new `DataRow` to the `DataTable` with the new index:

```csharp
myCollection.Add(myNewInstance);

var newMaxIdx = myCollection.Count-1;
tv.Table.Rows.Add(newMaxIdx,newMaxIdx,newMaxIdx, [...]);

tv.Update();
tv.SetNeedsDisplay();
```

If you are adding and taking away rows then it gets more complex:

I would first try to identify a key into your data structure e.g. Name or ID etc.  That way you will be able to persist the users selection and generally be sensible about handling updates.  I would use a concurrency safe collection e.g. `ConcurrentDictionary<k,v>`.  

Then I would store the Key instead of the index in the `DataTable`. 

```
tv.Table.Rows.Add(objectsKey,objectsKey,objectsKey,...);
```

That would change the `RepresentationGetter` (to something like below - if your key is a string):

```
tv.Style.GetOrCreateColumnStyle(id).RepresentationGetter = (k) => customers[(string)k].ID.ToString();
```

Then you can prune the DataTable as often as you want and sync it with your collection.  Make sure to call `Update()` and then `SetNeedsDisplay()` so that it knows the underlying table has changed and updates the UI.

**Comment by phspies** [comment]
Perfect, thank you!
