### ISSUE TITLE
Support unicode chars in ListViews and TextFields

### ISSUE THREAD

**Issue by awaescher** [migueldeicaza/gui.cs#146]
I am not sure if I just repeat issue #93 here. Sorry if I do.

## Issue

I am currently using some unicode signs like: ≡ ⌂ ↑ ↓ …

![unicodesguics](https://user-images.githubusercontent.com/3630638/48164927-4aca6880-e2e4-11e8-92f1-59335e372394.png)

While rendering them in a ListView or TextField, I got a `IndexOutOfRangeException`. In Labels, everything is okay.
```
   at System.Rune.bisearch(UInt32 rune, UInt32[,] table, Int32 max)
   at System.Rune.ColumnWidth(Rune rune)
   at Terminal.Gui.ListView.ListWrapper.RenderUstr(ustring ustr, Int32 col, Int32 line, Int32 width)
   at Terminal.Gui.ListView.ListWrapper.Render(Boolean marked, Int32 item, Int32 col, Int32 line, Int32 width)
   at Terminal.Gui.ListView.Redraw(Rect region)
   at Terminal.Gui.View.Redraw(Rect region)
   at Terminal.Gui.Window.Redraw(Rect bounds)
   at Terminal.Gui.View.Redraw(Rect region)
   at Terminal.Gui.Application.Redraw(View view)
   at Terminal.Gui.Application.Begin(Toplevel toplevel)
   at Terminal.Gui.Application.Run(Toplevel view)
   at grrui.Program.Main(String[] args) in D:\Develop\GitHub\RepoZ\grrui\Program.cs:line 43
```

It turns out that `"\u2261"` for example, returns Rune `8801`. `Rune.ColumnWidth(8801)` throws.

![indexoutofrangeexception](https://user-images.githubusercontent.com/3630638/48164772-c37cf500-e2e3-11e8-82ac-bf54110d221d.png)

## How to reproduce
Simply replace the **Example\demo.cs** in your solution and hit <kbd>F5</kbd>.

```
using Terminal.Gui;

static class Demo {
    static void Main()
    {
	Application.Init();
	var top = Application.Top;
	var tframe = top.Frame;

	var win = new Window("Unicode chars") {
	    X = 0,
	    Y = 0,
	    Width = Dim.Fill(),
	    Height = Dim.Fill()
	};

	var unicodeChars = "\u2261 \u2302 \u2191 \u2193 \u2026";

	var lbl = new Label("They work in Labels: " + unicodeChars) 
	{
	    X = 1,
	    Y = 2
	};

	// ** COMMENT THIS OUT TO SEE THE CRASH **
	unicodeChars = "--CENSORED--";

	var txt = new TextField("But they won't work in TextFields: " + unicodeChars)
	{
	    X = Pos.Left(lbl),
	    Y = Pos.Bottom(lbl) + 1,
	    Width = 50
	};

	var lst = new ListView(new string[] {
	    "They won't work in ListViews as well.",
	    "Here they come: " + unicodeChars,
	    "If you want to try this out by yourself,",
	    "simply remove that line saying \"CENSORED\" in code."
	    }
	) {
	    X = Pos.Left(lbl),
	    Y = 6,
	    Width = Dim.Fill(),
	    Height = Dim.Fill()
	};
	lst.SelectedItem = 0;

	win.Add(lbl);
	win.Add(txt);
	win.Add(lst);
	top.Add(win);

	Application.Run();
    }
}
```

**Comment by awaescher** [comment]
I fixed this issue in NStack, so I opened [a further issue it over there](https://github.com/migueldeicaza/NStack/issues/43) to be able to fix it with [PR44](https://github.com/migueldeicaza/NStack/pull/44).

Let's keep this one open until the fix made it into NStack and gui.cs updates to a new version.

**Comment by tig** [comment]
The `UnicodeInMenu` scenario in `UI Catalog` would be a great place to put a repro of this...

**Comment by tig** [comment]
Using the `Unicode` Scenario, I believe this no longer repros.
![image](https://user-images.githubusercontent.com/585482/84182539-cdc71e00-aa47-11ea-87ba-293f7a48e75c.png)

**Comment by awaescher** [comment]
Beautiful. I can confirm this is fixed. Thank you very much:

![image](https://user-images.githubusercontent.com/3630638/84248392-a59ff380-ab09-11ea-8226-f10f59309e2b.png)
