### ISSUE TITLE
Example pegs cpu, laggy input handling

### ISSUE THREAD

**Issue by isaksky** [migueldeicaza/gui.cs#1460]
After doing this (with latest master):

```
cd gui.cs/example
dotnet run
```

This is what I'm seeing when I expected the app to be idle (I wasn't interacting with it, or even moving the mouse):

![image](https://user-images.githubusercontent.com/607986/132892799-b3d328d1-59ea-47a2-9ad6-155a72c7bcc4.png)

https://user-images.githubusercontent.com/607986/132892676-aab4f441-f5c4-431c-bd54-421b13b524ae.mp4

In that example, I'm smashing the keyboard for a second or so, and as you can see it takes it a very long time to catch up.

Above I just did dotnet run, but building release version and running that .exe yields the same result.

## System Info:
- Windows 10 (Build 19041), 
- .NET 5.0.400.
- Windows Terminal Preview 8 (but the results seem similar in other terminals)

**Comment by isaksky** [comment]
Oh, it was just the Example.csproj. The other projects, like UICatalog, seem fine.

**Comment by BDisp** [comment]
The main reason for this lag occur is because it is using the `NetDriver` which working with the `System.Console`. So writing is made cell by cell because there is no buffering system of contents that can provide a one output from once.
