### ISSUE TITLE
TableView Sorting

### ISSUE THREAD

**Issue by phspies** [migueldeicaza/gui.cs#1461]
Been using the TableView and for the most part, when the widget seems to honor my sorting arrangement in the DataView. I have a DataTable using a DateTime type as its first column and then I apply a sorting of descending to this view, the TableView seems to ignore it.

I exported the DataTable to a file to confirm the order, and it's correct, but DataTable seems to apply its own sorting to this one table. Is there something I need to do to make this work?

**Comment by phspies** [comment]
Appologies, I was using the .Data method to set the source for this TableView and not the .Table.

**Comment by tznind** [comment]
> 
> Apologies, I was using the .Data method to set the source for this TableView and not the .Table.

Have done this myself, more than once lol.  Its annoyingly easy mistake to make.
