### ISSUE TITLE
Mouse button release outside console window

### ISSUE THREAD

**Issue by tlemmons** [migueldeicaza/gui.cs#1462]
I am selecting text by mouse button on pressed and then released.  The problem I have is that if the mouse goes outside of the console window while held, I do not get any event saying the button is released or that the mouse left the window.  Am I missing something or how can I recognize the end of my selection.

**Comment by tznind** [comment]
I am still getting mouse events even with cursor outside the console window.  Can you run UICatalog and say if you are able to replicate the behavior in the gif below (still getting mouse events even outside the console window).

Also please use Editor and Notepad scenarios and see if you are able to end a text selection with a mouse up event outside the console window.  If you see different behavior in UICatalog please say and include the Terminal and OS you are running.

![mouse-events](https://user-images.githubusercontent.com/31306100/133311213-1986434b-fc93-49fb-ae65-592b6ec24641.gif)

**Comment by tlemmons** [comment]
Thanks for the pointer.  I looked through the mouse scenario and found Application.RootMouseEvent which does seem to work for my needs.  A little different then just using the mouseEvent but workable.  Thanks.

**Comment by tlemmons** [comment]
Well some issues with using rootMouseEvent is that I get the mouse events even if my window is not focused.  However it does not seem like the "hasfocus" check works as it shows the window has focus when the main menu is clicked on.  I think I need access to Application.mouseGrabView but it is marked as internal.  For my app I would need it public.

**Comment by tlemmons** [comment]
That makes sense.  I did not see that.  I will try it.  Thanks.

**Comment by tig** [comment]
@tlemmons let us know if you are still having issues with this.

**Comment by tlemmons** [comment]
Nope.  Got it working.  Thanks for checking.
