### ISSUE TITLE
Threading Question

### ISSUE THREAD

**Issue by phspies** [migueldeicaza/gui.cs#1464]
I have 7 tables that are updated by a background thread continuously. The code seems to work but from time to time the TableView code crashes with random error, which I assume has to do with the Table collection being altered.

Is there a way to "pause" the TableView or lock the DataTable to allow the background threads to update the table and then continue once the update is complete?

**Comment by tznind** [comment]
Hey, can you try only applying changes to your `DataTable` through invoking on the MainLoop.  I think that should resolve your problem and prevent the changes clashing with redraw etc.

```csharp
Application.MainLoop.Invoke (() => { 
             // make changes to your table here
});
```

**Comment by phspies** [comment]
Ok refactored my code to use RepresentationGetter approach from a List<T> and applied the fix you mentioned. The only problem is that the TableView won't refresh not until I click with my mouse or hit the tab key.

Any reason for this change of behaviour?

**Comment by BDisp** [comment]
That why you must use the `Application.MainLoop.Invoke` or `Application.DoEvents` from the thread where the changes was made to refresh the UI.

**Comment by phspies** [comment]
When I do that I get the following Exception: System.Data.RowNotInTableException: 'This row has been removed from a table and does not have any data.  BeginEdit() will allow creation of new data in this row.'

The process to sort a DataTable after updating requires the creation of a new DataTable. This seems to throw the TableView widget off as setting the TableView object's Table attribute forces an update on this control:

		`public DataTable Table { get => table; set { table = value; Update (); } }`

Between this process forcing the update and me also trying to perform the update, might be cause this problem?

**Comment by BDisp** [comment]
If you are iterating with foreach and delete at the same time you'll get errors. You must convert to an array, doing the changes and then updating the `DataTable`. Since you have multi processes updating the same `DataTable` maybe you need to notify them that the `DataTable` was changed or updating the `ConcurrentDictionary<,>` which is shared between the processes.

**Comment by tznind** [comment]
> Ok refactored my code to use RepresentationGetter approach from a List and applied the fix you mentioned. The only problem is that the TableView won't refresh not until I click with my mouse or hit the tab key.

Thanks for persisting with this.  Sounds like you were almost there at this point.  Did you call `SetNeedsDisplay()` after making changes in the `Application.MainLoop.Invoke`.  Are you able to share code so I can try to reproduce your issue?

**Comment by phspies** [comment]
I'm using a ConcurrentDictionary for my data but the exception happens inside the TableList control.

This is what I've done which seems to have solved the problem.

I added a new attribute to the TableView Class called: public bool IsUpdatingTable = false;

Also added a check in Redraw and Update to make sure nothing else tries to perform an update while I'm pusing a new DataTable:

```
		public override void Redraw (Rect bounds)
		{
			if (IsUpdatingTable)
            {
				return;
            }

-----

	public void Update ()
		{
			if (IsUpdatingTable)
			{
				return;
			}
```
Inside my code I do the following:

```
                eventsTableView.IsUpdatingTable = true;
                podsTableView.IsUpdatingTable = true;
                Application.DoEvents();
                eventsList.AddChange(new EventType(eventType, pod));
                eventsTableView.Table = eventsList.RebuilDataTable();
                eventsTableView.IsUpdatingTable = false;
                eventsTableView.Update();
                podsList.AddChange(new PodType(pod));
                podsTableView.Table = podsList.RebuilDataTable();
                podsTableView.IsUpdatingTable = false;
                podsTableView.Update();
```

And this seems to have solved the problem now.

**Comment by BDisp** [comment]
As @tznind said, you need to call `SetNeedsDisplay()` to your `TableView` object in the threading before the `Application.MainLoop.Invoke` or the `Application.DoEvents`. Otherwise the `TableView` would not be redrawed.

**Comment by phspies** [comment]
Yes, that doesnt help:

`   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at Terminal.Gui.TableView.RenderRow(Int32 row, Int32 rowToRender, ColumnToRender[] columnsToRender) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Views\TableView.cs:line 418
   at Terminal.Gui.TableView.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Views\TableView.cs:line 252
   at Terminal.Gui.View.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Core\View.cs:line 1401
   at Terminal.Gui.TabView.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Views\TabView.cs:line 183
   at Terminal.Gui.View.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Core\View.cs:line 1401
   at Terminal.Gui.Window.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Core\Window.cs:line 271
   at Terminal.Gui.View.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Core\View.cs:line 1401
   at Terminal.Gui.Toplevel.Redraw(Rect bounds) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui\Core\Toplevel.cs:line 632
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in C:\Users\Phillip\source\repos\k8config\k8config\Terminal.Gui`

**Comment by phspies** [comment]
So trying to get close to what you said about `SetNeedsDisplay()`. I have the following code which seems to work if I lock the TableView object between the threads. Is this what you were refering to?

      ```
          lock (eventsTableView)
                {
                    Application.DoEvents();
                    eventsTableView.SetNeedsDisplay();

                    eventsList.AddChange(new EventType(eventType, pod));
                    eventsTableView.Table = eventsList.RebuilDataTable();
                }
```

**Comment by BDisp** [comment]
eventsTableView.SetNeedsDisplay(); must be called before Application.DoEvents(); to be signalled when returned from the mainloop

**Comment by tznind** [comment]
Ok so some general observations here.

- `ColumnStyles` is a dictionary of `DataColumn` to `ColumnStyle` which means changing the `Table` to a new instance with different column instances will probably mean you need to re-declare the styles
- Any time you are accessing a `DataTable` you should have a lock around it or do it using `Application.MainLoop.Invoke`

TableView has no background processing tasks itself.  It will only access your table during ReDraw and if you call `Update` or change the `Table` property (which as you spotted triggers Update).

Since redrawing all happens on the main loop UI thread I would suggest avoid making any Table changes at all in your threads and just deal with the `ConcurrentDictionary`.

Then when it comes time to rebuild the table do that using `Application.MainLoop.Invoke` so that it happens after drawing and on the main UI thread.  Since the callback happens after drawing you presumably need both `SetNeedsDisplay` and `DoEvents` to ensure that the changes get redrawn correctly (otherwise they wouldn't appear till a keystroke - like you were seeing).


### Side Note
This behavior/constraint is consistent with other UI frameworks like WinForms.  When you set `myTextBox.Text = "bob";` from a Thread that isn't the UI thread you get an Exception (`Winforms Cross-thread operation not valid: `).  In that framework you would use `myControl.Invoke(()={ ... })`,  Here you use the MainLoop Invoke.

**Comment by BDisp** [comment]
Only to clarify. If you are changing many things, other than only setting the `SetNeedsDisplay`, then you must use the `Application.MainLoop.Invoke` which adds a idle to the main loop and return `true` from the events pending. The `Application.DoEvents()` will return `false` from the main loop events pending, if there are no idle functions to be running and only will redraw the `UI` if `!NeedDisplay.IsEmpty || ChildNeedsDisplay || LayoutNeeded`.

**Comment by phspies** [comment]
> eventsTableView.SetNeedsDisplay(); must be called before Application.DoEvents(); to be signalled when returned from the mainloop

Thank you, I've made that change.

**Comment by phspies** [comment]
Ok, I implemented all the controls mentioned and sadly we still crashing in the TableView Class.

`           lock (eventLockObject)
            {
                eventsTableView.SetNeedsDisplay();
                Application.DoEvents();
                eventsList.AddChange(new EventType(_eventType, _object));
                eventsTableView.Table = eventsList.RebuilDataTable();
                eventsTableView.SetNeedsDisplay();
            }
`

This is run from two threads that needs to update same table but with the lock inplace. The TableView is only updated in this method with the `ConcurrentDictionary` being the only source for the `eventsTableView.Table = eventsList.RebuilDataTable()' function call.

This is my code that updates the `ConcurrentDictionary` object:
`public void AddChange(EventType newObject)
        {
            newObject.Index = Dictionary.Count > 0 ? Dictionary.Max(x => x.Key) + 1 : 0;
            Dictionary.TryAdd(newObject.Index, newObject);
        }
`

And then my DataTable rebuild code:
`
    public DataTable RebuilDataTable()
        {
            lock (dataTable.Rows.SyncRoot)
            {
                dataTable.Rows.Clear();
                (from x in Dictionary orderby x.Value.TimeStamp descending select x).ToList().ForEach(record =>
                {
                    DataRow _row = dataTable.NewRow();
                    for (int i = 0; i < Members.Length; i++)
                    {
                        _row.SetField((Members[i].GetCustomAttribute(typeof(DataNameAttribute), false) as DataNameAttribute).Column, record.Key);
                    }
                    dataTable.Rows.Add(_row);
                });
                Debug.WriteLine($"{dataTable.Rows.Count} EventType rows to return");
            }
            return dataTable;
        }
`

None of my subroutines fails, it's just the TableView that keeps crashing.

**Comment by BDisp** [comment]
Do the call to the `RebuilDataTable` is inside a `Application.MainLoop.Invoke (() => RebuilDataTable ())`?

**Comment by phspies** [comment]
I think that is the problem. Let me see if that solves the problem.

**Comment by phspies** [comment]
This fixed the problem. Thank you for your patience and assistance with this :)
