### ISSUE TITLE
AlternateForward/BackwardKey bypasses dialog modality

### ISSUE THREAD

**Issue by crnobog** [migueldeicaza/gui.cs#1467]
I'm trying to create a dialog which contains a TabView, where the tabs contain TextViews. I expected to be able to use the AlternateForward/BackwardKey controls to switch tabs when in the text view, because Tab/Ctrl+Tab would get swallowed by the text view.
Unfortunately, the input seems to bypass the modality of the dialog, and start cycling through the controls of the Window the Dialog ought to be blocking.
My solution is to bind KeyPress on the TabView and override these keys, but I'm not sure if this should be necessary.

**Comment by BDisp** [comment]
Yes it's necessary. See the `Editor` scenario of the `UICatalog`. Change like the following.

```cs
Win.KeyPress += (e) => {
	var keys = ShortcutHelper.GetModifiersKey (e.KeyEvent);
	if (winDialog != null && (e.KeyEvent.Key == Key.Esc
		|| e.KeyEvent.Key == (Key.Q | Key.CtrlMask))) {
		DisposeWinDialog ();
	} else if (e.KeyEvent.Key == (Key.Q | Key.CtrlMask)) {
		Quit ();
		e.Handled = true;
	} else if (keys == (Key.Tab | Key.CtrlMask)) {
		if (_tabView.SelectedTab == _tabView.Tabs.ElementAt(_tabView.Tabs.Count - 1)) {
			_tabView.SwitchTabBy (-1);
		} else {
			_tabView.SwitchTabBy (1);
		}
		e.Handled = true;
	} else if (keys == (Key.Tab | Key.CtrlMask | Key.ShiftMask)) {
		if (_tabView.SelectedTab == _tabView.Tabs.ElementAt (0)) {
			_tabView.SwitchTabBy (_tabView.Tabs.Count - 1);
		} else {
			_tabView.SwitchTabBy (-1);
		}
		e.Handled = true;
	}
};
```

**Comment by crnobog** [comment]
Thanks for the quick response! 

Just to be clear, it's not fact that the TextView consumes the Tab presses that's the problem. That seems entirely reasonable to me. I was just explaining why I was trying to use AlternateBackwardKey/AlternateForwardKey to navigate.

The issue I see is that Ctrl+PgUp/Ctrl+PgDown (AlternateBackwardKey/AlternateForwardKey) change the focused widget to something in a different Toplevel, outside of the model dialog that I've opened using a recursive call to Application.Run. If anything, I would expect those keys to cause focus to cycle around the elements of the dialog - whatever controls and buttons I've added to it.

**Comment by BDisp** [comment]
Yes you are right. The `TextView` consumes this keys combinations. The `AlternateBackwardKey/AlternateForwardKey` are a good solution. Change to this keys and sets the `e.Handled = true`. On a dialog window it can't navigate to different toplevels because the dialog is modal.

**Comment by crnobog** [comment]
I'm saying that it _does_ navigate to different toplevels in my program. I can try to put together a minimal repro.

**Comment by crnobog** [comment]
This example reproduces the issue for me in UICatalog:

```csharp
using System;
using System.Text;
using Terminal.Gui;

namespace UICatalog {

	[ScenarioMetadata (Name: "Cycle Under Dialog", Description: "Shows cycling of controls under modal dialog")]
	[ScenarioCategory ("Bug Repro")]
	class CycleUnderDialog : Scenario {
		public override void Setup ()
		{
			Win.Add (new Button ("Button One") { X = 2, Y = 2 });
			Win.Add (new Button ("Button Two") { X = 2, Y = 4 });

			var open_button = new Button ("Open Dialog") { X = 2, Y = 6 };
			open_button.Clicked += () => OpenDialog ();
			Win.Add (open_button);
		}

		void OpenDialog ()
		{
			Action confirm = () => { Application.RequestStop (); };
			Action cancel = () => { Application.RequestStop (); };

			var button_ok = new Button ("Ok");
			button_ok.Clicked += confirm;
			var button_cancel = new Button ("Cancel");
			button_cancel.Clicked += cancel;
			var dialog = new Dialog ("Modal Dialog", 50, 6, new Button [] { button_ok, button_cancel });

			dialog.Add (new Label ("Try cycling with Ctrl+PgUp, Ctrl+PgDown") { X = Pos.Center (), Y = Pos.Center () });

			Application.Run (dialog);
		}
	}
}
```

**Comment by tznind** [comment]
Thanks for taking the time to write a scenario  @crnobog! @BDisp looks like the alternate page up/page down is detected in `TopLevel` making it a different code path to normal Tabbing?

**Comment by BDisp** [comment]
@crnobog, @tznind thanks for point this bug to me and for the scenario. I already submitted a PR with the fix.

**Comment by BDisp** [comment]
The bug were related with both, the `Ctrl+Tab/Ctrl+Shift+Tab` and the `AlternateBackwardKey/AlternateForwardKey`.

**Comment by crnobog** [comment]
Great! Thanks for the fix. I grabbed the PR locally and it works great in the UICatalog scenario I added.

**Comment by BDisp** [comment]
Yes please. Thanks.
