### ISSUE TITLE
Mouse input delay in Windows Terminal

### ISSUE THREAD

**Issue by Trolldemorted** [migueldeicaza/gui.cs#1477]
I just ran `dotnet run --project UICatalog` in a cmd, a powershell and a windows terminal powershell, and noticed a huge mouse input delay in the latter.

I guess that is not intended? Can I do something do make gui.cs programs run smoothly in the windows terminal?

**Comment by BDisp** [comment]
It's a bug that is causing the click event is not processing. Checkout the PR https://github.com/migueldeicaza/gui.cs/pull/1447 and test, please.

**Comment by Trolldemorted** [comment]
That branch works significantly faster! However after pressing ctrl+q the bottom line (`Caps: Off │ Num: Off │ Scroll: Off │ CTRL-Q Quit │ F10 Hide/Show Status Bar │ WindowsDriver`) remains.

**Comment by BDisp** [comment]
@Trolldemorted I already fixed, please test. Thanks for reporting this.

**Comment by Trolldemorted** [comment]
Works like a charm!

Could you publish a new stable release with these fixes?

**Comment by BDisp** [comment]
Thanks. Only @migueldeicaza or @tig can do that.
