### ISSUE TITLE
Change Background Color

### ISSUE THREAD

**Issue by stevozilik** [migueldeicaza/gui.cs#148]
Any way to change background color from blue to something else?
I've tried setting ColorScheme on everything I can see and no luck...

Regards,
Stefan

**Comment by tayabsoomro** [comment]
Has anyone figured this out yet?

**Comment by wolfbyte** [comment]
From what @migueldeicaza has asked, I would gather that it's possible to set the Color Scheme, but I can't find out in the documentation how to do it. 

Can we get some guidance on that?

**Comment by PioArchiver** [comment]
I found the following in [CursesDriver.cs](https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Drivers/CursesDriver.cs
)

I could use any information regarding how to implement it properly. 
Also found this and a bunch of other color theme methods in the above named file. 

```
public override void SetColors (ConsoleColor foreground, ConsoleColor background)
```

Maybe their is an issue with #84 for cross platform compat.

I saw these too #61, #29, and #48 too

**Comment by PioArchiver** [comment]
Hi @migueldeicaza was wondering if I should put up an issue for guidance about the last commit you did to expose the MakeColor part of the curses API?

**Comment by Benjamintf1** [comment]
That's rather confusing. I'd assume that `SetColors()` or `SetAttribute` to set the background colors, but I was only able to set the colors by manually setting `Terminal.gui.Colors.Base` and editing the `application.Driver` didn't seem to do anything. 

Specificially the line to change the blue is 

```
using Terminal.Gui;
...
            Colors.Base = Colors.Dialog;
```

I'mt testing this on windows.

**Comment by migueldeicaza** [comment]
There are a number of ways of changing the color.

The first thing is to configure the `ColorScheme`, which defines all the global colors after you have called Application.Init:

```
Application.Init ();
Colors.Base.Normal = Application.Driver.MakeAttribute (Color.Green, Color.Black);
```

The other one is to set the ColorScheme on a specific view, here I just change it to the error one, but you can create your own:

```
var win = new Window (...)
win.ColorScheme = Colors.Error;
```

**Comment by Benjamintf1** [comment]
Solid, TY!
