### ISSUE TITLE
Docker compatibility / switching back to regular console

### ISSUE THREAD

**Issue by kierenj** [migueldeicaza/gui.cs#1480]
I'm curious as to the path I can take to implement this..

1. I'd like to be able to run the UI in a docker container - specifically on Kubernetes, being able to attach to a pod and use a UI. The app runs, but I get "container did not allocate a TTY" when connecting, and the UI doesn't display correctly. Is there any big reason for this?
2. I'd like to be able to switch on/off the UI. Looking at the drivers, it looks like the input is handled with a `while(true)` in a `Task.Run`, so it seems infinite? Do I have that right?

**Comment by tznind** [comment]
Could you explain a bit more about what you want? Does regular `Console.ReadLine` and `Console.WriteLine` work as you want in the environment you are using?

**Comment by tznind** [comment]
Here is a simple example

```csharp
for (int i=0;i<3;i++) {

	Application.Init ();

	Task.Run (() => {
		Task.Delay (3000).Wait ();

		Application.MainLoop.Invoke (() => {

			Application.RequestStop ();
		});
	});


	var r = new Random ().Next ();
	var l = new Label ($"Greetings agent {r}.  Your mission should you choose to accept it is to write a multi threaded program");
	var l2 = new Label ($"This message will self destruct in 3 seconds") { Y = 1 };
	var window = new Window () {
		Width = Dim.Fill (),
		Height = Dim.Fill ()
	};
	window.Add (l);
	window.Add (l2);

	Application.Run (window);

	Application.Shutdown ();

	Console.WriteLine ("Press any button to go again");
	Console.ReadLine ();
}
```

![image](https://user-images.githubusercontent.com/31306100/136648977-9bd0e09d-0036-47a0-8120-3c192e97d219.png)
