### ISSUE TITLE
Wrong Background Colors when using in System.Console

### ISSUE THREAD

**Issue by arakis** [migueldeicaza/gui.cs#1485]
If you integrate Gui.cs in an existing application that's logging to text System.Console, it will mess up the gui.cs colors. You do not see any System.Console Text s (that's fine), and the texts of Gui.cs are fine, but at some point, the background color of panels will stick to an specific style color.

For example, if i'm using green as a text color within gui.cs, at some point the whole background will stick to green (for ever), and you cannot read the green text on green background.

I've fixed that issue with using a Fake System.Console that redirects all the output and not touching the Sytem.Console.ForegroundColor. I did not tested if it has todo with the Systme.Console....Colors. But you should know, gui.cs is randomly sticking to colors NOT USING in system.console, for example, i never used "green" there before.

**Comment by tig** [comment]
is this a bug?

**Comment by BDisp** [comment]
No, was a thread implementation issue only.

**Comment by arakis** [comment]
I try to provide an mini Sample within the next days.

**Comment by tig** [comment]
@arakis if you are still struggling with this please reopen
