### ISSUE TITLE
GraphView.MarginBottom shifts ScrollOffset

### ISSUE THREAD

**Issue by Trolldemorted** [migueldeicaza/gui.cs#1487]
I have a graph that displays only discrete values on the y-axis, so I set the ScrollOffset to `(0, 0)` and `AxisY.Increment` to an "integer". This works like expected, I see only "integers" on the y labels and everything is fine.

However if I set `MarginBottom` to e.g. 3 I don't get the expected margin around the graph space where my labels can reside, but all my y labels are now askew and no longer "integers".

Is that the intended behaviour? Do I have to calculate an appropriate ScrollOffset from `CellSize`?

**Comment by Trolldemorted** [comment]
Do you think it would be possible to include the fix in a release within the next few days? I have a non-negotiable deadline coming up and would otherwise have to adapt our CI to build your branch directly :)

**Comment by tznind** [comment]
Hmn... I'm not sure about what the release timeline will be.  I know @tig is planning a nuget release soon... @tig any chance of please reviewing/including this PR (https://github.com/migueldeicaza/gui.cs/pull/1488) in the next release?
