### ISSUE TITLE
Textfield input events

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#149]
I would like to limit what type of keys can be input to a box. In my case some numbers only. In WPF I'd have a PreviewTextInput event where I could see the key and either allow it or cancel it.

This could also be used to process other items like max width. Right now just the Changed Event that passes the whole thing.

**Comment by migueldeicaza** [comment]
I feel that this should be achieved with a subclass, and overriding the "Pre" handler for the keyboard input.
