### ISSUE TITLE
Changing the text of Label won't update the terminal

### ISSUE THREAD

**Issue by qdwang** [migueldeicaza/gui.cs#1498]
Changing the text of Label won't update the terminal unless I move the mouse around in the console frame.

And I don't find and update methods like `label.Update()` or `label.Refresh()`.

OS: windows 10, terminal: CMD

**Comment by qdwang** [comment]
Sorry but it's not working. I tried both setting `SetNeedsDisplay` on label and `Application.Top`, but it still needs moving the mouse to repaint the UI.

**Comment by tznind** [comment]
I have had a little look.  The following minimum example works but if you remove `Application.DoEvents()` then it doesn't work (requires the mouse to move before it will update).  @BDisp was it always like this or is this a regression/deliberate change? 

```csharp
static void Main(string[] args)
{
    Application.Init();

    var w = new Window();
    var lbl = new Label();
    w.Add(lbl);

    var t = new Task(()=>
    {
        while(true)
        {
            lbl.Text = DateTime.Now.ToString();
            lbl.SetNeedsDisplay();
            Application.DoEvents();
            Task.Delay(1000).Wait();
        }
    });

    t.Start();

    Application.Run(w);

    Application.Shutdown();


}
```

**Comment by BDisp** [comment]
Only call SetNeedsDisplay() doesn't ensure the view to being redraw on a thread. The main loop must be called and the second example is the better as solution.

**Comment by qdwang** [comment]
Updating contents in `Application.MainLoop.Invoke` works for me. Thanks, problem is solved.
