### ISSUE TITLE
Cannot switch off 3D borders on MessageBox

### ISSUE THREAD

**Issue by fergusonr** [migueldeicaza/gui.cs#1499]
3D borders are now on by default. Can explicitly turn them off for a Dialog but not a MessageBox

**Comment by BDisp** [comment]
A Dialog is designed to appear on the top of another top-level. So, if no 3D border is needed, then a Window must be used, in my opinion.

**Comment by tznind** [comment]
Has the border style changed between patches for `MessageBox`? If so we could add an overload to `Show` that takes a style parameter at the end?

**Comment by fergusonr** [comment]
```Dialog``` and ```MessageBox``` have consistent default border styles (3D), but if I want to switch both off, I can do this with a ```Dialog```, but there is now equivalent for ```MessageBox```

```csharp
var d = new Dialog ();
d.Border.Effect3D = false;
```

**Comment by tznind** [comment]
`MessageBox` is a static Factory/helper class for `Dialog`:

https://github.com/migueldeicaza/gui.cs/blob/28580de3c57fe4fc03ddef157f4c4cc879a5bda0/Terminal.Gui/Windows/MessageBox.cs#L164

**Comment by BDisp** [comment]
Yes is true. This must be implemented without breaking anything. Thanks to both.
