### ISSUE TITLE
Textfield -	"Offset and length were out of bounds for the array."

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#150]
So I'm currently trying to use the Changed Event to filter the text only  to allow numbers. My filter works. I then update the Text of the control so it removes the unwanted character. This works. However after this is done. If I enter a valid character (a number) it fails with this error.

```c#
TextField TextFieldSSHPort = new TextField(24, 1, 5, MainConfig.SSH.Qstr("port"));
TextFieldSSHPort.Changed += new EventHandler(UpdateSSHPort);

private static void UpdateSSHPort(object sender, EventArgs e)
        {
            TextField TF = (TextField)sender;

            string PortString = TF.Text.ToString();
            string result = Regex.Replace(PortString, @"[^\d]", "");

            if (PortString != result) TF.Text = result;

            int ParsedPort = 8889; //default port

            if (Int32.TryParse(result, out ParsedPort))
            {
                MainConfig.SSH["port"] = ParsedPort;
            }
        }
```

```
System.ArgumentException
  HResult=0x80070057
  Message=Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at Terminal.Gui.TextField.ProcessKey(KeyEvent kb)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke)
   at Terminal.Gui.WindowsDriver.Mono.Terminal.IMainLoopDriver.MainIteration()
   at Mono.Terminal.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view)
   at ENiGMAConfig.Program.StartGUI() in C:Program.cs:line 58
   at ENiGMAConfig.Program.Main(String[] args) in C\Program.cs:line 23

```

**Comment by migueldeicaza** [comment]
Thanks for filing this bug, as a temporary workaround, please adjust the cursor position to be within the bounds.    I should make it so that changing the Text will always update the cursor position to be within bounds.

**Comment by SemperFu** [comment]
Thanks for the fix! Just for my knowledge, how I could move the cursor since CursorPosition is read only and I tried using TF.PositionCursor() and TF.Move(0, width) but they didn't change the point. Point isn't public so I couldn't modify it directly.

**Comment by SemperFu** [comment]
Looks like this is still happening in latest version.

`>	Terminal.Gui.dll!Terminal.Gui.TextField.ProcessKey(Terminal.Gui.KeyEvent kb) Line 307	C#
 	Terminal.Gui.dll!Terminal.Gui.View.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 867	C#
 	Terminal.Gui.dll!Terminal.Gui.View.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 867	C#
 	Terminal.Gui.dll!Terminal.Gui.View.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 867	C#
 	Terminal.Gui.dll!Terminal.Gui.View.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 867	C#
 	Terminal.Gui.dll!Terminal.Gui.Toplevel.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 1224	C#
 	Terminal.Gui.dll!Terminal.Gui.View.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 867	C#
 	Terminal.Gui.dll!Terminal.Gui.Toplevel.ProcessKey(Terminal.Gui.KeyEvent keyEvent) Line 1224	C#
 	Terminal.Gui.dll!Terminal.Gui.Application.ProcessKeyEvent(Terminal.Gui.KeyEvent ke) Line 1687	C#
 	Terminal.Gui.dll!Terminal.Gui.WindowsDriver.Mono.Terminal.IMainLoopDriver.MainIteration() Line 516	C#
 	Terminal.Gui.dll!Mono.Terminal.MainLoop.MainIteration() Line 481	C#
 	Terminal.Gui.dll!Terminal.Gui.Application.RunLoop(Terminal.Gui.Application.RunState state, bool wait) Line 1896	C#
 	Terminal.Gui.dll!Terminal.Gui.Application.Run(Terminal.Gui.Toplevel view) Line 1959	C#
 	Terminal.Gui.dll!Terminal.Gui.Application.Run() Line 1928	C#
`
