### ISSUE TITLE
Starting a background process breaks rendering and shell on Linux if UseSystemConsole is false

### ISSUE THREAD

**Issue by Trolldemorted** [migueldeicaza/gui.cs#1501]
Take this brief example (started with `dotnet run` via ssh:
```c#
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Terminal.Gui;
namespace Guitest
{
    class Program
    {
        static void Main()
        {
            try
            {
                // Application.UseSystemConsole = true; // this helps, but occupies one CPU core
                Application.Init();
                Task.Run(() =>
                {
                    var psi = new ProcessStartInfo("python3", "test.py")
                    {
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = false,
                    };
                    var process = new Process
                    {
                        StartInfo = psi,
                        EnableRaisingEvents = false,
                    };
                    process.OutputDataReceived += (sender, args) => {
                    };
                    process.Start();
                    process.BeginOutputReadLine();
                    process.WaitForExit();
                    process.CancelOutputRead();
                });
                
                var tabView = new TabView()
                {
                    X = 0,
                    Y = 0,
                    Width = Dim.Fill(),
                    Height = Dim.Fill(),
                };
                tabView.AddTab(new TabView.Tab("Tab 1", new Label("Hello World")), false);
                tabView.AddTab(new TabView.Tab("Tab 2", new Label("AAAA\nBBBB\nCCCC\nDDDD\nEEEE\nFFFF\n")), false);
                Application.Top.Add(tabView);
                Application.Top.Add(new StatusBar(new StatusItem[]
                {
                    new StatusItem(Key.CtrlMask | Key.C, "~^C~ Quit", () => Application.RequestStop()),
                }));
                Application.Top.LayoutSubviews();
                Application.Run();
            }
            finally
            {
                Application.Shutdown();
            }
        }
    }
}
```

If you set `Application.UseSystemConsole = true`, everything looks like expected:
![grafik](https://user-images.githubusercontent.com/10261186/139685995-d758ce48-a772-4ef0-9a6e-1857de6d70f6.png)
![grafik](https://user-images.githubusercontent.com/10261186/139686059-edc325f1-6b9a-44df-a3ef-21901a765763.png)

However if you do not, things get ugly:
![grafik](https://user-images.githubusercontent.com/10261186/139686268-05fc49e4-1b6e-4dd9-85e1-73db6420d4bd.png)
![grafik](https://user-images.githubusercontent.com/10261186/139686314-5f06bc4a-ea36-43ed-977d-a08d86e2db95.png)

In this example only the label is skewed, but in my prod use case this breaks entire GraphViews (wrong y values, sudden color changes, duplicate axis descriptions, ...). I tried to come up with an explanation to *why* this happens, but to no avail. Mondays should be abolished!

To make things even worse, after stopping the app with ctrl+c, the surrounding bash is broken, keeps the colors, old data and reacts to mouse events:
![grafik](https://user-images.githubusercontent.com/10261186/139687299-057ee5a8-fb05-4c40-bc4c-50cb8b6450df.png)

At least this problem is perfectly reproducible. Got any ideas?

**Comment by Trolldemorted** [comment]
I just installed an ubuntu 2004 desktop vm, the problem occurs in a "normal" terminal too.

**Comment by BDisp** [comment]
I confirm this issue on `Linux`, both using a virtual machine or using `WSL`. Is some conflict with `Clipboard` using `BashRunner` class and another background process.

**Comment by BDisp** [comment]
@Trolldemorted you need do these changes:

If you don't want error displaying in the screen use `process.ErrorDataReceived`, `process.BeginErrorReadLine` and `process.CancelErrorRead`.

`Height = Dim.Fill(1)`, to accommodate the status bar or using inside a `Window` without borders. Try clicking in the status bar and it will disappear.

You don't need `Application.Top.LayoutSubviews()` because it will be done by the `Application.Run()`

**Comment by Trolldemorted** [comment]
Thanks!

Could you release aa fixed version on nuget?
