### ISSUE TITLE
Application.UseSystemConsole = true consumes an entire cpu core on Ubuntu

### ISSUE THREAD

**Issue by Trolldemorted** [migueldeicaza/gui.cs#1502]
If I `dotnet run` this demo code in an ubuntu20 desktop vm, it takes 100% of one cpu core:
```c#
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Terminal.Gui;
try
{
    Application.UseSystemConsole = true;
    Application.Init();
    Application.Top.Add(new Label("Hello World"));
    Application.Run();
}
finally
{
    Application.Shutdown();
}
```

Am I doing it wrong, or is this a bug?

**Comment by Trolldemorted** [comment]
@BDisp @tig could you merge that/a fix and ship a new release soonish?

My app is often started several times on the same machine, and users are complaining about the CPU consumption.

**Comment by BDisp** [comment]
@Trolldemorted only @tig or @migueldeicaza can do it, sorry.

**Comment by Trolldemorted** [comment]
@tig @migueldeicaza could you ship a release with the fix during the next week?

**Comment by tig** [comment]
I’m traveling and behind. Is the fix in and tested? If so, probably 😜

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by tznind** [comment]
> I’m traveling and behind. Is the fix in and tested? If so, probably 😜

I think the PR is https://github.com/migueldeicaza/gui.cs/pull/1504 which is not yet merged.

**Comment by migueldeicaza** [comment]
Hello,

My quick review:

The patch seems to have two unrelated changes, I am not sure if they are both necessary.   The fundamental fix seems to be the introduction of a thread sleep in the WaitWinChange.    Would love to know if these are coupled or not.

The other issue is why would the WaitWinChange do a continuous poll.   This code is new, and I am unfamiliar with, it is not clear to me why we are doing polling for window changes like this, it seems that window changes should be posted as a sort of event that wakes up the main thread, and then processes the change.

As a band aid, the wait will help, but this seems to be some tightloops that are not necessary - or I do not understand the evolution of this code.   I dont think that we should be running a tight loop on each event.

Additional question:

Is this with Mono with the .NET-framework style assemblies, or .NET Core?

If I read this code correctly, the idea is to have a background task continuously checking on the size of the terminal, and on a change, it posts an event.    I am not a fan, but if this is the only solution possible (without introducing native code, where the solution would be clean and straight-forward), we could probably change the delay to only probe once a second or so (which is not perfect, but is also acceptable, 10ms is IMO too little for a tight loop)

**Comment by BDisp** [comment]
Thanks for your feedback @migueldeicaza.

> Is this with Mono with the .NET-framework style assemblies, or .NET Core?

I'm testing on `Net5.0`, but runs with `Mono` as well.


> If I read this code correctly, the idea is to have a background task continuously checking on the size of the terminal, and on a change, it posts an event. I am not a fan, but if this is the only solution possible (without introducing native code, where the solution would be clean and straight-forward), we could probably change the delay to only probe once a second or so (which is not perfect, but is also acceptable, 10ms is IMO too little for a tight loop)

Exactly. This is for the `NetDriver` which works with `Windows`, `Linux` and `Mac`. The same native code won't work on all OS and this was the solution I adopted to deal with windows resizing. `System.Console` doesn't have any events that is raised when the windows is resized. I agree with increasing the delay, so 1000ms is good?
