### ISSUE TITLE
FileDialog.FilePath

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#151]
FileDialog.FilePaths is an array of full paths. I have multiple files off so I should just be able to use FilePath. However this is only the FileName. 

This should be changed to the Full FilePath and there should include a FileName as well.

**Comment by BDisp** [comment]
But joining the `FilePath `with each `FilePaths `you get the full path.

**Comment by SemperFu** [comment]
Closing as this was already merged. Thank you
