### ISSUE TITLE
The title of a focused FrameView is displayed in ColorScheme.HotNormal

### ISSUE THREAD

**Issue by idontsov** [migueldeicaza/gui.cs#1514]
Hi!

The title of a focused FrameView is [painted in ColorScheme.HotNormal](https://github.com/migueldeicaza/gui.cs/blob/d84ab39ec3d38c48f18e4fa9f560fc997055c69e/Terminal.Gui/Views/FrameView.cs#L230-L231). According to the documentation, the [HotNormal](https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.ColorScheme.html#Terminal_Gui_ColorScheme_HotNormal) is the color for the hotkey when a view is not focused.

Is that a bug in the code?

**Comment by BDisp** [comment]
This was intentional to give the same background color of the superview and another color to the foreground. The `FrameView` sets the focus to the current focused subview. Sometimes it is needed to adapt colors to certain views.
