### ISSUE TITLE
Label ColorScheme issue

### ISSUE THREAD

**Issue by ctyar** [migueldeicaza/gui.cs#1521]
In version `1.2.1` the code below would output a red label:
```csharp
using Terminal.Gui;

Application.Init();

var top = Application.Top;

top.Add(new Label
{
    Width = 4,
    Height = 4,
    Text = "test",
    ColorScheme = new()
    {
        Normal = new(Color.BrightRed),
    },
    
});

Application.Run();
```
![Screenshot 2021-11-22 190940](https://user-images.githubusercontent.com/1432648/142891475-45a2e965-571c-4d7e-8627-8c3f3b978ed7.png)

But after `1.3.1` outputs a red rectangle

![Screenshot 2021-11-22 191235](https://user-images.githubusercontent.com/1432648/142891547-f7a4fb01-99ae-41bc-a4df-ba035c562fb0.png)

**Comment by BDisp** [comment]
Your instruction give the same color for the foreground and the background.
You need to do like this:
```cs
Normal = new(Color.BrightRed, Color.Black),
```

**Comment by ctyar** [comment]
Oops.
Thank you for the great project.
