### ISSUE TITLE
Need to set `Handled = true` in event handler before `MessageBox`, else odd behaviour

### ISSUE THREAD

**Issue by kierenj** [migueldeicaza/gui.cs#1523]
Not sure if this is intentional!

This code has odd behaviour: `Confirm` does nothing except dismiss the dialog, and `Cancel` seems to dismiss it, but then it immediately reappears? Unless double-clicking quickly.

````c#
            _tableView.KeyPress += args =>
            {
                if (args.KeyEvent.Key == (Key)'c')
                {
                    if (MessageBox.Query("Confirm", "Really cancel this item", 1, "Confirm", "Cancel") != 0) return;
                    var row = _table.Rows[_tableView.SelectedRow];
                    var id = _idsByRow[row];
                    try
                    {
                        _cancelsById[id]?.Invoke();
                    }
                    catch (Exception ex)
                    {
                        MessageBox.ErrorQuery("Error cancelling", ex.Message, "OK");
                    }
                    args.Handled = true;
                }
````

To fix, I moved `args.Handled = true;` to before the `MessageBox.Query` call.

I guess it's something message loop related? Just wanted to share in case it's a bug or helps someone else.

**Comment by tznind** [comment]
I think it could be considered best practice to mark the event as handled as soon as possible in the handler especially when calling a blocking modal dialog.

But if theres an easy fix that would be cool too.
