### ISSUE TITLE
Mdi container won't repaint when the visibility of the child is changed

### ISSUE THREAD

**Issue by garyng** [migueldeicaza/gui.cs#1529]
Minimal reproducible example:

```cs
var top = new Toplevel
{
	IsMdiContainer = true
};

var sb = new StatusBar(new[]
{
	new StatusItem(Key.A, "~A~ New child", () =>
	{
		var child = new Window("Test")
		{
			X = Pos.Center(),
			Y = Pos.Center(),
			Height = 20,
			Width = 20
		};
		var hide = new Button("Hide");
		hide.Clicked += () =>
		{
			child.Visible = false;
		};
		child.Add(hide);
		Application.Run(child);
	})
});
top.Add(sb);

Application.Run(top);

```

1. Click on Add new child in the Status bar
![image](https://user-images.githubusercontent.com/4453664/144735264-0b86feec-50c5-41da-a525-adbabc62def5.png)
2. Click on the Hide button in the child
3. The content of the Child is hidden, but the Child window stays until a new Child is added
![image](https://user-images.githubusercontent.com/4453664/144735251-e60174a6-f791-443e-a1cf-15b7eca2cc96.png)

**Comment by BDisp** [comment]
Thanks for reporting this. It's a bug that I'll submit a pull request with the fix.

**Comment by garyng** [comment]
Thanks!
