### ISSUE TITLE
Ncurses 6

### ISSUE THREAD

**Issue by klaumann** [migueldeicaza/gui.cs#153]
If you have ncurses 6 the program won't start as it is looking for version 5...
Should I rather look for an older ncurses or is there a plan to also work with the newer versions ?

**Comment by Therzok** [comment]
https://github.com/migueldeicaza/gui.cs/commit/27c5468a105fbf301dc6a160af21a29afa08034e#diff-90b8a2cd7e7715122b5e760d8a4d2b57

Seems fixed, just not released yet?
