### ISSUE TITLE
How to bring a Mdi child to the front?

### ISSUE THREAD

**Issue by garyng** [migueldeicaza/gui.cs#1530]
How to bring a Mdi child to front? 
I've tried `child.SetFocus()`, `Application.EnsuresTopOnFront()` and `.BringSubViewsToFront(child)` but seems like they all won't work.

Thanks!

**Comment by BDisp** [comment]
With `Mdi` container you must use the `ShowChild` method from `Toplevel` class.

**Comment by garyng** [comment]
`child.ShowChild()` works. Thanks!
