### ISSUE TITLE
Label: inside a Mdi container won't redraw properly when `Text` is changed

### ISSUE THREAD

**Issue by garyng** [migueldeicaza/gui.cs#1534]
Reproducible example:
```cs
Application.Init();

var label = new Label("xxxxxxxxx");

var change = new Button("Change")
{
	Y = Pos.Bottom(label)
};
change.Clicked += () =>
{
	label.Text = "y";
};

var window = new Window();
window.Add(label, change);

var top = new Toplevel
{
	IsMdiContainer = true
};

var sb = new StatusBar(new[]
{
	new StatusItem(Key.A, "~A~ Run", () => Application.Run(window))
});
top.Add(sb);

Application.Run(top);
```

1. Click on `Run`
![image](https://user-images.githubusercontent.com/4453664/144919587-19c1eeb2-4731-4cb9-add2-51012977abb7.png)
2. Click on `Change`
![image](https://user-images.githubusercontent.com/4453664/144919616-7591ed4a-88ab-4abf-8a6b-b76b15c1242b.png)

The original text are not cleared out. 

I've tried with `Application.MainLoop.Invoke()` and `label.SetNeedsDisplay()`, but they doesn't seem to work.

**Comment by BDisp** [comment]
I already fixed. I recommend you to create the `Window` inside the status bar action:

```cs
var sb = new StatusBar (new []
{
	new StatusItem(Key.A, "~A~ Run", () => {
		var label = new Label ("xxxxxxxxx");

		var change = new Button ("Change") {
			Y = Pos.Bottom (label)
		};
		change.Clicked += () =>
		{
			label.Text = "y";
		};

		var window = new Window ();
		window.Add (label, change);

		Application.Run(window);
	})
});

```

**Comment by garyng** [comment]
Okay, sure! Thanks again!
