### ISSUE TITLE
Menuitem - Disable

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#154]
It would be nice if the menu items had an enable/disable option. If I don't have a file open, I'd like the save/save as/close menus to be grayed out.

**Comment by Slesa** [comment]
I have a PR for this feature, but it depends on another PR for the menu separators

**Comment by tig** [comment]
This can be accomplished by setting the `CanExecute` property to a method that returns false (or true to enable).

```c#
item.CanExecute = delegate () { return false; };
```

closing.
