### ISSUE TITLE
Question: vim-like bindings

### ISSUE THREAD

**Issue by MikaelElkiaer** [migueldeicaza/gui.cs#1544]
Hi, love this library for its simplicity, while it is still quite powerful.

However, one thing I am having trouble with is the seeming limitations in regards to keybindings.
I'd like to change the defaults (arrow keys, tab, etc.) and use alpha bindings without mods (e. g. use hjkl for navigation).
Would this require a fork and some rewrite, or is there somewhere I can hook in and change stuff like this?

I use tools like https://github.com/jesseduffield/lazygit and https://github.com/jesseduffield/lazydocker daily, and love how the navigation works.

**Comment by tznind** [comment]
It would be a nice feature to have a `Keybindings` class/system instead of referencing the `Key` enum values directly.  However it would be quite a big rewrite.  There are a lot of `switch` statements that wouldn't work with dynamic values e.g.

```csharp
case Key.N | Key.CtrlMask:
case Key.CursorDown:
case Key.P | Key.CtrlMask:
```
_case statements only work with constant expressions_

Some controls support limited modification e.g. `TableView.CellActivationKey` and `Autocomplete.SelectionKey`.  Any solution would ideally preserve backwards compatibility with these.

**Comment by tznind** [comment]
Sorry, Just brainstorming really.  

So  the use case that @MikaelElkiaer has (correct me if I've misinterpreted).  Is to override the default bindings to e.g. so that `j` acts as CursorLeft under some (or all conditions)*.

For example these are the Vim text editor shortcuts:

>  Cursor movement
>    h - move cursor left
>    j - move cursor down
>    k - move cursor up
>    l - move cursor right
>    H - move to top of screen 

I think the only way to do that currently would be to override `ProcessHotKey(KeyEvent e)` and edit the `KeyEvent`.  Or set it to handled and carry out the relevant command directly.

I was initially thinking of a static `Keybindings` class .  But it could just as well be a non-static  property on `View` that gets inherited by subviews (like `ColorScheme` does).

```csharp
public class Keybindings {
    public Key CursorUp {get;set;} = Key.CursorUp;
    public Key CursorDown {get;set;} = Key.CursorDown;
        
    public Key Copy {get;set;} = Key.C | Key.CtrlMask;
    public Key Paste {get;set;} = Key.Y | Key.CtrlMask;
}
```

Then the 
```csharp
switch (kb.Key) {

[...]

    case Key.Y | Key.CtrlMask: // Control-y, yank
        if (isReadOnly)
            break;
        Paste ();
        return true;
[...]
}
```

Becomes:

```csharp
if(kb.Key == Keybindings.Paste)
     if (isReadOnly)
         break;
      Paste ();
     return true;
```

`*` Presumably for editable text controls `j` would still type the letter though? 

Looking at vim though there are 'chords' (i.e. functions accessed by hitting multiple keys in succession).  Might want to explore the basics of keybinding before worrying about that (if at all) though:

> Cut and paste

>  yy - yank (copy) a line
>  2yy - yank (copy) 2 lines

**Comment by BDisp** [comment]
> ```cs
> if(kb.Key == Keybindings.Paste)
> ```

In this case the `Keybindings` could be static and no need for an instance.


> `*` Presumably for editable text controls `j` would still type the letter though?

I think so, otherwise it will moving down instead of writing the `j` letter.

**Comment by tznind** [comment]
> In this case the Keybindings could be static and no need for an instance.

I am in two minds about whether to make it static.  I can see  2 reasons to make it instance:

- Having different keybindings for different controls (in the same app)
- To make persistence easier (deserialzing yaml / xml etc into an instance class is usually easier than setting up a static class).

But I don't think these are very compelling reasons so would be fine with taking the static approach if it simplifies things.

**Comment by BDisp** [comment]
We could work by sharing our code. As I said before, I would like that the `Key` enum only have keys, like the `System.ConsoleKey`, by excluding the `CharMask`, `SpecialMask`, `ShiftMask`, `AltMask`, `CtrlMask `and `BackTab`. But the `KeyModifiers` must be kept to maintain the keys removed. If you have good ideas for this to work feel free to go ahead :-)
This will be a very hard job.

**Comment by MikaelElkiaer** [comment]
Thanks for spending your time on this.

My thoughts, based on the previous comments:
I don't need the "chords", so forget about those.
I would like to change the default navigation keys from arrow keys to hjkl.
And I would also like to be able to set non-shifted alpha keybindings - so I can use any alpha for custom keybindings.

In regards to text controls, I would just like to make it view-specific how to treat the keybindings. It might be I want to enter text if a text control is focused. It might be that I want to keep hjkl for navigation and only enter text once I press enter and esc to leave text entry.
That's another interesting property of vim - different modes. One could perhaps relate keybindings to being in different modes, while also depending on which view is in focus. But specifically for text controls it makes sense to have a navigation mode in order to move to and from other views, and an insert mode in order to write text.

It might be that I can do some of this stuff already, I am still not that deep into this library.

**Comment by BDisp** [comment]
> In regards to text controls, I would just like to make it view-specific how to treat the keybindings. It might be I want to enter text if a text control is focused. It might be that I want to keep hjkl for navigation and only enter text once I press enter and esc to leave text entry.

The `Enter` and `Esc` keys may enable and disable the keys bindings for only the focused view or for all application views? What yours opinions?

**Comment by MikaelElkiaer** [comment]
Focused view makes the most sense to me.

If there's not a third option that is going up in the view hierarchy until a view reacts to the keybinding, before reaching the application? 
It could be that there's a view and its sub-view that both can go to an enter state. So in the sub-view I can be in an text state, press `Esc` and am back to normal. Then if I press `Esc` again that would be handled by the parent view, if it is also in an entered state, if not pass the press along the hierarchy until it hits application.
Am I making any sense here? :P

**Comment by BDisp** [comment]
Yes, thanks. And if a view was previously pressed the `Esc` key to disable key bindings and you open that view again by mouse, view should have the keys bindings enabled or only if the `Enter` key is pressed?

**Comment by MikaelElkiaer** [comment]
Only if `Enter` is pressed. A big thing here is to use alphas for navigation, and only enter insert mode if explicitly requested via `Enter`. The same would be true for using the mouse which would work purely for navigation and should not start insert mode.

**Comment by tznind** [comment]
So seems like there might be 2 separate issues here

- Ability to change key bindings e.g. `j` to act as `Cursor.Left` 
- Ability to enter a 'read only' state where letter keys don't enter data

Some controls already have a read only state (e.g. `TextView.ReadOnly` ).

So a user of the API could set up some code

```
TextView myView = new TextView();

// store the normal bindings used when editing
KeyBindings normalKeybindings =  myView.KeyBindings;

// create new ones for letter based navigation
KeyBindings letterBasedNavigation =  new KeyBindings{[...]};

// start the view in readonly mode and using letter based navigation
myView.KeyBindings = letterBasedNavigation;
myView.ReadOnly = true;

// Register for Enter being pressed to toggle the mode of the control
myView.KeyPressed += (s,e)=>
{
    if(e.Key == Keys.Enter)
    {
         myView.ReadOnly = false;
         myView.KeyBindings = normalKeyBindings
    }
}

```

I think we want to make it as easy as possible to set this feature for API users up without baking it all into the core code.  There could be people already doing stuff with Enter and Esc that wouldn't want it suddenly flipping the control into a readonly state.

But something like making `ReadOnly` an interface or part of `View` would make it easier to apply the above pseudocode to all views in an app for example.

**Comment by BDisp** [comment]
This must be made with a public class that stores the views, input and output keys. In the `View` class when passing the key event for the focused view will check if there enabled binding keys and send the output key instead. More and less :-)

**Comment by MikaelElkiaer** [comment]
All of this feels a bit hacky to me - but might just be my lack of understanding and that you have to override a lot of the default behaviour in a way that's possible and maintainable.

I'd have guessed the problems were more as so:
* Override or disable default keybindings
* Extend currently available keys with non-shifted (lowercase letters)
* Set specific keybindings for the focused view

If I had a layout like the following, with 3 views:
```
----------------------
|   1   |            |
-------        3     |
|   2   |            |
----------------------
```
where 1 and 2 are ListView and 3 is a TextView, and 1 is currently focused.
If I press `l` it should shift focus to 2. Then while focused on 2, pressing `k` or `j` would navigate up and down in the ListView.
Pressing `enter` on an item here would shift focus to 3. In 3 it would use `k` and `j` to scroll up and down. Then if `enter` is pressed, it would go into insert mode and `hjkl` would now insert the letters in the text view at the cursor. Insert mode is then exited via `esc`, after which 3 is still in focus but `k` and `j` now scrolls again. Then pressing `esc` one more time would bring focus back to 2, and `hjkl` once again navigates between views or within the ListView.

Another neat thing would be, while focusing on an item in a ListView to have bindings which can do various things, most likely bringing up modals with options. E.g. if having an item selected, pressing `x` would bring up a delete modal, where `y` or `n` can be pressed to confirm deletion.

**Comment by tznind** [comment]
You are right, lets not rush in and over engineer this thing!

I have taken a look at what you can already do out of the box.  I think I have replicated all the stuff that you want @MikaelElkiaer from your last post just using the current published version on NuGet and a new console app.

![image](https://user-images.githubusercontent.com/31306100/146532230-8ea8ed1c-d180-44ba-b830-d62f83f1845c.png)

https://github.com/tznind/TerminalGuiVimlikeBindingsExample

Please can you clone and check out that to provide feedback on what it doesn't do that you would want.  

We can then look at the code and discuss what is painful to implement as I have and what could be streamlined by making changes in the main library?

**Comment by BDisp** [comment]
**Additional features:**
- `EnableKey` and `DisableKey` can configurable to choose others keys than `Enter` and `Esc`. Also they can be executed or not. For example, the `Enter` key in a `ListView` can be used to leave the binding key and execute the `Enter` that is used to open the selected item, right? On the other hand, on a `TextView` the `Enter` key must not be executed to avoid a new line.

**Question:**
Should the binding keys be propagated in the `KeyPress` event or only in the override `ProcessKey`?
In my opinion they only should be propagated in the override `ProcessKey` because the `KeyPress` event is normally used by dev consumers of the `Terminal.Gui` and they can handle the key he wants because the key bindings is managed and provided by the dev consumers. Please give yours opinions.

**Comment by MikaelElkiaer** [comment]
@tznind That is really nice, thank you so much. I will give it a go when I get the chance and then I can bring some feedback in regards to how cumbersome it is to use.

**Comment by BDisp** [comment]
> * Also they can be executed or not. For example, the `Enter` key in a `ListView` can be used to leave the binding key and execute the `Enter` that is used to open the selected item, right? On the other hand, on a `TextView` the `Enter` key must not be executed to avoid a new line.

Forget about this please. Pressing `Enter` key always will enter insert mode leaving the keys bindings. Pressing `Enter` again will process the focused view defaults. Pressing `Esc` key always will leave insert mode returning to the keys bindings. Pressing `Esc` again will process the focused view defaults. So, @MikaelElkiaer doing the example you mentioned always have to be done by a specific development as @tznind did, with the exception that the keys bindings will be already configurable. I almost have this ready to submit a PR which I would like yours feedbacks. Thanks.

**Comment by BDisp** [comment]
Please see here https://github.com/BDisp/gui.cs/tree/keybindings-feature

**Comment by tig** [comment]
@MikaelElkiaer have you had a chance to try out the new `KeyBindings` feature that was introduced in PR #1556? 

If you do not feel it addresses this issue, please re-open the issue and let us know! Thanks.

**Comment by MikaelElkiaer** [comment]
@tig I did not, but I appreciate your effort. I will come back to you once I get to it. :)
