### ISSUE TITLE
Please create an issue template to avoid submitting solved issues.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1545]
Please see [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) @tig.

First of all recommending if the current main branch was already tested, before submitting a new issue.

**Comment by tig** [comment]
@migueldeicaza - is there a way of getting me access to the Settings for the repo so I can do things like add issue templates?

<img width="582" alt="image" src="https://user-images.githubusercontent.com/585482/146682702-393fcbda-f73d-488e-8f9a-5c9644a360cd.png">

**Comment by tig** [comment]
Pinging @migueldeicaza and @migueldeicaza-msft ...

**Comment by BDisp** [comment]
Bip..bip...bip :-)

**Comment by migueldeicaza** [comment]
Just enabled notifications - will set up tonight :-)

**Comment by migueldeicaza** [comment]
Mhm, I can not find any obvious way of granting additional permissions.

What error do you get?

**Comment by migueldeicaza** [comment]
Ok, I could not figure how to enable additional settings, but I setup all the templates - and they should be editable now for anyone
