### ISSUE TITLE
Ncurses backend outputs a black screen in tty

### ISSUE THREAD

**Issue by adryzz** [migueldeicaza/gui.cs#1551]
Platform: Linux, tty (no display server)

Helllo! It's my first time trying out this library. While testing, i found out that the default backend outputs a black screen.
Setting `Application.UseSystemConsole = true;` fixes it, but the CPU isage spikes up to 100%, which is not something i'd want.
After testing with ssh in gnome-terminal on my desktop, i can observe that the default backend is MUCH faster than the System.Console backend (as expected)

I don't think it's an ncurses issue as other tools that use it work just fine (alsamixer)

Is this a known issue?

**Comment by tznind** [comment]
Hi, thanks for reporting this.  It should be fixed with the next nuget release ( https://github.com/migueldeicaza/gui.cs/pull/1549 ) which was merged 24 hours ago and should (I think) go live on NuGet soon.

**Comment by adryzz** [comment]
yes, the high CPU usage is gone. I guess this issue is also not really that useful to fix as you aren't going to use mouse in tty anyway...

**Comment by tznind** [comment]
Glad that the CPU problem was resolved.

Usually odd colors (or all black) is an issue with `$TERM` not being set correctly.  See this thread for example:

https://github.com/migueldeicaza/gui.cs/discussions/1455#discussioncomment-1373575
