### ISSUE TITLE
Should TreeView hide the cursor the same way ListView does?

### ISSUE THREAD

**Issue by Dimagog** [migueldeicaza/gui.cs#1559]
When I create an app with just a `TreeView` the cursor is visible, it follows the selection, and it does not look good.

`ListView` calls `SetCursorVisibility(CursorVisibility.Invisible)` in its `OnEnter` handler.
Should `TreeView` do the same?

**Comment by tznind** [comment]
Good spot thanks.  I have created a PR to add a property `public CursorVisibility DesiredCursorVisibility` like `TextView`.  Cursor makes sense if you have multi select on so I think leaving it in app developers hands makes sense rather than forcing invisible.

**Comment by Dimagog** [comment]
Thank you for the fix!
