### ISSUE TITLE
Ponder: domain-specific TextFields

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#156]
Perhaps these should be called "Inputs" to track what the Web does, and those would provide some high-level data input, like:

* Colors
* Dates
* Numbers only
* Email addresses
* File (would include a file browser button to pick a file)
* Month selector
* Year selector
* Telephone
* Time
* Url

Some inspiration from here:
https://www.w3schools.com/html/html_form_input_types.asp

**Comment by tig** [comment]
`TextValidateField` largely addresses this.

See #1230 

Closing.
