### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by SadE54** [migueldeicaza/gui.cs#1560]
Hi,

I just saw that the link for main loop management is broken : 
https://migueldeicaza.github.io/articles/mainloop.html

**Comment by BDisp** [comment]
There were some changes to the `Docfx` API that corrupt the use of slash before the `api/` and `articles/`, so they should be removed.
I submitted a PR with the fix.

**Comment by mcraiha** [comment]
It seems both *api* and *articles* are still broken

**Comment by BDisp** [comment]
> It seems both _api_ and _articles_ are still broken

Sure, the PR wasn't merged yet.

**Comment by tig** [comment]
> Hi,
> 
> I just saw that the link for main loop management is broken : https://migueldeicaza.github.io/articles/mainloop.html

I merged @BDisp's PR.

But, @mcraiha, the link you have here is incorrect.  It's missing `gui.cs`:

https://migueldeicaza.github.io/gui.cs/articles/mainloop.html

**Comment by tig** [comment]
It's still broken. I'm working on fixing now...

**Comment by tig** [comment]
Ok. PR #1586 fixed everything.

Key was:

- Relative links should start with `(~/)` (e.g. `(~/api/...)`
- References to API pages should reference `.yml` not `.html`
- References to specific API must be of form `...api.yml#full_bookmark_name`
