### ISSUE TITLE
Deadlock (?!)

### ISSUE THREAD

**Issue by mozesa** [migueldeicaza/gui.cs#1570]
**Hello**, 
I am sure that there is something trivial that I miss, but please, let me know why it happens.

Thanks for your help in advance!

P.S.: using `ConfigureAwait(false)` makes it independent the `Application.Init()`'s position.

Deadlock(!?)
------
```c#
using System.Net.Http;
using Terminal.Gui;

var httpClient = new HttpClient();

Application.Init(); // This line is above the await call.
var response = await httpClient.GetStringAsync("https://catfact.ninja/fact");

var top = Application.Top;
var win = new Window(response) { Width = Dim.Fill(), Height = Dim.Fill() };
top.Add(win);
Application.Run();
```
![image](https://user-images.githubusercontent.com/49973426/148352356-f3aa4371-a271-4c0d-8efa-d989e81018a0.png)

Works fine
------
```c#
using System.Net.Http;
using Terminal.Gui;

var httpClient = new HttpClient();

var response = await httpClient.GetStringAsync("https://catfact.ninja/fact");
Application.Init(); // This line is below the await call.

var top = Application.Top;
var win = new Window(response) { Width = Dim.Fill(), Height = Dim.Fill() };
top.Add(win);
Application.Run();
```
![image](https://user-images.githubusercontent.com/49973426/148352529-095ebb06-2f5e-4caf-86c8-d1ccac5c5fb1.png)

**Comment by mozesa** [comment]
Okay, it is the same as [895](https://github.com/migueldeicaza/gui.cs/issues/895).

**Comment by BDisp** [comment]
Changing this:
```cs
var response = await httpClient.GetStringAsync("https://catfact.ninja/fact");
```

to this:
```cs
var response = Task.Run (async () => await httpClient.GetStringAsync ("https://catfact.ninja/fact")).Result;
```

works perfectly on both the cases.
