### ISSUE TITLE
How to set fontsize?

### ISSUE THREAD

**Issue by dsp6414** [migueldeicaza/gui.cs#1575]
Very excellent repository. pls provide more tutorial on how to use gui.cs.

**Comment by tznind** [comment]
> How to set fontsize?

Font size cannot be changed by console applications.  You can still change your font in the console itself though.  For example in Powershell you use Properties->Font:

![image](https://user-images.githubusercontent.com/31306100/149727255-0a2266d9-582c-4652-b7c9-8a91568ece0c.png)

**Comment by dsp6414** [comment]
已收到！

**Comment by DeCEll-1** [comment]
Sorry for necroing, but it seems as when i try to use ctrl scroll to change the font size i cannot do it on Windows Terminal, works fine on the default cmd terminal and powershell terminal (however i cannot use them for my needs)
My version is 2.0.0-develop.5180

**Comment by tig** [comment]
Sorry, but this has nothing to do with Terminal.gui unless I'm misunderstanding you.

**Comment by DeCEll-1** [comment]
I though maybe the library was disabling it, sorry for disturbing

**Comment by tig** [comment]
It's all good. 

I don't think it's possible to disable terminal keys. 

Does that key work for you if you're not running a TG app?

**Comment by DeCEll-1** [comment]
Yes, the only change i have done to the code is integrating the library.
The code before i added the library:
https://github.com/DeCEll-1/ShaderTerminal/tree/1a9190d8c3811d9c7e04c7ad41ace2c1d7ff62f8
And after:
https://github.com/DeCEll-1/ShaderTerminal/tree/5c944effc650104453929ae8694b88e8f235fd11
