### ISSUE TITLE
Ponder: ListView, should it support multiple columns, and if so, what?

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#16]
We could likely have a simple listview that relies on text being returned, and a more complicated one, that allows users to provide a full view to be rendered in place - to allow colors and other features.

Implemented as ListView, some features missing:

- [x] Mouse support
- [ ] Ponder: Should it show scrollbars?
- [ ] Should it support multiple-columns?

**Comment by adamlonsdale** [comment]
I would expect a ListView with multiple columns to allow some sort of array of column views. I.e I specify a list of column objects, their widths, caption and possibly the property of the class passed as the data source to map fields to. If fields are too long they would truncate and show a nice list.

`var lstBugs = new List<Bug>();`
`lstBugs.Add(new Bug()); //etc... load from SQL backend`
`var lvBugs = new ListView(new Rect(2, 1, 25, 10), lstBugs);`
`lvBugs.Columns = new ListViewColumn[]`
`  {`
`    new ListViewColumn(25, "BugDescription", "Description"),`
`    new ListViewColumn(1, "FixedInd", "F"),`
`    new ListViewColumn(1, "TestedInd", "T"),`
`    new ListViewColumn(5, "DeveloperCode", "Dev")`
 `  };`

**Comment by SteveL-MSFT** [comment]
With [PowerShell Core 6](https://github.com/powershell/powershell) being cross platform.  One request from customers is to support [out-gridview](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-gridview?view=powershell-5.1) which relied on WPF and thus not cross platform portable.  I think if this library had a listview control, that would be sufficient to have a basic `out-gridview` cmdlet for PowerShell Core 6.  What customers want is the ability to get objects using PowerShell cmdlets, pipe that to `out-gridview` so they have a GUI to do filtering, sorting, and selection, and upon closing `out-gridview` those objects would be passed to the pipeline for further processing.

The inputs from the pipeline and outputs to the pipeline are clearly in the domain of PowerShell and is supported today, but need a console GUI library we can build upon.

Initially, just being able to represent a .Net objects specified properties as columns with ability to sort and select would be great.

**Comment by ebekker** [comment]
Perhaps that's the difference between a ListView and a GridView?  But I think both would be useful components for this library.

**Comment by TylerLeonhardt** [comment]
I was able to make a grid from a `ListView` but behind the scenes I'm having to do a much of string manipulation.

![image](https://user-images.githubusercontent.com/2644648/74369055-92faf500-4d89-11ea-8010-efe14bf70f40.png)

If there was a properly supported `GridView` that would make this `Out-GridView` a much nicer experience.

**Comment by tig** [comment]
I assert https://github.com/migueldeicaza/gui.cs/pull/1015 addresses this. 

I plan on re-implementing `OutConsoleGridView` using TableView at some point....

Closing.
