### ISSUE TITLE
"The selected file is not a valid solution file"

### ISSUE THREAD

**Issue by tedekeroth** [migueldeicaza/gui.cs#1604]
**Describe the bug**
When opening the Terminal.sln, the following error occurs:

"The selected file is not a valid solution file"

**To Reproduce**
1. Clone the repo
2. Open the sln file
3. Error popups up as above

**Expected behavior**
Expected the sln to open without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/10088477/154806420-5ef6e136-e9c0-4282-9dd6-a3f5cdabb434.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Tested in Visual Studio 2019 (16.11.9) and Visual Studio 2022 (v 17.1.0 Preview 4.0)

**Comment by tznind** [comment]
Can you open the csproj files seperately? I don't have this issue so it might be an environment thing.

**Comment by BDisp** [comment]
Although VS 2019 (16.11.10) is not supporting `Net6.0`, it's possible open the solution. My recommendation is use the VS 2022 (17.1.0), but I'm not using the Preview 4.0.

**Comment by tedekeroth** [comment]
The Preview 4.0 can open all sln files I have, even ones also being opened by VS 2019, so there is something weird going on. Anyways, I guess I can create  my own sln file.

**Comment by BDisp** [comment]
Verify if the path where is the solution reside is too long.
