### ISSUE TITLE
Is Alpine Linux supported?

### ISSUE THREAD

**Issue by mcraiha** [migueldeicaza/gui.cs#1607]
**Describe the bug**
I am writing a sample password manager app that uses **gui.cs**, and I created a Dockerfile for building it for an Alpine Linux. Build goes fine, but once I execute the generated binary I get errors about **libgcc_s.so** and **libstdc++.so**

I did build it with `-r linux-musl-x64` and since Terminal.Gui is the only package refence in my project, I assume this issue is somehow related to **ncurses** 

I am very sorry if I misunderstood something and this is not gui.cs related at all.

**To Reproduce**
1. Clone repo https://github.com/mcraiha/WhisperDragonCLI
2. Run `docker build .`
3. Run `docker image ls` and get the image id
4. Run `docker run -it IMAGEID`
5. Try to execute the binary with `./WhisperDragon_CLI`

**Expected behavior**
No crash / errors

**Additional context**
List of first three errors:

> /app # ./WhisperDragon_CLI
Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./WhisperDragon_CLI)
Error loading shared library libstdc++.so.6: No such file or directory (needed by ./WhisperDragon_CLI)
Error relocating ./WhisperDragon_CLI: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm: symbol not found

**Comment by tznind** [comment]
Could be related to this https://stackoverflow.com/questions/68010688/docker-run-error-loading-shared-library-libstdc-so-6-and-libgcc-s-so-1

Theres some suggested dependencies to install for curses there (libgcc libstdc++ ncurses-libs)?

**Comment by mcraiha** [comment]
You are right.  `RUN apk upgrade --no-cache && apk add --no-cache libgcc libstdc++ icu-libs` got rid of those errors. Now there is the **libcoreclr.so** issue.

**Comment by BDisp** [comment]
> Now there is the **libcoreclr.so** issue.

You have to search on how to install `ncurses` on `Alpine`, I think.
