### ISSUE TITLE
Use of `new` on Text property of Button

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1619]
**Describe the bug**
Button has `new` on its Text property.  This means that if you maintain a reference to it as a `View` (e.g. keeping a list of views in your class) and assign its `.Text` property then it is not properly preserved for use later on if you reference it as its explicit Type again.

This could be problematic in quite a few situations especially if using reflection.  Is it possible to make `Button` work without the `new` keyword or make the Text property virtual and use `override` instead of `new` in Button if inheritence is the only way to make it work?

```csharp
[Fact]
public void TestAssignTextToButton ()
{
	View b = new Button ();
	b.Text = "heya";
	Assert.Equal ("heya", b.Text);

	// fails here
	Assert.Equal ("heya", ((Button)b).Text);
}
```

![image](https://user-images.githubusercontent.com/31306100/155878792-b0e2b697-2f24-4b81-84f4-c63d5e4403db.png)

**Comment by BDisp** [comment]
The only way it pass is by using this:
```cs
Assert.Equal ("heya", b.GetType ().BaseType.GetProperty ("Text").GetValue (b).ToString ());
```
See the lines above this line where I had some difficulty to test this.

**Comment by BDisp** [comment]
The only way to avoid `new` keyword in the `Text` property is the `Button` view deal with his own redraw by overridden the `Redraw` method.

**Comment by tznind** [comment]
> The only way to avoid `new` keyword in the `Text` property is the `Button` view deal with his own redraw by overridden the `Redraw` method.

I think that makes sense.  The current pseudocode (correct me if I am wrong) is:

- Declare `new string Text`
- In setter update the `base.Text` to the formatted button name

So there are 2 versions of the `Text` property in the view.  One in the `Button` class with the name only of the button and one in the base class with the formatted string.

I think changing Button to use `override` instead of  `new` and storing the formatted string in a private field.  Then override `Redraw` to draw the formatted string?

I've not tried it but it sounds like you were thinking along the same lines?

Do you think its worth doing? I think it will leave a tidier class that is more consistent with the way other views operate and its not breaking?

**Comment by BDisp** [comment]
> I think that makes sense. The current pseudocode (correct me if I am wrong) is:
> 
>     * Declare `new string Text`
> 
>     * In setter update the `base.Text` to the formatted button name
> 
> 
> So there are 2 versions of the `Text` property in the view. One in the `Button` class with the name only of the button and one in the base class with the formatted string.

Yes, it behaves as you described.

> I think changing Button to use `override` instead of `new` and storing the formatted string in a private field. Then override `Redraw` to draw the formatted string?
>
> I've not tried it but it sounds like you were thinking along the same lines?

Yes, that is what I talked about.


> Do you think its worth doing? I think it will leave a tidier class that is more consistent with the way other views operate and its not breaking?

Yes, you are right. It'll be much more consistent with all views. When @tig decided to do that way, was to leverage the `Redraw` method on the `View` class to draw the text using the `TextFormatter` alignments methods. But since the `Button` view has his own format, it's justified to assume the responsibility to redraw itself. If you don't mind, can you handle this?

**Comment by tznind** [comment]
Cool, glad we are on the same page.  I will get a PR together.

**Comment by tznind** [comment]
Hmnnn I looked into it in https://github.com/tznind/gui.cs/tree/button-new-text but looks like a lot of work.  The `Text` property on View has the textFormatter and its own layout logic.  I didn't want to make a lot of changes for something so small like this.

In my branch I changed `Button.Text` it to use `override` and function as it does now (call `base.Text`) but this means that Text always returns the formatted name (which is nice and consistent at least).  But thats a breaking change and could be bad if people have code like `if(btn.Text == "Ok")` so I think we just have to live with the replication for now as its less disruptive.

But to make crystal clear what the current situation is.  The following test passes:

```csharp
[Fact]
public void Constructors_Defaults ()
{
     var btn = new Button ();
   
     // If you have a reference to Button in a variable of Type Button you get this:
     Assert.Equal (string.Empty, btn.Text);

    // If you have a reference to Button in a variable of Type View you get this:
     Assert.Equal ("[  ]", ((View)btn).Text);

     // This was in the test previously but it is the same as doing a cast (above line)
     Assert.Equal ("[  ]", btn.GetType ().BaseType.GetProperty ("Text").GetValue (btn).ToString ());
      ...
```

I'm going to leave this for now and just put a workaround in my code :)

**Comment by BDisp** [comment]
@tznind here my changes related with this:
https://github.com/BDisp/gui.cs/tree/button-new-text

What do you think?

**Comment by tznind** [comment]
> @tznind here my changes related with this: https://github.com/BDisp/gui.cs/tree/button-new-text
> 
> What do you think?

That looks great!  I think I got a bit lost in the text formatter and where everything was stored.  But that looks like it ticks all the boxes 👍
