### ISSUE TITLE
LineView namespace

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1653]
**Describe the bug**
Not sure if this is a 'bug' exactly but more of an oversight.

Currently the `LineView` class is in the namespace `Terminal.Gui.Views`.  It is the only thing in that namespace.  Its annoying and untidy but fixing it would be breaking for anyone that is using it (they would need to remove the `using Terminal.Gui.Views` directive since it no longer would exist.

Just raising this issue for awareness rather than saying we definitely should fix it.  Also go get a feel for other peoples opinions on this (whether to fix).

**Comment by BDisp** [comment]
I have already noticed this before but perhaps by inertia I did not report. @tig from beginning it outlined that the namespace would always be `Terminal.Gui` regardless of the existence of folders and sub-folders. The only exception would be in the project of unit tests where namespace would be used from the place where the component resides. In my opinion it would be uniformed this pattern and change. By the way @tig had asked LineView unit tests and maybe you want to present it :-)
