### ISSUE TITLE
Message Box Rune Support Erroneous 

### ISSUE THREAD

**Issue by StefanGreve** [migueldeicaza/gui.cs#1673]
**Describe the bug**
As of version 1.5.0, the `MessageBox` still seems to take issues with runes. Something similar was recently report in issue #1657 (with a PR to solve this in PR #1658). Then again there was also issue #1665 (context menu width) which subsequently got solved in PR #1666. I think a similar bug fix is required for the `MessageBox` class.

Here's a summary of the current state of message box:

| language | `-usc` | result                                                                                            |
|-----------|--------|----------------------------------------------------------------------|
| `en_US`   | `false`  | works as expected                                                                       |
| `en_US`   | `true`   | invisible message box                                                                  |
| `ja_JP`      | `false` |  works but the alignment of the message box message is off    |
| `ja_JP`      | `true`  | invisible message box                                                                  |

**To Reproduce**
I noticed this behavior on the application I am currently working on (https://github.com/StefanGreve/dtui/tree/chatview). To reproduce this bug you can run this application with `dtui.exe run --langauge [en_US|ja_JP] -usc`. Try to log in (login method is not implemented yet, so any combinations of strings would do the trick) and cancel the process by clicking on the `[ cancel ]` button to trigger the message box.

**Expected behavior**
The message box should be visible (notice that it is still possible to exit the message box form with the now invisible `ok` button). Also the Japanese text (and likely any other text which contains runes) should not be cut off. In the GIF below, the text is not really centered when the language profile is set to Japanese.

**Screenshots**

![2022-04-18-15-43-34](https://user-images.githubusercontent.com/32100623/163818655-1996c26b-1f7f-4bb8-aaf5-36cc09ac25bb.gif)

**Desktop (please complete the following information):**
 - OS: 10
 - Version 10.0.19044

**Additional context**
This behavior was observed on CMD, PowerShell and Windows Terminal with always the same outcome. The example in the GIF was run on Windows PowerShell.

**Comment by tig** [comment]
Super clear bug report. Thank you.

**Comment by BDisp** [comment]
This is how the `NetDriver` will work with wide runes.

**Comment by tznind** [comment]
In your gif it sort of looks like your MessageBox is popping under the main UI.  Also according to your table `en_US with -usc ` manifests the problem which makes it seem like its not to do with the language and instead to do with `-usc`? 

I have cloned your repo and tested.  One thing I noticed is that if you resize the UI the dialog reapears.

![Deleteme](https://user-images.githubusercontent.com/31306100/165235161-a8d4d71e-1127-4a3c-a3c1-b7b868c52954.gif)
I

**Comment by BDisp** [comment]
@tznind is really a bug, but related to several factors, since `TextFormatter`, `NetDriver` and more, related with wide runes.
I almost have a fix ready.

**Comment by StefanGreve** [comment]
> In your gif it sort of looks like your MessageBox is popping under the main UI. Also according to your table en_US with -usc manifests the problem which makes it seem like its not to do with the language and instead to do with -usc?

Correct, the `-usc` parameter (which enables `Application.UseSystemConsole`) is meant to be a workaround for Windows Terminal where the TUI wouldn't look correct if it were not for that. But even without `-usc` flag there is still the issue with the text alignment in the message box looking cut off on Windows PowerShell if there are any rune characters (see also: attached screenshot).

```cli
.\dtui.exe run --language ja_JP
```

<img width="661" alt="image" src="https://user-images.githubusercontent.com/32100623/165251431-fd8ae2b5-a14b-4917-95e7-f751e6bc7548.png">

Just for reference, this is the same table but for Windows terminal:

language | -usc | result
-- | -- | --
en_US | false | works as expected
en_US | true | invisible message box
ja_JP | false | see also issue #1661 (explained [here](https://github.com/migueldeicaza/gui.cs/issues/1661#issuecomment-1095596132)
ja_JP | true | invisible message box
