### ISSUE TITLE
MainLoop.RunTimers() method throws System.ArgumentException after few hours.

### ISSUE THREAD

**Issue by kacperpikacz** [migueldeicaza/gui.cs#1679]
Can someone explain me why I'm getting this error after around 8 hours of running? 
Terminal.Gui version 1.4

`AmiAI - System.ArgumentException: An item with the same key has already been added. Key: 637865266986268040 (Parameter "key")`
                                                                                                                                at System.Collections.Generic.SortedList"2.Add(TKey key, TValue value)
                at Terminal.Gui.MainLoop.RunTimers()
                                                       at Terminal.Gui.MainLoop.MainIteration()
                                                                                                  at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
                                                                                                                                                                      at Terminal.Gui.Application.Run(Toplevel view, Func"2 errorHandler)
                                                   at Terminal.Gui.Application.Run(Func"2 errorHandler)
                                                                                                          at Pai.Ama.Run()
                                                                                                                                at Pai.Program.Main(String[] args)

**Comment by tig** [comment]
We probably can't help debug this without knowing what your code does.

**Comment by tznind** [comment]
Hi, do you get this error consistently (after long periods of execution) or was this a one off? What operating system are you using? 

One thing I can advise if you are using a lot of timeouts is to add them using `Application.MainLoop.Invoke` e.g. 

```csharp
Application.MainLoop.Invoke(()=> {
		Application.MainLoop.AddTimeout (TimeSpan.FromSeconds(1), (s) => { /*your method here*/ });
});
```

I was stress testing the timeout system with the following multi threaded 'test' (warning: will eat your CPU and RAM if you run it).

```csharp
[Fact,AutoInitShutdown]
public void TestAddManyTimeouts()
{
	for(int i=0;i<1000;i++) {
		Task.Run (() => {
			Task.Delay (100).Wait();
			while (true) {
				
				Application.MainLoop.Invoke(()=> {
					Application.MainLoop.AddTimeout (TimeSpan.Zero, (s) => { return true; });
				});
			}
		});
	}
	
	Application.MainLoop.Run ();
}
```

The test runs fine with the MainLoopInvoke bit but if you remove it then you get a veriety of failures including:

```
  Message: 
    System.ArgumentException : An item with the same key has already been added. Key: 637865486955401012 (Parameter 'key')

  Stack Trace: 
    SortedList`2.Add(TKey key, TValue value)
    MainLoop.AddTimeout(TimeSpan time, Timeout timeout) line 125
    MainLoop.RunTimers() line 181
    MainLoop.MainIteration() line 241
    MainLoop.Run() line 260
    MainLoopTests.TestAddManyTimeouts() line 23
```

```
System.NullReferenceException : Object reference not set to an instance of an object.

Stack Trace: 
MainLoop.RunTimers() line 180
MainLoop.MainIteration() line 241
MainLoop.Run() line 260
MainLoopTests.TestAddManyTimeouts() line 23
```

```
  Message: 
System.ArgumentException : Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

  Stack Trace: 
Array.BinarySearch[T](T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
SortedList`2.IndexOfKey(TKey key)
SortedList`2.ContainsKey(TKey key)
MainLoop.AddTimeout(TimeSpan time, Timeout timeout) line 122
MainLoop.RunTimers() line 181
MainLoop.MainIteration() line 241
MainLoop.Run() line 260
MainLoopTests.TestAddManyTimeouts() line 23
```


```

 Message: 
System.InvalidOperationException : Collection was modified after the enumerator was instantiated.

  Stack Trace: 
Enumerator.MoveNext()
MainLoop.RunTimers() line 176
MainLoop.MainIteration() line 241
MainLoop.Run() line 260
MainLoopTests.TestAddManyTimeouts() line 25
```

**Comment by BDisp** [comment]
@kacperpikacz this used to happen on macOS but also may happen under an unit test in some racing condition.
Please say what which OS this happens.

**Comment by kacperpikacz** [comment]
I'm using MacOS. Everytime i got this error it's around 8 hours. I have maybe 3 timers in whole code.

Will send the code in 2 hours.

**Comment by BDisp** [comment]
But do you have the timers inside a `Application.MainLoop.Invoke(()=> {})` as @tznind said?

**Comment by kacperpikacz** [comment]
No, I'm using AddTimeout method directly. I think this is why I'm getting Exception.
`Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(1000), timer);`

**Comment by BDisp** [comment]
> No, I'm using AddTimeout method directly. I think this is why I'm getting Exception. `Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(1000), timer);`

Thanks for your information. Now I think we are more closer to what is causing this issue. Before the timeouts are processed a copy is made and all that returns true they are recreated. Although they are locked maybe there are some bug that allows in a racing condition, perhaps when having much stress, that create a new timeout with the same key. I have to check it up.

**Comment by BDisp** [comment]
By the way, while this is not fixed yet, try to put the `Application.MainLoop.AddTimeout` inside the `Application.MainLoop.Invoke`, as @tznind said to check is it stop the errors or continues giving the same errors. Thanks.

**Comment by kacperpikacz** [comment]
Just done that. Now, waiting.

**Comment by tig** [comment]
Folks, I've tagged this issue as a bug. The discussion above makes me believe there are easy work around that will address this for @kacperpikacz (hope so), but the fact he's not doing anything in his code obviously incorrect means there's a bug somewhere.

I don't want this issue to get lost/closed until the root cause is well understood and there's either a code or doc fix.

Happy sluething!

**Comment by kacperpikacz** [comment]
After changing the code and starting timers via Application.Mainloop.Invoke(), the program didn't throw any exceptions after 24 hours of running.

**Comment by kacperpikacz** [comment]
Today I got the same problem even by adding all timeouts inside Application.Mainloop.Invoke() with @tznind modified Mainloop code.

**Comment by tznind** [comment]
Do you have a stack trace for the error you got and the exact error message please? Is it the same one in the first post or different?

**Comment by kacperpikacz** [comment]
The error is the same as in first post.

**Comment by BDisp** [comment]
> Today I got the same problem even by adding all timeouts inside Application.Mainloop.Invoke() with @tznind modified Mainloop code.

Please try on MacOS without the fix to see if it still happens.

**Comment by kacperpikacz** [comment]
@BDisp checked, again same error.

**Comment by tznind** [comment]
Please can you try cloning my PR here https://github.com/migueldeicaza/gui.cs/pull/1692 and see if the issue is resolved.  I'm pretty sure this is the right fix for you this time.

**Comment by BDisp** [comment]
It seems that the locks statements are handled differently on macOS. I already had struggled with this situation before. Another situation that can happen is when the timeout are checked on a certain thread, it may has a timeouts copy with no updated values.

**Comment by tznind** [comment]
Do you think that #1692 will not help then @BDisp ?

**Comment by tznind** [comment]
> But at first sight it mainly do the same thing as original but using a method. 

`RunTimers` has an if/else statement in it.  The 'if' condition uses `AddTimer` but the 'else' just directly added to the dictionary.  My PR adds the collision dodging to that else statement not just a new method.

```csharp
foreach (var t in copy) {
		var k = t.Key;
		var timeout = t.Value;
		if (k < now) {
			if (timeout.Callback (this))
				AddTimeout (timeout.Span, timeout); // has the collision dodging code
		} else {
			lock (timeoutsLockToken) {
				timeouts.Add (k, timeout); // does not have the collision dodging code
			}
		}
	}
```

**Comment by tig** [comment]
Should this Issue be re-opened?

**Comment by kacperpikacz** [comment]
@tznind your code modification fixed the issue on MacOS. No more problems during 23 hours.
