### ISSUE TITLE
Characters printed when clicking in terminal after quitting application

### ISSUE THREAD

**Issue by elfalem** [migueldeicaza/gui.cs#1686]
**Describe the bug**
Characters are printed to the terminal when clicking in terminal after quitting application.

**To Reproduce**
1. Create a new dotnet core console application with the following code in `Main()`:
```csharp
Application.Init();
var label = new Label ("Hello World");
Application.Top.Add(label);
Application.Run();
```
2. Run the application (`dotnet run`)
3. Quit the application with Ctrl+Q
4. Clicking the mouse in the terminal results in characters being printed (e.g. `j$#j$ q$#q$ q$#q$`)

If I set `Application.UseSystemConsole` to `true`, then characters are printed when moving and/or clicking the mouse.

**Expected behavior**
I expect the application to fully quit and no characters to be printed to the terminal when clicking the mouse.

**Desktop (please complete the following information):**
 - Terminal.Gui added via NuGet package v1.5.0
 - OS: Linux Mint 19.3
 - dotnet core 5
 - bash terminal

**Additional context**
My guess is that something is still grabbing the mouse and listening to mouse events after quitting.

**Comment by tznind** [comment]
Add `Application.Shutdown()` to the end of your program.

**Comment by elfalem** [comment]
That fixes it, thank you!

It might be worthwhile adding that to the examples on https://migueldeicaza.github.io/gui.cs/articles/overview.html so that new users (such as myself) aren't confused.

**Comment by tznind** [comment]
> It might be worthwhile adding that to the examples on https://migueldeicaza.github.io/gui.cs/articles/overview.html so that new users (such as myself) aren't confused.

Thanks for pointing this out.  I have submitted a PR to update those docs #1687
