### ISSUE TITLE
Menu doesn't close on button pressed and misalignment on open menus without HotKey.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1699]
After a menu is opening by a button pressed it can't be closed by a button pressed again.
If the menu bar is created without shortcut keys, the right menus are open misaligned.

![menu-issues](https://user-images.githubusercontent.com/13117724/167253399-70ad11e4-f11b-4f47-aaa6-23ef4fa12a62.gif)

**Comment by tig** [comment]
If I read this correctly, there are two separate Issues here, right?

**Comment by BDisp** [comment]
> If I read this correctly, there are two separate Issues here, right?

Right. I'm almost finishing the fix.

**Comment by tig** [comment]
Could you make them two issues and PRs? Not a huge deal, but it's just better to separate Issues if they are actually separate.

**Comment by BDisp** [comment]
> Could you make them two issues and PRs? Not a huge deal, but it's just better to separate Issues if they are actually separate.

Sorry @tig, but no, because the fix is only on the `Menu.cs` and is all mixed up. So it'll give me a lot of work to change the code to separate them and could corrupt some of the changes.

**Comment by tig** [comment]
No problem then!
