### ISSUE TITLE
TreeView and ListView: Per Node ColorTheme

### ISSUE THREAD

**Issue by arakis** [migueldeicaza/gui.cs#1702]
**Is your feature request related to a problem? Please describe.**
I want to use custom Colors per TreeNode.

**Describe the solution you'd like**
https://github.com/migueldeicaza/gui.cs/blob/main/Terminal.Gui/Views/TreeView.cs#L456
I'd like to specify the ColorScheme per TreeNode.

**Describe alternatives you've considered**
Because all required members in Tree.Redraw are private and, Branch<T> is internal and there's no way to specify a custom Branch<T> type like a CreateBranchInstance, it's impossible to use a custom ColorTheme per Node.

**Additional context**
I have a Command-Runner, and need a (compact) way to differentiate between a Command-Node and a Folder-Node without wasting space for a prefix text or something else.

It would be great if this is possible for ListView as well.

**Comment by BDisp** [comment]
For the `ListView` see the "`List View With Selection`" scenario.

**Comment by arakis** [comment]
Thanks for the hint regarding ListView. I fake a tree view now with ListView:
![image](https://user-images.githubusercontent.com/1831942/167314316-cf90c9a9-57bb-4d1c-9224-0f3e97548de6.png)

For the future, a NodeRenderer in TreeView like RowRenderer in ListView would be awesome.

**Comment by BDisp** [comment]
For `TreeView` probably @tznind will tell something.

**Comment by tznind** [comment]
Thanks for this great suggestion.

I have created a pull request that lets you tailor the color of the tree view item.  We could look into providing full control via inheritance or row renderer but I think that would be quite a bigger  change.

**Comment by arakis** [comment]
I just pulled `main` is it looks amazing. That's exactly what I need. Thank you so much. For simplicity: Is it possible to create a new nuget version (maybe pre-release)?

**Comment by tznind** [comment]
> I just pulled `main` is it looks amazing. That's exactly what I need. Thank you so much. For simplicity: Is it possible to create a new nuget version (maybe pre-release)?

@tig manages the nuget releases so could say more.  There are a few nice bugfix/feature PRs merged recently so hopefully a new release is planned.

**Comment by tig** [comment]
> > I just pulled `main` is it looks amazing. That's exactly what I need. Thank you so much. For simplicity: Is it possible to create a new nuget version (maybe pre-release)?
> 
> @tig manages the nuget releases so could say more. There are a few nice bugfix/feature PRs merged recently so hopefully a new release is planned.

TBH, I do releases when someone asks for one ;-). 

I'll do one asap!
