### ISSUE TITLE
Help Needed: Assign custom value to Colors.<token> 

### ISSUE THREAD

**Issue by PioArchiver** [migueldeicaza/gui.cs#172]
`Dialog jr = new Dialog("JSON", 150, 50) { ColorScheme = Colors.Menu };`

The above code would give you custom dialog with the default menu colors, but how do you set the colors for the Menu attribute if you wanted to change it and can you create custom attributes?

**Comment by migueldeicaza** [comment]
Just create your own ColorScheme class, and initialize the values on your own.

Currently this is platform specific, so that need to change.

**Comment by migueldeicaza** [comment]
I added a convenience Attribute.Make () method that should allow you to make new attributes more easily, and then you can create your own ColorScheme by setting the four values normal, focus, hotNormal and hotFocus with the values that you desire.
