### ISSUE TITLE
Scrolling text

### ISSUE THREAD

**Issue by amura11** [migueldeicaza/gui.cs#174]
I'm trying to create a `TextView` that scrolls (I'm not using a `ScrollView` for this, I couldn't find a way to make that work plus `ScrollView` doesn't seem to support the relative positioning yet) to the bottom as text is entered. Essentially I'm creating my own little debug console inside a `Window`. Is there any way to handle this? If there were something like `ScrollToEnd()` I could just call that each time text is added.

**Comment by migueldeicaza** [comment]
I have not exposed the API to control that, it is a good suggestion.

Generally, much of the code exists in the keyboard handler - but none of it has been turned into reusable commands.   I should change that.

That said, the go-to-first-line and go-to-last line commands are not implemented, so I would need to do that first.

**Comment by migueldeicaza** [comment]
Can you try the new method `ScrollTo(row)`, which will set the row to display at the top.   You might want to compute the row based on the height of your view if you want to keep a scrolling view going.
