### ISSUE TITLE
PR Requests: Color Themes

### ISSUE THREAD

**Issue by PioArchiver** [migueldeicaza/gui.cs#175]
I have three color schemes and working on a forth

1. Label  
2. Aside  
3. Development
4. Production - WIP

I was wondering if I could contribute a PR to add these default themes to the project.

**Comment by migueldeicaza** [comment]
I would love to!   Can you share in this comment section what the code looks like?

One limitation with the current design is that the theme needs to be replicated in the various drivers, and would be nice to have a platform agnostic way of declaring colors and color schemes.

**Comment by migueldeicaza** [comment]
I added a helper Attribute.Make(Color fore, Color back) method that should make it simpler to create these themes without having to worry about platform specific issues.

**Comment by PioArchiver** [comment]
Thanks @migueldeicaza, I just push updates to a repo here => https://github.com/PioArchiver/gui.cs.

Its the last two commits, the very last one was just some clean up.

**Comment by PioArchiver** [comment]
Not very complex I just rinsed and repeated the methods already there.  If you don't want to include the views I made I will leave them out.

**Comment by migueldeicaza** [comment]
Mhm, I do not see the repo ther.e
