### ISSUE TITLE
Update all .csproj files with Release version # upon Release

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#1753]
I facing a differential versions with the Terminal.Gui displayed from the `UICatalog` (1.6.2.0) with the development project version and the `StandaloneExample` (1.6.3.0.) with the nuget package version. Both file properties have also different versions. Is this normal?

![uicatalog](https://user-images.githubusercontent.com/13117724/170788620-312f8e67-bcd9-4cc5-9bad-70b27b4dc587.png)
![nuget-package](https://user-images.githubusercontent.com/13117724/170788655-fa6d62a9-e300-4ab5-bdbc-76db343aaa50.png)

**Comment by jas88** [comment]
Versions get bumped during tagged release builds in the Github action, so the version indicated in source is likely to lag a little behind actual release numbering: the version in Git isn't the number sent to Nuget.org any more.

**Comment by BDisp** [comment]
I didn't know, thanks for the explanation.

**Comment by tig** [comment]
In a future release I will do the following:

- Add a step to the Release instructions in `./Terminal.Gui/README.md` that do a `dotnet-gitversion /updateprojectfiles` to ensure all `.csproj` files have the Release Version #

**Comment by tig** [comment]
Changed my mind. With what's in `main` now, there are no version #s in any of the .csproj files. UI Cat's about box will always show 1.0. 

This is the simplest route given how `giversion` works. 

Closing this.
