### ISSUE TITLE
Label: If created with 'string.Empty' in constructor, fails to render

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1769]
**Describe the bug**
If `Label` is created with `new Label(string.Empty)` it fails to ever render. In some cases it causes an exception in `TextFormatter` (`throw new InvalidOperationException ("Size must be set before accessing Lines");`).

**To Reproduce**
Modify `Generic.cs`:

```csharp
using Terminal.Gui;

namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "Generic", Description: "Generic sample - A template for creating new Scenarios")]
	[ScenarioCategory ("Controls")]
	public class MyScenario : Scenario {
		public override void Setup ()
		{
			// Put your scenario code here, e.g.
			var button = new Button ("Press me!") {
				X = 1,
				Y = 1,
			};

			var label = new Label (string.Empty) {
				X = 1,
				Y = 2,
				ColorScheme = Colors.Error,
				Width = 50
			};
			Win.Add (label);

			button.Clicked += () => {
				label.Text = "Hello";
			};
			Win.Add (button);
		}
	}
}
````

**Expected behavior**
Change thee above constructor to 
```csharp
		var label = new Label (" ") {
````

To see it operate correctly.

I found this upgrading `Out-ConsoleGridView` from 1.0 to 1.6. A temporary fix in OCGV is to use `" "` instead of `string.Empty`.

**Comment by BDisp** [comment]
This is not really a bug because the label is not auto size, since it is instantiated with a width equal to 50. So the height must be provided too, "`Height = 1`". If you want to make it auto size, don't provide any size.

**Comment by tig** [comment]
Here's the original code that started crashing after upgrading to v1.6.4

```csharp
            var filterErrorLabel = new Label(string.Empty)
            {
                X = Pos.Right(_filterLabel) + 1,
                Y = Pos.Top(_filterLabel) + 1,
                ColorScheme = Colors.Base,
                Width = Dim.Fill() - _filterLabel.Text.Length
            };

            _filterField.TextChanged += (str) =>
            {
                // str is the OLD value
                string filterText = _filterField.Text?.ToString();
                try
                {
                    filterErrorLabel.Text = " ";
                    filterErrorLabel.ColorScheme = Colors.Base;
                    filterErrorLabel.Redraw(filterErrorLabel.Bounds);

                    List<GridViewRow> itemList = GridViewHelpers.FilterData(_itemSource.GridViewRowList, filterText);
                    _listView.Source = new GridViewDataSource(itemList);
                }
                catch (Exception ex)
                {
                    filterErrorLabel.Text = ex.Message;
                    filterErrorLabel.ColorScheme = Colors.Error;
                    filterErrorLabel.Redraw(filterErrorLabel.Bounds);
                    _listView.Source = _itemSource;
                }
            };
```

(Note this was coded before we supported `Visible`; I now just simplify all of this by hiding/showing the Label vs all the gymnastics of causing redraws (which is where the crash happened)).

This code did not crash before. It crashes now. By definition, for a library like ours, it's a bug.

If the real root cause is the lack of specifying Height, then I'd argue that the fix is to implement an intelligent default for Height in this case (e.g. make it 1).

Even if it is determined that this can't be done, the error that is thrown is not helpful in figuring out what was wrong. It took a bunch of trial and error for me to determine what was going on.

**Comment by BDisp** [comment]
I can't reproduce this to thrown the exception. Can you do a unit test that reproduce this?

**Comment by BDisp** [comment]
`AutoSize` were not supported before either. When vertical wide runes was implemented on `TextFormatter` I got some difficulties to deal with `AutoSize` as true and setting the size in simultaneously. By other side I also got some difficulties to clean a text when the text length is shrinking. So I decided if a size is defined on a view his `AutoSize` property is defined as false. In this case it's necessary to provide both sizes, width and height. Must we define default for `Height` equal to "1" only for a `Label` or for all views? This is valid for horizontal direction but not for vertical direction.
My opinion is that this exception doesn't make any sense since `Size.IsEmpty` is the same as `Width=0` and `Height=0` which is the same as `ustring.IsNullOrEmpty (Text) is true`.

**Comment by BDisp** [comment]
I have two solutions for this. For horizontal direction forcing the minimum height to be 1 and for vertical direction, forcing the width to be 1 or 2, dependent of the maximum rune column width. My question is if I should do on the `View` class for all the views or only for the `Label` view? If is in the `View` class some `Dim` unit test will be changed to reflect this change. Please say your opinions.
