### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by mgood7123** [migueldeicaza/gui.cs#1775]
does this support the Android platform?

**Comment by BDisp** [comment]
I already executed it on Android through https://github.com/jsuarezruiz/xamarin-forms-gui.cs, but is without updates at a long time.

**Comment by mgood7123** [comment]
alright, also is this a Terminal Emulator or a Terminal UI such as ncurses

**Comment by tznind** [comment]
This is a terminal GUI toolkit.  There are multiple display drivers (e.g. `NetDriver`, `CursesDriver` - which is a wrapper on ncurses).  The toolkit has controls for interactive tables, tree views, buttons etc.  It declares  events, keypresses, window layering etc.

There is currently active development to support a Blazor driver (for web rendering) and I think the Android support @BDisp linked follows a similar pattern (adding a new display driver).  There also might be future support for MAUI.

But in terms of what is production ready now then it is running in terminals on Windows/Linux/MackOS (e.g. powershell, Terminal, terminator etc).

**Comment by mgood7123** [comment]
alright :)
