### ISSUE TITLE
View should not turn off AutoSize (in setting Width and/or Height)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1791]
**Describe the bug**
In https://github.com/migueldeicaza/gui.cs/pull/1685 from @BDisp, there's this commit:

```
Commit a82ac45843d6153f10d7c545721d4aeabb75266d
Author: BDisp <bd.bdisp@gmail.com>
Date: Friday, April 29, 2022 5:12 PM
Parent: 933a1bda

Fixes AutoSize, Window Tile and added option to Border for fill or not.
```

https://github.com/migueldeicaza/gui.cs/pull/1685/files#diff-4a82080ff9e808d1867c94cdd6ac106755bd80a81509546e43f154aed1fe90deR572

```csharp
		/// <summary>
		/// Gets or sets the width of the view. Only used the <see cref="LayoutStyle"/> is <see cref="LayoutStyle.Computed"/>.
		/// </summary>
		/// <value>The width.</value>
		/// <remarks>
		/// If <see cref="LayoutStyle"/> is <see cref="LayoutStyle.Absolute"/> changing this property has no effect and its value is indeterminate. 
		/// </remarks>
		public Dim Width {
			get => width;
			set {
				if (!ValidatePosDim (width, value)) {
					throw new ArgumentException ();
				}

				width = value;
				if (autoSize && value.Anchor (0) != TextFormatter.Size.Width) {
					autoSize = false;
				}
				SetNeedsLayout ();
				if (width is Dim.DimAbsolute) {
					frame = new Rect (frame.X, frame.Y, width.Anchor (0), frame.Height);
				}
				TextFormatter.Size = frame.Size;
				SetNeedsDisplay (frame);
			}
		}
```

See how `AutoSize` is set to false? This breaks code where a `Button` (or any View) has been set to autosize and then has it's text changed and the view has been moved (e.g. in the new `Dialog` code for justifying buttons). 

I found this in coding up Wizard. I noticed that when I changed the text of the `NextFinished` button from `Next...` to `Finished` (which is longer) the button did not resize. A workaround is to re-set `AutoSize` to true when changing the text, but this should not be needed (and will not work in other scenarios).

This Unit Test should be added once this bug is fixed:

```csharp
		[Fact, AutoInitShutdown]
		public void AutoSize_Stays_True ()
		{
			var btn = new Button () {
				X = Pos.Center (),
				Y = Pos.Center (),
				Text = "Say Hello 你",
				AutoSize = true
			};

			var win = new Window () {
				Width = Dim.Fill (),
				Height = Dim.Fill (),
				Title = "Test Demo 你"
			};
			win.Add (btn);
			Application.Top.Add (win);

			Assert.True (btn.AutoSize);

			Application.Begin (Application.Top);
			((FakeDriver)Application.Driver).SetBufferSize (30, 5);
			var expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│      [ Say Hello 你 ]      │
│                            │
└────────────────────────────┘
";

			GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);

			Assert.True (btn.AutoSize);
			btn.Width = Dim.Fill ();
			Assert.True (btn.AutoSize);
		}
```

@BDisp, can you find another way to solve whatever you fixed by doing this?

**Comment by tig** [comment]
The workaround doesn't work. Setting `AutoSize` on `Button` causes `Update()` to be called which eventually sets `Width` causing `AutoSize` to be turned off again.

**Comment by BDisp** [comment]
@tig if `AutoSize` is mandatory don't set the size but only the position.

**Comment by tig** [comment]
@BDisp, i don't think you are understanding what I'm saying.

This has nothing to do with buttons with greater HEIGHT. 

Nowhere does `AutoSize` say "If you set AutoSize to true any changes to Height or Width will turn AutoSize off".

Button just has a case where this bug is exposed more easily: Changing the text of a button causes `Button.Update` to be called. And `Button.Update` changes the `Width`, thus causing `AutoSize` to be set to false. This is unexpected and incorrect behavior.

**Comment by BDisp** [comment]
I know what is the problem :-) I'll handle the same way as I handled the `LayoutStyle` in the `Update` method.

**Comment by BDisp** [comment]
@tig this breaks the `AutoSize` feature. As you said if the text changed and `AutoSize` is true the `Button` must set the `Width` itself and not setting the `btn.Width = Dim.Fill ()`. If the width exceeds the right frame then the left position must be adjusted.

**Comment by BDisp** [comment]
If `AutoSize` is true is must handled like this and `AutoSize` is still true.

```cs
		[Fact, AutoInitShutdown]
		public void AutoSize_Stays_True_Center ()
		{
			var btn = new Button () {
				X = Pos.Center (),
				Y = Pos.Center (),
				Text = "Say Hello 你",
				AutoSize = true
			};

			var win = new Window () {
				Width = Dim.Fill (),
				Height = Dim.Fill (),
				Title = "Test Demo 你"
			};
			win.Add (btn);
			Application.Top.Add (win);

			Assert.True (btn.AutoSize);

			Application.Begin (Application.Top);
			((FakeDriver)Application.Driver).SetBufferSize (30, 5);
			var expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│      [ Say Hello 你 ]      │
│                            │
└────────────────────────────┘
";

			GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);

			Assert.True (btn.AutoSize);
			btn.Text = "Say Hello 你 changed";
			Assert.True (btn.AutoSize);
			Application.Refresh ();
			expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│  [ Say Hello 你 changed ]  │
│                            │
└────────────────────────────┘
";

			GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);
		}

		[Fact, AutoInitShutdown]
		public void AutoSize_Stays_True_AnchorEnd ()
		{
			var btn = new Button () {
				Y = Pos.Center (),
				Text = "Say Hello 你",
				AutoSize = true
			};
			btn.X = Pos.AnchorEnd () - btn.TextFormatter.Text.Length + 1;

			var win = new Window () {
				Width = Dim.Fill (),
				Height = Dim.Fill (),
				Title = "Test Demo 你"
			};
			win.Add (btn);
			Application.Top.Add (win);

			Assert.True (btn.AutoSize);

			Application.Begin (Application.Top);
			((FakeDriver)Application.Driver).SetBufferSize (30, 5);
			var expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│            [ Say Hello 你 ]│
│                            │
└────────────────────────────┘
";

			GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);

			Assert.True (btn.AutoSize);
			btn.Text = "Say Hello 你 changed";
			btn.X = Pos.AnchorEnd () - btn.TextFormatter.Text.Length + 1;
			Assert.True (btn.AutoSize);
			Application.Refresh ();
			expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│    [ Say Hello 你 changed ]│
│                            │
└────────────────────────────┘
";

			GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);
		}
```

**Comment by tig** [comment]
What breaks the autosize feature?

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by BDisp** [comment]
Setting the width or height there is no needed to be autosize. If it is autosize then set only the position and the width and height will be dynamically set.

**Comment by tig** [comment]
I am not setting the width. The code in Button.Update is.



-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by BDisp** [comment]
But that width change in the Button.Update is not currently changing autosize to false, as you can see in the unit tests.

**Comment by BDisp** [comment]
```cs
				if (autoSize && value.Anchor (0) != TextFormatter.Size.Width) {
					autoSize = false;
				}
```
As you can see the autosize only will changed to `false` if the `value.Anchor (0) != TextFormatter.Size.Width`. Since the `Button.Update` handles the `TextFormatter.Size` before changing the `Button.Width`, thus the condition always return `false`.
