### ISSUE TITLE
TextView with ScrollView: If TextView is set to read-only TAB and ENTER keys are eaten

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1799]
This can be reproduced in the Wizard Scenario by setting `helpTextView.CanFocus = false` in `WizardStep()`.

Not sure if this is a bug in `TextView` or `ScrollView`, or if there is a different way of enabling scrolling on `TextView` that works around this.

What I want is a read-only TextView that 

a) Doesn't take focus
b) Can be scrolled with either mouse or keyboard

**Comment by BDisp** [comment]
`CanFocus` equal to false doesn't allow to be focused. If you want use the scroll bar set the `ReadOnly = false`.

**Comment by BDisp** [comment]
Or maybe you want `TabStop = false`.

**Comment by tig** [comment]
> `CanFocus` equal to false doesn't allow to be focused. If you want use the scroll bar set the `ReadOnly = false`.

This is what I have done. `helpTextView.ReadOnly = true`. The problem is, when you tab into the `helpTextView` you can't tab out. 

But... I just discovered setting `helpTextView.AllowTab = false` addresses the issue.

In other words, the REAL bug here is when `TextView.ReadOnly == true` the view should IGNORE tabs (as though `AllowTab = true`). 

Note that when `AllowReturn` is set to false, something else is goofy, but that's another bug which I'll file a separate issue on.

**Comment by tznind** [comment]
> when tabbing into the helpTextView one can't tab out again.

What is `AllowsTab` value? that might swallow the tab out keypress?

**Comment by BDisp** [comment]
To continue tab to go out you must press Ctrl+Tab/Ctrl+Shift+Tab or Ctrl+PageDown/Ctrl+PageUp.

**Comment by BDisp** [comment]
> What is `AllowsTab` value? that might swallow the tab out keypress?

Since it's read only that really matter but using the combinations keys are better.

**Comment by tig** [comment]
Here's the big idea: 

A read-only TextView with a ScrollBarView is useful for displaying long text. When it is read only the user should be able to tab into and out of it. There is no world where it should eat tab presses when it is focused (and read-only).

Right now when `ReadOnly == true` the developer has to explicitly set `AllowTabs = false` for the control to work as expected.

The workaround is to set `AllowTabs = false`. 

I assert this is a bug, and if `ReadOnly == true` the control should ACT as though `AllowTabs == false`. I do NOT think the fix is to automatically set `AllowTabs` when `ReadOnly` changes.

**Comment by BDisp** [comment]
I think this was fixed by the #1804.
