### ISSUE TITLE
Proposal: fluent API

### ISSUE THREAD

**Issue by zabulus** [migueldeicaza/gui.cs#181]
Hi there. Good library, looks pretty awesome!
But I have a proposal for API.
From samples:
```
	win.Add (
	    // The ones with my favorite layout system
  	    login, password, loginText, passText,
```
It's quite hard to gather all controls, that I've spawned before to add to ```win``` through ```Add``` method (I've created around 5 or 6 label-text pairs, and it's already cumbersome to register them all in ```win```). 
Proposal is following:
```
loginLabel = win.Label("Login")
   .Position(3, 2);
passwordLabel = win.Label("Password")
   .Position(Pos.Left(loginLabel), Pos.Top(loginLabel) + 1);
```
This will allow to combine adding to ```win``` and initialization of objects. I'll create my own extension methods, as I see there is nothing complicated and that could be done from consumer side.

**Comment by migueldeicaza** [comment]
This is generally a good idea, but I would like to see a comprehensive proposal to what this does.

Generally, .NET guidelines do not use fluent APIs, and I would like to learn more about what the good practices are for this.
