### ISSUE TITLE
Return current step index in StepChangeEventArgs

### ISSUE THREAD

**Issue by GaikwadPratik** [migueldeicaza/gui.cs#1823]
**Is your feature request related to a problem? Please describe.**
`StepChangeEventArgs` should contain `CurrentStepIndex`, since that would be helpful during workflow to integrate 

**Describe the solution you'd like**
[Details in here](https://github.com/migueldeicaza/gui.cs/issues/1794#issuecomment-1157923521)

**Comment by tig** [comment]
CLosing as won't fix as Wizard doesn't use indexes anymore. 

When handling `StepChanging` or `StepChanged`, to get the current step, just access `wizard.CurrentStep`.
