### ISSUE TITLE
Context menu Copy command freezes app (on main branch)

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1837]
**Describe the bug**
In Ubuntu when I activate Copy the app freezes.  Console is Terminator.  

Ctrl+Q does not respond, no response to clicks/keypresses etc.  Only way out is to close terminal or `kill` process.

Also worth noting is that while the program is blocking I can't copy anything in other apps either (e.g. Firefox).  Its like the Copy method is blocking and holding onto xclip (or the clipboard process) so nobody else can use it but never exits.

**To Reproduce**

1. Open Editor Scenario
2. Select some text
3. Select Copy

**Screenshots**

![copyFreezeCrash](https://user-images.githubusercontent.com/31306100/175806294-13700512-6757-4006-9e47-e1043a8920a2.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by tznind** [comment]
Issue does not exist in 8e70756cd857f5f273d9471e35a98caae83769ae so I think it was introduced in #1828

**Comment by BDisp** [comment]
Do you are using `CursesDriver` or `NetDriver`?

**Comment by tznind** [comment]
> Do you are using `CursesDriver` or `NetDriver`?

Curses Driver

**Comment by BDisp** [comment]
Sorry, at the time, I was going to make some changes that I ended up not concluding or not making sense and forgot to replace.

**Comment by tznind** [comment]
> Sorry, at the time, I was going to make some changes that I ended up not concluding or not making sense and forgot to replace.

No worries, glad we caught this before a nuget package shipped and thanks for the quick fix
