### ISSUE TITLE
Window always has padding because of ContentView

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1855]
**Describe the bug**
The Window class contains a ContentView, referenced as 'Client'. This view is positioned at X = Y = 1. 

This means that even if you set Window.Border.BorderThickness to 0, there's still a 1 row/column pad. 

I think this can be worked around by changing dimensions of Client, but it's annoying. 

This may just be a doc issue. I'm filing it so I don't forget.

**Comment by BDisp** [comment]
@tig that can tweaked by setting the `DrawMarginFrame` to false.

![imagem](https://user-images.githubusercontent.com/13117724/179556579-5c02e57b-a503-4ade-b05d-35afe36a21a2.png)

**Comment by tznind** [comment]
Looks like you can't set `DrawMargineFrame` to `false` till you first set `BorderStyle.None`.  Also `BorderBrush` doesn't seem to do anything

![border](https://user-images.githubusercontent.com/31306100/179558981-cc5a5924-4dcf-46de-a4e2-e570eb55fb52.gif)
