### ISSUE TITLE
Wizard Controls class is poorly thought thru

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1856]
I added 'Controls' and force users to Add controls via 'wizard.Controls.Add'. 

Instead I should have just leveraged the fact Window already has 'Client' (ContentView) and just automatically size/position it. 

I think. 

The only issue I see in doing this is dealing with HelpView. 

I'll look into this asap and will fix (or not) before next release (wizard is still not in production so breaking changes are ok).

**Comment by tig** [comment]
Nevermind.

I just started looking into this and, in `FrameView`:

```csharp
		/// <summary>
		/// ContentView is an internal implementation detail of Window. It is used to host Views added with <see cref="Add(View)"/>. 
		/// Its ONLY reason for being is to provide a simple way for Window to expose to those SubViews that the Window's Bounds 
		/// are actually deflated due to the border. 
		/// </summary>
		class ContentView : View {
			public ContentView (Rect frame) : base (frame) { }
			public ContentView () : base () { }
		}
```

So trying to automatically prevent Views added to the Wizard's "Control" area from overlapping the help won't work by resizing `ContentVeiw` (which isn't exposed `public` anyway).

I am going to rename `Controls` to `Content` though, just to be consistent with MIguel's original terminology.

**Comment by BDisp** [comment]
For a modal wizard I think is better the Dialog because it's derived from Window we which is a Toplevel. For a non modal wizard the Frame looks fine.

**Comment by tig** [comment]
> For a modal wizard I think is better the Dialog because it's derived from Window we which is a Toplevel. For a non modal wizard the Frame looks fine.

See my latest commits to #1853 

I've actually gone ahead and radically simplified all this.
