### ISSUE TITLE
 Why do strings have a `_`?

### ISSUE THREAD

**Issue by luizfernandonb** [migueldeicaza/gui.cs#1863]
I'm starting to use the library and I have a question, what's the point of using a `_` at the beginning of the string?

Example:
![image](https://user-images.githubusercontent.com/42288418/179844253-f9021ce7-415a-4b98-b964-409611e4469a.png)

In the print I sent, the `_` of the word "Cut" is after the first letter, why?

I've searched the internet, but I couldn't find anything about it, thanks to whoever responds.

**Comment by BDisp** [comment]
It's a codification to create a hot key which will draw with a different color. The 'u' is draw in yellow in this case.

![imagem](https://user-images.githubusercontent.com/13117724/179845812-c4c2cbae-e771-44ff-a8f1-ed3397d01eed.png)

**Comment by luizfernandonb** [comment]
> It's a codification to create a hot key which will draw with a different color. The 'u' is draw in yellow in this case.
> 
> ![imagem](https://user-images.githubusercontent.com/13117724/179845812-c4c2cbae-e771-44ff-a8f1-ed3397d01eed.png)

Thank you, and is this only useful?

**Comment by luizfernandonb** [comment]
> Yes, by creating a shortcut where by using the Alt+U key combination you can execute that command.

Thanks!
