### ISSUE TITLE
Binding `Ctrl` + `A`

### ISSUE THREAD

**Issue by luizfernandonb** [migueldeicaza/gui.cs#1864]
Can't do a `Ctrl` + `A` binding? When I press these two buttons together, the Windows console places the cursor at the beginning.

Before:
![image](https://user-images.githubusercontent.com/42288418/179868305-e0e2cbd3-3d41-471b-b1c5-e9299ca38c25.png)

After:
![image](https://user-images.githubusercontent.com/42288418/179868325-ec79936d-9db8-4c2b-913d-4cf1812e9aac.png)

Extra note: I didn't find a `Ctrl` + `A` binding to select all the text in a TextView, so I'm doing it by hand.

**Comment by tznind** [comment]
@tig I was about to link the documentation for the Keybinding system but it seems to have been removed from README.md in this commit https://github.com/tznind/gui.cs/commit/cc04bb37f5c7684d45833dabd3f7e1ca9c53786f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L73-L87 

Now there is just a single sentence:

> Apps can change key bindings using the `AddKeyBinding` API.

I can see how going into too  much detail on the landing page could dilute things but do you want that content moved elsewhere e.g. 

- https://migueldeicaza.github.io/gui.cs/articles/overview.html (input handling section)
- https://migueldeicaza.github.io/gui.cs/articles/keyboard.html

**Comment by tig** [comment]
Yeah, I wanted to keep the README.md as tight as possible. I assumed that detail was in the API docs. If not, then please do add a PR to add it to the overview articles.

Thanks.

**Comment by BDisp** [comment]
> Extra note: I didn't find a `Ctrl` + `A` binding to select all the text in a TextView, so I'm doing it by hand.

@luizfernandonb, `TextView` already has that binding by using `Ctrl+T` key combination.

![imagem](https://user-images.githubusercontent.com/13117724/179987162-9f7e9dbe-d116-4d11-89dc-e66a37fb6fde.png)

**Comment by luizfernandonb** [comment]
> Hi, thanks for getting in touch.
> 
> The default behaviour of TextView is to treat Ctrl+A as 'go to start of line' you can override this with a single line:
> 
> `tv.AddKeyBinding(Key.A | Key.CtrlMask, Command.SelectAll);`
> 
> Here is an example:
> 
> ```cs
> Application.Init();
> TextView tv = new TextView {Width = Dim.Fill(),Height = Dim.Fill()};
> 
> // this is the line you are looking for
> tv.AddKeyBinding(Key.A | Key.CtrlMask, Command.SelectAll);
> 
> var w = new Window();
> w.Add(tv);
> Application.Run(w);
> Application.Shutdown();
> ```

I had already done that too, but I ended up forgetting to put it in the description, and it didn't work either, keep going to the beginning of the line

**Comment by asphergers** [comment]
Isn't there a way to override existing commands on View and View inherited objects using AddCommand()?  I've read over the implementation in [#1556](https://github.com/migueldeicaza/gui.cs/pull/1556) but haven't been able to get anything working.

**Comment by tznind** [comment]
> Isn't there a way to override existing commands on View and View inherited objects using AddCommand()? I've read over the implementation in [#1556](https://github.com/migueldeicaza/gui.cs/pull/1556) but haven't been able to get anything working.

Do you mean remove an existing keybound command? You should be able to do that with this:

`tv.ClearKeybinding(Command.SelectAll);`

**Comment by luizfernandonb** [comment]
> > Hi, thanks for getting in touch.
> > The default behaviour of TextView is to treat Ctrl+A as 'go to start of line' you can override this with a single line:
> > `tv.AddKeyBinding(Key.A | Key.CtrlMask, Command.SelectAll);`
> > Here is an example:
> > ```cs
> > Application.Init();
> > TextView tv = new TextView {Width = Dim.Fill(),Height = Dim.Fill()};
> > 
> > // this is the line you are looking for
> > tv.AddKeyBinding(Key.A | Key.CtrlMask, Command.SelectAll);
> > 
> > var w = new Window();
> > w.Add(tv);
> > Application.Run(w);
> > Application.Shutdown();
> > ```
> 
> I had already done that too, but I ended up forgetting to put it in the description, and it didn't work either, keep going to the beginning of the line
> 
> I will test again, I believe I did it differently

Yeah, I had done it wrong, thanks for helping me.

**Comment by tznind** [comment]
> Yeah, I had done it wrong, thanks for helping me.

Glad you got it sorted :+1: and if you have any further difficulties don't hesitate to open a new issue.  Issues like this help identify where documentation is lacking as well as provide answers to future users searching the closed issues.
