### ISSUE TITLE
Strange characters in console when opening executable without using Visual Studio

### ISSUE THREAD

**Issue by luizfernandonb** [migueldeicaza/gui.cs#1879]
**Describe the bug**
Strange characters appear on the screen after opening the executable generated without an IDE, they appear before loading the layouts.

**To Reproduce**
1. Just open the generated executable without using an IDE.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/42288418/180463936-a5999c77-8aea-4b26-93ad-455c0aac7519.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 - Build 19044.1826
 - Browser: Edge
 - Version: 103.0.1264.62

Extra note: Maybe the problem is the CMD and not the library?

**Comment by BDisp** [comment]
This is because of this statement `Console.Out.Write ("\x1b[3J");`. In `Windows Terminal` on `Windows 11` this doesn't happen.

**Comment by luizfernandonb** [comment]
> This is because of this statement `Console.Out.Write ("\x1b[3J");`. In `Windows Terminal` on `Windows 11` this doesn't happen.

And why does this `Console.Out.Write ("\x1b[3J");` does it exist in the source code? If I remove it, will it cause any problems?

**Comment by BDisp** [comment]
In the `Window Terminal` yes, because the vertical scroll bar remains allowing users scrolling out the `Terminal.Gui` application, corrupting the views.

**Comment by luizfernandonb** [comment]
> In the `Window Terminal` yes, because the vertical scroll bar remains allowing users scrolling out the `Terminal.Gui` application, corrupting the views.

Got it, and is there no way to hide or execute this write without showing these characters in the console?

**Comment by BDisp** [comment]
> Got it, and is there no way to hide or execute this write without showing these characters in the console?

Windows Terminal assumes it as a escape sequence and execute it. The cmd assume as it's writing to the console. I think it isn't worth to worry about this because it show only for a very little time.

**Comment by luizfernandonb** [comment]
> > Got it, and is there no way to hide or execute this write without showing these characters in the console?
> 
> Windows Terminal assumes it as a escape sequence and execute it. The cmd assume as it's writing to the console. I think it isn't worth to worry about this because it show only for a very little time.

Okay, no problem, thanks for responding.
