### ISSUE TITLE
TopLevels with `Modal == false` don't receive an event indicating their container is Loaded/Ready

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1883]
In `Application.cs`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/585482/180605611-e08faced-4740-47f8-9cfd-d5ceddaa8ae8.png">

And in `Begin()`:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/585482/180605633-7b251e28-ccea-4f1e-91fc-f494e4fd3eb2.png">

Neither `TopLevel.OnReady` or `TopLevel.OnLoaded` recurse contained `TopLevels`. They should.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/585482/180605705-de43a5f8-f632-4381-b74c-c6f353ba8692.png">

Something like this:

```csharp
		/// <summary>
		/// Called from <see cref="Application.Begin(Toplevel)"/> before the <see cref="Toplevel"/> is redraws for the first time.
		/// </summary>
		virtual public void OnLoaded ()
		{
			foreach (Toplevel tl in Subviews.Where (v => v is Toplevel)) {
				tl.OnLoaded ();
			}
			Loaded?.Invoke ();
		}
```

**Comment by BDisp** [comment]
Because they are added as a superview's subview, so the `Loaded` event will never be invoked. Since you do `Top.Add (wizard);` automatically the wizard view is a Top's subview. To the `Loaded` event being invoked then it have to do `Application.Run (wizard);` instead.

**Comment by tig** [comment]
> Because they are added as a superview's subview, so the `Loaded` event will never be invoked. Since you do `Top.Add (wizard);` automatically the wizard view is a Top's subview. To the `Loaded` event being invoked then it have to do `Application.Run (wizard);` instead.

Sorry @BDisp , but I'm not following what you are saying. I think you are just stating why it is this Issue exists. 

I have tested my proposed fix (see above) and it works as expected, alleviating the need for me to set the first step manually in the `WizardAsView` scenario.

In the `Wizards` scenario, the non-modal codepath creates the `Wizard` AFTER `Application.Run(Top)` has been called, and thus `Loaded` never fires even with my fix. So, in the PR to fix this Issue I am going to change the `Wizard` API docs to read:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/585482/180616819-29b4a1ad-e974-4afb-9271-62089878d919.png">


Make sense?

**Comment by BDisp** [comment]
I think your fix to the `OnLoaded` may work if the `Toplevel` is added before the `Application.Run`. The API docs to explain why doesn't work if the `Wizard` is added after run makes sense. I only was justifying why the `Loaded` event of a `Toplevel`, which is a subview of another `Toplevel`, isn't invoked. Good work.
