### ISSUE TITLE
TextField - Doesn't keep text alignment while window resizing

### ISSUE THREAD

**Issue by neciolaza** [migueldeicaza/gui.cs#1888]
I created a text field like this inside a frameview:
`TxtServerUrl = new TextField(linuxServiceSettings.ServerUrl) 
{ X = leftTextBoxes + X_SEPARATOR, 
Y = Pos.Top(LblServerUrl), 
Width = Dim.Fill(margin),
 Enabled = false };
TxtServerUrl.TextAlignment = TextAlignment.Left;
Add(TxtServerUrl);`
and it shows the text ok, but while resizing the window (using the mouse, or clicking on maximize and minimize), the text isn´t shown from the left to the right as expected (i also have a label containig long text and it works as expected) instead it shows always like from right to left and at some point it starts showing the whole text while enlarging, but not exactly after having enough room.

Tested it running from VS 2022 but also on Ubuntu 20.04 with desktop
![ScreenCapture_03_After maximizing using mouse](https://user-images.githubusercontent.com/68996756/180864113-86ea3d6d-c647-490d-addd-ed6f0b37d917.png)
![ScreenCapture_01_OriginalState](https://user-images.githubusercontent.com/68996756/180864115-fbc833ce-a493-4b26-9934-f4588c4f096b.png)
![ScreenCapture_02_After shrinking using mouse](https://user-images.githubusercontent.com/68996756/180864116-7cb5459b-3803-4323-ad28-4ab8ed0eb70a.png)
.

**Comment by BDisp** [comment]
`TextField` after initialized always set the cursor position in the end. If you want to show beginning in the position zero then set the cursor position to zero too.

**Comment by neciolaza** [comment]
Sorry if my question is too basic, but i've tried SelStart set to 0 or 1 and didn´t get the cursor position to the beginning, how can i achieve that?

**Comment by BDisp** [comment]
The `SelStart ` is for selecting text. Use `CursorPosition` = 0.

**Comment by neciolaza** [comment]
Thank you, sorry for the inconvenience!

**Comment by tznind** [comment]
> Thank you, sorry for the inconvenience!

Raising issues is always helpful, it provides answers for future users as well as identifying any areas of the API that are confusing.  No need to apologies!
