### ISSUE TITLE
StandardApplication

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#196]
The StandardApplication should be the gui.cs version of Xamarin.Forms' Shell that does:

* Create a menu with nothing in it
* Add a statusbar and global shortcuts
* Rely on a "New Window" idiom to create multiple windows
* Allow the windows to be resized/closed (bring this to Window)
* Commands for tiling/closing/send-to-back/bring-to-front.

**Comment by tig** [comment]
I think we have enough samples that this can be closed.

**Comment by andreasciamanna** [comment]
I've been trying to find the answer to "Commands for tiling/closing/send-to-back/bring-to-front.".

As there are enough samples, where can I find this one?

**Comment by tznind** [comment]
> As there are enough samples, where can I find this one?

Windows & FrameViews sounds like what you want for multiple windows overlaying one another

![mdi](https://github.com/gui-cs/Terminal.Gui/assets/31306100/525d330f-47ed-4471-86d5-8aecc8f1bd80)

https://github.com/gui-cs/Terminal.Gui/blob/develop/UICatalog/Scenarios/WindowsAndFrameViews.cs

**Comment by andreasciamanna** [comment]
I was looking at an example with menus, where menu items open different (full-screen) windows.

I'm missing something in how TGUI works because I could not figure out the correct way to do that.

I think most of these examples are great for showcasing the library, but I'm more comfortable with simpler code-only examples.

I'm temporarily giving up TGUI and pursuing a more "classic" approach (with Avalonia). I'm on a tight deadline and have already spent a whole day achieving very little.

I'll revisit TGUI once I have more time.

Thanks, by the way,

**Comment by tznind** [comment]
Easiest way to get stuff done fast with Terminal.Gui is with [the designer](https://github.com/gui-cs/TerminalGuiDesigner).

Create a new project using the terminal gui project template:
```
dotnet new --install Terminal.Gui.templates
dotnet new tui -n myproj
cd myproj
```

Install and run the designer
```
dotnet tool install --global TerminalGuiDesigner
TerminalGuiDesigner
```

Use the New option to create a new Window (or Toplevel) and add a MenuBar.

Type to change menu bar titles
Use Enter to add new menu items
Use shift right to move the selected item to a submenu:

![normalApp](https://github.com/gui-cs/Terminal.Gui/assets/31306100/315aa155-4000-4d9d-91e9-8f41d1a45f3a)

Create a few more windows with the designer then add the code to join the bits together:

Update Program.cs to

```
using myproj;
using Terminal.Gui;

Application.Init();

try
{
    Application.Run(new MyToplevel());
}
finally
{
    Application.Shutdown();
}
```

Update the constructor for MyToplevel.cs to register menu actions:

```
public MyToplevel() {
    InitializeComponent();
    showWindow1MenuItem.Action = ()=> Application.Run(new Window1());
    window2MenuItem.Action = ()=> Application.Run(new Window2());
}
```

- Use F9 to open menus
- Close the popup windows with Ctrl+Q 

Alternatively you can add a close button to your windows and set the action for that to `Application.RequestStop()`

**Comment by tig** [comment]
FWIW:

* v1 of Terminal.Gui has almost no support for using the keyboard for moving, sizing, closing, tiling, arranging, minimizing, maximizing, overlapped non-modal views. Apps that use an MDI-like metaphor are thus inaccessible to users who want/need to use just the keyboard. For this reason alone, I recommend not building apps that use overlapped (non-modal) views.
* v2 of Terminal.Gui will have a different API for overlapped non-modal views. Getting this sorted is a relatively low priority and we will NOT block releasing v2 for it. Further, the existing Mdi/Toplevel functionality in v1 has been refactored in v2 in a half-assed way (I am responsible) and right now is buggy/unstable. In otherwords: Do not count on v2 magically fixing my first point above.

My recommendation is for you to NOT try to use multiple overlapping, non-modal windows. Instead, follow @tznind's advice and use a "pane" style UI like UICatalog does, or leverage the awesome `TabView` view (see the `Notepad` example).

**Comment by BDisp** [comment]
@tig if you look at the PR #2778, you'll see it's now possible to close non-modal toplevels with Ctrl+Q. It has a lot of unit tests that prove that and had some improvements.
