### ISSUE TITLE
Add resizing support to the core

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#2]
Resizing of the toplevel windows, and message boxes should be relatively easy, but there is no support to relayout the views.   As we do not currently have a layout system, beyond the absolute positioning system.

*Update* The https://github.com/migueldeicaza/gui.cs/tree/layout branch now contains a C# port of the Xamarin Flex engine that Stephane Delcroix did, while the port is complete, it is completely untested, that needs to be done.

**Comment by attilah** [comment]
Can't we use https://github.com/xamarin/flex ?

**Comment by migueldeicaza** [comment]
I have the code in a branch, have not tested it yet.

Stephane Delcroix ported Flex to C# and I adapted that port to gui.cs, check it out here:

https://github.com/migueldeicaza/gui.cs/tree/layout

**Comment by migueldeicaza** [comment]
New layout system in place, not based on Flex, which now I need to wire up.

**Comment by migueldeicaza** [comment]
Done the Linux one.
