### ISSUE TITLE
OpenDialog example?

### ISSUE THREAD

**Issue by dquinter** [migueldeicaza/gui.cs#217]
Hi all.

I need some example with this view, can you help me?

Thanks!

**Comment by zmira** [comment]
`
var dialog = new Dialog("Dialog Title", 50, 8, new Button("Ok")
{
	Clicked = () =>
	{
		Application.RequestStop();
	}
});

var label = new Label("Dialog label...")
{
	X = Pos.Center(),
	Y = 1
};
dialog.Add(label);

Application.Run(dialog);
`

**Comment by tig** [comment]
See `Editor` Scenario in `UI Catalog`

![image](https://user-images.githubusercontent.com/585482/82745361-80a53580-9d40-11ea-8d3f-732bd3b12243.png)

Re-open this if you still have issues.
