### ISSUE TITLE
F11 and F12

### ISSUE THREAD

**Issue by worksofliam** [migueldeicaza/gui.cs#220]
Right now I understand that F11 and F12 are not valid keys in gui.cs.

F11 makes the console full screen (on Windows) and F12 didn't do anything. Is it possible to override those keys and support handling those keys in gui.cs?

Thanks!

**Comment by tig** [comment]
Do you want to use the key for an app-level thing, or have `Terminal.Gui` do something with them?

I do believe `WindowsDriver.cs` could be modified to support this, easily.

**Comment by tig** [comment]
Fixed in #535
