### ISSUE TITLE
Unresponsive mouse click in Ubuntu

### ISSUE THREAD

**Issue by adienakhmad** [migueldeicaza/gui.cs#223]
Hey, I'm having a problem where the mouse clicks are very not responsive. Sometimes you really have to mash the mouse click for it to register.

Is there anything I can do to fix/ diagnose/work around this problem.

Happening on Ubuntu 18.04 LTS including the WSL ones

**Comment by migueldeicaza** [comment]
Might depend on your terminal emulator.   I am sorry, I can not reproduce this.
