### ISSUE TITLE
[Bug] Resize window cause graphics glitches.

### ISSUE THREAD

**Issue by MairwunNx** [migueldeicaza/gui.cs#224]
#### Bug description:
> Incorrect behavior of rendering and redrawing of content in the window when the window is resized by the user.

#### Idea of the fix:
> When resizing the window, just freeze the rendered image in the state it was in before resizing, the same feature uses Minecraft which uses OpenGL.

#### Reproduce problem:

> ###### 1. Run with Debug mode or Build Example project.

> ###### 2. After build run Terminal.exe and try resize window.

#### Result of reproduction:

![window](https://user-images.githubusercontent.com/39625750/60107056-e7a41e00-976e-11e9-8a75-03485778cf52.gif)

**Comment by MiroslavMikus** [comment]
Hey, I have a strange effect after resizing the application. It's without problem when I make the console window larger, but the GUI has a problem when I try to make it small again. This affects only vertical resizing. 

![Terminal Gui](https://user-images.githubusercontent.com/29312172/80289529-3891f380-873f-11ea-91ff-388a21fda7ce.gif)

![image](https://user-images.githubusercontent.com/29312172/80289536-434c8880-873f-11ea-8323-45ee2a3f484e.png)

Should I create a new issue for this??

Great lib :) 
Thanks in advice

**Comment by BDisp** [comment]
Hi, it's the normal behavior for now. It is not a bug. It has always been like that.
