### ISSUE TITLE
Chinese is displayed as overlapping

### ISSUE THREAD

**Issue by maikebing** [migueldeicaza/gui.cs#225]
```

   //Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
      //  Application.UseSystemConsole = true;
		Application.Init ();

```
![image](https://user-images.githubusercontent.com/3445167/60755238-780c1980-a01f-11e9-97bd-8465143ad10c.png)

```

   Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
     Application.UseSystemConsole = true;
		Application.Init ();

```

![image](https://user-images.githubusercontent.com/3445167/60755282-139d8a00-a020-11e9-84da-70749c2166e6.png)

But the mouse can't be used.

**Comment by chengts95** [comment]
Actually, the Chinese characters become squares in the latest version,
![image](https://user-images.githubusercontent.com/6616679/96216829-7decec00-0f3e-11eb-8386-265f70377d03.png)
They can be displayed correctly in v0.81.

**Comment by BDisp** [comment]
There is a bug in the code that not letting unicode to process if `Rune.ColumnWidth` is greater than 1. That the case of chinese characters. Since the chinese language has installed the chinese characters should be outputed. If the system don't don't recognize the charater let the SO output the default string, perhaps "?". I'll submit a PR to fix this.

![chinese-unicode](https://user-images.githubusercontent.com/13117724/96262052-2770c380-0fb9-11eb-86cc-57663b83c87f.png)

**Comment by BDisp** [comment]
Here a screenshot on the `Linux`.

![chinese-linux](https://user-images.githubusercontent.com/13117724/96272946-ad473b80-0fc6-11eb-881e-aeffb02101a5.png)

**Comment by BDisp** [comment]
On `Mac `I can print chinese on the prompt but not in the app. I think maybe is related with the #949.

![chinese-mac-terminal](https://user-images.githubusercontent.com/13117724/96279879-2cd90880-0fcf-11eb-80c2-4e6f15c87337.png)

![chinese-mac](https://user-images.githubusercontent.com/13117724/96279896-31052600-0fcf-11eb-860e-7ddc3f1d52a6.png)

**Comment by chengts95** [comment]
Nice Fix! Thanks, bro!

**Comment by chengts95** [comment]
Looks like typing Chinese is still a problem, I get nothing shown up on windows.

**Comment by BDisp** [comment]
Do you tried with my PR? If you did, do you have the chinese font installed?

**Comment by chengts95** [comment]
IME Input is not working, the display is ok.

**Comment by chengts95** [comment]
![image](https://user-images.githubusercontent.com/6616679/96355598-852c0b00-10a0-11eb-8bf6-db0cb6959e35.png)
The characters are shown in the menu bar, however, no Chinese character can be typed in login or demo text editor.

**Comment by BDisp** [comment]
Ah ok. I didn't test the input. I only did copy /paste. Well I never wrote Chinese before and I don't know if I can typed with my keyboard.  I will try.

**Comment by chengts95** [comment]
That only happens on Windows, on Ubuntu 20.04, it works well.
![image](https://user-images.githubusercontent.com/6616679/96356629-86fccb00-10ae-11eb-9cde-843fd79fc9a2.png)

**Comment by chengts95** [comment]
However,  in the text editor demo the typing becomes abnormal. I believe it is another issue for multi-byte characters in TextView.  The TextField is OK.
