### ISSUE TITLE
Is there any way to copy text to the clipboard?

### ISSUE THREAD

**Issue by timothyparez** [migueldeicaza/gui.cs#228]
Is there any way to copy text to the clipboard?
There is a `Clipboard` class but there's not much in there.

**Comment by migueldeicaza** [comment]
There is a managed API, but more importantly the text editor use the Emacs key bindings to move any deleted text (words, or to-end-of-line) into the clipboard, and you can access it again by pasting it (control-y)

**Comment by timothyparez** [comment]
I mean to do something like this:

`Clipboard.SetText("somepassword")`

Not text that the user selects and copies to the clipboard

**Comment by timothyparez** [comment]
What I want to do is copy text from a database to the Clipboard  
not from a text field but directly from the database to the Clipboard without displaying it on the screen.

**Comment by kasiaturbiarz** [comment]
I have the similar issue, any workarounds?
