### ISSUE TITLE
Spam issues are being posted?

### ISSUE THREAD

**Issue by tom-corwin** [migueldeicaza/gui.cs#239]
It seems that a bot spammed the following issues early this morning:

- #230
- #231
- #232
- #233
- #234
- #235
- #236
- #237
- #238

One of the titles translate to (via Google):
> King's College London did not graduate? Purchased a high imitation London King's College diploma, micro: jywenping quickly processed the London King's College graduation certificate transcript, returning to school qualifications,

**Comment by migueldeicaza** [comment]
Thanks for reporting - it looks like GitHub deleted them
