### ISSUE TITLE
I want to go back to normal Console Mode after using gui.cs as a login

### ISSUE THREAD

**Issue by YamanAlhalabi** [migueldeicaza/gui.cs#240]
I want to go back to normal Console Mode after using gui.cs as a login, and I may also need to start it again.

**Comment by migueldeicaza** [comment]
I do not understand what the problem is

**Comment by oSumAtrIX** [comment]
he wants to finalize/destroy the running application object and continue with the normal console

**Comment by tig** [comment]
I don't understand either.

See `Application.Init` and `Application.Shutdown`.

**Comment by tig** [comment]
Closing. @YamanAlhalabi if this is still a concern please reopen.
