### ISSUE TITLE
TimeField is not fully implemented

### ISSUE THREAD

**Issue by fstiffo** [migueldeicaza/gui.cs#246]
I'm using the NuGet package for version 0.24 in an F# (core 4.7) project , but TimeField view is no present. Any idea?

**Comment by kbilsted** [comment]
I have the same problem. So I cannot run the example from https://github.com/migueldeicaza/gui.cs/blob/master/Example/demo.cs 

The code is in the repo (https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Views/TimeField.cs) but inspecting the nuget it does not contain the type.

**Comment by tig** [comment]
Renamed Issue to reflect state of control.

See `UI Catalog` scenario to illustrate. See PR #475

**Comment by tig** [comment]
I think we're good here. Reopen if you don't think so.
