### ISSUE TITLE
Menu.ShortCut is not hooked up to anything

### ISSUE THREAD

**Issue by BarryNolte** [migueldeicaza/gui.cs#254]
Menu.ShortCut has no effect.  Looking at the code, it's never used. It can be set, but is never compared against anything so it can fire the MenuItem.Action.

**Comment by tig** [comment]
This has been refactored since. Closing.

**Comment by abiratur** [comment]
This issue is still valid.
there are no references to MenuItem.ShortCut.

i can try to work on a PR

**Comment by tig** [comment]
Reopening. Thanks.

**Comment by BarryNolte** [comment]
That’s one way to fix it 😊

**Comment by tig** [comment]
@BarryNolte - @BDisp worked hard to implement this feature over the past week. However, the number and complexity of changes required was deemed too big right before the release of 1.0. It would have delayed it significantly. 

If there is demand for this feature, please open a new issue to request it, indicating the use-cases that are important. We can then consider it post 1.0.
