### ISSUE TITLE
Buttons capture focus and stop responding to mouse events

### ISSUE THREAD

**Issue by bryancostanich** [migueldeicaza/gui.cs#257]
If i have a button on my window and click it with a mouse, everything is hunky dory, my message box displays:

```csharp
top.Add(_actionButton);
_actionButton.Clicked = () => {
    this.ShowClicked();
};
```

...

```csharp
protected void ShowClicked()
{
    var n = MessageBox.Query(50, 7, "Clicked", "Button was clicked.", "OK!");
}
```

but after dismissing my message box, the button retains focus, and if i click it again with the mouse, nothing happens. however, if I hit *space bar*, it clicks the button again. I can't seem to "unselect" the button. 

repro attached.

[TerminalGui_ListRowView.zip](https://github.com/migueldeicaza/gui.cs/files/3571516/TerminalGui_ListRowView.zip)

**Comment by tig** [comment]
Fixed somewhere along the line. Closing.
