### ISSUE TITLE
.NET Standard 2, NuGet Package

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#26]
Need to make a .NET Standard 2 library out of a this, and a NuGet package.

Desired:

[x] Link the  mono-curses files directly, to reduce dependencies
[x] Link Mainloop directly, same reason

Challenges:

* Moving to .NET Standard means the main application will end up pulling some 99 assemblies, unless we switch it to .NET Core.  Either option is slower.

* There is a bug in P/Invoke against poll that renders the results of poll unusable.

**Comment by jamesharling** [comment]
Any ETA on a NuGet package for this? It would be very useful!

**Comment by migueldeicaza** [comment]
No ETA, more details here: https://github.com/migueldeicaza/gui.cs/pull/39

**Comment by migueldeicaza** [comment]
Alternative to netstandard: use multi targeting and build desktop and netapp library packages

**Comment by migueldeicaza** [comment]
While I have checked in the support for netcore packages, I do not seem to be able to consume it.

**Comment by migueldeicaza** [comment]
Solved
