### ISSUE TITLE
Progress dialog scenario

### ISSUE THREAD

**Issue by adalon** [migueldeicaza/gui.cs#260]
Given a progress dialog containing:

- A ListView for output details and
- A ProgressBar to show the complete %

Which it's going to be updated from a worker/background thread,
what would it be the best way to show the dialog?

It seems Application.Run(dialog) should be executed in the main loop
to avoid errors but I'm not getting any UI updates. And if I do Application.Run
from a worker thread I'm getting the following error randomly when clicking on
anywhere but the progres is shown correctly:

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key '637038121364968052' was not present in the dictionary.
   at System.Collections.Generic.SortedList`2.get_Item(TKey key)
   at Mono.Terminal.MainLoop.RunTimers()
   at Mono.Terminal.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view)
```

Looping @kzu @migueldeicaza

**Comment by migueldeicaza** [comment]
Application.Run is the way to show the dialog.

What you probably are running into, is that you are calling the toolkit from a background thread, which is not allowed (this is a property of almost every UI toolkit, as the complexity of doing this is too high). 

What you need to do is use the Invoke method on Application.MainLoop which will trigger the code to update the UI to be executed on the main thread.

**Comment by migueldeicaza** [comment]
This document covers this:

https://migueldeicaza.github.io/gui.cs/articles/mainloop.html
