### ISSUE TITLE
Text only / Numeric only

### ISSUE THREAD

**Issue by worksofliam** [migueldeicaza/gui.cs#265]
Is there a way to implement text-only or numeric-only input fields?

Has anyone does this before?

Thanks

**Comment by stanac** [comment]
Artificial example, does not handle copy/paste

```csharp
class Program
{
    static void Main(string[] args)
    {
        Application.Init();
        var win = new Window("window");
        Application.Top.Add(win);
        win.Add(new NumbersOnlyTextField(0, 0, 25, ""));
        Application.Run();
    }
}

public class NumbersOnlyTextField: TextField
{
    public NumbersOnlyTextField(string text) : base(text)
    {
    }

    public NumbersOnlyTextField(NStack.ustring text) : base(text)
    {
    }

    public NumbersOnlyTextField(int x, int y, int w, NStack.ustring text) : base(x, y, w, text)
    {
    }

    private readonly int[] _acceptableKeyValues = new int[] { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' };
    private readonly Key[] _acceptableKeys = new Key[] { Key.Backspace, Key.Delete, Key.CursorLeft, Key.CursorRight, Key.DeleteChar };

    public override bool ProcessKey(KeyEvent kb)
    {
        if (_acceptableKeys.Contains(kb.Key) || _acceptableKeyValues.Contains(kb.KeyValue))
        {
            return base.ProcessKey(kb);
        }
        return true;
    }
}
```

You could for example pass list of acceptable keys/key-values in the constructor to handle different cases, also you could look at the source of `TextField` to see what cases should be passed to base class to handle copy/paste, selection, ...

**Comment by worksofliam** [comment]
Hi @stanac 

Thanks for this great example. This answers a lot of my follow up questions too, so appreciate it.

By any chance, would you know how I might go about underlining fields too? Is that even possible?

Thanks!

**Comment by stanac** [comment]
Hi @worksofliam I'm not sure what do you mean by "underlining fields". Underlining text label or ... ?

**Comment by worksofliam** [comment]
Hey @stanac 

Sorry I should have been more specific. Yes, underline for an input `TextField`

```csharp
new TextField ("") {
  X = field.Position.X, Y = field.Position.Y,
  Width = field.dataType._Length,
  Height = 1
};
```

Thanks

**Comment by stanac** [comment]
I don't think it's possible, I am not sure if any framework has that option in the text input (including basic html). You could change color scheme by overriding `Redraw` of `TextField`, if you look at the [source of redraw](https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Views/TextField.cs#L148) you could see method is setting color scheme, if you set it to something else it could be a kind of highlighting the text in the field.

Also `Label` has `TextColor` field which can be set to custom value, if that helps.

**Comment by worksofliam** [comment]
Thanks for the info. You did solve my original issue so I will close this for now.

Thanks for your help!
