### ISSUE TITLE
TextField with predefined text does not act as expected

### ISSUE THREAD

**Issue by stanac** [migueldeicaza/gui.cs#267]
Windows 10 x64, .net core 2.2

Issue, when `TextField` is added with predefined text and user types in it, original text will be lost (replaced).

Repro code:

```csharp
class Program
{
    static void Main(string[] args)
    {
        Application.Init();
        var win = new Window("window");
        Application.Top.Add(win);
        win.Add(new TextField(0, 0, 25, "test"));
        Application.Run();
    }
}
```

Repro gif:

![2](https://user-images.githubusercontent.com/8450675/65535816-70fbf580-df02-11e9-93b1-f11a4206556c.gif)

The problem is in `ProcessKey` method of `TextField` in default case field `used` is set to false, once this field is set to true (by pressing e.g. right array key) value will not replaced.

```csharp
default:
	// Ignore other control characters.
	if (kb.Key < Key.Space || kb.Key > Key.CharMask)
		return false;

	var kbstr = TextModel.ToRunes (ustring.Make ((uint)kb.Key));
	if (used) {  // <<< THIS FIELD
		point++;
		if (point == text.Count) {
			SetText (text.Concat (kbstr).ToList ());
		} else {
```

Override `HasFocus` like in the code below seams to solve the problem.

```csharp
public override bool HasFocus
{
    get { return base.HasFocus; }
    internal set
    {
        base.HasFocus = value;
        if (value) used = true;
    }
}
```

I am not sure if this change has any undesired side effects.

Should I send a PR?

**Comment by BDisp** [comment]
You are not initiating the TextField view in the right way if you want used the text declared already in the constructor. In that case you should use this:	
var txt = new TextField ("test") {
	Used = true
};

**Comment by stanac** [comment]
@BDisp thanks, I'll try that

**Comment by BDisp** [comment]
@stanac or using your example with in a single line:
win.Add (new TextField (0, 0, 25, "test") { Used = true });

**Comment by tig** [comment]
No repro anymore. Closing.
