### ISSUE TITLE
TextView: Does not support \r\n (renders as \r as square box on Windows)

### ISSUE THREAD

**Issue by kzu** [migueldeicaza/gui.cs#279]
With the default Windows driver (default init), adding newlines to TextView renders as follows:

![image](https://user-images.githubusercontent.com/169707/67626496-27ad0780-f81a-11e9-9268-8cd2a06a6c31.png)

**Comment by Mashrien** [comment]
For me, it displays as a musical note (different font I'm assuming)

Is there an easy fix to TextView class for this? I'm currently digging around in it trying to find out how it's registering/displaying 0x13 (the newline character)

**Comment by Mashrien** [comment]
Replication is very simple:
textView.Text += Environment.Newline + "text";

Repeat that a few times.. it also seems to duplicate the 0x13 char in-place any time it's rendered.

**Comment by kbilsted** [comment]
What should be rendered ? We can trim \r and \n . It will improve the case a line ends with a newline.

But how should a multiline text be handled ? Say a text with 3 x 80 characters.

**Comment by Mashrien** [comment]
I don't understand the confusion..
Newline's shouldn't render as a character- When a newline is found, just move down to the next line and continue printing characters?. I've tried trimming \r and \n, even tried Regex.Replace("\n+", "") to remove duplicates, but they (newline symbols, ♪) still appear after successive inputs.

`♪
some example text♪
this isn't how to render a newline♪
lol, hope this shows the problem♪
`

**Comment by Mashrien** [comment]
A temporary solution is to remove the '\r' from your newlines, and only display the '\n'
(On Windows, a newline is two characters, 0x0D 0x0A. The TextView is rendering 0x0D as a literal character, rather than treating it as a proper new line, just remove 0x0D (byte 13) from your text, leaving ONLY the 0x0A (byte 10) before sending to TextView.

string = Regex.Replace(string, "\r", "");
textView.Text = string;

**Comment by kbilsted** [comment]
There could be a confusion when the field has a height of 1 and containing multi line content

**Comment by Mashrien** [comment]
No.. It's a multiline box, height approximately 12 characters. Each time a line is inserted it adds another ♪ to the previous lines where a newline should be..

![shot3](https://user-images.githubusercontent.com/29497715/69746934-06865200-110b-11ea-819a-ff66600a1ea4.png)
![shot4](https://user-images.githubusercontent.com/29497715/69746941-09814280-110b-11ea-9189-4ebbeaac2f4f.png)

**Comment by tig** [comment]
I fixed this in `Label` in #605 

It still needs to be fixed in `TextView` and `TextField`.

**Comment by Mashrien** [comment]
Appreciate you fixing it in Label. :)
I had cobbled together a workaround locally that produced the desired results, however it's been long enough I can't remember what I had to do to get it to work lol

**Comment by tig** [comment]
I'll get to TextView asap. Thanks.

**Comment by BDisp** [comment]
Fixed by the PR #1025.
