### ISSUE TITLE
ListView renders cursor

### ISSUE THREAD

**Issue by kzu** [migueldeicaza/gui.cs#280]
Even if there's nothing to type in a listview :)

![Cursor](https://user-images.githubusercontent.com/169707/67626520-6216a480-f81a-11e9-9d89-d218183ef14c.gif)

**Comment by BDisp** [comment]
I really don't know if the cursor can be hidden in the `Gui`, without overshadowing the color.

**Comment by tig** [comment]
Fixed somewhere along the line.
