### ISSUE TITLE
After running app and exiting app, random text is displayed in console

### ISSUE THREAD

**Issue by JamesLoyd** [migueldeicaza/gui.cs#281]
When I run the app, via dotnet run in a terminal on Ubuntu, I run into an issue that right after I exit the program via F9, I get weird text in my terminal view.

And, the more I move my mouse in it, the more it shows. The only solution I have found is to close the current terminal. 

I am not exactly sure why this is happening. Even, if I completely use my keyboard and move my mouse over it, the same random text displays.

I have noticed this in Sensible-i3-term, tilix, and sakura.

I have included an image of the text that is randomly generated.

![image](https://user-images.githubusercontent.com/1821671/67767836-af1b9600-fa27-11e9-882b-4771e29202f7.png)

**Comment by JamesLoyd** [comment]
I think the solution is to inform ncurses to refresh the current terminal view after exiting.
When, I did a reset, it fixed the issue and no more random text is generated when I mouse over it.

**Comment by domints** [comment]
You probably close your app via `System.Environment.Exit(0)`, which sounds reasonable, but doesn't let Terminal.Gui properly restore ncurses state (call `Curses.endwin()` method). 

I resolved this problem by calling `Application.Driver.End();` before killing the app - it still feels like it's not the cleanest way, but the best I have now. 

I'm not sure how to properly close an app using for example menu, when having multiple views open...

**Comment by JamesLoyd** [comment]
I usually have it run as a self-hosted .net core app. So I think it uses: `System.Environment.Exit(0)` under the hood?

**Comment by domints** [comment]
Self-Hosted .NET Core console app? That’s first time I hear about such solution. What do you mean?
Anyway, maybe you have some way to inject your code on application exit to restore ncurses state.

**Comment by JamesLoyd** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1

In case this is relevant to fixing it.

**Comment by domints** [comment]
So you’re using both web-app and console interface in single application? Guess that’s quite unusual combination :) 

Guess you still should have `Program.cs` with method `Main`.
You could add `Application.Driver.Exit()` in `Main` method after you call `Run()` on your `Host`. This piece of code should be executed after application stops.

**Comment by JamesLoyd** [comment]
No, its a generic host, it uses the console lifetime versus the web-app.

I think I need to call it at StopAsync() in my hosted service hook.

**Comment by migueldeicaza** [comment]
You should not call Environment.Exit() because this does not properly reset the terminal settings as you just observed.   We need to tell the terminal to stop sending the mouse movement escape sequences, as well as restoring the proper buffer (Alt vs Normal) and the application keypad mode among other things.

So yes, if you call Environment.Exit() you will be shooting yourself in the foot.

**Comment by darthwalsh** [comment]
On dotnet 5.0.100 MacOS iTerm, with current release version `0.90.3` the [official doc's recommended sample](https://migueldeicaza.github.io/gui.cs/articles/overview.html):

```csharp
  static int Main(string[] args) {
    Application.Init();
    var n = MessageBox.Query(50, 7, "Question", "Do you like console apps?", "Yes", "No");
    return n;
  }
```

causes the same garbage on mouse movement. Same problem for the other two samples. (To be fair the second sample with just a label doesn't offer any way to gracefully shut down and I sent a SIGKILL.) On the third sample clicking Quit is calling `Application.RequestStop()` and yet still leaves my console with garbage from the mouse.

Maybe in .NET 5 after `Main()` returns the process shutdown is too aggressive and the driver cleanup didn't get a chance to run?

A workaround is to include `Application.Driver.End();` in a try-finally in `Main()` -- should that line be in the official docs?

**Comment by BDisp** [comment]
Calling `Application.Shutdown()` is more recommended than calling `Application.Driver.End()`, because the first does all the cleaning needed including calling the Driver?.End().
Unfortunately, with `Net5.0` the `Unix` isn't restored properly, even stopping sending mouse events escapes sequences. I think, someway `Net5.0` is wrongly restoring the terminal again after the application exit.
