### ISSUE TITLE
Repaint Issue

### ISSUE THREAD

**Issue by Scordo** [migueldeicaza/gui.cs#282]
Hello,

I've found an issue where the RadioGroup-Control does not repaint correctly. Here is the code to reproduce it:

```csharp
Application.Init();

Window window = new Window("Repaint Issue") {X = 0, Y = 0, Width = Dim.Fill(), Height = Dim.Fill()};
RadioGroup radioGroup = new RadioGroup(1, 1, new[] { "Short", "Longer Text  --> Will not be repainted <--", "Short" });

Button replaceButton = new Button(1, 10, "Replace Texts above")  {
    Clicked = () => { radioGroup.RadioLabels = new string[] { "Longer than before", "Shorter Text", "Longer than before" }; }
};

window.Add(radioGroup, replaceButton);
Application.Top.Add(window);
Application.Run();
```

The "--> Will not be repainted <--" will not be repainted with "blanks".
I think there are more issues with repainting especially when replacing SubViews and so on.

Regards,
Jens

**Comment by BDisp** [comment]
This commit https://github.com/migueldeicaza/gui.cs/pull/269/commits/eded3758402e1f76d061ffc84206dbcf038ae71f fixes this issue

**Comment by Scordo** [comment]
Hi,

thanks for the fix. When will this be available with the next nuget package?
Currently I do have to call Application.Refresh to workaround it, which is really bad.

Regards,
Jens

**Comment by BDisp** [comment]
That is with Miguel

**Comment by acuntex** [comment]
I second that, can't wait for a release :-)

**Comment by rychlym** [comment]
Hello,
 I am not sure whether it has something to do with this. I have encountered troubles when updating a certain Label within a ScrollView in time of a button handler execution. 
I have following ScrollView: 
`            
var infoView = new ScrollView(new Rect(1, 1, 40, 20))
{
                ContentSize = new Size(80, 40),
                ContentOffset = new Point(1, 1),
                ShowVerticalScrollIndicator = true,
                ShowHorizontalScrollIndicator = true
};
`
Then added several labels. After updating one  of the lablel's text  only the label text is shown and all other labels disappear including the ScrollView's scroll bars  itself. (The whole content appears again bu clicking to menu, which overrides the area of the ScrollView.)
