### ISSUE TITLE
ListView not Allowing Selection

### ISSUE THREAD

**Issue by Giss47** [migueldeicaza/gui.cs#289]
In your Terminal example code, ListView with AllowMarking value is True renders checkboxes and return mark values in the list, Source.IsMarked. I use your Nuget and the ListView with AllowMarking set to True doesn't do anything. No checkbox beside list fields show up at all.

**Comment by Falthazar** [comment]
Had the same issue. Looks like the version on github is .25, but it's not on nuget yet. See:
https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Terminal.Gui.csproj
In release notes you can see:
0.25: **Added new TimeField from Jörg Preiß;** 
Fixes for Backtab by Martin Björkström;  
**ListView now supports simple selection;**  
Bug fixes by giladlevi, Daniel Cazzulino and Marius Ungureanu;  
New Application.Run of T entry point by Daniel Cazzulino;   
Added various View methods to bring forward, backwards and move views in the hierarchy;  
Switch to Portable PDBs by Daniel Cazzulino;  
Dims can now be compared by Daniel Cazzulino; OnMenuOpen handler by giladlevi;  
Various memory usage optimizations by giladlevi;  
FileDialog.FilePath is now a full path by Yanwei Wang;  
ISupportInitialize/ISupportInitializeNotification is now supported thanks to the work from Daniel Cazzulino; 
Support for non-modal TopLevels by Daniel Cazzulino and Adrian Alonso;

**Comment by tig** [comment]
I believe this is fixed. Closing.
