### ISSUE TITLE
Is there a functional example not just a controls demo?

### ISSUE THREAD

**Issue by gitblit** [migueldeicaza/gui.cs#305]
I'm very excited to create a few CLI utilities using this library (especially since Core 3 gives us the beginnings of single EXE deployment) but I am not sure how best to layout the code.

The bundled example is somewhat helpful to get an idea how to build the main UI, but is not as helpful when building something more sophisticated with dialogs, wizards, or background IO/tasks. 
 Some of this information can be found by mining the issues or PRs.  Please don't think I am complaining (too much)  :).  I admire your work, but I want to understand how to harness it.

Are there any examples (maybe community tools built using gui.cs) which demonstrate doing something real and might be recommended for patterns/architectures/techniques?

**Comment by Scordo** [comment]
Hi,

there is a "Used by" Button on top of this page, where you can see projects using this library.
Just have a look at the most starred projects how they use the lib:

https://github.com/migueldeicaza/gui.cs/network/dependents?package_id=UGFja2FnZS0xNTg1ODA4MzM%3D

**Comment by migueldeicaza** [comment]
Wow, I did not know about this "used by" feature - that is so cool!

**Comment by migueldeicaza** [comment]
@gitblit I would love to add more samples and documentation to address any specific questions you have.

**Comment by kbilsted** [comment]
@migueldeicaza  One simple example is an application with several "screens" - eg 
* a master view holding a list of entries 
* and detail view showing a particular entry 
* and a create screen creating a new entry

**Comment by gitblit** [comment]
That's a great list.  Even better to pair those screens with some async IO and not just an in-memory/singleton provider.  Maybe hit the Github API and show the list of open issues or open PRs in this repo?

**Comment by tig** [comment]
PowerShell core now has a `Terminal.gui` based cmdlet: `Out-ConsoleGridView`. 

```powershell
PS> Install-Module Microsoft.PowerShell.ConsoleGuiTools
PS> ls | out-consolegridview
```

The code is here: https://github.com/PowerShell/GraphicalTools here:

https://github.com/PowerShell/GraphicalTools/blob/master/src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs

**Comment by migueldeicaza** [comment]
Oh this is delightful!

**Comment by migueldeicaza** [comment]
Got a screenshot to share on twitter?

**Comment by tig** [comment]
> Oh this is delightful!

Just wait until my PRs to make it better get accepted (after the ones I've added to `Termina.gui` get accepted). The key is the current version is way too hard to exit out of.

**Comment by tig** [comment]
`UICatalog` is merged. Closing this issue. If there are scenarios you want added to `UICatalog` open a new issue with a title prefixed by "UI Catalog: ". Thanks.
