### ISSUE TITLE
Changing colors using `ColorScheme` makes cursor disappear

### ISSUE THREAD

**Issue by kbilsted** [migueldeicaza/gui.cs#308]
To reproduce modify the demo code of the project to

       var loginText = new TextField("")
        {
            X = Pos.Right(password),
            Y = Pos.Top(login),
            Width = 40,
            ColorScheme = new ColorScheme()
            {
                Focus = Attribute.Make(Color.BrightYellow, Color.DarkGray),
                Normal = Attribute.Make(Color.Green, Color.BrightYellow),
                HotFocus = Attribute.Make(Color.BrightBlue, Color.Brown),
                HotNormal = Attribute.Make(Color.Red, Color.BrightRed),
            },
        };

the textfield goes gray but the cursor disappears.

I am using windows

**Comment by BDisp** [comment]
![CursorGray](https://user-images.githubusercontent.com/13117724/69186956-7eec8200-0b11-11ea-8f68-04a54de649e2.png)

@kbilsted although gray I can see the cursor as shown in the attached image. And I am using windows too.

**Comment by kbilsted** [comment]
On my end

![image](https://user-images.githubusercontent.com/1616338/69190680-33da6b00-0b21-11ea-8f3f-fc05c5d7ffe8.png)

Im using the gui.cs directly rather than the nuget since the nuget is missing some definitions

**Comment by BDisp** [comment]
I am using the gui.cs with all updates, including mine. By the way, can you test with my 'textfield-text-selection' branche and check if it still happens, please?

**Comment by kbilsted** [comment]
@BDisp  thanks for your screenshot. I think you are forgetting, it still changes the existing behaviour from a very noticeable cursor to an invisible or near-invisible one.

**Comment by BDisp** [comment]
@kbilsted you're welcome. But this color behavior is from your demonstration. I just made color changes in two situations:
Menu item disabled and text selection as per images. Greetings.

![menu-item-disabled](https://user-images.githubusercontent.com/13117724/69263099-8fa60200-0bbc-11ea-89c7-86b9be141d90.png)
![text-selection](https://user-images.githubusercontent.com/13117724/69263101-8fa60200-0bbc-11ea-8769-9d99ddfb4e80.png)

**Comment by kbilsted** [comment]
@BDisp I'm not sure what you are trying to say, why are you bringing menus into the discussion? The problem is to do with

1. the cursor shows which component has focus
2. data entry and manipulation highly benefit from easily knowing the position of the cursor

Using the standard color scheme we get a nice red cursor that helps with both 1 and 2. Thinking of it, perhaps it would be useful to have the color scheme also define a cursor color. 

I don't see the same requirements for menu items. 

ps. I'm not trying to "shoot" you.

**Comment by BDisp** [comment]
@kbilsted I'm sorry, I thought you were referring to something I had sent. After all, you were demonstrating new features. I really didn't care about the cursor but I think it's a good idea, sometimes there are situations where it is disadvantageous to have the cursor visible and any improvements you make are welcome. I'm sorry again for the misunderstanding. Thanks.

**Comment by tig** [comment]
Can we close this issue?

**Comment by BDisp** [comment]
I think you can.
