### ISSUE TITLE
Control: HotLabel

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#31]
A hotlabel, is just a label but it has the following properties:

* It uses hot-strings so that the hot-letter can be used as a hotkey
* Is linked to another View that can be focused
* Responds to the hotkey and when pressed, focuses the provided view.

Should this just be folded into the regular Label?

**Comment by Slesa** [comment]
I don't think the naming is optimal. What should a 'label' without a linked view be if not some static text called TextBlock or similar. So both, Label and HotLabel or simply StaticText and Label, are needed.
