### ISSUE TITLE
Make `ListWrapper` public so it can be used by consumers

### ISSUE THREAD

**Issue by timothyparez** [migueldeicaza/gui.cs#313]
Currently if you want to assign an `IList` to `Source` have to use the `SetSource` method  
because the `SourceProperty` is actually of type `IListDataSource`.

But when implementing DataBinding that means you need to convert `IList` to `IListDataSource`  
and you do this by wrapping the `IList` into an `IListDataSource` implementation.

For example, here I define 2 bindings, one for a `Label` the other for a `ListView`

    var ustringConverter = new UStringValueConverter();
    var listWrapperConverter = new ListWrapperConverter();

    var labelBinding = new Binding(this, "Text", label2, "Text", ustringConverter);
    var listBinding = new Binding(this, "Heroes", listView, "Source", listWrapperConverter);

Looking at the code for the converter:

    public class ListWrapperConverter : IValueConverter
    {
        public object Convert(object value, object parameter = null)
        { 
            var wrapper = new CustomListWrapper((IList)value);
            return wrapper;            
        }
    }

All it does it wrap the `IList` into a `CustomListWrapper` instance.  
But this `CustomListWrapper` class is just a 1:1 copy of the internal `ListWrapper` class.
Id would be nice to just write `var wrapper = new CustomListWrapper((IList)value);`

**Comment by kbilsted** [comment]
I think if you override `ToString()` on your list element types you can do without the ListWrapper class

**Comment by timothyparez** [comment]
@kbilsted not sure we are talking about the same thing.
I may not have explained it properly.

Imagine we have a `List<Person>` called `people` and a `ListView` called `theList`.
   
     //This way, the render process will call ToString() on every instance of Person
     theList.SetSource(people); 

So to customize what gets rendered, you can just override `ToString()` that is true.

I`m creating a `Binding` class which takes 
 - a `Source` instance of type `object`
 - a `SourceProperty` property of type `string`
 - a `Target` instance of type object
 - a `TargetProperty` property of type `string`
 - an optional instance of `IValueConverter` 

When the `Source` value is changed the `Target` is updated by setting the `TargetProperty`
on the `Target`:
    
    var targetProperty = Target.GetType().GetProperty(TargetPropertyName);                 
    targetProperty.SetValue(Target, finalValue);   
  
Since the `Binding` does not know the difference between a `Label` and a `ListView` it does not  
know about `ListView.SetSource(IList source)` so it tries to `ListView.Source = value;`  

But the type of `ListView.Source` is `IListDataSource` so a `IValueConverter` is required:

    public class ListWrapperConverter : IValueConverter
    {
        public object Convert(object value, object parameter = null)
        {
            var wrapper = new CustomListWrapper((IList)value);
            return wrapper;            
        }
    }

And since `ListWrapper` is a private subclass I cannot just pass a new instance of it.  
Instead I had to copy the source code to `CustomListWrapper`.

**Comment by kbilsted** [comment]
+1 I was too fast :)

**Comment by migueldeicaza** [comment]
The PR has been merged
