### ISSUE TITLE
Is there something like a FrameView but without the frame around it?

### ISSUE THREAD

**Issue by OverMatto** [migueldeicaza/gui.cs#316]
So basically I was trying to make something like a status bar in the bottom of the window. I decided not to use Window, or FrameView, because I don't want it to have a frame around itself. I tried to use the View class, but it wasn't displayed (labels I tried to add to it weren't also displayed). Finally I decided to use a Label that I simply added to the Application.Top.
```C#
static Label StatusBar = new Label("There it is"){
            Y = Pos.AnchorEnd()-1,
            Width = Dim.Fill(),
            Height = 1,
            ColorScheme = AppCS,
};
```
While I was writing this message I realised that I can just add more components there by making their width smaller, but I'm still curious how can I make what I wanted to do before.

(Sorry if it has a simple answer, I'm a beginner)

![image](https://user-images.githubusercontent.com/48324005/69915930-e4ffd000-1454-11ea-8512-1bab12f7fddd.png)

By the way, is it normal that there is a black line under the content I inserted?

**Comment by tig** [comment]
Dupe: #519
