### ISSUE TITLE
Clicking on control does not close menu

### ISSUE THREAD

**Issue by FraserElectronics** [migueldeicaza/gui.cs#319]
Using the sample code, if I drop down the Edit menu then click on the Password textbox, the password text appears on top of the menu. I think when a control gains focus, the menu should collapse?

Andy

**Comment by BDisp** [comment]
Test with this branche https://github.com/BDisp/gui.cs/tree/menu-with-submenus

**Comment by FraserElectronics** [comment]
Yep that works :-)
Sorry if this issue was covered previously, could not see anything.

Andy
