### ISSUE TITLE
Key handling

### ISSUE THREAD

**Issue by rueckertch58521** [migueldeicaza/gui.cs#322]
Hi everyone,

I found this nice UI and would like to use it. While doing some coding some things went fine other not. 

Right now I'm struggling with the KeyEvent handling. Is there any sample that shows how to implement a KeyEvent (I don't know if this is the correct term for this).

Use Case:
I have a label and when I hit a **Key**, let's say "Key.ControlB" I would like to change the Text of this label.

Any idea how to achieve this?

Thanks in advance =)

**Comment by BDisp** [comment]
@rueckertch58521 here is a sample:

```
public static void Main (string [] args)
{
	Application.Init ();

	Window window = new Window ("Sample button click event") { X = 0, Y = 0, Width = Dim.Fill (), Height = Dim.Fill () };
	string strLonger = "Button with a long text";
	Label label = new Label (3, 2, "abcdef");
	Button button = new Button (1, 5, strLonger);
	button.Clicked += () => {
		//When the button is 'clicked' the following is executed
		if (button.Text != strLonger) {
			button.Text = strLonger;
			label.Text = "abcdef";
		} else {
			button.Text = "Small text";
			label.Text = "012";
		}
	};

	window.Add (button, label);
	Application.Top.Add (window);
	Application.Run ();
}

```

**Comment by rueckertch58521** [comment]
Thx for your answer. 

Ups, there was a mistake in my description. My fault.

Correct Use Case:
I have a label and when I hit a **Key,**  let's say "Key.ControlB" I would like to change the Text of this label.

**Comment by BDisp** [comment]
@rueckertch58521 in this case here it is:

`class MyWindow : Window {
	public Action ControlB_Pressed;

	public MyWindow () : base ("Key event")
	{
	}
	public override bool ProcessKey (KeyEvent keyEvent)
	{
		if (keyEvent.Key == Key.ControlB) {
			if (ControlB_Pressed != null) {
				ControlB_Pressed.Invoke ();
				return true;
			}
		}
		return base.ProcessKey (keyEvent);
	}
}

class MainClass {
	public static void Main (string [] args)
	{
		Application.Init ();

		var myWindow = new MyWindow () {
			X = 0,
			Y = 0,
			Width = Dim.Fill (),
			Height = Dim.Fill ()
		};

		Label label = new Label (3, 2, "abcdef");
		myWindow.ControlB_Pressed += () => {
			//When the Ctrlkey+B is 'pressed' the following is executed
			if (label.Text != "abcdef") {
				label.Text = "abcdef";
			} else {
				label.Text = "012";
			}
		};

		myWindow.Add (label);
		Application.Top.Add (myWindow);
		Application.Run ();
	}

}
`

**Comment by rueckertch58521** [comment]
Perfect! thank you very much
