### ISSUE TITLE
Application.Run() NullReferenceException

### ISSUE THREAD

**Issue by flipchart** [migueldeicaza/gui.cs#323]
Getting the following after running the app for a while:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Terminal.Gui
  StackTrace:
   at Mono.Terminal.MainLoop.RunIdle()
   at Mono.Terminal.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view)
   at Terminal.Gui.Application.Run()
```

Application uses a long running thread which updates the Gui.cs views (via `Application.MainLoop.Invoke`). Before you ask: I need to use threads because I need a larger-than-normal stack size.

**Comment by BDisp** [comment]
Can you please provide a demonstration of how you get this exception?

**Comment by tig** [comment]
Ancient with no repro. Closing.
