### ISSUE TITLE
Gui.cs  in browser ?

### ISSUE THREAD

**Issue by dubo** [migueldeicaza/gui.cs#324]
Hi,  would be possible run gui.cs app  in browser compiled to Webassembly ?   ( using e.g. https://itnext.io/run-c-natively-in-the-browser-through-the-web-assembly-via-mono-wasm-60f3d55dd05a   )

**Comment by BDisp** [comment]
@dubo, I don't think so. As you can see the output in html is displayed in a text area. If you have a UI with textview, labels, etc ... written in guis.cs, you have to turn them to html controls, so this adaptation is not automatic. But I may be wrong, so if what I said is a big mistake, I'm sorry.

**Comment by ebekker** [comment]
The output for Gui.cs is a stream of terminal characters and control characters.  You can target something like [xtermjs](https://xtermjs.org/) for browser output to render it in a fixed sized terminal window in the browser.  I think the Gui.cs architecture supports different output _drivers_ to enable cross-platform support (e.g. Windows vs. Linux) so this could just be a different driver that targets xtermjs or something similar for running in the browser.

**Comment by grahamehorner** [comment]
@dubo #Blazor may be of interest to you; blazor has a rendering engine that can be replaced and therefore a compliable gui.cs rendering engine could in theory translate the stream of terminal charaters into HTML dom elements/events

**Comment by migueldeicaza** [comment]
Closing the issue - the comments are correct, this would require a terminal emulator on top of things.
