### ISSUE TITLE
Any idea when the next version will be released?

### ISSUE THREAD

**Issue by TylerLeonhardt** [migueldeicaza/gui.cs#328]
What's in master has several crucial bug fixes for `ListView` that I need. I'd really like to pull this in via a NuGet package instead of something else. Thanks - this library is incredible!

**Comment by domints** [comment]
+1 on this.

@migueldeicaza , Would you mind releasing 0.25 to nuget? Changelog claims it has some performance optimisations and that would always be welcome :)

**Comment by TylerLeonhardt** [comment]
It happened!
