### ISSUE TITLE
feature request: ListView should allow clickable checkboxes when `AllowMarkings` is set

### ISSUE THREAD

**Issue by TylerLeonhardt** [migueldeicaza/gui.cs#329]
Consider this small piece of code:
```csharp
var list = new ListView(items)
            {
                X = 3,
                Y = 3,
                Width = Dim.Fill(2),
                Height = Dim.Fill(2),
                AllowsMarking = true
            };
```

![image](https://user-images.githubusercontent.com/2644648/74377867-a57d2a80-4d99-11ea-9628-eb21519c12be.png)

I would like to be able to click on the empty box and an "X" appears like so:
![image](https://user-images.githubusercontent.com/2644648/74377913-bc238180-4d99-11ea-9910-325deaa915f4.png)

It seems I can click on a list item and it becomes highlighted, but I can't seem to mark it.

**Comment by BDisp** [comment]
I believe that this issue is resolved by this pr https://github.com/migueldeicaza/gui.cs/pull/302

**Comment by TylerLeonhardt** [comment]
Awesome! Hoping that can get in before the next release :)

**Comment by migueldeicaza** [comment]
The PR has been merged, thanks!
