### ISSUE TITLE
How do I open the menu bar items via the keyboard?

### ISSUE THREAD

**Issue by TylerLeonhardt** [migueldeicaza/gui.cs#336]
It seems like clicking doesn't seem to work on Windows for the menu bar so how do I open a menu bar item via the keyboard.

example... how do I open `Options`:

![image](https://user-images.githubusercontent.com/2644648/75743934-9b2ebc00-5cc7-11ea-9b5d-c75e3290454c.png)

The code is:
```csharp
            var menu = new MenuBar(new MenuBarItem []
            {
                new MenuBarItem("_Options", 
                    new MenuItem []
                    {
                        new MenuItem("_Accept", "", () => { if (Quit("Accept", ACCEPT_TEXT)) top.Running = false; }),
                        new MenuItem("_Cancel", "", () => { if (Quit("Cancel", CANCEL_TEXT)) _cancelled = true; top.Running = false; })
                    })
            });
```

I would have guessed that pressing `O` would have worked.

**Comment by BDisp** [comment]
From Demo.cs: "Press F9 (on Unix, ESC+9 is an alias) to activate the menubar"

**Comment by BDisp** [comment]
> It seems like clicking doesn't seem to work on Windows for the menu bar

By the way clicking is working on Windows for the menu bar.

**Comment by TylerLeonhardt** [comment]
Thanks @BDisp! I think we can close this issue now that you've answered my question.

Im curious which terminal you were using. I believe I tried Windows Terminal and Conhost and neither seemed to work... Maybe I just need to try again with latest.

**Comment by BDisp** [comment]
You welcome. I'm using Windows Command Prompt and Windows PowerShell in Windows 10. Only you can close this issue :)
