### ISSUE TITLE
How to use Application.MainLoop correctly

### ISSUE THREAD

**Issue by rueckertch58521** [migueldeicaza/gui.cs#341]
Hi,

I am programming a process window for a test runner. To visualize all the information I am using your GUI. I figured a way out to constantly update my window but I am not quite sure if I do it as it's supposed to. 

this is where I set the Mainloop and run the application

```
private void WatchCompletedTests()
        {
            //Application.Init is already invoked and the Application has already  a top view

            Terminal.Gui.Application.MainLoop.Invoke(() => UpdateProcessWindow());

            Terminal.Gui.Application.Run();
        }
```

As far as I understand: After calling Application.Run the Application Mainloop is Invoked, in this case  "UpdateProcessWindow". To keep my process window constantly updated I keep the thread in a while loop as long as some condition comes true. 

```
        public void UpdateProcessWindow()
        {
             while (true)
             {
                
               //do stuff

                if (//some condition came ture)
                {
                      Application.RequestStop();
                }

                Thread.Sleep(500);
             }
        }

```
It works but I wonder if this is the correct way. Also while the while loop is running, the size of the top window does not change its height or width when I change the frame of the console window, although I've set the Height/Width properties of the process win to Dim.Fill(). When the thread leaves the while loop the top window automatically fits into the frame of the console (tried it in some other code).

**Comment by BDisp** [comment]
Hi, see if this link can help you in some how. Dealing with screen buffer is very complicated.

https://github.com/migueldeicaza/gui.cs/issues/339#issuecomment-595395407
