### ISSUE TITLE
TextField does not accept characters like @

### ISSUE THREAD

**Issue by rueckertch58521** [migueldeicaza/gui.cs#346]
Hi,
I'm using some TextFields in my application and I came across a problem. Every time I try to write an '@' character into the field it spawns a 'q' instead. Does somebody have a solution for this? Thanks in advance.

Greetings

**Comment by BDisp** [comment]
In my it spawns well.
![textfield](https://user-images.githubusercontent.com/13117724/76511808-8e3e6500-644b-11ea-9717-478185a6325e.png)

**Comment by rueckertch58521** [comment]
Hmmm, 

at first thanks for your answer. I'm also running it on Windows 10 and Terminal.Gui version 0.70.0. I can't help it, but my TextFields do not accept '@' or '€'. Other characters that are created with an "Alt" combination like '|' or '²' are correctly written into the TextField. 

Am I missing some property that I need to set? 

I can't post my original code because of it is too long. Here is a little sample that also has this problem.


```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terminal.Gui;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Application.Init();
            
            var topWindow = new Window("test runner");

            TextField randomTextField = new TextField("") { Width =29 };
            topWindow.Add(randomTextField);

            Application.Top.Add(topWindow);

            Application.Run();
        }
    }
}
```

**Comment by BDisp** [comment]
No, you don't missing anything. You are right. Try with my pr at https://github.com/migueldeicaza/gui.cs/pull/345

**Comment by rueckertch58521** [comment]
Still not working on my machine
here I tried to write '@' and '€', it's also not working when I try to copy it.

![image](https://user-images.githubusercontent.com/34653494/76524361-382cea00-646a-11ea-9b35-594390c7dac6.png)

**Comment by BDisp** [comment]
In my pr the '€' really spawns to 'e'. I' will see that. But '@' spawns correctly. Try in the console to verify if it spawns alright too.

**Comment by rueckertch58521** [comment]
In the normal console the mentioned characters spawn correctly.

When I set '@' as text in the constructor of Textfield it works. But while running the app it doesn't.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terminal.Gui;

```
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {

            Application.Init();
            
            var topWindow = new Window("test runner");

            var rndTextField = new TextField("@@@@@@@@@@@@");

            topWindow.Add(rndTextField);

            Application.Top.Add(topWindow);

            Application.Run();

        }
    }
}
```

But when I try to set '€' as text in the constructor of TextField I run into a "System.IndexOutOfRangeException"

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terminal.Gui;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {

            Application.Init();
            
            var topWindow = new Window("test runner");

            var rndTextField = new TextField("€");

            topWindow.Add(rndTextField);

            Application.Top.Add(topWindow);

            Application.Run();

        }
    }
}
```

**Comment by BDisp** [comment]
Ok, I already got it. It's a bug in Stack and there is an pr to fix at https://github.com/migueldeicaza/NStack/pull/42. I created a package and is working at constructor. Writing inside the text there still have some incorrect mapping.

![textfield](https://user-images.githubusercontent.com/13117724/76547994-ff9b0980-6485-11ea-94b6-28ff034b34c1.png)

**Comment by rueckertch58521** [comment]
Nice to hear you found a solution for one of the problems.

**Comment by migueldeicaza** [comment]
I am confused, the issue for the NStack#42 should have been fixed a long time ago, I do not think I need #42 do I?   It shows a conflict for a change that is already there.

**Comment by BDisp** [comment]
There is a pr in https://github.com/migueldeicaza/NStack/pull/42/commits/fe8866e169dcf2ab1657d2e0f2041ae6f3146d2c that needs to be merged in NStack to solves this issue.

**Comment by migueldeicaza** [comment]
I am confused - that PR was already merged.

**Comment by migueldeicaza** [comment]
This is my version of the fix, and it is quite old:

https://github.com/migueldeicaza/NStack/commit/3fc024fb2c2e99927d3e12991570fb54db8ce01e#diff-8ddd7307a3d5c77d1e274e484581031c

**Comment by BDisp** [comment]
But why they are still open in the pr? Another day I merged into a new branch and used in the Gui and I didn't get the error in the ColumnWidth method of the Rune class on the textfield at Redraw. And I've some changes that will be possible to use the AltMask + ControlA + delta and special characters, like €. I'm still working to solve some small bugs that yet persist. If you can update the Stack I'll include that improvments too. Thanks.

**Comment by BDisp** [comment]
@migueldeicaza, that is the pr that solves the ColumnWidth of Run class error
https://github.com/migueldeicaza/NStack/pull/44

**Comment by BDisp** [comment]
It's working well now. Some cache problem with the NStack nuget package, I think. Sorry

**Comment by migueldeicaza** [comment]
Good point, I should keep at least the test.
