### ISSUE TITLE
Error colorscheme is hard to read

### ISSUE THREAD

**Issue by SteveL-MSFT** [migueldeicaza/gui.cs#350]
The current Colors.Error ColorScheme has red on blue.  The contrast is not sufficient to make it accessible and hard to read in general.  Consider defaulting to red on black for errors?

**Comment by migueldeicaza** [comment]
Red on blue?   That sounds odd, it should be bright white on red.

can you post a screenshot?

**Comment by SteveL-MSFT** [comment]
This doesn't repro now, must have been an older version of the library.
