### ISSUE TITLE
Label: Implement line wrap

### ISSUE THREAD

**Issue by stijnherreman** [migueldeicaza/gui.cs#352]
I'm trying to make a Label fit its parent Window, but I can't figure out how to make the text wrap.

```c#
Application.Init();

var window = new Window("window")
{
	Width = 20,
	Height = 5
};
Application.Top.Add(window);

var label1 = new Label(string.Join(" ", Enumerable.Repeat("label 1", 10)))
{
	Width = Dim.Fill(),
	Height = Dim.Fill()
};
window.Add(label1);

var label2 = new Label(string.Join(" ", Enumerable.Repeat("label 2", 10)))
{
	Y = 10,
	Width = 20,
	Height = 5
};
Application.Top.Add(label2);

Application.Run();
```

This is the output:
![image](https://user-images.githubusercontent.com/1618054/77008197-fc13f080-6965-11ea-9a67-efc9d43511a2.png)

I've gone over the docs a couple times and searched existing issues, but came up empty.

**Comment by migueldeicaza** [comment]
Currently there is no support in the label for trimming or wrapping around, that would need to be implemented in the control itself.

That said, we should make sure that if this is aded to a window, that the contents are clipped, that is a genuine bug.

**Comment by tig** [comment]
+1 

Just discovered Label doesn't honor `Width.Fill()` which is same underlying issue, I think.

**Comment by tig** [comment]
When we make `Label` wrap, an important use-case will be having it not just word wrap, but support char wrap as well.

**Comment by migueldeicaza** [comment]
I discussed clipping on twitter with @BDisp 

I think we need to add clipping to the view, it will require changes to all the code that currently uses Driver.AddXxx to view.AddXxx but that way everything will get proper clipping and offset support.

Independently of that work - the wrapping capabilities should be implemented

**Comment by tig** [comment]
I'm glad to hear this. It's gonna be a big change, but is really needed.

**Comment by stijnherreman** [comment]
I suppose it will be too difficult for me to help out? I've only played around a bit with the library.
