### ISSUE TITLE
Garbled code appears in the display under Windows 2008 R2

### ISSUE THREAD

**Issue by sqlnew** [migueldeicaza/gui.cs#353]
When I test under Windows 2008 R2, the routine doesn't work normally, and I don't know why?

![20200319101453](https://user-images.githubusercontent.com/5029826/77025021-01efed00-69cb-11ea-88e0-8ce53dc19823.jpg)

![20200319101453](https://user-images.githubusercontent.com/5029826/77025076-306dc800-69cb-11ea-8467-33cc2cd3af37.jpg)

**Comment by migueldeicaza** [comment]
Sorry, I do not have access to that Windows system, I am afraid you are going to have to debug that yourself.

**Comment by tig** [comment]
This happens in all terminals (cmd.exe, ConEmu, and Windows Terminal) on Windows. Not clear if this is something Termina.Gui can address, but may be just the way it is. Leaving open in case anyone has ideas.

**Comment by BDisp** [comment]
Para mim, isso só acontece durante o redimensionamento. Depois de soltar o botão, o Windows parece bem redesenhado.
