### ISSUE TITLE
PosCombine.ToString() has an invalid runtime cast (in 0.80.0 and NOT 0.70.0)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#356]
Repro by modifying `demo.cs` to have this code at the end:

```csharp
		var label = new Label ("Fitler") {
			X = 2
		};
		var spacing = 20;

		var button = new Button ("apply") {
			X = Pos.Right (label) + spacing + 2,
			Y = 0
		};

		win.Add (label, button);

		top.Add (win);
		//top.Add (menu);
		top.Add (menu, statusBar, ml);
		Application.Run ();
	}
}
```

Result:

![image](https://user-images.githubusercontent.com/585482/79093123-7d199a00-7d10-11ea-9359-002c4a3e3690.png)

The offending code is here:

https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Types/PosDim.cs#L193

With the above demo code, the `PosCombine` contains:

```
left = {Label()({X=0,Y=0,Width=0,Height=0}),Pos.Absolute(20)}
right = {Pos.Absolute(2)}
```

This code worked fine with `0.70.0`.

Changing the code above to:

```csharp
		var button = new Button ("apply") {
			X = Pos.Right (label) + spacing,
			Y = 0
		};
```

(removing the ` + 2`) works.

**Comment by migueldeicaza** [comment]
Thank you, fixed!

**Comment by BDisp** [comment]
PosCombine only allows to add once and in the demo you had 2 add's (Pos.Right (label) + spacing + 2)

**Comment by BDisp** [comment]
@migueldeicaza  great fixe.
