### ISSUE TITLE
StatusBar disappears on resize (smaller)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#357]
Loving the new `StatusBar`.

However, on-resize, if the console is made smaller (not if made bigger), it disappears.

![image](https://i.imgur.com/4k6Aguj.gif)

**Comment by BDisp** [comment]
@tig  I would love to do that. I have already tried it, but if you check in issue #335 I have already questioned is there any way to get the top and bottom of the window according to the size and position of the scroll bar.

**Comment by BDisp** [comment]
@tig Now I am noticing that the vertical frame is not being well designed in your video. It must be a limitation of PowerShell.

**Comment by tig** [comment]
> @tig Now I am noticing that the vertical frame is not being well designed in your video. It must be a limitation of PowerShell.

I think this is an issue with `gui.cs` on Windows Terminal. See https://github.com/migueldeicaza/gui.cs/issues/332

**Comment by tig** [comment]
This seems to work:

```csharp
		public StatusBar(StatusItem [] items) : base()
		{
			X = 0;
			Y = Application.Driver.Rows - 1; // TODO: using internals of Application
			Width = Dim.Fill ();
			Height = 1;
			Items = items;
			CanFocus = false;
			ColorScheme = Colors.Menu;

			Driver.SetTerminalResized (new Action(() => {
				Y = Driver.Rows - 1;
				Redraw (Frame);
			}));
		}
```

**Comment by tig** [comment]
Still does not work in Windows Terminal, cmd.exe, or ConEmu.

https://i.imgur.com/W6CKJdH.png

**Comment by BDisp** [comment]
Because WindowsDriver don't trigger the buffer event changed on the vertical shrink resizing, there is no way to caught that to resize the buffer.
