### ISSUE TITLE
Cool (but not quality) redraw glitches when resizing

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#358]
See

![https://i.imgur.com/YLqwHtQ.gif](https://i.imgur.com/YLqwHtQ.gif)

More pronounced in Windows Terminal (above) than in cmd.exe, mostly because cmd.exe paints much faster.

**Comment by BDisp** [comment]
But at least now the image is not distorted when we have finished scaling it. Although it is boring, despite that.

**Comment by migueldeicaza** [comment]
I think this is a problem with the Windows terminal - where the "reflow smarts" trigger before the application has received a notification that the window size changed.   So the reflow kicks-in, reorders the content, then the message is sent to the application "Hey your size changed" which triggers the repaint.

This is exactly the same problem that XtermSharp and SwiftTerm surface.

**Comment by BDisp** [comment]
@migueldeicaza That is why I insist that if it is not the gui.cs itself that deals with repainting then the problem would be enormous, if it is personalized by each application that integrates it in its projects.

**Comment by migueldeicaza** [comment]
I am not sure I understand the suggestion @BDisp

**Comment by BDisp** [comment]
It's nothing. Never mind.
