### ISSUE TITLE
Vertical spacing too tall on Windows Terminal

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#359]
Related to, but I believe distinct from https://github.com/migueldeicaza/gui.cs/issues/332

![](https://i.imgur.com/AxlddQT.png)

Note gaps between pipe characters on the sides. It does this with all fonts, and every screenshot of `gui.cs` in Windows Terminal seems to show this. Figured filing an Issue on it specifically would be a good thing.

**Comment by tig** [comment]
This appears to be a Windows Terminal bug:

https://github.com/microsoft/terminal/issues/455

https://github.com/microsoft/terminal/issues/3498

**Comment by BDisp** [comment]
I already suspected that it would be because otherwise I would also have this problem with cmd.exe or Windows 10 PowerShell which is what I use.

**Comment by migueldeicaza** [comment]
Interesting find - I am actually having the same issue with my Xterm terminal emulator on Mac.
