### ISSUE TITLE
Is there any way drag n drop

### ISSUE THREAD

**Issue by pandaboy1942** [migueldeicaza/gui.cs#365]
is there anyway to transform normal winform code to terminal gui? I see they both same structure.

**Comment by BDisp** [comment]
It is very different to work with pixels and columns and lines but the principle is more or less the same. Drag n drop is possible with some work. It is now possible to move the windows and keep them framed at the top-level. Only in reducing the size of the windows does it get a mess but we cannot change the console's buffer. But it has gone further :-)

**Comment by pandaboy1942** [comment]
uh, i seen the source of winform have same struct. Maybe one day it will be true

**Comment by tig** [comment]
Closing; not a bug.
