### ISSUE TITLE
UI Catalog

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#368]
The current demo.cs is acceptable to test code, but it is neither good to showcase, nor to explain different concepts.   This issue is a place to start tracking ideas of things that we should showcase in Gui.cs and try to get the various workflows that people would like to see shown.

Ideas:

- [ ] Main app contains a menu, statusbar, and just instructions in the middle of the screen, with buttons that the user can tab back and forth and invoke demos ("Use the arrow keys or tab to choose one of the buttons below, and then either press return or space to activate;   Press ESC-9 or F9 to activate the menubar; Use the mouse to click on different parts of the screen")
- [ ] How to implement a multi-stage wizard
- [ ] Show how to implement simple dialogs with default values being set and read
- [ ] Simple demo showing a background operation that updates the UI - to show how a background thread must communicate with the front-end
- [ ] A demo that shows how to use a background thread with async/await to show the SynchronizationContext in action and best practices on how to write that code
- [ ] Mouse demo - a paint program to show how to draw on the screen
- [ ] Dedicated menu to show the different styles of ListViews that can be shown
- [ ] "Custom Control" to show the basics of implementing a custom control, not in the core

**Comment by tig** [comment]
Better to have one mondo demo app, or smaller demo apps that show specific use-cases?

It is very challenging to work on new / improved capabilities and avoid effing up existing demo functionality. 

I think moving most demo code out of demo.cs into separate classes would also address this.

**Comment by migueldeicaza** [comment]
Absolutely we can take code from there.  I am picturing a new project and one capability per file - most can be done this way except maybe the main launching app.

**Comment by tig** [comment]
This may be my weekend project now that I got the `StatusBar` and `MenuBar` stuff done (which was all about making the PowerShell `out-consolegridview` sing.

**Comment by tig** [comment]
Closing and moving each idea @migueldeicaza's original list to new Issues tagged with "UI Catalog:" for tracking now that this general idea is implemented as #387.
