### ISSUE TITLE
Refactoring into one file class per .cs file?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#369]
How would folks react to me doing some refactoring of the `gui.cs` project?

It is driving me nuts having multiple classes in one file. It makes it really hard to keep track of which implementation of an override I'm looking at. 

I think this may be a religious debate. If so, and I'm coming down on the wrong side of other contributor's religion then never mind, it's not that big of deal.  ;-)

**Comment by migueldeicaza** [comment]
I love multiple classes per file, I like to arrange them by theme :-)

That said, I think I could split a couple out from Core.cs

**Comment by tig** [comment]
I had a feeling it was intentional. Nobody would do that by accident. 

To each his own.
