### ISSUE TITLE
StatusBar should support snapping to top

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#376]
I have an app where a menu doesn't make sense, but a legend of hotkeys does. 

Because `StatusBar` tracks to bottom, and on some terminals (namely `cmd.exe`, Curses, and Net) don't (seem to) support terminal resizing console apps correctly, it is not an ideal control.

There are two ways of addressing my underlying ask:

1) Make `MenuBar` be able to act like a `StatusBar` with shortcuts, titles, and actions. This can be partially addressed (I have a PR in progress) by supporting `MenuItems` at the top-level of `MenuBar`. But not completely, because `MenuBar` doesn't support ctrl keys as shortcuts (as far as I can tell).

2) Make it so if an app doesn't want a `MenuBar` it can place a `StatusBar` at the top. 

I have a PR with a modified `StatusBar` that *almost* does this ready. However, late in testing, I discovered that a bunch of `core.cs` has hard dependencies on both `MenuBar` and `StatusBar` (e.g. `TopLevel.HasStatusBar`). 

So, to do #2 correctly that all needs to be refactored. I have half-a-mind to do this by refactoring both `MenuBar` and `StatusBar` on top of a base class `TopBotttomBar` that can address all the stuff `core.cs` needs to place things around them correctly. This would let `MenuBar` also work on the bottom if (god forbid) anyone ever wanted to do that. I would also enable folks to build additional controls.

**Comment by BDisp** [comment]
The hotkeys for menu is `Alt key`. `Alt + F` open the File menu. I agree that both the menu and the status bar can be arranged at the top, button, left or right. I had to create the properties for `HasMenuBar` and `HasStatusBar` because the movement of the windows does not exceed the upper and lower limits. But everything can be redone, as long as it is to improve.

**Comment by tig** [comment]
Here's my terminology. It may not be right and it may be overly influenced with my history in Windows:

- Accelerator Keys - A way of accelerating access to menus. Almost always involve using the Alt key. E.g. Alt to open the menu, Alt-F to accelerate to the File menu). Accelerator keys enable navigating menus via keyboard. Some accelerator keys lead to direct invocation of commands, but this is rare.
- Shortcut keys - A way of bypassing the menu altogether with simple keystrokes. E.g. Ctrl-C to copy, F1 for help. Shortcut keys invoke commands.

Right now `gui.cs` mixes and matches these concepts leading to confusion and inconsistent CX.

I'd like to work (over-time, not breaking things, always simplifying, always improving) towards greater consistency in `gui.cs`.

**Comment by BDisp** [comment]
@tig you cannot trust in the Action Application.OnLoad because it is static and only the last invocation to it is called. Thus its use in the StatusBar contructor is never called because it is invoked later in the Demo.

**Comment by tig** [comment]
I don't really believe this is needed anymore. Closing.
