### ISSUE TITLE
Apps don't start full size in Windows Terminal

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#377]
1. Start a Windows Terminal session with more than 35 rows.
2. Run the `demo.cs` app.
3. Note until your resize the Windows Terminal window, the app is not full height.

This does not repro on ConEmu or `cmd.exe`.

![](https://i.imgur.com/YTzeR8J.gif)

Related, but not the cause, is `demo.cs` has this line in it:

		Console.WindowHeight = 35;

Which should be removed, I think.

**Comment by BDisp** [comment]
Yes it will be removed. I already push a PR to change that.

**Comment by tig** [comment]
No longer repro. Yay. Closing.
