### ISSUE TITLE
Lower-case menu accelerators don't work

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#378]
To repro, change `demo.c` such that the `assorted` menu title is `a_ssorted`:

	new MenuBarItem ("A_ssorted", new MenuItem [] {
		new MenuItem ("_Show text alignments", "", () => ShowTextAlignments ()),
		new MenuItem ("_OnKeyDown/Up", "", () => OnKeyDownUpDemo ())
	}),

The fix is in `Menu.c` in `FindAndOpenMenuByHotkey`:

	if (Char.ToUpperInvariant((char)mi.Title [p + 1]) == c) {

Before I do a PR, please verify that this is the right way to `ToUpper` a char with `Runes/ustring` (which I don't quite grok yet).

**Comment by BDisp** [comment]
Use this lower `char`:

`if (char.ToUpperInvariant ((char)mi.Title [p + 1]) == c) {`

**Comment by tig** [comment]
This was fixed in the menu PR miguel accepted this morning.
