### ISSUE TITLE
Is this thing called `gui.cs` or `Terminal.gui`?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#379]
The repo & `README.MD` implies it's called `gui.cs`.

The nuget package is named `Terminal.gui`.

Which is it?

**Comment by garyng** [comment]
`Terminal.Gui` is the nuget package name. I think this is called `gui.cs` because its original name given back in [2007](https://tirania.org/blog/archive/2007/Apr-16.html).

**Comment by tig** [comment]
My OCD is set off whenever I work with this project. I think it is confusing and adds to friction of people adopting the project. My suggestion: Establish that the formal, common, name for the project is `Terminal.Gui` and change `README.md` and other docs to refer to `Terminal.Gui` instead of `gui.cs`. 

I vote in favor of this vs. `gui.cs` because:

* the nuget package is out there as `Terminal.Gui` and is harder to change than internal references. 
* The directory that contains the library, and the `.csproj` file is already named `Termina.Gui`.
* `Terminal.Gui` actually, accurately, describes what it does. 

I admit that none of this probably actually matters and it's just my own OCD-angst driving me. That said, I'm willing to do the work, but not if other maintainers (esp. Miguel) are opposed to it.

**Comment by garyng** [comment]
I’m fine with the name actually, but the decision is still up to the main maintainers and contributors of this project.

**Comment by BDisp** [comment]
It is fine for me to change to Terminal.gui, but it will be possible to change the name of the project without breaking all links to the current project, including forks, followers, etc ... But in this matter only @migueldeicaza's decision counts .

**Comment by migueldeicaza** [comment]
Right, `gui.cs` is part of the joke, because it used to be a single-file UI toolkit in 2007.

I think it could be renamed without breaking anything, GitHub supports that, but I do not want to erase that tradition.

**Comment by BDisp** [comment]
Loud and clear :-)

**Comment by tig** [comment]
Roger. We will not rename the github repro. But we will:

* Refer to the project as `Terminal.Gui` in documentation and comments.
* Avoid referring to it as `gui.cs` exept when pointing people the the github repo.

Do I have that right?

**Comment by BDisp** [comment]
I think so and lets the jokes to the @migueldeicaza :-) Just joking.

**Comment by tig** [comment]
I think this is settled. Closing.
