### ISSUE TITLE
F9 should close menu as well as open it

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#380]
`F9` activates `MenuBar`. 

The only way to de-activate the menu is to either select a menu item or press `esc` (or click elsewhere with the mouse in terminals that support mouse).

`F9` should dismiss the menu bar as well as activate it.

**Comment by BDisp** [comment]
Try this in the `Menu.cs`

```
public override bool ProcessHotKey (KeyEvent kb)
{
	if (kb.Key == Key.F9) {
		if (!MenuOpen)
			StartMenu ();
		else
			CloseMenu ();
		return true;
	}
```

**Comment by tig** [comment]
What the heck?

		internal bool isMenuClosed;
		public bool MenuOpen;

Are these independent?

My PR used `isMenuClosed`.

**Comment by BDisp** [comment]
I'm not sure that `isMenuClosed` can be set to `true` and in reality there may be some sub-menu open. It is a matter of opening in all menus and sub-menus and testing. If it works well, let it be.

**Comment by BDisp** [comment]
The last `MenuOpen` wasn't mine :)

**Comment by tig** [comment]
This has the makings of a bug farm. ;-)

I think I mentioned this before, but I'm currently working through some other menubar enhancements and stuff like this is making it harder to do. I'll probably fix this...but I'll double check that there's not some explicit reason for both to exist. 

FWIW, I tested my PR #380 and am very confident using `isMenuClosed` worked. I've also tested it using `MenuOpen` and it works too...

**Comment by BDisp** [comment]
I implemented the sub-menus and believe that it’s not easy, at least for me, I don’t have much experience. The biggest difficulty was dealing with the movement of the mouse, which automatically opens or closes menus accordingly. If it were just to handle clicks it was much easier.

**Comment by tig** [comment]
Well, you did a great job. The sub-menu work is pretty awesome. I hope you don't take offense with me mucking in your code!

**Comment by BDisp** [comment]
Not at all. Make it even better :-)
