### ISSUE TITLE
Drawing cursor on top-level MenuBar?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#382]
@BDisp this is really a question for you; starting a new thread on a slightly different topic from our other convo...

I noticed `MenuBar.PositionCursor` doesn't actually do anything today. It's dead code. 

		public override void Redraw (Rect region)
		{
			Move (0, 0);
			Driver.SetAttribute (Colors.Menu.Normal);
			for (int i = 0; i < Frame.Width; i++)
				Driver.AddRune (' ');

			Move (1, 0);
			int pos = 1;

			for (int i = 0; i < Menus.Length; i++) {
				var menu = Menus [i];
				Move (pos, 0);
				Attribute hotColor, normalColor;
				if (i == selected) {
					hotColor = i == selected ? ColorScheme.HotFocus : ColorScheme.HotNormal;
					normalColor = i == selected ? ColorScheme.Focus : ColorScheme.Normal;
				} else {
					hotColor = Colors.Base.Focus;
					normalColor = Colors.Base.Focus;
				}
				DrawHotString (" " + menu.Title + " " + "   ", hotColor, normalColor);
				pos += menu.TitleLength + 3;
			}
			PositionCursor ();
		}

You can comment out `PositionCursor()` and there is no behavior change (that I could find).

In addition, the not-selected case above means the accelerator key hints (after `_`) don't get drawn.

My questions: Was it intentional that 

a) Accelerator hints aren't drawn for top-level menu bar items? 

b) Did you ever try to get `PositionCursor()` to work? It appears it worked at some point because it's mostly correct. 

The reason I'm asking is I want to add support for top-level `MenuBar` items to be actions (not a menu that drops down, but just a single action). 

Imagine this menu:

  menu = new MenuBar (new MenuBarItem [] {
      new MenuBarItem ("_File", new MenuItem [] {
      new MenuItem ("_New", "Creates new file", NewFile),
      new MenuItem ("_Open", "", Open),
      new MenuItem ("_Close", "", () => Close ()),
          null,
      new MenuItem ("_Quit", "", () => { if (Quit ()) top.Running = false; })
  }),
  new MenuBarItem ("_About...", "help", () =>  MessageBox.ErrorQuery (50, 7, "About Demo", "This is a demo app for gui.cs", "Ok")),
  }

(note last `MenuBarItem` takes an action)

For this to work, we need:

1) Accelerator highlights so the action is discoverable.
2) The cursor to show on the "A" of "_About" when the menu is active (just as the cursor shows on drop-down menu items).

I've already fixed #1 (which was easy; just use the right `ColorScheme` colors for `hotColor/normalColor`.

But #2 is proving tricky ... as you indicated dealing with all the cursor `Move(x,y)` stuff is challenging.

I just don't want go any further into this blindly if you have any thoughts already. 

Thanks.

**Comment by tig** [comment]
FWIW, I think I have it all working nicely now. Look for a big PR tonight or tomorrow!

**Comment by BDisp** [comment]
Replace this
`hotColor = Colors.Base.Focus;`
with this
`hotColor = Colors.Menu.Normal;`

You'll see the hot string highlight.

**Comment by BDisp** [comment]
I don't think you can get rid of the cursor. He is always there. What you can do is to obscure it so that it is more or less invisible.

**Comment by BDisp** [comment]
As I mentioned, increasing the size of the top-level, it is relatively easy to keep the menu and status bar visible at all times. But when you are reducing the size of the top-level you cannot get the last visible line. If we only had to deal with the Windows Console class, it was possible, but not with the gui.

**Comment by BDisp** [comment]
@tig do KeyDown and KeyUp perform key combinations simultaneously? If so, it would be a good idea to print the key combinations too.

**Comment by tig** [comment]
Did you mean to comment on this issue or this one: https://github.com/migueldeicaza/gui.cs/pull/395 ?

**Comment by BDisp** [comment]
You're right. I was wrong on the issue :-)

**Comment by tig** [comment]
This is fixed. Closing.
