### ISSUE TITLE
ScrollViews and focus

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#40]
Scrollviews should take the focus for any focusable controls and show allow for the key navigation keystrokes to control where the focus goes.

Additionally, we probably should make "PositionCursor" return the Point where the cursor would be in a View, instead of manually positioning it.   The caller would place the cursor in the right place.

This would allow us to figure out where the cursor should go in a scrollview and scroll to the right location on those scenarios.

**Comment by tig** [comment]
@BDisp I think our work on `ScrollView` and `Focus` essentially addressed this. No?

**Comment by BDisp** [comment]
> 
> 
> @BDisp I think our work on `ScrollView` and `Focus` essentially addressed this. No?

Yes indeed we did.

**Comment by tig** [comment]
Nice!
