### ISSUE TITLE
Can ListViews have titles?

### ISSUE THREAD

**Issue by psantosl** [migueldeicaza/gui.cs#405]
Hi,

I'd like to write some sort of "htop-like" console inside our Plastic SCM server. I guess ListView is the one to show lists of requests and open connections and things like that. But, can ListViews show titles?

Thanks!

**Comment by psantosl** [comment]
Ok, just realized I need something like a table or a grid :-)

**Comment by BDisp** [comment]
Good. It would be very useful to put here the code that you have implemented so that others who have the same question are also clarified. Thanks.

**Comment by psantosl** [comment]
Of course, if I implement a view, I'll share it.

I think the best starting point for some sort of table will be the HexView, correct?

**Comment by BDisp** [comment]
I would not like to give my opinion yet. However, you could take a look at this project where they use gui.cs and implement a ListView.
https://github.com/PowerShell/GraphicalTools/tree/master/src/Microsoft.PowerShell.ConsoleGuiTools

**Comment by psantosl** [comment]
Another question: when I create a list and put inside a scrollbox... it doesn't really scroll completely, does it? I mean, I try to scroll horizontally but if the list is much bigger than the scrollbox, it doesn't work:

```
		// This is just to debug the visuals of the scrollview when small
		var scrollView2 = new ScrollView (new Rect (0, 0, 50, 4)) {
			ContentSize = new Size (120, 10),
			ShowVerticalScrollIndicator = true,
			ShowHorizontalScrollIndicator = true
		};

		var listView = new ListView(new string [] {
"Name                                      Request IP              Time      Thread   Status   Protocol  Sec  User",
"Unknown-plasticproto                           22 127.0.0.1       00:00:00  26       Proto    Plastic   None",
"CalculateMerge                                 21 127.0.0.1       00:00:00  24       Read     Plastic   None pablo"
			});

		listView.Width = Dim.Fill();
		listView.Height = Dim.Fill();

		scrollView2.Add(listView);
```

No matter how much I scroll, I can't go through the whole list :-)

![image](https://user-images.githubusercontent.com/380766/80112379-5580c800-8581-11ea-8242-b0ab1e8806a9.png)

**Comment by BDisp** [comment]
There really is a bug and naturally in many other views. Normally, the fact that the X or Y limit is negative is not considered and starts to print at the beginning. The frame is correct, I just referred to the text that is printed on the screen. I will try to improve the ScrollView and ListView to demonstrate this.
