### ISSUE TITLE
Execute code with key press?

### ISSUE THREAD

**Issue by 20repsej** [migueldeicaza/gui.cs#408]
Hi! I want to execute some code by pressing the enter key while I have an item in a ListView selected. The problem is that I don't understand how this is done.

```csharp
var LibraryListWin = new ListView(LibraryList)
            {
                X = 0,
                Y = 1,
                Width = Dim.Fill(),
                Height = Dim.Fill()

            };
```
![image](https://user-images.githubusercontent.com/25184889/80383847-6d6b8b00-88a4-11ea-91b3-05e40b72cc70.png)

So when I press Enter when the ListView looks like this I want to do something with the selected item. How do I go about doing this?

**Comment by BDisp** [comment]
Look at the ProcessKey event to handle the Enter key.
