### ISSUE TITLE
Must measure output size with Rune.ColumnWidth

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#41]
Many characters that take up two slots are not properly rendered as we render those two, but do not fully fill the requested region.   Need to use `Rune.ColumnWidth` to compute the current position.

**Comment by tig** [comment]
@migueldeicaza do you have a test case for this?

**Comment by tig** [comment]
FWIW, this is a disaster. I dare anyone to follow the discussions w.r.t. wide unicode chars in Windows Terminal land and successfully follow along... Or have any idea what we should do.

Examples: 

* https://github.com/microsoft/terminal/pull/2928
* https://github.com/microsoft/terminal/issues/900
* https://github.com/microsoft/terminal/issues/5095#issuecomment-619186373

**Comment by tig** [comment]
FWIW, I believe at some point I modified the code (in `ConsoleDriver`? to explicitly ignore Runes with ColumnWidth > 1 and print the default char as a work around of this issue until it can be addressed correctly. In #949, it appears @BDisp discovered that I missed a case.

**Comment by BDisp** [comment]
@migueldeicaza I think maybe it's time to use `System.Text.Rune`.

**Comment by BDisp** [comment]
I submitted a PR at https://github.com/migueldeicaza/NStack/pull/48 to be able to control what kind of rune is being passed to `AddRune`. I hope that @migueldeicaza takes into account to be able to come up with a solution.

**Comment by migueldeicaza** [comment]
The patch from @BDisp is now merged and should be on the new NStack.Core

**Comment by BDisp** [comment]
@migueldeicaza there is another PR (https://github.com/migueldeicaza/NStack/pull/52) that fixes the "Chess Symbols (U+1fa00-1fa0f)". Thanks.

**Comment by migueldeicaza** [comment]
Merged - I will release a new NStack in the morning.
