### ISSUE TITLE
Layout questions

### ISSUE THREAD

**Issue by psantosl** [migueldeicaza/gui.cs#412]
Hi!

I'm trying to create an htop-like sample (I'll publish it soon in GitHub) with gui.cs:

![image](https://user-images.githubusercontent.com/380766/81042561-ae6d2c00-8eb0-11ea-9b73-b1378b1a9fef.png)

My question is, how can I really anchor panels as follows?

![image](https://user-images.githubusercontent.com/380766/81042586-be850b80-8eb0-11ea-9a65-52a7e7938c40.png)

I'm trying to use this for the bottom panel:

frame.Y = Pos.AnchorEnd(3);
frame.Height = Dim.Fill();

But not really working (what you see in the screenshot is global positioning, but of course it doesn't work when you resize).

Also, I'm seeing issues in the parent window (height gets smaller for some reason) after some changes.

**Comment by BDisp** [comment]
I think this is what you want more or less.

```
class Program {
	static void Main ()
	{
		Application.Init ();

		var top = Application.Top;

		var margin = 1;
		var win1 = new Window ("Window 1") {
			X = 0 + margin,
			Y = 0 + margin,
			Width = Dim.Percent (50) - margin,
			Height = Dim.Percent (50) - margin
		};
		var win2 = new Window ("Window 2") {
			X = Pos.Right(win1) + margin,
			Y = 0 + margin,
			Width = Dim.Fill(margin),
			Height = Dim.Percent (50) - margin
		};
		var win3 = new Window ("Window 3") {
			X = 0 + margin,
			Y = Pos.Bottom (win1) + margin,
			Width = Dim.Fill(margin),
			Height = Dim.Fill(margin)
		};

		top.Add (win1, win2, win3);

		Application.Run ();
	}
}

```

**Comment by psantosl** [comment]
Thanks!!

Looking amazing!

![image](https://user-images.githubusercontent.com/380766/81115112-7e12a580-8f23-11ea-99db-2b080a28e3e1.png)

I'll share the url to my repo here asap.

**Comment by psantosl** [comment]
Here it is my sample app:

https://github.com/psantosl/htopsharp


https://github.com/psantosl/htopsharp/raw/master/images/htopsharp-initial-demo.gif

**Comment by psantosl** [comment]
Something else I mus be doing wrong:

I can't make the second "process area" grow correctly:
```
		int margin = 1;

		cpuArea.X = 0 + margin;
		cpuArea.Y = 0 + margin;
		cpuArea.Width = Dim.Percent(50) - margin;
		cpuArea.Height = Dim.Percent(30) - margin;

		processArea.X = 0 + margin;
		processArea.Y = Pos.Bottom(cpuArea) + margin;
		processArea.Width = Dim.Percent(50) - margin;
		processArea.Height = Dim.Fill(margin);

		processArea1.X = Pos.Right(processArea1) + margin;
		processArea1.Y = Pos.Bottom(cpuArea) + margin;
		processArea1.Width = Dim.Percent(50) - margin;
		processArea1.Height = Dim.Fill(margin);

		top.Add(cpuArea, processArea, processArea1);
```

![image](https://user-images.githubusercontent.com/380766/81282668-c7fea700-905b-11ea-9234-924e5b944d52.png)

If I try a different option:

```
		int margin = 1;

		cpuArea.X = 0 + margin;
		cpuArea.Y = 0 + margin;
		cpuArea.Width = Dim.Percent(50) - margin;
		cpuArea.Height = Dim.Percent(30) - margin;

		processArea.X = 0 + margin;
		processArea.Y = Pos.Bottom(cpuArea) + margin;
		processArea.Width = Dim.Percent(50) - margin;
		processArea.Height = Dim.Fill(margin);

		processArea1.X = Pos.Right(processArea1) + margin;
		processArea1.Y = Pos.Bottom(cpuArea) + margin;
		processArea1.Width = Dim.Fill(margin);
		processArea1.Height = Dim.Fill(margin);

		top.Add(cpuArea, processArea, processArea1);
```

Shows this: (one of the "process windows" missing):

![image](https://user-images.githubusercontent.com/380766/81282572-a1d90700-905b-11ea-8b75-5527e7da0caf.png)


Finally: should this work when you resize the window? Everything seems to break :)

**Comment by BDisp** [comment]
processArea1.Width = Dim.Fill(margin);

**Comment by psantosl** [comment]
I got the whole thing working :-)

But, it is looking slightly different on Linux than windows :)

![image](https://user-images.githubusercontent.com/380766/81420491-518fa100-9150-11ea-9a7e-d13c7d92a9ae.png)

Don't know yet is this is because Putty:


![image](https://user-images.githubusercontent.com/380766/81420510-58b6af00-9150-11ea-81f6-1394c66165b0.png)

**Comment by psantosl** [comment]
Hey @BDisp do you know what I have to fix to display it correctly on Linux?

Looks totally different on Linux than Windows. I'm connecting remotely through bash (Windows subsystem) to a Linux system, but layouts don't look the same, they're broken on Linux.

**Comment by BDisp** [comment]
Must see why Unix does not update the screen on resizing. Only updates when hover the mouse or with keyboard.

**Comment by psantosl** [comment]
My issue is also with layout. Look: top is windows, how I expected it to be, down is Linux, through ssh and bash, and layouts don't look correct. I'll give a try in a Linux locally.

![image](https://user-images.githubusercontent.com/380766/81447031-2b7ff600-917c-11ea-99ce-59456faa5891.png)

**Comment by BDisp** [comment]
I've noticed that. Then say something. Thank you.

**Comment by psantosl** [comment]
I managed it to run my sample app in OpenSuse, but I struggle with rendering issues:

![image](https://user-images.githubusercontent.com/380766/81475970-98909b80-920f-11ea-9bf2-b28e72e462c6.png)

And status bar: there should be a F-10 close to Quit:

![image](https://user-images.githubusercontent.com/380766/81475990-a7774e00-920f-11ea-910e-5b1dba1378e3.png)

**Comment by BDisp** [comment]
The problem is in mainloop.cs at IMainLoopDriver.EventsPending
in line:
n = poll (pollmap, (uint)pollmap.Length, pollTimeout);

n is always -1 on resizing and only is not -1 with mouse hover or key press.

**Comment by psantosl** [comment]
Cool. Do you plan to release a new version?

**Comment by BDisp** [comment]
I haven't been able to figure it out yet. I'm still trying to figure it out. I am not a Linux or macOS expert. But I will try.

**Comment by psantosl** [comment]
Regarding the rendering issues => the system where I see the render issues is using libncursesw.so.6.

The system where I fixed it to force to use libncursesw.so.5, works well in terms of layout.

Just in case it throws some light :-)

**Comment by psantosl** [comment]
Absolute positioning works on that system (it is an Amazon Linux).

But as soon as I try to place a control to the right of the previous with Pos.Right, it doesn't render well.

**Comment by BDisp** [comment]
Did you try with the master version of the gui.cs? There are a new commit that solves that layout issue with the linux.

**Comment by psantosl** [comment]
I'll check

**Comment by psantosl** [comment]
Tested it. Layout works fine with master!

![image](https://user-images.githubusercontent.com/380766/81478490-325f4500-921e-11ea-84db-71b9916e1c43.png)


But, FrameViews don't render the title now :-(

![image](https://user-images.githubusercontent.com/380766/81478540-7d795800-921e-11ea-8e5d-eec52e67a277.png)

**Comment by BDisp** [comment]
And how about in windows?

**Comment by psantosl** [comment]
Same:

![image](https://user-images.githubusercontent.com/380766/81478729-6a1abc80-921f-11ea-8c5c-b5aebfd05dde.png)


This is not as important as the layout. Good layout is great progress :-)

**Comment by BDisp** [comment]
It's was a bug in FrameView. I already fixed it. See my pull request #410
