### ISSUE TITLE
WindowsDriver deferred screen buffer allocation?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#417]
@migueldeicaza or anyone else:

In `WindowsDriver.cs` the creation of the `ScreenBuffer` happens when `WriteToConsole` is called. 

```
public bool WriteToConsole (CharInfo [] charInfoBuffer, Coord coords, SmallRect window)
{
	if (ScreenBuffer == IntPtr.Zero) {
		ScreenBuffer = CreateConsoleScreenBuffer (
			DesiredAccess.GenericRead | DesiredAccess.GenericWrite,
			ShareMode.FileShareRead | ShareMode.FileShareWrite,
			IntPtr.Zero,
			1,
			IntPtr.Zero
		);
		if (ScreenBuffer == INVALID_HANDLE_VALUE) {
			var err = Marshal.GetLastWin32Error ();

			if (err != 0)
				throw new System.ComponentModel.Win32Exception (err);
		}

		if (!SetConsoleActiveScreenBuffer (ScreenBuffer)) {
			var err = Marshal.GetLastWin32Error ();
			throw new System.ComponentModel.Win32Exception (err);
		}

		OriginalStdOutChars = new CharInfo [Console.WindowHeight * Console.WindowWidth];

		ReadConsoleOutput (OutputHandle, OriginalStdOutChars, coords, new Coord () { X = 0
	}

	return WriteConsoleOutput (ScreenBuffer, charInfoBuffer, coords, new Coord () { X = window
}
```

It tears this down in `CleanUp`:

```
public void Cleanup ()
{
	ConsoleMode = originalConsoleMode;
	ContinueListeningForConsoleEvents = false;
	if (!SetConsoleActiveScreenBuffer (OutputHandle)) {
		var err = Marshal.GetLastWin32Error ();
		Console.WriteLine ("Error: {0}", err);
	}

	if (ScreenBuffer != IntPtr.Zero)
		CloseHandle (ScreenBuffer);

	ScreenBuffer = IntPtr.Zero;
}
```

However, `WindowsDriver.Init` is where this stuff, logically, should happen.

As a result of the current implementation, `Init` calls `Console.Clear` before the secondary `ScreenBuffer` is allocated in `WriteToConsole`. I believe this is the cause of the bug inflicting `out-ConsoleGridView` where the output of the the CmdLet gets erased:

https://github.com/PowerShell/GraphicalTools/issues/96

So, the question, before I go and fix this by simplifying, does anyone have a good reason why the creation of the screen buffer was deferred to the first call to `WriteToConsole` vs. doing it at init time?

**Comment by tig** [comment]
FWIW, the urgency of this is lessened given the simple fix in #423 was so simple (just remove the `Console.Clear()` call. But the way `WindowsDriver` is implemented is a bit off. It should be refactored such that all init is done in `Init` and all cleanup in `End`.

**Comment by BDisp** [comment]
The problem is also concern with the use of Console commands after the creation of the ConsoleDriver. @migueldeicaza had already said that before and it happened with me when I used some Console commands to do some stuffs. There only should be used kernel functions to deal with the buffer in windows.

**Comment by tig** [comment]
Won't fix. Closing.
