### ISSUE TITLE
CursesDriver should emit the "Set cursor key to application mode" ANSI escape code when it exits

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#418]
`out-consolegridview` currently has this clean-up code in it to fix https://github.com/PowerShell/GraphicalTools/issues/49.

```
     public void Dispose()
        {
            // By emitting this, we fix an issue where arrow keys don't work in the console
            // because .NET requires application mode to support Arrow key escape sequences
            // Esc[?1h - Set cursor key to application mode
            // See http://ascii-table.com/ansi-escape-sequences-vt-100.php
            Console.Write("\u001b[?1h");
        }
```

Driver's clean-up code should emit the `\u001b[?1h` ANSI escape code when it exits.

According to @TylerLeonhardt he put this here as a quick fix, but it should really be fixed in `gui.cs`.  See: https://github.com/PowerShell/GraphicalTools/issues/99#issuecomment-628109936

The issue is not reproduceable in `ConEmu` or `Windows Terminal` on Windows, so this appears to be specific to Linux and Mac. I believe this should be done in the `CursesDriver`'s implementation of `ConsoleDriver.End()` which currently looks like this:

		public override void End () => Curses.endwin ();

Thus:

		public override void End () 
		{
			// See gui.cs Issue #418
			Console.Out.Write ("\x1b[?1h");
			Console.Out.Flush ();
			Curses.endwin();
		}

But I don't know enough about Curses to know if this actually makes sense.

**Comment by TylerLeonhardt** [comment]
If possible this should reset it only if that's what it was set to before launching a gui.cs app.

**Comment by tig** [comment]
Reopening. See $945.

**Comment by BDisp** [comment]
> If possible this should reset it only if that's what it was set to before launching a gui.cs app.

The main problem is how to get it before application launch and assign at exit.

**Comment by BDisp** [comment]
> 	public override void End () 
> 	{
> 		// See gui.cs Issue #418
> 		Console.Out.Write ("\x1b[?1h");
> 		Console.Out.Flush ();
> 		Curses.endwin();
> 	}


I've already tested that before with no success.

**Comment by BDisp** [comment]
@tig after all works but not alone. Before `initscr `must call
```
				Console.Out.Write ("\x1b[?1h");
				Console.Out.Flush ();
```
and before `endwin `must call
```
			Console.Out.Write ("\x1b[?1l");
			Console.Out.Flush ();

```
I think that the most correct is `1h` on start and `1l` at end like the mouse.

**Comment by migueldeicaza** [comment]
Mhm, I see what is going on here.

So PowerShell is expecting regular cursor key commands, while gui.cs uses Application Key commands.

The proper way of doing this would be to lookup the terminfo database and output the strings for rmkx and smkx.

You can use `tigetstr` to get the values of those strings.
