### ISSUE TITLE
Unhandled Exception...

### ISSUE THREAD

**Issue by hditano** [migueldeicaza/gui.cs#430]
I don't know what else to do to make it work.
Pretty much it calls a function that says...if 1 write "Test1" if 2 write "Test2"

            var dbLabelRecords = new Label("Prueba")
            {
                X = 25,
                Y = 4,
                Width = 20,
                Height = 1
                
            };
            win.Add(dbLabelRecords);
            dbLabelRecords.Text = MainMenu.DTotalRecords(userLabel.Text.ToString());

**Comment by BDisp** [comment]
What you ask for is so simple that if you look in the closed issues you will find good examples for what you want. A little effort is good :-)

**Comment by hditano** [comment]
Yes.. I'm sorry.. Already found out how to do it.
Just started to learn C# about a month ago..so this is my first time getting out of my comfort zone. 
My apologies.
