### ISSUE TITLE
If StatusBar handles <key>, <key> is eaten for all Toplevels except Application.Top

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#436]
Easily reproduced in the main `UI Catalog` window where opening the `File` menu, selecting `Quit` and hitting `ENTER` starts the selected scenario vs. exiting. 

This is true of any key that `StatusBar` eats: E.g. if there's a `StatusItem` for `Key.Left` left arrow on Menu won't work. 

I'm using `ENTER` this way, because `ListView` currently doesn't support `ENTER` to select an item, nor does it provide a "ItemDoubleClicked" event (#429).

**Comment by BDisp** [comment]
`ENTER` key is working on `Menu`.

**Comment by BDisp** [comment]
I'm going to create an `OpenSelectedItems` event for `ListView` right now. Invoked by the `ENTER` key and `DoubleClicked`.

**Comment by tig** [comment]
> `ENTER` key is working on `Menu`.

Not for me. It causes the selected Scenario to run instead of exiting. Have you tried reproducing on Windows? I can repro on Linux too.

(Note I just remembered OnKeyDown only works on Windows and thus `UI Catalog` scenarios currently can't exit on Linux...)

**Comment by BDisp** [comment]
Yes I did. It's working on both. I'll checkout your PR and see if it's happen too.

**Comment by BDisp** [comment]
> 
> 
> I'm going to create an `OpenSelectedItems` event for `ListView` right now. Invoked by the `ENTER` key and `DoubleClicked`.

Done! #440

**Comment by tig** [comment]
Pretty sure the underlying bug here is the same as what is causing #437.

**Comment by tig** [comment]
@BDisp this is fixed, right?
