### ISSUE TITLE
A secondary Toplevel with a Menubar and no other child window behaves badly

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#437]
See `UI Catalog`'s `TopLevelNoWindowBug` for repro. When run, the menu appears, but draws incorrectly and some keystrokes don't work.

```csharp
using Terminal.Gui;

namespace UICatalog {
	[ScenarioMetadata (Name: "TopLevelNoWindowBug", Description: "Illustrates that not having a Window causes Application.Run to wedge. #")]
	[ScenarioCategory ("Bug Repro")]

	class TopLevelNoWindowBug : Scenario {

		public override void Run ()
		{
			var ntop = new Toplevel (new Rect (0, 0, Application.Driver.Cols, Application.Driver.Rows));

			var menu = new MenuBar (new MenuBarItem [] {
				new MenuBarItem ("_Файл", new MenuItem [] {
					new MenuItem ("_Создать", "Creates new file", null),
					new MenuItem ("_Открыть", "", null),
					new MenuItem ("Со_хранить", "", null),
					new MenuItem ("_Выход", "", () => ntop.Running = false )
				}),
				new MenuBarItem ("_Edit", new MenuItem [] {
					new MenuItem ("_Copy", "", null),
					new MenuItem ("C_ut", "", null),
					new MenuItem ("_Paste", "", null)
				})
			});
			ntop.Add (menu);

			// BUGBUG: This being commmented out causes Application.Run to wedge.
			//var win = new Window ($"Scenario: {GetName ()}") {
			//	X = 0,
			//	Y = 1,
			//	Width = Dim.Fill (),
			//	Height = Dim.Fill ()
			//};
			//ntop.Add (win);

			Application.Run (ntop);
		}
	}
}
```

Note, because this code is running in `UICatalog` it is possible this won't reproduce if there is not ANOTHER `Toplevel` in the mix.

**Comment by BDisp** [comment]
@tig there can be only one top-level top. All top-levels must be built on top of an existing top-level. In this case instead of:
`var ntop = new Toplevel (new Rect (0, 0, Application.Driver.Cols, Application.Driver.Rows));`

will have to be:
`var ntop = Top;`

**Comment by tig** [comment]
> @tig there can be only one top-level top. All top-levels must be built on top of an existing top-level. In this case instead of:
> `var ntop = new Toplevel (new Rect (0, 0, Application.Driver.Cols, Application.Driver.Rows));`
> 
> will have to be:
> `var ntop = Top;`

Sorry, but you are incorrect. There may be bugs, but I have no doubt the design is such that multiple `Toplevel`s are supported. 

`Application.Run` calls `Application.Begin(Toplevel topLevel)` is and creates a `RunState` with the `topLevel` and puts it on `static Stack<Toplevel> toplevels`:

```csharp
		static public RunState Begin (Toplevel toplevel)
		{
			if (toplevel == null)
				throw new ArgumentNullException (nameof (toplevel));
			var rs = new RunState (toplevel);

			Init ();
			if (toplevel is ISupportInitializeNotification initializableNotification &&
			    !initializableNotification.IsInitialized) {
				initializableNotification.BeginInit();
				initializableNotification.EndInit();
			} else if (toplevel is ISupportInitialize initializable) {
				initializable.BeginInit();
				initializable.EndInit();
			}
			toplevels.Push (toplevel);
    ...
```
In other places, that stack is navigated to ensure all `TopLevels` are dealt with. E.g.:

```csharp
		static void TerminalResized ()
		{
			OnResized?.Invoke ();
			var full = new Rect (0, 0, Driver.Cols, Driver.Rows);
			Driver.Clip = full;
			foreach (var t in toplevels) {
				t.PositionToplevels ();
				t.RelativeLayout (full);
				t.LayoutSubviews ();
			}
			Refresh ();
		}
```

I built UICatalog this way because it was pretty clear to me that things were coded to support multiple calls to `Application.Run`.

**Comment by tig** [comment]
I have proven that this does not reproduce if the `Toplevel` in question is the one created `Application.Init()`.

So it's def a bug that only happens when subsequent `Toplevel`s are used. 

I've also noted that the (bad) behavior also manifests differently depending. For example a simple app like this doesn't wedge, but things don't work right:

```csharp
		static void Main (string [] args)
		{
			Application.Init ();
			_top = Toplevel.Create (); // Application.Top; 
			var menu = new MenuBar (new MenuBarItem [] {
				new MenuBarItem ("_File", new MenuItem [] {
					new MenuItem ("_Quit", "", () => Application.RequestStop() )
				}),
				new MenuBarItem ("_About...", "About this app", () =>  MessageBox.Query (0, 6, "About UI Catalog", "UI Catalog is a comprehensive sample library for Terminal.Gui", "Ok")),
			});
			_top.Add (menu);
			Application.Run (_top);
		}
```

The workaround is to add a `Window` to the `Toplevel`.

**Comment by tig** [comment]
Found the cause of the bug:

in `Core.cs`:

```csharp
		public override void Add (View view)
		{
			if (this == Application.Top) {
				if (view is MenuBar)
					HasMenuBar = true;
				if (view is StatusBar)
					HasStatusBar = true;
			}
			base.Add (view);
		}
```

This code (and other functions that deal with `HasMenuBar/HasStatusBar`) assumes there can be only one `Toplevel` and that it is `Application.Top`. 

To fix this, we should do something like this:

```csharp
		public override void Add (View view)
		{
			if (this is Toplevel) {
				if (view is MenuBar)
					HasMenuBar = true;
				if (view is StatusBar)
					HasStatusBar = true;
			}
			base.Add (view);
		}
```

I think. Not a critical bug, because there's a work around, and it is a pretty esoteric issue. But this is def. a bug.

**Comment by tig** [comment]
FWIW, I've worked around all of this in the latest `UI Catalog` by refactoring such that each time a `Scenario` runs I call `Application.Init` etc... and then when you exit the scenario the main app does another `Init`. IOW, it's now working such that the toplevel is always `Application.Top`. 

This bug should still be fixed eventually though because there are reasons to have multiple toplevels.

**Comment by BDisp** [comment]
> ```cs
> static void Main (string [] args)
> 		{
> 			Application.Init ();
> 			_top = Toplevel.Create (); // Application.Top; 
> ```

@tig, you are creating a new Top again because the call `Application.Init` already create a `Application.Top`. You can create all top-levels you want but you can only have one `Application.Top` at one time. Even `Window` is a toplevel, it's derived from `Toplevel` but it can't be an `Application.Top`. So why you want to waste resources on having many `Toplevels` instances if you can use only one? If you could opening all the console windows for each `Toplevel` it's worths, but you can't. So to maintain low resources is better use always the same `Application.Top` and rebuild on it.
In each `Application.Top` there can only be one `MenuBar` and only one `StatusBar`. I think this is logic at least for me. I've already submitted a PR #420 to change `HasMenuBar` and `HasStatusBar` types to `MenuBar` and `StatusBar` respectively. It's like an `MDI` where wou can have multiple windows but you have only one top-level.

**Comment by BDisp** [comment]
> Anywhere where `this` is compared to `Application.Top` is a bug related to this.

`Window` is also a `Toplevel`. Do you want to compare it to `Application.Top`? I doubt it.

**Comment by BDisp** [comment]
`Dialog` is derived from `Window`. Do you want to compare it to `Application.Top`? I doubt it.

**Comment by tig** [comment]
Note that the documentation is pretty clear that there can be multiple `TopLevel` windows, each with it's own `Menu`:

>You would use a toplevel Modal view for example to launch an entire new experience in your application, one where you would have a new top-level menu for example. You typically would add a Menu and a Window to your Toplevel, it would look like this:

**Comment by BDisp** [comment]
Yes I know @tig and that was what I said that each `Toplevel` can have a `Menu` and a `StatusBar`, but you can´t work with more than one each time, because they are `modal`. So you are creating a news `Toplevel `instances but all is using the same `Frame `or part of the `Frame `of the `Application.Top`. I only wanted to tell that.
