### ISSUE TITLE
Not working on Windows?

### ISSUE THREAD

**Issue by fanoI** [migueldeicaza/gui.cs#45]
Trying to compile this on Windows it wants "Unix" something?

>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Unix' does not exist in the namespace 'Mono' (are you missing an assembly reference?)	Terminal.Gui	V:\Downloads\gui.cs-master\gui.cs-master\Terminal.Gui\MonoCurses\mainloop.cs	28	Active
Error	CS0246	The type or namespace name 'Pollfd' could not be found (are you missing a using directive or an assembly reference?)	Terminal.Gui	V:\Downloads\gui.cs-master\gui.cs-master\Terminal.Gui\MonoCurses\mainloop.cs	86	Active
Error	CS0246	The type or namespace name 'PollEvents' could not be found (are you missing a using directive or an assembly reference?)	Terminal.Gui	V:\Downloads\gui.cs-master\gui.cs-master\Terminal.Gui\MonoCurses\mainloop.cs	217	Active
Error	CS0006	Metadata file 'V:\Downloads\gui.cs-master\gui.cs-master\Terminal.Gui\bin\Debug\Terminal.Gui.dll' could not be found	Terminal	V:\Downloads\gui.cs-master\gui.cs-master\CSC	1	Active

**Comment by migueldeicaza** [comment]
Did you restore the NuGet packages?   This should bring Mono.Posix.

**Comment by migueldeicaza** [comment]
That said - the Windows driver is not complete yet, see: 

https://github.com/migueldeicaza/gui.cs/issues/27

**Comment by migueldeicaza** [comment]
Duplicate

**Comment by migueldeicaza** [comment]
You are correct, this currently needs Mono.POsix, I need to move the code to a NuGet that will work.

**Comment by migueldeicaza** [comment]
I removed the Mono.Posix dependency to simplify things, but the Windows driver is still not ready :-)
