### ISSUE TITLE
HotKeys

### ISSUE THREAD

**Issue by d2ortiz** [migueldeicaza/gui.cs#455]
Add Boolean parameters in widget constructor that ignore the Hotkey creation for that widget

**Comment by tig** [comment]
Can you explain the use case more clearly? I want to make sure I understand.

Also, why does this need be a parameter in the constructor vs. a property? Adding more and more parameters to constructors doesn't scale.

**Comment by d2ortiz** [comment]
1. I use buttons to make a Menu. Using the first Upper case letter can cause the same letter will be used for different buttons,  we can avoid the problem ignoring the creation of the hot key for some widget. 

In my case, I created a widget called HLButtonGroup that create the menu and assign the hot keys

![image](https://user-images.githubusercontent.com/16270593/82484525-08bcde00-9aa8-11ea-90a0-fc1ccaf95b83.png)

2. Can be a property. I need to verify the hotkey creation to be sure, but a property may required a false default changing the behavior of previous developed applications. With a constructor only need additional constructor for new code and old code can behave as is now.

**Comment by tig** [comment]
Gotcha. FWIW `Termanal.Gui` is currently inconsistent on how hot keys are specified. `MenuBar` uses `_` as an indicator an `Button` uses first upper case character. I've opened #456 to track fixing this.
