### ISSUE TITLE
UI Catalog: Scenario showing using threads/async/wait

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#472]
A demo that shows how to use a background thread with async/await to show the SynchronizationContext in action and best practices on how to write that code.

**Comment by tig** [comment]
`Progress` now shows a simple threading use-case:

```csharp
			_timer = new Timer ((o) => {
				Application.MainLoop.Invoke (() => Pulse ());
			}, null, 0, 20);
```

But it does not (yet) illustrate using async/wait such that `MainLoopSyncContext` gets exercised. But it will someday...

**Comment by BDisp** [comment]
I'll do it if you want.

**Comment by tig** [comment]
> I'll do it if you want. But in another scenario or the same? I think it is better in a new one because what I have in mind will cover the whole scenario.

I'd like to continue to work on `Progress`. Feel free to add another scenario. If it uses threading tag it with `[ScenarioCategory ("Threading")]`.

**Comment by BDisp** [comment]
Done #539
