### ISSUE TITLE
UI Catalog: ListViews Scenarios

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#473]
Add Scenarios to show the different styles of ListViews that can be shown.

**Comment by fergusonr** [comment]
Tig, I'll pick this up. I've basically made a start with my ListsAndCombos.cs scenario. The changes will come through on my existing PR.

**Comment by tig** [comment]
Sweet. Let me know if you need any help.

-cek
Sent from mobile device. Expect brevity, typos, and dangerous driving.

________________________________
