### ISSUE TITLE
Make Windows draggable with the mouse.

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#5]
We are currently reporting the mouse movement events, but it looks like the terminal via curses
is not sending us the events we need when the mouse is clicked and then moved.

**Comment by migueldeicaza** [comment]
Ok, I managed to make the windows draggable.

The problem is that ncurses consumes events, unless you set the mouse timeout to zero, but then double-clicks are not produced.    I might need to do this, and just generate synthetic double clicks so I can get my move-events after the user presses a button.

**Comment by Slesa** [comment]
Why would that be needed? Shouldn't the text mode have the big advantage to be able to work mouse-free? I can see the advantage to select buttons and list items with the mouse, but dragging? Maybe in v2?

**Comment by tig** [comment]
This is supported now.
