### ISSUE TITLE
Typing goes all wrong on Windows/.NET Framework 4.7

### ISSUE THREAD

**Issue by sandord** [migueldeicaza/gui.cs#50]
I can type anywhere, characters are just printed on top of the views.
Typing a non-alpha character makes the next character overwrite the previous etc.

**Comment by gregbair** [comment]
It happens to me on netcoreapp2.0 on Windows 10, both cmd.exe and powershell.

**Comment by migueldeicaza** [comment]
Thanks for reporting the bug!

Simple mistake!   I did not pass true to ReadKey, fixed and published.

**Comment by sandord** [comment]
Thanks but I still can't type any non-alpha characters.

**Comment by fabianPas** [comment]
I can't input non-alpha characters either.
