### ISSUE TITLE
Computed Layout: Pos.Left/Top/Bottom/Right(Win) throws exception

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#504]
```csharp
			var defaultButton = new Button ("Quit") {
				X = Pos.Center (),
				// BUGBUG: Throws an exception
				Y= Pos.Bottom(Win),
```

>System.Exception: 'There is a recursive cycle in the relative Pos/Dim in the views of ContentView()({X=1,Y=1,Width=95,Height=18})'

If `Y= Pos.Bottom(Win)` is changed to `Y= Pos.Bottom(Win) - 0`  or `Y= Pos.Bottom(Win) - 1` it does not fault. 

While `Y= Pos.Bottom(Win)` is outside of `Win` this is actually not a valid thing to do, but it should not throw an exception, right?

This repros for `Left`, `Top`, `Bottom`, and `Right`.

**Comment by tig** [comment]
Better repro:

```csharp
		public override void Setup ()
		{
			// Put your scenario code here, e.g.
			Win.Add (new Button ("Press me!") {
				X = Pos.Center (),
				Y = Pos.Center (),
				Clicked = () => MessageBox.Query (20, 7, "Hi", "Neat?", "Yes", "No")
			});

			var button = new Button ("button");
			button.X = Pos.Center ();
			button.Y = Pos.Bottom (Win) + 0;
			button.Y = Pos.Bottom (Win) + 1;
			button.Y = Pos.Bottom (Win) - 10;
			// BUGBUG: Throws an exception
			button.Y = Pos.Bottom (Win);

			Win.Add (button);
		}
```

I can't get this to repro in UnitTests... 

```csharp
[Fact]
public void Bottom_Win_ShouldNotThrow ()
{
	// Setup Mock driver
	Application.Init (new FakeDriver ());

	//var winRect = new Rect (0, 0, 10, 10);
	var win = new Window ("window") {
		X = Pos.Center (),
		Y = Pos.Center (),
	};
	Application.Top.Add (win);

	var button = new Button ("button");
	button.X = Pos.Center ();
	button.Y = Pos.Bottom (win) + 0;
	button.Y = Pos.Bottom (win) + 1;
	// BUGBUG: Throws an exception
	button.Y = Pos.Bottom (win);

	win.Add (button);

	Application.Shutdown ();
}

```

Hmmm..

**Comment by tig** [comment]
`button.Y = Pos.Bottom() + 1` results in `{Pos.Combine(Pos.View(side=bottom, target=Window()({X=0,Y=0,Width=0,Height=0}))+Pos.Absolute(0))}`.

`button.Y = Pos.Bottom()` results in `{Pos.View(side=bottom, target=Window()({X=0,Y=0,Width=0,Height=0}))}`.

So this has something to do with lack of `PosCombine`

**Comment by tig** [comment]
Repro test-case:

```csharp
		[Fact]
		public void Bottom_Win_ShouldNotThrow ()
		{
			// Setup Fake driver
			Application.Init (new FakeDriver ());

			var win = new Window ("window") {
				X = 0,
				Y = 0,
				Width = Dim.Fill (),
				Height = Dim.Fill (),
			};
			Application.Top.Add (win);

			var button = new Button ("button") {
				X = Pos.Center (),
			};
			button.Y = Pos.Bottom (win) + 0;
			// BUGBUG: Causes exception in Application.Run
			button.Y = Pos.Bottom (win);

			win.Add (button);

			Application.Iteration = () => {
				Application.RequestStop ();
			};
			Assert.Throws<InvalidOperationException> (() => Application.Run());
			Application.Shutdown ();
		}
```

Now to see if the fix causes any regressions....

**Comment by tig** [comment]
My fix feels like a hack. I am going to ask @migueldeicaza to look at this and make a call on how to fix it.

**Comment by BDisp** [comment]
`System.InvalidOperationException: 'TopologicalSort (for Pos/Dim) cannot find Window()({X=0,Y=0,Width=120,Height=30}). Did you forget to add it to ContentView()({X=1,Y=1,Width=118,Height=28})?'`

Wasn't it supposed to be the other way around? It should notify that it forgot to add ContentView to the Window. It seems that there is some inversion here.

**Comment by tig** [comment]
No, the logic is right. If you don't `Add` you'll get this same error.
