### ISSUE TITLE
Strange behavior with the color of the scenario changing from time to time in linux

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#515]
I am observing a strange behavior with the color of the scenario changing from time to time in linux, verified here.
![color-behaviour](https://user-images.githubusercontent.com/13117724/82738765-2d2beb00-9d32-11ea-8263-354c1ff3e037.gif)
![color-behaviour2](https://user-images.githubusercontent.com/13117724/82738767-2e5d1800-9d32-11ea-8630-0801a6226bab.gif)

**Comment by tig** [comment]
Very odd.

**Comment by BDisp** [comment]
Yeah. Do you remember the other time you said that the console was just black and white? This was what was happening. Are you using the TERM = xterm-1006 setting on linux?

**Comment by tig** [comment]
I don't know what that is. I have never changed any settings on Linux. Sorry. 

I can't repro this in WSL under Windows Terminal.

**Comment by tig** [comment]
Just repo'd it (didn't change any "TERM" settings since I don't actually know what those are):

![image](https://user-images.githubusercontent.com/585482/82739559-abba6580-9cfd-11ea-8f77-a5ca6847bed7.png)

**Comment by BDisp** [comment]
Aha. `TERM=xterm-1006` allows you to use the mouse across the screen. You can try clicking more to the right of the screen and the mouse stops working because Linux suspends the system in some way.
If you want to use this configuration do the following:

`nano .bashrc`

And at the end add:

`export TERM=xterm-1006`

Save and restart WSL

**Comment by BDisp** [comment]
The cause is the` Curses.endwin ()` call which forces the restoration of linux to default and does not allow any further calls to be made to any `Curses `functions. It is not easy to solve, because as there are no more `Toplevels `you can not just call this function if it really is to close the program completely. In `windows `this is no problem. Same as #536
