### ISSUE TITLE
MessageBoxneed to take ustrings

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#521]
This is annoying:

    Clicked = () => MessageBox.Query (20, 7, Win.Title.ToString (), "Neat?", "Yes", "No")

**Comment by BDisp** [comment]
Maybe it was created by someone not very friendly or knowledgeable about ustrings :-)
It is changeable, it can give many errors in many implementations that use the gui.

**Comment by tig** [comment]
FWIW, I belong to the group of people who "not very friendly or knowledgeable about ustrings".

**Comment by BDisp** [comment]
It was just a joke. Not to be upset :-)

**Comment by tig** [comment]
Yep. I was joking too.

(FWIW, it takes a LOT to get me upset).
