### ISSUE TITLE
Proposal to re-organize the source to make dev/debugging easier

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#541]
Now that I've gotten my head around this project by writing a comprehensive sample, fixing a dozen bugs, adding new features, revising the API documentation, and reading/categorizing every Issue I feel pretty comfortable saying the following: 

1. The current structure makes it hard for newcomers to understand what does what. A little re-arranging would make it all more logical. As a result contributors introduce bugs (or potential bugs) when they try to contribute. 
2. The current structure makes debugging harder than it should be. I don't believe in "one class per file", but I also know having to scroll through a 2600 line file containing 5 fairly massive (and in the case of `Window`, not related) classes is painful. 
3. Legacy structure derived from where this project came from (mono-curses) causes confusion. e.g. `MainLoop` is a fundamental, "core" concept of `Terminal.gui`, but is found in an unrelated namespace (`Mono.Terminal`) and bundled with a bunch of `curses` crap (pardon the pun). 

Here's my understanding of how the the project currently is laid out.  Please let me know if I misunderstood something:

* `Terminal.Gui/` - The folder containing all files required to build the library (and nuget package) for people to build console GUI apps
   * `MonoCurses/` - A folder containing a (diverged) copy of `Mono.Terminal` from `mono-curses` that provides two (independent) things:
       * The curses implementation for the Unix driver (see below)
       * The `MainLoop` structure & implementation used by `Application` (see below). 

   * `Types`/ - A folder (not namespace) containing:
      * `Point`, `Rect`, and `Size` which are ancient versions of the modern `System.Drawing.Point`, `System.Drawing.Size`, and `System.Drawning.Rectangle`. [*Tig's Opinion: these types should be updated to match the current versions from `System.Drawing`, particuarly given how they now support more modern C# stuff.*]
      * `DimPos` - The core of Terminal.Gui's *Computed Layout* system. These classes have deep dependencies on `View`. [*Tig's Opinion: this file should be organized 'closer' to `View` as they are completely dependent.*]

   * `Drivers/` - A folder (not namespace) containing the terminal drivers for .NET, Unix, and Windows plus their base `ConsoleDriver` class.

   * `Events.cs` - Defines keyboard and mouse related structs/classes. It is almost all 'struct' except I added a `ToString` implementation to `KeyEvent` requiring it to become a class. [*Tig's Opinion: these structures should be more obviously/closely organized with the definition of `Responder` and `View`.*]

   * `Core.cs` - The "core" (duh) of the library
     * `Application` - A `static` class that provides the base 'driver'. Given it defines an application it is both logically and (because it's `static`) literally a singleton. It has direct dependencies on `MonoTerminal.MainLoop`, `Events.cs` `NetDriver`, `CursesDriver`, `WindowsDriver`, `Responder`, `View`, and `TopLevel` (and nothing else). 
     * `Responder` - Key & mouse events
         * `View` - Adds the basics of laying out and drawing stuff, enables "modeless controls" that both render and take mouse/keyboard input.
             * `TopLevel` - Enables modal views; define the concept of MenuBar and StatusBar
                * `Window` - A TopLevel with a visible frame and Title

    * `Dialogs/` - A folder (not namespace) containing all built-in classes that derive from `Window`. [*Tig's opinion: This folder should be renamed `Windows` (like `Views`). *]

    * `Views/` - A folder (not namespace) containing all built-in classes that drive from `View` (non-modals).

My specific proposal for re-organizing: 

- The `Terminal.Gui` folder should have the following structure:
  - `Terminal.Gui.sln`
  - `Core/` - Source files for all types that comprise the core building blocks of `Terminal.Gui` - `Application`, `MainLoop`, `ConsoleDriver`, `Events.cs`, `PosDim.cs`, `Responder`, `View`, and `Toplevel`. 
  - `ConsoleDrivers/` - Source files for the three `ConsoleDriver`-based drivers. 
  - `Windows/` - Source files for all built-in Window-derived (modal) classes
  - `Views/` - Source files for all built-in non-modal `View` derived classes

Like this:
![image](https://user-images.githubusercontent.com/585482/82776028-c1678200-9e06-11ea-8c0a-e8f2fa017343.png)

As you can see I've already got a branch setup where I've already done it... ;-)

What do you think?

**Comment by BDisp** [comment]
I fully agree. It is much better.

**Comment by migueldeicaza** [comment]
I am fine with this change.

My only request is that the move of files be done with "git mv", so that we preserve the history of the files and that we decouple the file shuffling from any additional code or refactorings.    I think that this might already be the case, but I wanted to confirm

**Comment by tig** [comment]
> My only request is that the move of files be done with "git mv", so that we preserve the history of the files and that we decouple the file shuffling from any additional code or refactorings. I think that this might already be the case, but I wanted to confirm

I don't think I did this right in the current PR. I will re-do it all using `git mv` as I agree it's important we retain history.

I may do this in several phases to be sure I don't break anything now that you've (correctly) raised it.
