### ISSUE TITLE
ProgressBar: Enhancement ideas

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#546]
- Support `Height` > 1
- Support a `Text` property that would be centered. Clients could do  `pc.Text = "${pc.Fraction:F0}%"`. 
- Support a `SegmentCharacter` property that would allow caller to specify the character drawn for each segment (currently hard coded to `Driver.Stipple`).
- Add a marquee mode (like https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.progressbarstyle?view=netcore-3.1). `Text` would scroll in marquee fashion.
- It should render more detail depending on the height. 1 line, current design; 2 progress plus percentage; 3 framed; 4 frame with progress; 6 frame wothnprogress padded (via #52).

**Comment by ichan-akira** [comment]
> Support a SegmentCharacter property that would allow caller to specify the character drawn for each segment (currently hard coded to Driver.Stipple).

Would be very great so we can actually draw opaque progress bar then.

**Comment by BDisp** [comment]
Guys, what do you think about this innovation?

![progressbar](https://user-images.githubusercontent.com/13117724/126051210-ad438c34-18f4-4276-a079-cb2d4e812c7e.gif)

**Comment by ichan-akira** [comment]
The continuous and opaque one is the one that I actually needed that will be excellent!

**Comment by hindermath** [comment]
All styles are good and I like them all!

**Comment by BDisp** [comment]
I intend to added options to print fraction text and framed before submit a PR.

**Comment by BDisp** [comment]
>     * Support a `Text` property that would be centered. Clients could do  `pc.Text = "${pc.Fraction:F0}%"`

I don't agree with this be a `Text `property because the `ProgressBar `already have the fraction value and must be him to handle this and print automatically, case for e.g. a `FractionText `enum property (`None`, `Inside`, `Outside`) is set to `Inside `or `Outside`. What yours opinions about this?

**Comment by BDisp** [comment]
>     * Support a `SegmentCharacter` property that would allow caller to specify the character drawn for each segment (currently hard coded to `Driver.Stipple`).

I added support to this but I do not guarantee that will work with all the `SegmentCharacter` choosed.

**Comment by BDisp** [comment]
>     * 6 frame wothnprogress padded

I didn't understand this part. Can someone explains, please?

**Comment by ichan-akira** [comment]
> > ```
> > * 6 frame wothnprogress padded
> > ```
> 
> I didn't understand this part. Can someone explains, please?

Originally from @migueldeicaza at https://github.com/migueldeicaza/gui.cs/issues/52

**Comment by BDisp** [comment]
> Originally from @migueldeicaza at #52

Yes I know that, thanks. But is the same thing. I'll ignore this part.

**Comment by BDisp** [comment]
Done folks. #546

**Comment by migueldeicaza** [comment]
Glorious!
