### ISSUE TITLE
UI-Catalog window is not updating after size restored

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#551]
To repo: With a normal window, click on any scene and maximize the window. Ctrl + Q to quit and the main window remains at its initial size when it should be maximized as well.

**Comment by tig** [comment]
Interesting...

**Comment by BDisp** [comment]
I'm almost to send a PR to solves all this. #536, #515, #518

**Comment by tig** [comment]
I think this is related to the way `WindowsDriver` attaches/detaches to the console. 

Right now it never explicitly attaches or detaches, but just uses the implied attach by calling `GetStdHandle`. I think the fix may be to explicitly call `AllocConsole` in the `WindowsConsole` constructor and `FreeConsole` in `Cleanup`.

**Comment by BDisp** [comment]
But that I think does not solve the problem in Unix and NetDriver because they have other methods of freeing up their resources. Anyway, I will present and we will exchange ideas.

**Comment by tig** [comment]
Oh, so this repros on Unix as  well? Gotcha!

**Comment by BDisp** [comment]
As a matter of fact this is not specific because in Unix refresh always updates the screen size, but the mouse and color problem does.
