### ISSUE TITLE
How to terminate cleanly the program?

### ISSUE THREAD

**Issue by fanoI** [migueldeicaza/gui.cs#56]
I expected to see a sort "Application.Stop()" but it does not exists, maybe the application is supposed to terminate when top.Running is set to false? In reality this makes that the application continues to run but it does not receive key pressions anymore.

The "rude" way to call "Environment.Exit(0)" does work but it leave the Console in a unclean state as you can see here:

[![Broken_Console.png](https://s10.postimg.org/6hatvdm3t/Broken_Console.png)](https://postimg.org/image/j8p01vvvp/)

the expected behavior is to have the cursor at the end of the application and with the previous Console colors restored.

**Comment by migueldeicaza** [comment]
You can call `Application.RequestStop`, which will do exactly what you are doing there. 

The bug you are experiencing is just a bug in the `System.Console` driver, it should clear the screen after completion.

**Comment by migueldeicaza** [comment]
This has been fixed on git.

**Comment by fanoI** [comment]
Thank you!

**Comment by fanoI** [comment]
Tested today after updating. The issue continues to be present...

**Comment by ebekker** [comment]
For me, the screen appears to be getting cleaned up, reverting to the correct colors but then the app appears to hang.
