### ISSUE TITLE
Something broken the background drawing.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#562]
It is also advisable to always test with a modal dialog box to check the background design of the previous visible toplevel.
![background-paint](https://user-images.githubusercontent.com/13117724/83084161-1661fd00-a080-11ea-9c7a-d922b0878617.gif)

**Comment by tig** [comment]
Heck, I didn't even know you could drag windows like that. ;-)

**Comment by BDisp** [comment]
Lol for a long time. This case is on `Windows `but on `Linux `it also works. As you can see the mouse is working fine on `Windows`, at least with me. Now we can change the point of click so that instead of being in the `MenuBar`, it will only be activated in the word, it will be activated in the width of the `MenuItem`.
