### ISSUE TITLE
Implement unit and regression tests

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#566]
This project desperately needs a set of automated unit and regression tests.

**Comment by tig** [comment]
My ideas:

- Use [xunit](https://xunit.net/) - I've used it before and dig it. 
- Ensure all tests run as part of CI/CD - I would prefer we use Github actions over Azure Pipelines or TravisCI just to keep things simple and contained.
- I envision a set of tests that leverage UICatalog `Scenarios` - build a mock `ConsoleDriver` that lets tests specify how a console buffer *should* look and then check after the Scenario has run.

**Comment by tig** [comment]
I now have a plan for the first set of automated tests.

- Define a set of `View` unit tests
  - Initialize Absolute
  - Initialize Computed
  - For each typical DimPos scenario set X, Y, Height, Width and verify no crashes
  - For anything with a Text or Title property, throw different strings at 'em ensuring no crashes (see #617)
  - Etc...
- I will leverage the code in the new `AllViewsTester` to dynamically run through every `View` derived class and automate most of the above so one test set runs against all controls.
- I'll enable per-control tests

This will be the start. I'm willing to bet that once the infrastructure is in place, having more people contribute tests will be contagious.

**Comment by BDisp** [comment]
> This will be the start. I'm willing to bet that once the infrastructure is in place, having more people contribute tests will be contagious.

I look forward to using it. I am a great advocate of regression testing and this initiative makes it much more contagious, believe me. Thank you.

**Comment by migueldeicaza** [comment]
Charlie asked me to comment on this.

I agree that we need unit tests, but have struggled to come up with a plan.

XUnit sounds like a fine choice

**Comment by tig** [comment]
Woot! Closed with #648
