### ISSUE TITLE
Provide a LayoutComplete event for View

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#569]
It is very common for apps and Views to need to know when they have been resized or their layout otherwise changed.

People are currently using `Application.Loaded` to get initial sizing or `Application.Resized` to get notified when the terminal size changes. 

But neither of these are useful for when a parent view's size changes independently of the terminal sizing. In preparation for being able to resize windows (e.g. consider the left & right panes of UI Catalog being resizable) we need a way for Views to know their layout has changed. It's possible to do this in a sub-class by overriding `LayoutSubviews` but this doesn't help app writers.

I'm proposing a new API for `View` to address this:

```csharp
		/// <summary>
		/// Event arguments for the <see cref="LayoutComplete"/> event.
		/// </summary>
		public class LayoutEventArgs : EventArgs {
			/// <summary>
			/// The view-relative bounds of the <see cref="View"/> before it was laid out.
			/// </summary>
			public Rect OldBounds { get; set; }
		}

		/// <summary>
		/// Fired after the <see cref="LayoutSubviews"/> method has completed.
		/// </summary>
		/// <remarks>
		/// Subscribe to this event to perform tasks when the <see cref="View"/> has been resized or the layout has otherwise changed.
		/// </remarks>
		public event EventHandler<LayoutEventArgs> LayoutComplete;

		/// <summary>
		/// Raises the <see cref="LayoutComplete"/> event. Called from  <see cref="LayoutSubviews"/> after all sub-views have been laid out.
		/// </summary>
		internal virtual void OnLayoutComplete (LayoutEventArgs args)
		{
			LayoutComplete?.Invoke (this, args);
		}
```

Existing classes that override `LayoutSubViews`, like `Dialog` can use this isntead:

```csharp
		public Dialog (ustring title, int width, int height, params Button [] buttons) : base (title, padding: padding)
		{
			X = Pos.Center ();
			Y = Pos.Center ();
			Width = width;
			Height = height;
			ColorScheme = Colors.Dialog;
			Modal = true;

			if (buttons != null) {
				foreach (var b in buttons) {
					this.buttons.Add (b);
					Add (b);
				}
			}

			LayoutComplete += (sender, a) => AdjustButtonLayout ();
		}

		void AdjustButtonLayout ()
		{
			int buttonSpace = 0;
			int maxHeight = 0;

			foreach (var b in buttons) {
				buttonSpace += b.Frame.Width + 1;
				maxHeight = Math.Max (maxHeight, b.Frame.Height);
			}
			const int borderWidth = 2;
			var start = (Frame.Width - borderWidth - buttonSpace) / 2;

			var y = Frame.Height - borderWidth - maxHeight - 1 - padding;
			foreach (var b in buttons) {
				var bf = b.Frame;

				b.Frame = new Rect (start, y, bf.Width, bf.Height);

				start += bf.Width + 1;
			}
		}
```

in `demo.cs`:

```csharp
		var bottom = new Label ("This should go on the bottom of the same top-level!");
		win.Add (bottom);
		var bottom2 = new Label ("This should go on the bottom of another top-level!");
		top.Add (bottom2);

		top.LayoutComplete += (sender, e) => {
			bottom.X = win.X;
			bottom.Y = Pos.Bottom (win) - Pos.Top (win) - margin;
			bottom2.X = Pos.Left (win);
			bottom2.Y = Pos.Bottom (win);
		};
```

Etc...

I've got a PR basically ready but want input before I submit it. Thoughts?

**Comment by tig** [comment]
Questions I have:

1. What properties do subscribers really care about? I assumed `OldBounds`, but maybe `OldFrame` is better? I note that `Dialog` uses Frame (I think incorrectly) to re-layout buttons. I say incorrectly, because the buttons should be located using view-relative coords.
2. Is there a need for a 'pre' Layout event as well? I can't think of any use case, and I've not found any code that overrides `LayoutSubViews` that does pre-processing, so I'm guess no.

**Comment by BDisp** [comment]
It depends on the value being passed, whether it be from `Frame `or `Bounds`. `Frame `is relative to the position of the `View `on the screen and the `Bound `is relative to 0.0, `Frame.Width`, `Frame.Heigth`. By the way, the `Frame `has to be redesigned so that it can have negative `X` and `Y` axes so that they are not drawn while the values are negative and also cannot be drawn if the values are greater than their container

**Comment by tig** [comment]
The new `DrawWindowFrame` code *is* defensive to negative values.
