### ISSUE TITLE
Enable Pos.Center(View)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#571]
Right now it's not possible/easy to center a View on another View because `Pos.Center(View)` does not exist. I may be missing something. 

I'd like to be able to do the following to have this button be centered below `frame`:

```csharp
			var showMessageBoxButton = new Button ("Show MessageBox") {
				X = Pos.Center (frame),
				Y = Pos.Bottom (frame),
```

**Comment by migueldeicaza** [comment]
Would the `frame` be the desired frame, or would that be the referenced view?

`Pos.CenterX`/`Pos.CenterY` are easy to do, if they do not need to take the new view width into consideration.   So to center things, it would still need something like:

```
X = Pos.Center (container) - SomeConstant;
Y = Pos.Center (container) - otherControl.Y;
```

**Comment by tig** [comment]
Closing; there are ways of doing this and lots of samples now show it.
