### ISSUE TITLE
Running on Visual Studio Mac (VSM)

### ISSUE THREAD

**Issue by strangegt** [migueldeicaza/gui.cs#579]
Hi
My VSM (v8.6.1) is in Spanish, then some can be bad translation, my english is not good.

I clone the repository and load the solution in VSM and all compile properly
But when run with the default config, wich use the terminal docked in the a tab of the IDE, the program works but with some display errors.(Lines breaks, and the screen seen broken)

For working fine i must to disable embedded terminal (this is a global option, cant be done by project), then the program run on external console properly
Nice job
PD.
you can udpate instructions to run on mac
Open solution on VSM and run on external terminal

**Comment by migueldeicaza** [comment]
I had a similar problem recently, and reported that to the VSMac folks, an update to VSMac should have that fixed.
