### ISSUE TITLE
Button: Cannot be resized by changing Frame.

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#583]
In the `LayoutStyle.Absolute`, views should be able to be moved and resized by changing the `Frame` property. With `Button` adjusting the location works, but not size (nothing happens).

**Comment by BDisp** [comment]
That's because it is forced by this method to `Height = 1`:

```
int SetWidthHeight (ustring text, bool is_default)
{
	int w = text.Length + 4 + (is_default ? 2 : 0);
	Width = w;
	Height = 1;
	return w;
}

```

**Comment by tig** [comment]
Nope. When `LayoutStyle.Absolute` is set, `SetWidthHeight` never gets called when `Frame` changes.

**Comment by tig** [comment]
FWIW, the `Buttons` UI Catalog scenario now has a repro for this Issue (in #601)

![image](https://user-images.githubusercontent.com/585482/83664433-39f8dc00-a587-11ea-9da9-f3c2715d4462.png)
