### ISSUE TITLE
ScrollView: Support horizontal scrolling with mouse

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#585]
Not sure if this applies on Unix or not.

I love what @BDisp has done in terms of getting the vertical mouse wheel working. It makes me want to be able to use my horizontal scroll wheel to scroll Scrollviews horizontally as well.

**Comment by BDisp** [comment]
I think neither `Windows `nor `Curses `supports this natively.

**Comment by BDisp** [comment]
This is already working with the Shift + wheel down and up in the `WindowsDriver `and `Unix`.
In the `NerDriver `is working with the Ctrl + wheel down and up.

**Comment by tig** [comment]
`WindowsDriver` def shows horz wheel events in the `Mouse` scenario, so this is possible on Windows for sure.

However, given shift + wheel works, I'm closing this as wont-fix.
