### ISSUE TITLE
[design] Text editors should handle the Tab key and provide Ctrl+Tab to move to the next View.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#589]
If I am typing in a text editor I would like to use all the available keys that can help me in its editing and not be worried if when I look at the screen I am already typing in another `View `after all. In `Windows`, the `TextBox `with multiple lines has this behavior, that is, I have to type `Ctrl + Tab` to move to the next control. `Gui.cs` already provides `Shift + Tab` to move to the previous control. Another example is the `Tab `control which when pressed opens the next `Tab`. Now a mandatory rule is `Views `that are justified in having to really need the `Tab `key to have to code `Ctrl + Tab` to allow moving to the next control. Or even better is that we are not too worried about forgetting it is in TopLevel's ProcessKey that we consider by default the two alternatives to move to the next `View `that would be `Tab `and `Ctrl + Tab`. That said, I think that a `View `cannot take hold of both of these alternatives or there can never be an alternative to moving to the next control. Excuse the long will but I would like to put my point of view.

**Comment by BDisp** [comment]
@tig please teach me how to put the label on the issue. Thank you.

**Comment by tig** [comment]
@migueldeicaza would have to give you rights to do that.

**Comment by BDisp** [comment]
Then okay. As the other time you asked me to put a label I thought I could do that. So it's not worth it :-)

**Comment by tig** [comment]
> In Windows, the TextBox with multiple lines has this behavior, that is, I have to type Ctrl + Tab to move to the next control.

This is not true. I just tried 3 examples:

- ConEmu's Environment Dialog:
![image](https://user-images.githubusercontent.com/585482/83423843-c9b45400-a3e8-11ea-8ebb-8aa814f0024e.png)

- My own MCE Controller's Command's dialog:
![image](https://user-images.githubusercontent.com/585482/83423904-dcc72400-a3e8-11ea-87bf-b04b7952dccb.png)

- Outlook's Contact editor
![image](https://user-images.githubusercontent.com/585482/83424038-16982a80-a3e9-11ea-8470-effc72ae50d2.png)

In all cases, `tab` tabs through ALL controls in the form. And `shift-tab` reverses through ALL controls. Even multi-line text controls. To put a tab in the control you must use 

In both Outlook and ConEmu `ctrl-tab` moves moves between dialog screens. 

If a Windows multi-line edit box has "AcceptTab" turned on (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.textboxbase.acceptstab?view=netcore-3.1).

Given how important using the keyboard for navigation is for console GUI apps, I really believe in the tenets expressed in the contributors guide:

## User Experience Tenets

**Terminal.Gui**, as a UI framework, heavily influences how console graphical user interfaces (GUIs) work. We use the following [tenets](https://ceklog.kindel.com/2020/02/10/tenets/) to guide us:

> *NOTE: Like all tenets, these are up for debate. If you disagree, have questions, or suggestions about these tenets and guideliens submit an Issue using the [design](https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+label%3Adesign) tag.*
> 
> 1. **Honor What's Come Before**. The Mac and Windows OS's have well established GUI idioms that are mostly consistent. We adhere to these versus inventing new ways for users to do things. For example, **Terminal.Gui** adopts the `ctrl/command-c`, `ctrl/command-v`, and `ctrl/command-x` keyboard shortcuts for cut, copy, and paste versus defining new shortcuts.
> 2. **Consistency Matters**. Common UI idioms should be consistent across the GUI framework. For example, `ctrl/command-q` quits/exits all modal views. See [Issue #456](https://github.com/migueldeicaza/gui.cs/issues/456) as a counter example that should be fixed.
> 3. **Honor the OS, but Work Everywhere**. **Terminal.Gui** is cross-platform, but we support taking advantage of a platform's unique advantages. For example the Windows Console API is richer than the Unix API in terms of keyboard handling. Thus, in Windows pressing the `alt` key in a **Terminal.Gui** app will activate the `MenuBar`, but in Unix the user has to press the full hotkey (e.g. `alt-f`) or `F9`. 
> 4. **Keyboard first, Mouse also**. Users use consoles primarily with the keyboard; **Terminal.Gui** is optimized for getting stuff done without using the mouse. However, as a GUI framework, the mouse is essential, thus we strive to ensure that everything also works via the mouse.

If we follow those tenets then the way we address this is by adding a OPTION to `TextView` that allows apps that DO want to accept `tabs` to do so. But we make the default be `tab` moves to next control.

Note that in UIs where the ONLY control is `TextView` (or `HexView`) the default behavior should be "`tab` inserts a tab"

**Comment by BDisp** [comment]
@tig try in the `Outlook`'s contact editor write a note, on the rigtth of the `Addresses`, and press `Tab `to see what happens. Really now the multiline of the `TextBox `is no longer working like this but it used to be. When I refer to editors I mean those who are truly an editor of great texts where you use them for a long time to record events, stories, etc ...
Like `TextView `for example. As for `ConEmu`, I don't use it so I can't comment. As for the suggestion to add to `Views `the option of how to use the Tab key, I fully agree and that is to follow the main tenets.
