### ISSUE TITLE
What about data binding?

### ISSUE THREAD

**Issue by FSharpCSharp** [migueldeicaza/gui.cs#59]
I have already looked at all the documents and other issues. Unfortunately, I couldn't find anything about it. So now my question: What about the topic of data binding? Is this already integrated by default, or is it still being implemented?

**Comment by migueldeicaza** [comment]
I have no idea what that would involve.

**Comment by FSharpCSharp** [comment]
@migueldeicaza 
Well, there used to be a console UI framework, which also offered data binding. This made it possible to build the applications for the console almost exactly as you know it from WPF. You could almost take over the XAML 1:1. And because of the topic of data binding, updating the data has also worked directly. Wouldn't that be something for this project, too? [Here ](https://github.com/elw00d/consoleframework)is the link to the other project I mean. Maybe it's worth taking a look into it, because they have already solved the problem.

**Comment by ericsink** [comment]
FWIW, I would probably prefer that binding not be a part of this library. It could certainly be implemented as a higher-level library on top of this one.

**Comment by migueldeicaza** [comment]
Makes sense, going to close this for now.

**Comment by jinek** [comment]
Hello colleagues. I'm working on relevant project which assumes full XAML support, data binding, animation etc 
https://github.com/jinek/Consolonia
That is TUI implementation of Avalonia UI

**Comment by FSharpCSharp** [comment]
Wow that looks really great. Thanks for the link, I will have a closer look in the next few days.
