### ISSUE TITLE
Is it possible to paint any control?

### ISSUE THREAD

**Issue by Zuzuk-null** [migueldeicaza/gui.cs#592]
Is it possible to paint any control? In this case, I am interested in the TextField element, I use it in [Terminal.Gui.Elmish](https://github.com/DieselMeister/Terminal.Gui.Elmish):
```F#
textField [
    Styles [
        Pos (AbsPos 0, AbsPos 1)
        Colors (Color.White, Color.Red)
        ]
    Value "Пароль"
    OnChanged (fun t -> Vk.login <- t)
]
```
This example has an error: When the color is set, the element still remains green
I can't figure out where the error is - in Terminal.Gui, Terminal.Gui.Elmish or in my code.
The version of Terminal.Gui that I use is 0.81.0

**Comment by Zuzuk-null** [comment]
I will answer any questions that can help come to a problem solution

**Comment by BDisp** [comment]
Try this:

`ColorScheme (Color.White, Color.Red)`

**Comment by Zuzuk-null** [comment]
> Try this:
> 
> `ColorScheme (Color.White, Color.Red)`
It doesn't work. Color Scheme is represented as a discriminated union
```Fsharp
type ColorScheme =
    | Normal
    | Focus
    | HotNormal
    | HotFocus
```

**Comment by BDisp** [comment]
That library is out of date in relation to [`Terminal.Gui`](https://github.com/migueldeicaza/gui.cs). In `FSharpExample `replaces the following on the line 332 on the `OnKeyDownPressUpDemo`:

```
        let mutable listView = new ListView (list,
            X = Pos.At(0),
            Y = Pos.At(0),
            Width = Dim.Fill () - Dim.op_Implicit(1),
            Height = Dim.Fill () - Dim.op_Implicit(2)
            )
        listView.ColorScheme <- Colors.TopLevel

```
For this:

```
        let mutable listView = new ListView (list,
            X = Pos.At(0),
            Y = Pos.At(0),
            Width = Dim.Fill () - Dim.op_Implicit(1),
            Height = Dim.Fill () - Dim.op_Implicit(2),
            ColorScheme = Colors.TopLevel
            )

```
See my PR #594

**Comment by tig** [comment]
Looks like this is answered. Closing. Reopen if that's wrong.

**Comment by smolck** [comment]
@Zuzuk-null Not sure if you're still dealing with this issue, but just in case and for future reference, I think `Terminal.Gui.Elmish` version `0.1.8-preview1` might fix your problem: see https://github.com/DieselMeister/Terminal.Gui.Elmish/issues/13#issuecomment-667655811
