### ISSUE TITLE
Error when running the stand alone example

### ISSUE THREAD

**Issue by jeffreyleblanc225** [migueldeicaza/gui.cs#60]
In .net core on ubuntu 16.04

$ dotnet run
Curses failed to initialize, the exception is: System.DllNotFoundException: Unable to load DLL 'dl': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Unix.Terminal.Curses.dlopen(String file, Int32 mode)
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ncurses': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Unix.Terminal.Curses.raw()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init()
   at Demo.Main() in /home/user/newTest/gui.cs/StandaloneExample/Program.cs:line 152

**Comment by migueldeicaza** [comment]
Bummer, I knew that pull request was going to come back to bite me.

Edit the source and replace "dl" for "libc" in DllImport.

**Comment by jeffreyleblanc225** [comment]
Ok I've made the changes in bindings.cs and I get this now.

$ dotnet run
/home/user/newTest/gui.cs/StandaloneExample/StandaloneExample.csproj : warning NU1701: Package 'Mono.Posix 5.4.0.201' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/home/user/newTest/gui.cs/StandaloneExample/StandaloneExample.csproj : warning NU1701: Package 'Mono.Posix 5.4.0.201' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/usr/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Image is too small. [/home/user/newTest/gui.cs/StandaloneExample/StandaloneExample.csproj]
Curses failed to initialize, the exception is: System.EntryPointNotFoundException: Unable to find an entry point named 'dlopen' in DLL 'libc'.
   at Unix.Terminal.Curses.dlopen(String file, Int32 mode)
   at Unix.Terminal.Curses.FindNCurses() in /home/user/newTest/gui.cs/Terminal.Gui/MonoCurses/binding.cs:line 58
   at Unix.Terminal.Curses.initscr() in /home/user/newTest/gui.cs/Terminal.Gui/MonoCurses/binding.cs:line 71
   at Terminal.Gui.CursesDriver.Init(Action terminalResized) in /home/user/newTest/gui.cs/Terminal.Gui/Driver.cs:line 641

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ncurses': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Unix.Terminal.Curses.raw()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized) in /home/user/newTest/gui.cs/Terminal.Gui/Driver.cs:line 645
   at Terminal.Gui.Application.Init() in /home/user/newTest/gui.cs/Terminal.Gui/Core.cs:line 1272
   at Demo.Main() in /home/user/newTest/gui.cs/StandaloneExample/Program.cs:line 152

**Comment by migueldeicaza** [comment]
You will also need ncurses installed, you should have a /usr/lib/libncurses.so somewhere.

**Comment by jeffreyleblanc225** [comment]
/usr/lib/x86_64-linux-gnu/libncurses.so is where the package is located.
Should I make a link to this somewhere?
Thanks.

**Comment by migueldeicaza** [comment]
As long as the file lives in a place that can be found by any directories listed in /etc/ld.so.conf or the directories in /etc/ld.so.conf.d/* you should be fine.

**Comment by migueldeicaza** [comment]
Ok, I am going to have to do some more work here, as Linux packages the wide support in a different library.

This is trivial to make work with Mono, as we could ship just an XML file to say "map all uses of ncurses to another version" , but .NET core does not support this, so I need to change my code to cope with two sets of libraries.

What a nightmare

For mono, just place this in your system config directory, or as a ".config" file next to Terminal.Gui.dll

```
<configuration>
   <dllmap dll="ncurses" target="libncursesw.so.5"/>
</configuration>
```

**Comment by migueldeicaza** [comment]
Ok, implemented the solution, it is a work around the fact that .NET Core after years of running on Unix still lacks basic capabilities to work nice with others.

**Comment by boonkerz** [comment]
it does not work for me.
i use the nuget version.

**Comment by jeffreyleblanc225** [comment]
Yes the screen goes blank, and then an error message is displayed with
tabs. not able to get it but I believe it is complaining about not finding
ncurses library.

Compare this to before when it wouldn't get far enough to clear the screen
even and complained about libc

**Comment by boonkerz** [comment]
what should i do?
