### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#602]
While I started this project, in the past couple of months, both @BDisp and @tig have done vast improvements to the codebase.   I would like to credit both of them.

While I know @tig's identity, I do not know @BDisp - and wanted to give him a chance to decide whether he wanted his name to be made public.

**Comment by BDisp** [comment]
Thank you. If you mean the real name I prefer to maintain anonimate but my nick yes you can.

**Comment by tig** [comment]
Hi Nick. Nice to meet you ;-). Curious where you live (roughly). No need to say if you're not comfortable!

**Comment by BDisp** [comment]
Feel free to talk to me on twitter whenever you want :-)

**Comment by tig** [comment]
`Terminal.Gui.csproj1 now reads:

```
    <Authors>Miguel de Icaza, Charlie Kindel (@tig), @BDisp</Authors>
```

Closing...
