### ISSUE TITLE
Toplevel repaint issue.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#604]
There are some cases where we only need to clear a certain region of the screen. We don't need clear all screen if it only a minor part needed to repaint. So I think that the `Redraw `methods had a region as parameter because it could be any frame dimensions we want to pass to it. So in the image you see that the `TextField `at the bottom and the `StatusBar `disapear and there are not redrawed again while dragging. Without these features it's not worth it developing dragging at all. I think that my original suggestion to resolve this is better.

![background](https://user-images.githubusercontent.com/13117724/83660403-b659e200-a5bc-11ea-8ced-e07a82bcc325.gif)

**Comment by tig** [comment]
I'm not disagreeing with you that hacking `Window` to call `Redraw` using the `Frame` when we the window being dragged is `Application.Top` fixes the problem. It does.

However, it does so using the API incorrectly. This means one of two things:

1. There is another way to solve the problem, using the API correctly.

Or 

2. The API is not designed correctly and needs to be improved.

Which of these two things do you think it is?

**Comment by tig** [comment]
I suggest you build a new `Scenario` for UI Catalog that can be used to clearly demonstrate and test window dragging.

Set it up so that there is a menu/status bar, the `Win` doesn't `Fill` and build several different versions of draggable windows.

**Comment by BDisp** [comment]
There are cases where we have to call Redraw directly. `ScrollView `do that for example.

**Comment by tig** [comment]
Let's do this: Go through the entire project and add a comment near every call to `Redraw`, and every use of `Rect bounds` within an implementing of `Redraw` describing precisely what it is doing.

I refuse to fix bugs like this by just ignoring the semantics that should be well defined and ignored. Let's first really understand it.

I did an experiment (twice; once just now and once a week ago when I was fixing all the clipping issues) where I changed every instance to use `Frame` (superview-relative) and it completely broke things. 

To be clear I am NOT saying I fully understand it. I am actually saying I don't and that we, collectively , need to if we are going to make this project really work for people.

**Comment by BDisp** [comment]
@tig I really appreciate your great work with no doubt and I congratulate you for your great job, but for now I don't see other way to work around it, for now. We can wait until discovery another solution. In the meanwhile if you want I can close the PR.

**Comment by tig** [comment]
I now see what @bdisp has been trying to articulate in this case. My apologies for being persistent on this, but after pouring over the entire project I'm hyper sensitive to people using the APIs correctly. 

Now that I've authored a comment in the code in `Window.MouseEvent`, I understand and see that @bdisp was correct:

```
	// SetNeedsDisplay takes super-view relative coordinates, so use Frame
	Application.Top.SetNeedsDisplay (regionToRedraw);

	// Redraw the entire app window using just our Frame. Since we are 
	// Application.Top, and our Frame always == our Bounds (Location is always (0,0))
	// our Frame is actually view-relative (which is what Redraw takes).
	Application.Top.Redraw (Frame);
```
