### ISSUE TITLE
Aalib support

### ISSUE THREAD

**Issue by Zuzuk-null** [migueldeicaza/gui.cs#610]
Will there be support for the aalib library? This makes it possible to draw any images in the terminal, i.e. in Terminal.Gui will be able to use images.

**Comment by BDisp** [comment]
I don't think if it will be possible.

**Comment by Zuzuk-null** [comment]
> Я не думаю, будет ли это возможно.

Why?

**Comment by BDisp** [comment]
It's doable but I don't know if it's in the owner's interest to do that. I'm not up to it :-)

**Comment by migueldeicaza** [comment]
I would rather not take a dependency on the core project.

The framework is intended to be extensible, and this is how you can get a full terminal emulator in a view, by using the control in GitHub.com/migueldeicaza/XtermSharp.

So AALib is entirely possible, and would be willing to link to it in the documentation, but I rather not put that in the core.
