### ISSUE TITLE
Converging on a 1.0 Release

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#612]
I am eager to drive hard to "finishing" Terminal.Gui 1.0. The current nuget packages is 0.81 and the number of fixes/improvements since are significant. 

I propose the following:

- We drive hard to getting the next interim release out. Call it 0.90. We define 0.90 as:
   - Feature Complete - We will strive to NOT add any new features between 0.90 and 1.0, only bug fixes. This means we must take the current list of Issues labeled as 'enhancment' and triage them. Then get them done quickly.
    - No more breaking changes. We will commit to our users that we will not make any breaking API changes after 0.90 unless it's completely unavoidable. This means that we CAN do some breaking changes now, but we should be judicious about it.
   - We will mark all issues for 0.90 with the 0.90 Milestone: https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.90
   - We shoot for mid June, 2020.

- We then drive for a 1.0 release by end of July.

There are currently only 11 issues marked as "bug" and "1.0".

https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+label%3A1.0

There are currently 53 issues marked as "enhancement":

https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement

Only 5 of those currently have the "1.0" label on them:

https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement+label%3A1.0

Please go through all issues (not just those linked above) and comment on whether you think they are required for putting a bow on a 1.0 release. If you know of other things that must get fixed please create Issues. 

I will use this Issue to drive conversations on converging to 1.0.

Ok?

**Comment by migueldeicaza** [comment]
I love the plan.

**Comment by tig** [comment]
This is the current list of bugs I think must be fixed to release 0.90:

https://github.com/migueldeicaza/gui.cs/milestones/v0.90

Anyone working on this project, looking for something to do, should focus on these first. Thanks.

**Comment by tig** [comment]
@BDisp, @fergusonr, @migueldeicaza  - Bumping this with a reminder link to the current set of `0.90` bugs:

https://github.com/migueldeicaza/gui.cs/milestones/v0.90

I'd like to start having people explicitly sign-up to fix these bugs, instead of just assuming they will get fixed. Otherwise we'll never close this puppy down. 

If there are bugs you want to tackle, let me know and I'll assign them to you.

**Comment by tig** [comment]
Now that we've launched `0.90` (Yay!) let's get focused on `1.0`. Per the original discussion above:

* `0.90` was to be "Feature Complete" and we'd strive to NOT add any new features or make any breaking changes before `1.0`

So... what bugs remain before we can release 1.0? This is the current list. 

https://github.com/migueldeicaza/gui.cs/labels/1.0

**Comment by tig** [comment]
see https://github.com/migueldeicaza/gui.cs/discussions/1060
