### ISSUE TITLE
PR #609 (Fix to Tabs) causes regressions in Dialogs

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#614]
@BDisp the PR you did for #609 completely breaks `Dialog`. This is easy to test.

Simply start `UI Catalog`, open the About box and hit tab.

We really need regression tests because we can't afford to have this kind of thing happen.

At the very minimum we need a set of manual tests that contributors run through before submitting a PR. I'll work on getting one started.

**Comment by BDisp** [comment]
Sorry. I also agree with the regression tests. Share it and we can work on it together. For example, can I submit PR to your PR's so that when they are merged they would be more improved?

**Comment by tig** [comment]
https://github.com/migueldeicaza/gui.cs/wiki
