### ISSUE TITLE
[Question] Is it possible to use this library without window borders?

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#616]
I'm trying to mimic the view of a ordinary windows console terminal. I do not want any window "borders".

Think of the Terraria server console, I want to have something like that. (see GIF below)

![Preview](https://camo.githubusercontent.com/d5437c2eb20db6d81082afb231246df4385bfd6d/68747470733a2f2f692e6779617a6f2e636f6d2f65313462383631326162626365643134663736636134303762376230313437302e676966)

Where I can receive output from the game server e.g. "Player has joined the server" and allow the user the write commands to console simultaneously.

If worse comes to worse I can settle with having a text field at the bottom for input and a view at top which would display all the incoming messages from the server and messages from the input commands.

Let me know if this library can do something like this, thanks in advance.

## Update
I found something called `ListView`, it seems to be part of what I want for my idea, however I have no idea how to add items to the actual list.
```cs
Application.Init();

var listView = new ListView();
var label = new Label("123");
listView.Add(label);

Application.Top.Add(listView);

Application.Run();
``` 
The above code does not seem to display the label 123. Although it works when I change ListView to View

**Comment by migueldeicaza** [comment]
You can, the borders are purely part of the existing set of UI views but nothing prevents you from authoring your own views.

**Comment by tig** [comment]
See https://github.com/migueldeicaza/gui.cs/issues/519

Until that's implemented, as long as you don't use views derived from `Window` or `FrameView` you can have no borders.
