### ISSUE TITLE
Prevent Console Application from being Resized

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#619]
How do I prevent the user from resizing the console application window?

I found this https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.Application.html#Terminal_Gui_Application_Resized

But I don't know how to use or prevent it.

**Comment by tig** [comment]
I don't think it's possible to prevent the host console window from being resized.

However, you can prevent any `Terminal.Gui` class derived from `View` from being resized when the console resizes by ensuring the `Height` and `Width` properties are set to absolute values.

**Comment by valkyrienyanko** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/1aa43c6c-71b9-42d4-aa00-60058a85f0eb/c-console-window-disable-resize?forum=csharpgeneral

This works but not going to do it after all as found a better solution to my problem.
