### ISSUE TITLE
Missing Events for View

### ISSUE THREAD

**Issue by Foxtrek64** [migueldeicaza/gui.cs#629]
Hello,

Maybe one of you guys can help me. I'm using this API for the first time and I'm trying to set up a main menu with an item which opens a message box and an item which exits the app. I figured it'd be a good way for me to familiarize myself with the API.

Using the documentation and sample projects as a guide, I came up with the following code:
```cs
var listItems = new List<ustring>
{
    "Show Message",
    "Exit",
};
var listView = new ListView(listItems);
```
I then attempted to register the [`View.OpenSelectedItem`](https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.ListView.html#Terminal_Gui_ListView_OpenSelectedItem) event on the list view to find that it was unavailable. Here's a screenshot to show what I'm seeing.

![image](https://user-images.githubusercontent.com/7003081/83936087-75f99000-a785-11ea-8ad8-6bcca43006e1.png)

Attempting to write it manually naturally comes up with the following error:
```
'ListView' does not contain a definition for 'OpenSelectedItem' and no accessible extension method 'OpenSelectedItem' accepting a first argument of type 'ListView' could be found (are you missing a using directive or an assembly reference?)
```

Wondering if I was doing something wrong, I attempted to recreate a section from `demo.cs`.

https://github.com/migueldeicaza/gui.cs/blob/master/Example/demo.cs#L505-L508

The block above returned the same error, one each for `KeyUp`, `KeyDown`, and `KeyPress`.

---

I am using Terminal.Gui version 0.81.0 (latest on Nuget) and my project targets netcoreapp3.1.

**Comment by tig** [comment]
Our apologies: We have been updating `Terminal.Gui` internally and the API documentation matches `master`, not what was published in the 0.81.0 Nuget package.

My suggestion is that you clone the latest, build it locally, and reference it for now if you want this functionality.
