### ISSUE TITLE
How to Stop Closing Application when Ctrl+C is Executed?

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#633]
How can I prevent the console application from closing when `Ctrl + C` is executed.

**Comment by BDisp** [comment]
Currently, this no longer happens, so in a future release it will no longer have this behavior. In the future to close the application we will have to use the `Ctrl + Q` keys.

**Comment by valkyrienyanko** [comment]
Thank you for letting me know.
