### ISSUE TITLE
Should the Action be flagged with the event word?

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#634]
According to this useful comment from @migueldeicaza (https://github.com/migueldeicaza/gui.cs/pull/621#issuecomment-639556768), `Action `doesn't really need to be flagged as an `event`. The only difference is that it appears with a different icon in the dropdown window according to the images. I personally would prefer to have the spark icon, so I ask you to give your opinion too. If you prefer the spark icon, I reset the last push made. Thank you.

![field](https://user-images.githubusercontent.com/13117724/83953326-9124d800-a837-11ea-86e2-b638f17396ba.png)
![spark](https://user-images.githubusercontent.com/13117724/83953327-91bd6e80-a837-11ea-87c8-f3e4fab0fa56.png)

**Comment by BDisp** [comment]
I will close this issue because regardless of the spark icon being more appealing, the event flag prevents an `Action `from being declared inside the construction of a class, such as this:

```
			_xRadioGroup = new RadioGroup (radioItems) {
				X = 0,
				Y = Pos.Bottom (label),
				SelectionChanged = (selected) => DimPosChanged (_curView),
			};

```

**Comment by tig** [comment]
I wish I understood why VS does that. Annoying.

**Comment by BDisp** [comment]
I had already come across that sometimes I was unable to declare events in the construction of the class and after all it was because of this :-)

**Comment by BDisp** [comment]
It only allows for fields.
