### ISSUE TITLE
[Question] Get Current Console Height on Resize

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#637]
How do I get the current console row height on resize? The docs don't seem to be up-to-date for 
`public static event EventHandler<Application.ResizedEventArgs> Resized`
https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.Application.html#Terminal_Gui_Application_Resized as there are no `Application.ResizedEventArgs` in the namespace `Terminal.Gui`.

Also when I resize the console and log the following `Console.Log(Application.Driver.Clip.ToString());`
Only the width changes and the height remains the same.

![image](https://user-images.githubusercontent.com/6277739/83955881-6d549880-a81d-11ea-8114-a8f09fce3791.png)

**Comment by BDisp** [comment]
Unfortunately, this is the behavior in `WindowsDriver`. In `CursesDriver`, this information is more realistic, I think.
