### ISSUE TITLE
StatusBar: Accessing Items is Array. Should be List?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#643]
It is not possible to dynamically modify a StatusBar after creation given the current API design.

Internally, it should use a `List<T>` for `Items` and expose `public void AddItemAt(int index, StatusItem item)` and `public StatusItem RemoveItem(int index)` as public APIs.

Or something like this.

**Comment by BDisp** [comment]
The `Menus `and `Children `properties in the `Menu `are also arrays. It's much more complicated to deal with them but with the `Array.Resize` method we can workaround with that, like I did in my PR #644.

**Comment by BDisp** [comment]
https://github.com/migueldeicaza/gui.cs/pull/1385#issuecomment-893019064
