### ISSUE TITLE
Windows/.NET Core: Menu doesn't appear

### ISSUE THREAD

**Issue by MrLinDowsMac** [migueldeicaza/gui.cs#65]
I was trying to use de StandaloneExample and Menus don't work. I can see the menu bar, but if I press ESC and then 9 (as suggested), weird characters are displayed in the textbox currently in focus ('left arrow' and '9' characters) and no menu options are displayed.

Not sure if keyboard or locale is related, but my OS (Windows 8.1) is configured in Spanish.

**Comment by migueldeicaza** [comment]
Could you attach a screenshot?

**Comment by migueldeicaza** [comment]
Perhaps it is the same issue as this?

https://github.com/migueldeicaza/gui.cs/issues/58

**Comment by jimmmeh** [comment]
I have the same issue in Windows 10. I tried uncommenting "Application.UseSystemConsole = true;" but it makes no difference.

It seems to not be capturing mouse events properly - clicking on the menus does nothing, as does clicking on the OK and Cancel buttons. The text that is meant to update based on the mouse position never shows and if I put a breakpoint in the Application.RootMouseEvent delegate it never fires.

Clicking on the screen seems to just select the character clicked on - double clicking selects the whole word clicked on. I also see the strange character issue when pressing esc as described earlier.

This looks really cool and I would love to do something with it but it seems a bit unusable on windows at the moment. Let me know if there is anymore information I could provide which might help!

**Comment by MrLinDowsMac** [comment]
When I press ESC, that arrow in Login textbox is displayed, then I press 9 and is overwritten.
![imagen](https://user-images.githubusercontent.com/1329091/38523312-4e35b1b0-3c08-11e8-869c-f08c6a2c2d63.png)

**Comment by migueldeicaza** [comment]
@MrLinDowsMac Could you try with regular .NET on Windows?   This might be a bug in the .NET Core driver.

On the mouse: there is currently no mouse support on Windows, nto sure how to get that.

**Comment by MrLinDowsMac** [comment]
Created another Standalone project with .NET Framework 4.6.1, menu still doesn't work.

**Comment by giggio** [comment]
I just tried it Windows 10 RS4, with .NET Core 2.1, I have the same problem, the menu does not work.

**Comment by YauhenPyl** [comment]
Menu works good for me at .NET Core 2.0:
![image](https://user-images.githubusercontent.com/32565875/39671492-adf46e36-5119-11e8-9157-fef9fda6d9ff.png)
But I used F9 to trigger it (same behavior at full .NET)

**Comment by migueldeicaza** [comment]
vastly improved console driver for windows merge into master.

Fixed by @nickvdyck pull request.

**Comment by giggio** [comment]
It seems much better on Windows now. I also can open the menu with `F9`, but not with `ESC + 9`.

**Comment by migueldeicaza** [comment]
Correct, ESC-9 is a Unix-driver only feature.   I updated the text in the sample.
