### ISSUE TITLE
Mouse DoubleClick on Scenario passes through to Scenario

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#674]
To repro:

1. Run UI Catalog
2. Double click on `MessageBoxes` - **Double click on `geBoxes`.**
3. Note that when the scenario starts up the `Error` radio button gets selected.

![](https://i.imgur.com/grapXMx.gif)

**Comment by tig** [comment]
Reopening as this is still reproducible. 

Double click on the `B` in `Buttons` to start the Buttons scenario and the `TopLevel` button will get activated.

**Comment by tig** [comment]
@BDisp, as noted, PR #675 did not fix this issue. Will you have a chance soon to look into it?

**Comment by BDisp** [comment]
@tig believe me it doesn't happen to me anymore. It has happened to me before and after correcting it it never happened to me again. Could the mouse be very sensitive?

**Comment by tig** [comment]
![](https://i.imgur.com/EK4GZu4.gifv)

There's nothing special about my mouse or settings as far as I know. I just double click in the video above. Wild this doesn't happen on your PC!

**Comment by tig** [comment]
FWIW, it has nothing to do with how fast I double click. As long as I do it fast enough that Windows would have detected it as a double click, the issue reproduces.

**Comment by BDisp** [comment]
What is that console? Give me the link to install it. This doesn't happen with cmd.exe and neither with Ubuntu.

**Comment by tig** [comment]
CMD.exe.

-cek
Sent from mobile device. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by tig** [comment]
I can't repro on my laptop. I'm now away from my desktop for a few days. But I'll be using another with a real mouse and will try to repro there. Anyone else reading this, please try to repro!

**Comment by tig** [comment]
This repros on my laptop with a real mouse attached with EITHER the mouse or touchpad. 

I now can not get it to NOT repro on this machine where I couldn't repro it yesterday. Frustrating!

**Comment by BDisp** [comment]
It really happened to me before, but after correcting it, it never happened to me again.

**Comment by tig** [comment]
I can't repro in WSL.

I can no longer repro in cmd.exe either. 

I changed nothing. Weird.

**Comment by BDisp** [comment]
> 
> 
> I can't repro in WSL.
> 
> I can no longer repro in cmd.exe either.
> 
> I changed nothing. Weird.

Maybe it was related to the window dragging that I fixed recently. Or related to the already fixed by avoiding the mouse `AllEvents `after a double click.
