### ISSUE TITLE
Linux. Ubuntu 17.04. Doesn't work

### ISSUE THREAD

**Issue by EntityFX** [migueldeicaza/gui.cs#68]
Unhandled Exception: System.DllNotFoundException: **Unable to load DLL 'ncurses'**: The specified module or one of its dependencies could not be found.
                                                                    (Exception from HRESULT: 0x8007007E)
                           at Unix.Terminal.Curses.call_mousemask(IntPtr newmask, IntPtr& oldmask)
                     at Unix.Terminal.Curses.mousemask(Event newmask, Event& oldmask)
        at Terminal.Gui.CursesDriver.Init(Action terminalResized)
                                                                    at Terminal.Gui.Application.Init()

libncurses5 is installed.

**Comment by EntityFX** [comment]
Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by migueldeicaza** [comment]
Can you install the ncurses development package and report back?

**Comment by williamleuschner** [comment]
I am able to reproduce this.

Product Version: Whatever is currently published on nuget
.NET Core Version: 2.0.3
Runtime: Ubuntu Linux 17.10, rid linux-x64

I have installed libncurses5-dev.

I'm testing in VirtualBox, using the default Ubuntu 17.10 release image. I installed .NET Core following Microsoft's official instructions here: https://www.microsoft.com/net/learn/get-started/linux/ubuntu17-10

Minimal working (failing?) example:

```
using System;
using Terminal.Gui;

namespace Testbed
{
    class Program
    {
        public static int Main(string[] args) {
            Application.Init();
            var menu = new MenuBar(
                new[]
                {
                    new MenuBarItem("_File", new[]
                    {
                        new MenuItem("_Quit", "", Application.RequestStop)
                    })
                });
            var window = new Window(new Rect(0,1,Application.Top.Frame.Width - 2, Application.Top.Frame.Height - 1), null);
            Application.Top.Add(menu);
            Application.Top.Add(window);
            Application.Run();

            return 0;
        }
    }
}
```
Stack trace:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ncurses': 
The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Unix.Terminal.Curses.call_mousemask(IntPtr newmask, IntPtr& oldmask)
   at Unix.Terminal.Curses.mousemask(Event newmask, Event& oldmask)
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init()
   at Testbed.Program.Main(String[] args) in /home/william/Documents/project3/Te
stbed/Program.cs:line 27
```

The same exception occurs whether I run it using `dotnet run` or first publish and then run the resulting executable.

The example runs fine on my macOS High Sierra laptop.

**Comment by migueldeicaza** [comment]
And are you using a NuGet package, or you are using the Git checkout?

Because there is special code in GitHub to handle that scenario specifically.

**Comment by williamleuschner** [comment]
I’m using the NuGet package, not a Git checkout. If you want me to, I can try with a Git checkout too.

**Comment by migueldeicaza** [comment]
I just tried on my Ubuntu machine.

Try this: 

```
cd StandaloneExample
dotnet run
```

**Comment by williamleuschner** [comment]
I just ran that on both master (8468d80) and v0.5 (e288ce8), and both of them produced the following exception, almost identical to the one above:

```
Curses failed to initialize, the exception is: System.Exception: Could not dlopen ncurses
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ncurses': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Unix.Terminal.Curses.raw()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init()
   at Demo.Main() in /home/william/Documents/gui.cs/StandaloneExample/Program.cs:line 152
```

**Comment by williamleuschner** [comment]
In the event that it's useful, here are the packages installed on the system:

```
$ apt list --installed | grep "curses\|dotnet"

dotnet-host/artful,now 2.1.0-preview2-26411-07-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.3/artful,now 2.0.3-1 amd64 [installed,automatic]
dotnet-runtime-2.0.3/artful,now 2.0.3-1 amd64 [installed,automatic]
dotnet-runtime-deps-2.1.0-preview2-26406-04/artful,now 2.1.0-preview2-26406-04-1 amd64 [installed,automatic]
dotnet-sdk-2.0.3/artful,now 2.0.3-1 amd64 [installed]
libncurses5/artful,now 6.0+20160625-1ubuntu1 amd64 [installed]
libncurses5-dev/artful,now 6.0+20160625-1ubuntu1 amd64 [installed]
libncursesw5/artful,now 6.0+20160625-1ubuntu1 amd64 [installed]
ncurses-base/artful,artful,now 6.0+20160625-1ubuntu1 all [installed]
ncurses-bin/artful,now 6.0+20160625-1ubuntu1 amd64 [installed]
pinentry-curses/artful,now 1.0.0-2 amd64 [installed]
```

The [full package listing is here](https://hastebin.com/irubofujir.sql)

**Comment by williamleuschner** [comment]
I tried both `master` and the published version of `Terminal.Gui`, and both of them work great!

My Ubuntu 17.10 VM is able to run both `StandaloneExample` and my own project, with and without the ncurses development package. Thanks!

**Comment by williamleuschner** [comment]
@EntityFX, can you check out the changes and see if they've fixed your issue? I suspect they have, but it's always good to check!

**Comment by migueldeicaza** [comment]
Will close the bug for now.
