### ISSUE TITLE
'end' key in ScrollView does not go to end - also scrolling left/right scrolls when shouldn't

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#689]
This is a regression that was introduced with this change:

https://github.com/migueldeicaza/gui.cs/commit/2766af8afe86c5b948a060f56e8f5d5b825caf23#r39885851

![image](https://user-images.githubusercontent.com/585482/84581101-44d71c00-ad92-11ea-9624-265ae3333c23.png)

Also, I believe, but am not 100% sure that previous to the PR referenced above if you pressed right or left arrows in CharMap it did NOT scroll right/left.

Regardless, if a ScrollView's contentSize's width is the same as the viewport, horizontal scrolling should not happen. Same for if the height is the same.

**Comment by BDisp** [comment]
@tig the scroll by keyboard only occurs if the `ScrollView`'s subviews can focus. The `End `and `Home `keys only works to the vertical scroll. I think it's has stopped working when you changed the `ScrollView `visual (to better than before :-)) putting the vertical down arrow one row up.

**Comment by BDisp** [comment]
It's working to me.

![scroll-view-keys](https://user-images.githubusercontent.com/13117724/84582080-2ba88c80-addf-11ea-9df3-dd624a1c2b1d.gif)

**Comment by BDisp** [comment]
@tig I think I was wrong, sorry.
