### ISSUE TITLE
Should Rect Width and Height have negative values?

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#694]
There is no logic in that because what defines that the `Rect `could have negative values are your sides.
e.g.:
`r = new Rect (-10, -10, 5, 5)` result in the follow:
`Left = -10, Right = -5, Top = -10, Botton = -5`

Thoughts, please???

**Comment by BDisp** [comment]
That the main reason why I have this:

```
w = Math.Max (width.Anchor (hostFrame.Width - _x), 0);

h = Math.Max (height.Anchor (hostFrame.Height - _y), 0);
```

**Comment by tig** [comment]
On Windows and Mac, I can drag a window partially off screen to the left or top.

Maybe someday we'd allow that?

**Comment by BDisp** [comment]
@tig I'm not referring to that. This I think has already been done here https://github.com/migueldeicaza/gui.cs/pull/672/commits/554202f5e7bca9ec88b55abca7a46b6cc6c3f5df.
The fact that the width and height can only have a positive value does not prevent the possibility of dragging off the screen in the future.

**Comment by tig** [comment]
If `Rect.x` can't be negative, how would I create a View, partially off the left of the screen with this API?

```csharp
public View (Rect frame)
```

or, what would `Frame` hold if a view was partially off to the left?

The point is moot, however: `Rect` IS the same as `System.Windows.Rect`.

**Comment by BDisp** [comment]
@tig was just referring to `Width `and `Height`. Currently, `X `and Y may already be negative. You're confusing :-)

**Comment by tig** [comment]
I still don't think we should change the way the types defined in `Types/` work.

**Comment by tig** [comment]
FWIW (you are basically right): https://referencesource.microsoft.com/#WindowsBase/Base/System/Windows/Size.cs

![image](https://user-images.githubusercontent.com/585482/84672369-537e1a00-aedd-11ea-97d3-6d89ca1c461d.png)

**Comment by tig** [comment]
But, in my opinion, instead of adding the exceptions ourselves, we should just delete the classes from the project and use the `System.Windows` versions.

**Comment by BDisp** [comment]
Just as `Size `should also not allow negative values. What defines that `Rect `is off the screen is `Point (X, Y) `and `Left, Right, Top, Bottom`.

But since you do not agree I will remove this change from my PR.

**Comment by BDisp** [comment]
> But, in my opinion, instead of adding the exceptions ourselves, we should just delete the classes from the project and use the `System.Windows` versions.

It would be a hypothesis but I think that the way `Terminal.Gui `is with a personalized is better.

**Comment by BDisp** [comment]
So I was right. @tig can I do the same in the `Size `class?

**Comment by tig** [comment]
If you do this, please bring over the the updated implementations of all three classes, or figure out how to reference System.Windows directly. We should NOT have duplicated/modified code for such fundamental classes that have been so thoroughly tested.

**Comment by BDisp** [comment]
Done @tig. Thanks.

**Comment by BDisp** [comment]
> 
> 
> If you do this, please bring over the the updated implementations of all three classes, or figure out how to reference System.Windows directly. We should NOT have duplicated/modified code for such fundamental classes that have been so thoroughly tested.

I think it is better not to mix `System.Windows` with `System `to not be too dependent so that any changes they make do not interfere with `Terminal.Gui`.

**Comment by migueldeicaza** [comment]
We should not allow negatives for now - this will catch bugs if they crop up.

If one day there is a scenario that makes sense we can explicitly enable this back, for now the checks seem like they do more good.    I merged the patch that had this.
