### ISSUE TITLE
Hotkeys for buttons don't work

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#701]
Open `Buttons` scenario and it `Alt-S` or `Alt-Q`. Nothing happens.

Expected:
- `Alt-S` invokes the "_Swap Default..." button.
- `Alt-Q` invokes the "_Quit" button.

Also, with the focus on the `TextField` press `enter`. Nothing happens.

Expected:
- `enter` would invoke the default button.

I suspect these are related and I'm working on a massive PR that will probably fix these; I'd recommend not fixing them until after my PR. I wanted to capture this as an Issue so that it was tracked regardless.

**Comment by tig** [comment]
This is partially fixed:

- `enter` now works

But hotkeys on buttons are still not working.

**Comment by tig** [comment]
This is one of the final bugs I think needs to be fixed for `0.90`.

https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.90

**Comment by BDisp** [comment]
Fixed by the PR #793.
