### ISSUE TITLE
v0.90 high CPU load

### ISSUE THREAD

**Issue by InvictusMB** [migueldeicaza/gui.cs#708]
An app build against v0.90 consumes 100% of one core.
Using v0.81 from Nuget the load is 0%.
Tested with [this project](https://github.com/InvictusMB/TerminalGuiUwpInputBug).

**Comment by BDisp** [comment]
I can't repo that. I get between 16% and 18% CPU usage.

**Comment by InvictusMB** [comment]
The number you see depends on the number of cores you have. I have 4 CPUs with hyperthreading so 8 in total. And my CPU load is 13% which equals to 100/8.
Anyways, even 16% is too much compared to 0.

**Comment by BDisp** [comment]
How can I check that per core?

**Comment by tig** [comment]
What OS?

**Comment by InvictusMB** [comment]
> What OS?

Windows 10.

<details>
  <summary>0.90 CPU load screenshots</summary>
  
![image](https://user-images.githubusercontent.com/3091209/85206884-749f9a00-b325-11ea-93e9-7f1019aa94e4.png)
![image](https://user-images.githubusercontent.com/3091209/85207095-d01e5780-b326-11ea-8a94-68d3cf2366d1.png)
 
</details>

<details>
  <summary>0.81 CPU load screenshots</summary>
  
![image](https://user-images.githubusercontent.com/3091209/85207446-0361e600-b329-11ea-8c2b-ea5b00c09b66.png)

![image](https://user-images.githubusercontent.com/3091209/85207458-1e345a80-b329-11ea-982e-949b868f2f43.png)

 
</details>

> How can I check that per core? 

On Windows 10 

<details>
  <summary>Bind to CPU core</summary>
  
![image](https://user-images.githubusercontent.com/3091209/85207243-b0d3fa00-b327-11ea-80cd-dcbffc23d815.png)

![image](https://user-images.githubusercontent.com/3091209/85207260-cd703200-b327-11ea-93c2-b204662594df.png)
 
</details>

**Comment by BDisp** [comment]
Thank you very much for the explanation. Now how can you put images with these drop downs?

**Comment by InvictusMB** [comment]
> Now how can you put images with these drop downs?

https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by InvictusMB** [comment]
@BDisp The loop introduced in #514 is what causes CPU load.

**Comment by BDisp** [comment]
> @BDisp The loop introduced in #514 is what causes CPU load.

@InvictusMB I believe you. It was the only way to respond to a thread. Feel free to arrange another alternative please.  Thanks for discover this.

**Comment by InvictusMB** [comment]
When I read #514 description literally I immediately think `AddIdle` should call `Driver.Wakeup`.

```csharp
public Func<bool> AddIdle (Func<bool> idleHandler)
{
  lock (idleHandlers)
    idleHandlers.Add (idleHandler);
  
  Driver.Wakeup (); // <-------- 
  return idleHandler;
}
```

**Comment by BDisp** [comment]
I already suspected that some `lock `was missing so I wouldn't have to do that loop and Int ic was the trick. You are awesome. Thanks.
Is it no longer necessary to call `Application.MainLoop.AddIdle` on the threads and just call `Task.Run`?
