### ISSUE TITLE
ComboBox issues

### ISSUE THREAD

**Issue by fergusonr** [migueldeicaza/gui.cs#709]
Discovered during extended testing:-

* Dim.Fill() incorrectly calculated

Both ListView and ComboBox have ```Height = Dim.Fill(2)```

![Dim Fill()](https://user-images.githubusercontent.com/17233550/85197079-b2c19d00-b2d6-11ea-8d05-8d7ae5d14344.jpg)

* List height not resizing

Resizing window, list does not fill Height.

![resize](https://user-images.githubusercontent.com/17233550/85197094-c7059a00-b2d6-11ea-8947-089391b27353.JPG)

* SetSource() not immediately updating list. 

If ```comboBox.SetSource (items);``` is called a second time after initial construction, the list does not instantly change

* Double click not selecting item

Double clicking the list should be the same as hitting the enter key

**Comment by tig** [comment]
@fergusonr can you confirm all of these issues are fixed in #710? If so I'll close it. Thanks!

**Comment by fergusonr** [comment]
Yes, all four named issues in this are resolved. - thanks
