### ISSUE TITLE
HexView is causing an error because of Source property in the AllViewsTester.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#725]
The `HexView `already have a `Source `property and the `GetType ().GetProperty ("Source")` is causing a `System.ArgumentException: 'Object of type 'Terminal.Gui.ListWrapper' cannot be converted to type 'System.IO.Stream'.'` error in the `AllViewsTester.cs`.

**Comment by tig** [comment]
I Fixed this earlier today in latest update to my mondo PR…
