### ISSUE TITLE
How often are listviews re-rendered?

### ISSUE THREAD

**Issue by kbirger** [migueldeicaza/gui.cs#728]
I am writing an application that does some work. I have created a ListView and have set its source to a list which gets updated to reflect the state to display.

How often is the control meant to be re-rendered? How do I signal that my collection has been updated and a re-render is necessary? Sorry, I cannot find this in the documentation. 

Currently, I have a very long delay before my updates are visible.

**Comment by tig** [comment]
There is no code to detect list changes and to automatically redraw. You will have to do this yourself. Call `SetNeedsDisplay`  (https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.View.html#Terminal_Gui_View_SetNeedsDisplay).

**Comment by kbirger** [comment]
D'oh. Okay, that solves it! I was looking at things like redraw or refresh, but missed this one. It did seem to re-render periodically, so I thought there was a timer.
