### ISSUE TITLE
Ship symbols with the Terminal.Gui Nuget 

### ISSUE THREAD

**Issue by bgianfo** [migueldeicaza/gui.cs#729]
Would be nice to have symbols available for debugging in the nuget symbol server.
See: https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

**Comment by tig** [comment]
I think we should do this for `0.90`. I don't know how to do it.

**Comment by lalo** [comment]
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

If you push it to nuget.org it should do the correct thing.

**Comment by pasisavolainen** [comment]
I see this was implemented (at least `.snupkg` generation, can't say about pushing those) at some point.

Could this rather be `embedded` symbol type? Like this: https://github.com/pasisavolainen/gui.cs/commit/66fd08ca11c40719258b252672b08545754d33c7

Plus side is that pdb never gets desynced from dll, stack traces always have line numbers even if pdb was never sidecar'd etc.

Negative is size of dll. Size on disk was:
> release-net5 - no symbols: 235K
> release-net5 -      symbols: 287K

I don't know about in-memory loaded size.

With that the `.snupkg` ends up virtually empty and also I don't know if there is any pushing machinery acting on them.

**Comment by tig** [comment]
I need to dive into this again. I believe this IS a 1.0 ship-blocker and must be fixed before we declare 1.0. 

Anyone disagree? 

Anyone want to help me fix it?
