### ISSUE TITLE
Frame vs X, Y, Width, Height - Unclear behavior

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#731]
`LayoutStyle.Absolute` means that `X`, `Y`, `Width`, and `Height` should not/cannot be used. 

If `LayoutStyle.Computed` is set, what happens when setting `Frame` is unclear but it seems it should not be allowed.

We have a lot of code that violates this and this is a source of several bugs.

I think we should either:

a) Throw exceptions if these properties are set when in the wrong mode.

OR

b) Change the `LayoutStyle` to the appropriate value if one of these is set when it shouldn't be, forcing the view into the right mode. 

Currently (but I'd like to debate it to be sure) I like a) best.

An example of where this is clearly messy, and confusing, see this code from `Window` that handles dragging Window with mouse:

```csharp
dragPosition = new Point (nx, ny);
Frame = new Rect (nx, ny, Frame.Width, Frame.Height);
X = nx;
Y = ny;
//Demo.ml2.Text = $"{dx},{dy}";
```

I don't think Views that have `LayoutStyle.Computed` should support being moved because doing so invalidates the `Dim` and `Pos` settings a caller sets. If a `View` has `Width = Dim.Fill()`, for example, 

This code in `Button` is similarly supsect:

```csharp
		internal void Update ()
		{
			if (IsDefault)
				base.Text = ustring.Make (_leftBracket) + ustring.Make (_leftDefault) + " " + text + " " + ustring.Make (_rightDefault) + ustring.Make (_rightBracket);
			else
				base.Text = ustring.Make (_leftBracket) + " " + text + " " + ustring.Make (_rightBracket);

			int w = base.Text.RuneCount - (base.Text.Contains (HotKeySpecifier) ? 1 : 0);
			Width = w;
			Height = 1;
			Frame = new Rect (Frame.Location, new Size (w, 1));
			SetNeedsDisplay ();
		}
```

What thoughts do others have on this?

**Comment by tig** [comment]
Related, does anyone know why `SetRelativeLayout` is only called if `SuperView == Application.Top` (in `LayoutSubviews`).

```csharp
if (SuperView == Application.Top && layoutNeeded && ordered.Count == 0 && LayoutStyle == LayoutStyle.Computed) {
	SetRelativeLayout (Frame);
}
```

**Comment by BDisp** [comment]
> Related, does anyone know why `SetRelativeLayout` is only called if `SuperView == Application.Top` (in `LayoutSubviews`).
> 
> ```cs
> if (SuperView == Application.Top && layoutNeeded && ordered.Count == 0 && LayoutStyle == LayoutStyle.Computed) {
> 	SetRelativeLayout (Frame);
> }
> ```

This ensures that a view that is not toplevel that has the `layoutNeeded `flag set to true and that there is no longer any view in the list ordered and that is `LayoutStyle.Computed` and whose `SuperView `is `Application.Top` must necessarily execute the `SetRelativeLayout (Frame)` method . Checks that the `Label `at the bottom of the `Window `is not repositioned if this condition does not exist.

**Comment by BDisp** [comment]
> I think we should either:
> 
> a) Throw exceptions if these properties are set when in the wrong mode.
> 
> OR
> 
> b) Change the `LayoutStyle` to the appropriate value if one of these is set when it shouldn't be, forcing the view into the right mode.

Imagine that initially a view is initialized as` LayoutStyle.Computed` and later there is a need to place it as `LayoutStyle.Absolute`. Option `a)` will never allow this change so `b)` would be more friendly in the transition from one layout to another, in which case to throw an exception if the type of layout is not changed before assignment.

**Comment by tig** [comment]
> > Related, does anyone know why `SetRelativeLayout` is only called if `SuperView == Application.Top` (in `LayoutSubviews`).
> > ```cs
> > if (SuperView == Application.Top && layoutNeeded && ordered.Count == 0 && LayoutStyle == LayoutStyle.Computed) {
> > 	SetRelativeLayout (Frame);
> > }
> > ```
> 
> This ensures that a view that is not toplevel that has the `layoutNeeded `flag set to true and that there is no longer any view in the list ordered and that is `LayoutStyle.Computed` and whose `SuperView `is `Application.Top` must necessarily execute the `SetRelativeLayout (Frame)` method . Checks that the `Label `at the bottom of the `Window `is not repositioned if this condition does not exist.

This does not answer my specific question, which is about this part: `SuperView == Application.Top`, because I don't think this test "ensures that a view is not toplevel". My read of this is it's actually testing "ensures that a view is a subview of Application.Top" which is not the same thing.

**Comment by BDisp** [comment]
>  My read of this is it's actually testing "ensures that a view is a subview of Application.Top" which is not the same thing.

The expression "whose `SuperView `is `Application.Top`" is the same as saying that "a view is a subview of `Application.Top`". What is the difference here? I reffered to the Label that is not a toplevel. Did you test with the `Example `project?

**Comment by BDisp** [comment]
I think it is enough to throw an exception if the view is `Layout.Computed` only in cases of its types being different from `PosAbsolute `and `DimAbsolute`, because changing these types does not affect the behavior of the view.
