### ISSUE TITLE
Help with refresh Label data.

### ISSUE THREAD

**Issue by reinaldocoelho** [migueldeicaza/gui.cs#732]
Hi, I have created an application who updates some label information every second and the label content is now updated on screen.

The code to update the label is that and was called by Timer:

```csharp
private Label GetTokenSeconds(int value)
{
	var tokenX = 1;
	var tokenY = 1;
	var tokenWidth = 50;
	var tokenHeight = 2;

	var message = $"Seconds to change: {value}.";
	if (tokenSeconds == null)
	{
		tokenSeconds = new Label(message) { X = tokenX, Y = tokenY, Width = tokenWidth, Height = tokenHeight };
	}
	else
	{
		tokenSeconds.Text = message;
		tokenSeconds.Redraw(new Rect(tokenX, tokenY, tokenWidth, tokenHeight));
	}
	return tokenSeconds;
}
```

Is this the correct approach to update some label every second?
If I press some Key, for exemple ESC, the screen update.

Thank you :-)

**Comment by BDisp** [comment]
You don't need to create a new `Label`. You only need to update the Text property and you don't need press any key to update the label too. Just add a timer to the mainloop.

```
bool timer (MainLoop caller)
{
	myLabel.Text = "New message";
	return true;
}

Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (100), timer);

```

**Comment by reinaldocoelho** [comment]
Worked!!
Thank you very mutch.
