### ISSUE TITLE
Turning on/off scroll bars in Scrolling Scenario has stopped working

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#758]
Last time I checked these worked.

Not sure what changed.

![](https://i.imgur.com/PeET04u.gif)

**Comment by BDisp** [comment]
@tig try to set `AutoHideScrollBars `to false first because if its true it won't check the `ShowHorizontalScrollIndicator `and `ShowVerticalScrollIndicator`.

**Comment by tig** [comment]
But it was working before. Did you add `AutoHideScrollBars` recently?

**Comment by BDisp** [comment]
> 
> 
> But it was working before. Did you add `AutoHideScrollBars` recently?

Yes.

**Comment by tig** [comment]
> > But it was working before. Did you add `AutoHideScrollBars` recently?
> 
> Yes.

Then adding `AutoHideScrollBars` was a breaking change. You should make it `false` by default. Or, since nobody but me has probably ever written code to turn them on/off dynamically, just fix the scenario ;-).
