### ISSUE TITLE
Controls that don't care about double click should be able to receive mouse clicks as fast as possble

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#759]
1. Run Progress scenario
2. Click on "[ Pulse ]" as fast as you can

Expected:

Progress bar updates as fast as I can click.

Actual:

Progress bar updates no faster than the double-click wait timeout (which is like 1s).

In this video I first use mouse. Then switch holding down space bar.

![](https://i.imgur.com/ZNcXNp2.gif)

**Comment by BDisp** [comment]
@tig this is so. The continuous click works with the `ScrollView `because the `WantContinuousButtonPressed `property of the `View `class is true.
