### ISSUE TITLE
Colors in Linux changing between windows.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#760]
This is happening again and for sure it is the application reinitializing the driver. With `WindowsDriver`, this behavior does not happen because the console settings are only assumed when the application is finished. On `Unix / Linux`, the driver termination runs` Curses.endwin` which immediately restores the console's defaults and the application cannot maintain its own settings. I've had to solve it at least twice, as I recall. Does it have to do with `IDispose`?

![unix-close-driver](https://user-images.githubusercontent.com/13117724/86854461-62a55180-c0b0-11ea-98a2-c770383a5146.gif)

**Comment by tig** [comment]
I will make it a priority to look into this tonight or tomorrow. I'm bad about testing on Linux. Bad. ;-)
