### ISSUE TITLE
A Load event for the View is missing.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#766]
To allows configurations and assignments to be performed only once before the view is drawn for the first time.

**Comment by tig** [comment]
How often is this an issue? 

Our bar for adding new APIs should be really high.

**Comment by BDisp** [comment]
It really isn't a issue. It is a new feature. I think it is very beneficial and comparable to `Form_Load`

**Comment by BDisp** [comment]
I think I was wrong to compare it with the `Form_Load `that only occurs once with the form. In this case, it occurs only once before making the first `Redraw `for each view in the current toplevel. I don't know if the name is the most appropriate (perhaps `Initialized`) but this event guarantees that all views that subscribe to the `Load `event will have all the real information of their content in order to be able to take some actions, which they won't have in the case of the `Added `and so I compared it to this one in the unit test.

**Comment by tig** [comment]
There's already an API on `TopLevel` that does what you want:

```csharp
/// <summary>
/// Fired once the Toplevel's <see cref="MainLoop"/> has started it's first iteration. 
/// Subscribe to this event to perform tasks when the <see cref="Toplevel"/> has been laid out and focus has been set.
/// changes. A Ready event handler is a good place to finalize initialization after calling `<see cref="Application.Run()"/>(topLevel)`. 
/// </summary>
public Action Ready;

/// <summary>
/// Called from <see cref="Application.RunLoop"/> after the <see cref="Toplevel"/> has entered it's first iteration of the loop. 
/// </summary>
internal virtual void OnReady ()
{
	Ready?.Invoke ();
}
```

We could simplify the whole thing by:

1) Move `Ready` (et. al.) from `TopLevel` to `Responder`
2) Rename `Ready` to `Initialize`
3) Modify `Application.RunLoop` to do the call. Right now it uses the idea of "first iteration". change this to "first iteration for THIS responder". To do this we'd add a `protected` field to `Responder`: `protected bool Initialized { get; set; }`.

What do you think?

**Comment by BDisp** [comment]
@tig say what you think of the following suggestion:

1. Change `Ready `to `Load `and keep it in toplevel as is. Instead of calling it within `RunLoop `first iteration I will call it within `RunState Begin (Toplevel toplevel)` after `Redraw (toplevel)`. In this case, the `firstIteration `variable will no longer be needed.

2. Change Load to `Initialize`, `Initialized `or `Initializing `because there are some views that already use the `Initialize `method in the constructor and I don't know if there might be a name conflict.

3. Keep 2 the same as it is in my PR but rename it. Then suggest the best name please.

With this I intend that the views are only notified once they are already properly resized and prepared so that they can take some action with more precision.
After this individual notification of the views, they will also have access to more generalized information of all other views by subscribing to `Load `which will also only occur once for the toplevel.

**Comment by BDisp** [comment]
Done!

**Comment by tig** [comment]
> @tig say what you think of the following suggestion:
> 
> 1. Change `Ready `to `Load `and keep it in toplevel as is. Instead of calling it within `RunLoop `first iteration I will call it within `RunState Begin (Toplevel toplevel)` after `Redraw (toplevel)`. In this case, the `firstIteration `variable will no longer be needed.

But if it's in `Begin`, it will only be called if the `View` was created before `Run` was called, right? 

> 2. Change Load to `Initialize`, `Initialized `or `Initializing `because there are some views that already use the `Initialize `method in the constructor and I don't know if there might be a name conflict.

I think `Initialize` is right; there will be no conflict of an event name and method, I think.

> 3. Keep 2 the same as it is in my PR but rename it. Then suggest the best name please.
> 
> With this I intend that the views are only notified once they are already properly resized and prepared so that they can take some action with more precision.
> After this individual notification of the views, they will also have access to more generalized information of all other views by subscribing to `Load `which will also only occur once for the toplevel.

**Comment by BDisp** [comment]
> But if it's in `Begin`, it will only be called if the `View` was created before `Run` was called, right?

Yes but the subviews where will be called before through the `Initialized `event will have all the information they needed, toplevel included, to be being redrawn. Later the Load event will provide all the information about all aviable views in the toplevel that it's usefull if you want to reposition on views based on another views.


> I think `Initialize` is right; there will be no conflict of an event name and method, I think.

Wrong because some views already uses the `Initialize `method `Toplevel `included. `VS2019 `gave me the warning you can check in my commit in this PR.

**Comment by tig** [comment]
> > But if it's in `Begin`, it will only be called if the `View` was created before `Run` was called, right?
> 
> Yes but the subviews where will be called before through the `Initialized `event will have all the information they needed, toplevel included, to be being redrawn. Later the Load event will provide all the information about all aviable views in the toplevel that it's usefull if you want to reposition on views based on another views.

I'm not understanding (maybe not enough coffee yet this morning). I thought the idea was to provide a simple, single API that a `View` (or creator of a `View`) could receive notification that the `View` had been created, and was ready for 1st time initialization. 

What am I missing?

> 
> > I think `Initialize` is right; there will be no conflict of an event name and method, I think.
> 
> Wrong because some views already uses the `Initialize `method `Toplevel `included. `VS2019 `gave me the warning you can check in my commit in this PR.

Gotcha. I don't have time this morning to run any code, so I can't test myself.

**Comment by BDisp** [comment]
> I'm not understanding (maybe not enough coffee yet this morning). I thought the idea was to provide a simple, single API that a `View` (or creator of a `View`) could receive notification that the `View` had been created, and was ready for 1st time initialization.
> 
> What am I missing?

And that what is happening for all the views that are created before `Run`. In `WinForms `the `Initialize `method only run when the `Form `is loaded with the controls created at design time and the controls that are dynamically created after the `Load `the `Initialize `for that control will never run.

**Comment by BDisp** [comment]
> And that what is happening for all the views that are created before `Run`. In `WinForms `the `Initialize `method only run when the `Form `is loaded with the controls created at design time and the controls that are dynamically created after the `Load `the `Initialize `for that control will never run.

@tig i gave you wrong information about my PR. The `Initialized `event will always be invoked before the first `Redraw `of each view, even if it is added dynamically because it is called inside the `View.Redraw` method. Only the Load method will be invoked only once for each toplevel.

**Comment by tig** [comment]
> > And that what is happening for all the views that are created before `Run`. In `WinForms `the `Initialize `method only run when the `Form `is loaded with the controls created at design time and the controls that are dynamically created after the `Load `the `Initialize `for that control will never run.
> 
> @tig i gave you wrong information about my PR. The `Initialized `event will always be invoked before the first `Redraw `of each view, even if it is added dynamically because it is called inside the `View.Redraw` method. Only the Load method will be invoked only once for each toplevel.

I am very much against raising an event like this within `Redraw`. I do not think it should be raised there. Reasons:

a) Redraw needs to be fast. Having it call out to other code that could do operations that take a long time will lead to slow re-draws in some situations. 

b) The `View` should not be raising this event, the entity that created the event should raise it. To do otherwise is poor archtiecture. 

c) Calling it from Redraw means WHEN it is called is not clearly defined. Is it invoked before stuff is drawn or after? 

d) Initialize has nothing to do with "draw". It feels like the only reason you put it in `Redraw` is it was convenient.

**Comment by BDisp** [comment]
@tig Got it. Thanks. I've already changed.

**Comment by tig** [comment]
Interesting! I had seen that interface somewhere...

I will study this...
