### ISSUE TITLE
Mac Alt key not working

### ISSUE THREAD

**Issue by praeclarum** [migueldeicaza/gui.cs#78]
I have tried both settings in Terminal but gui.cs never registers my Alt. Esc + 9 works, but I would much prefer Alt.

<img width="460" alt="screenshot 2018-05-03 09 43 07" src="https://user-images.githubusercontent.com/323548/39590686-7f76d0f4-4eb6-11e8-818d-af5c53c89874.png">

Is there a trick or is this a bug?

**Comment by praeclarum** [comment]
It doesn't work for me. When I press Alt, the menu does not light up. And if I press Alt+F nothing happens. I am able to access the file menu with the mouse though. I am trying the StandaloneExample.

<img width="1018" alt="screenshot 2018-05-03 10 21 02" src="https://user-images.githubusercontent.com/323548/39592531-deea82f6-4ebb-11e8-994b-2a829f44977f.png">

If I turn off "Option as Meta" and press Alt+F then the app records:

```
?~C?~B?~R?~F
```

**Comment by migueldeicaza** [comment]
Alt alone is not reported back to the application, so it would never light up.

Only Alt-key would be reported.

Now, Alt-9 should bring up the menu.    I am on the fence as to whether Alt-F should be the hotkey for the File menu.   I tried to convey that this would not be the case by not highlighting the F in File on the menu.

Alt-F currently is bound to Forward-word on the text editor, hence the need for Alt-9 to activate (hopefully I will implement soon a tab bar at the bottom to show the option).   Alt-9 is the Norton Commander default, while the SAA/CUA default is supposed to be F2 (Alt-2)

**Comment by praeclarum** [comment]
Oh!! Thank you for explaining. It see how it works now.

Wow, sorry - the app I was trying to emulate is an old DOS app that I run in DOSBox and its menus lit up when pressing Alt itself - but it makes sense terminals don't have this feature.

Thanks again for taking the time to explain!

**Comment by patanne** [comment]
I recognize the design has emacs overtones and so the escape key has meta functionality. What if I wanted to disable that so escape behaves more like it would on any old Mac or PC. Is there an easy way to do that?
