### ISSUE TITLE
Launch `0.90`

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#792]
Team:

Right now there is one bug remaining that is blocking releasing 0.90. Recall the plan for 0.90 is part of the plan to get to 1.0, documented here: #612 

List of 0.90 bugs:

https://github.com/migueldeicaza/gui.cs/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.90

If there are any other bugs you feel are critical for the `0.90` release, please speak up now!

Please review the release notes (in https://github.com/migueldeicaza/gui.cs/blob/master/Terminal.Gui/Terminal.Gui.csproj) for typos or missing items and submit a PR if you make any changes.

I would like to launch `0.90` today or tomorrow.

FWIW, I have updated `Out-ConsoleGridView` to use the latest and it works well. 

I've reached out to @migueldeicaza to get the nuget package generated.

**Comment by tig** [comment]
Update: I am trying to find time this weekend to do the workflow work to generate the nuget package. Lots going on so I have low confidence I'll find the time. But I'll try.

I think we're ready!

**Comment by tig** [comment]
Update: I have the publish to nuget Action basically working. I can't get the pdbs to publish and have asked @migueldeicaza to check to ensure nuget is configured for the v3 API, which may be the issue.

As a final test I'm updating `out-console-grid-view` to the latest API. I've found a bug where it doesn't exit correctly. I can't tell if it's my code or `Terminal.gui` but it's a show-stopper at this point until I can find the time to debug.

I will submit a PR we can all iterate on to finalize 0.90. Please watch for it.

**Comment by migueldeicaza** [comment]
Just for the record: we suspect that this needs additional work on the action, and is not something controlled by nuget.org

**Comment by tig** [comment]
Done! Woot!

Thanks for everyone's help. Now on to 1.0.
