### ISSUE TITLE
UICatalog selected screen - menu bar File - Quit causes app to hang (linux only)

### ISSUE THREAD

**Issue by daltskin** [migueldeicaza/gui.cs#800]
Scenario screens that contain a menu bar with the option File - Quit (eg. Editor), cause the application to hang on return to the main menu screen.  This happens on linux only (testing on WSL ubuntu)

- Select Editor screen
- Select File - Quit (from Menu bar)
- You are returned to the main menu - note that the cursor continues to blink - but the app is now unresponsive to any input

Note: Selecting the key combo CTRL-Q (ie. not using the menu bar) from the Editor screen behaves as expected.  So this is related to the menubar only.

**Comment by tig** [comment]
This doesn't repro in the main UI Catalog app or demo.cs?

**Comment by daltskin** [comment]
Are you trying to repo from running the code?  I've seen this from the running the published binaries for linux.
