### ISSUE TITLE
TextField: Unable to set text programatically if set to read only

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#814]
I'm not sure if this is a semantics thing, but when coding for things like WPF/Winforms with a textfield/box, if the dialog is read-only it cannot be hand-edited by the user, however you can set the displayed text still by assigning the backing data value.

Looking at the source for gui.cs however, if the text field is read only, you cannot set the .Text variable, even programmatically through the `Text` variable. Is this by design or by limitations of the console system(s)? I want a text box that is not editable by the user that display a path, however I want to update it to account for the path when I set it in code (for example, after the user chooses a path in a dialog). This seems like a pretty common UI concept. I'm not sure if it can't be distinguished when it is a user vs programatic change.

**Comment by BDisp** [comment]
This was to avoiding user could make a copy and paste. It's possible to set the text through the constructor. But the current behavior could be debatable.

**Comment by tig** [comment]
My opinion is read only applies only to user action, thus setting `Text` programmatically should work. Paste should not work.
