### ISSUE TITLE
How to update label text?

### ISSUE THREAD

**Issue by brian-pickens-web** [migueldeicaza/gui.cs#821]
What are the rules around how Label text gets updated in the console? I have a class that extends View, and every time AddValue() is called, it is supposed to update a `_divider` Label based on the new width of the View. However no matter what I try, including putting the update inside an `Application.MainLoop.AddTimer()`, the _divider label text doesn't seem to update.

```c#
private readonly Label _divider;
public Constructor(string name)
{
    _divider = new Label(string.Empty);
    Add(_divider);
}
public void AddValue(string value)
{
    if (value.Length > _width)
    {
        _width = value.Length;
        Width = _width;
        _divider.Text = string.Empty.PadLeft(value.Length, '-');
    }
    Add(new Label(value) { Y = Pos.Y(this) + this.Subviews.Count });
}
```

**Comment by BDisp** [comment]
It's better you put all the code to look at it, but it's seems that you are adding another label too. I think this is running after `Application.Init` and `Application.Run` of course.

**Comment by brian-pickens-web** [comment]
Is it a problem if `App`, my TopLevel view, is constructed before being passed into `Application.Run()`? 

```c#
public class Program
{
    private static Container _serviceProvider;

    public static void Main()
    {
        _serviceProvider = ConfigureServices();
        Application.Init();
        Application.Run(_serviceProvider.GetService<App>());
    }

    private static Container ConfigureServices()
    {
        var container = new Container();
        container.Options.DefaultLifestyle = Lifestyle.Singleton;

        container.Register<App>();
        container.Register<MainView>();

        return container;
    }
}
```

**Comment by BDisp** [comment]
> 
> 
> It's better you put all the code to look at it, but it's seems that you are adding another label too. I think this is running after `Application.Init` and `Application.Run` of course.

That is not what I intended to say. I was just saying that you can only update the Label when the application is actually running, that is, after Application.Run. If the issue really is after this instruction, I will have to analyze it with a more or less real code of the problem you are facing. Thanks.

**Comment by brian-pickens-web** [comment]
Okay, that may actually answer my question. Because the flow of execution means that the label gets updated while the TopLevel view is still being constructed.

**Comment by BDisp** [comment]
It's possible but it won't be shown, but if it the text `Label `is setted it will display the new text. But if it doesn't  display try to remove the `readonly `on the declaration of the `Label`.

**Comment by brian-pickens-web** [comment]
Okay, I figured out my issue. While the Label text was actually changing. I was unaware that the width of the label was set during its construction. And because all I was really doing was attempting to make the `_divider` longer with additional `-` characters the issue was hidden.

**Comment by BDisp** [comment]
I'm glad you managed to resolve it.
