### ISSUE TITLE
Question: How do I add views after Application.Run()?

### ISSUE THREAD

**Issue by brian-pickens-web** [migueldeicaza/gui.cs#833]
Hello,

How do I add views to the application after Application.Run() is called? The following code sample does not result in the ListView displaying on the screen like I would expect. If I rearrange the code so that listView is added before Application.Run() is called, the listview displays as expected.

```c#
public static void Main()
{
    Application.Init();
    
    var window = new Window()
    {
        Height = Dim.Fill(),
        Width = Dim.Fill()
    };

    Application.Top.Add(window);
    Application.Run();

    var listView = new ListView(new[] { "foo", "bar", "foobar" })
    {
        Height = Dim.Fill(),
        Width = Dim.Fill()
    };

    window.Add(listView);
}
```

**Comment by tig** [comment]
`Run()` is a blocking API that will not return until the application exits. 

See the `Application.Loaded` event: https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.Application.html?q=loaded

You'll want to subscribe to this event, and create the other views in your event handler.

Or, you could do it using `View.BeginInit()` or any other event that gets fired after the application is running.

**Comment by BDisp** [comment]
You must declare subroutines that are called when Application.Run is executed to do that.

**Comment by brian-pickens-web** [comment]
Thanks!
