### ISSUE TITLE
MainLoop.RunTimers(): System.ArgumentException: 'An entry with the same key already exists

### ISSUE THREAD

**Issue by brian-pickens-web** [migueldeicaza/gui.cs#835]
Hello,

I'm having trouble in the MainLoop execution which is throwing an exception in the RunTimers() method. It is failing when trying to add the Timeout back to be run again in the next iteration. The issue seems to be that the calculated ticks can be a duplicate with what is already in the `SortedList` which then throws the exception. I'm thinking that when RunTimers() adds the Timeouts back for the next iteration, it causes `DateTime.UtcNow` to possibly be the same for multiple timeouts. So then any timeouts with the same TimeSpan defined would then cause a collision.

![image](https://user-images.githubusercontent.com/3659859/89073843-e3b6d800-d340-11ea-8049-10f19b365c11.png)
![image](https://user-images.githubusercontent.com/3659859/89073857-e9acb900-d340-11ea-8965-74e73c4df82a.png)

**Comment by brian-pickens-web** [comment]
One possible solution might be to implement a [custom IComparer](https://stackoverflow.com/questions/5716423/c-sharp-sortable-collection-which-allows-duplicate-keys) that allows for duplicate keys.

**Comment by BDisp** [comment]
>  It is failing when trying to add the Timeout back to be run again in the next iteration.

Can you show how you are doing this please.

**Comment by brian-pickens-web** [comment]
Ill see if I can come up with a simple recreation.

**Comment by brian-pickens-web** [comment]
This code triggers the exception even without attempting the setup the second iteration of the Timers.

```c#
public static void Main()
{
    Application.Init();

    var window = new Window() { Height = Dim.Fill(), Width = Dim.Fill() };
    Application.Top.Add(window);

    var progress1 = new ProgressBar() { Height = 1, Width = Dim.Fill(), Y = 1 };
    var progress2 = new ProgressBar() { Height = 1, Width = Dim.Fill(), Y = 2 };

    window.Add(progress1);
    window.Add(progress2);

    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), loop =>
    {
        progress1.Pulse();
        return true;
    });

    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), loop =>
    {
        progress2.Pulse();
        return true;
    });

    Application.Run();
}
```

**Comment by brian-pickens-web** [comment]
This code snippet will make it through and execute Application.Run(), but when the MainLoop attempts to setup the next iteration of the Timeouts, thats when it will throw the exception.

```c#
public static void Main()
{
    Application.Init();

    var window = new Window() { Height = Dim.Fill(), Width = Dim.Fill() };
    Application.Top.Add(window);

    var progress1 = new ProgressBar() { Height = 1, Width = Dim.Fill(), Y = 1 };
    var progress2 = new ProgressBar() { Height = 1, Width = Dim.Fill(), Y = 2 };
    var progress3 = new ProgressBar() { Height = 1, Width = Dim.Fill(), Y = 3 };

    window.Add(progress1);
    window.Add(progress2);

    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), loop =>
    {
        progress1.Pulse();
        return true;
    });

    Thread.Sleep(1000);
    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), loop =>
    {
        progress2.Pulse();
        return true;
    });

    Thread.Sleep(1000);
    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), loop =>
    {
        progress3.Pulse();
        return true;
    });

            Application.Run();
}
```

**Comment by BDisp** [comment]
None of them are giving any error. Do you are using the nuget package or the Gui repository?

**Comment by brian-pickens-web** [comment]
I am running a clone of master.

**Comment by BDisp** [comment]
I haven't any exception.

![run-timers](https://user-images.githubusercontent.com/13117724/89105905-264de280-d41d-11ea-8fb2-a59097b9e8bc.gif)

**Comment by BDisp** [comment]
This might be something you are doing that there isn't in these snippets that is causing the exception.

**Comment by brian-pickens-web** [comment]
I’ll pull from master again and rerun my test but I’ll post the whole Program class along with my .csproj when I have a chance.

**Comment by tig** [comment]
Does this still repro? I'm closing for now. Please comment if it's still repro and we can reopen.
