### ISSUE TITLE
"Hiding" an element, but keeping it's position for when it's visible again?

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#838]
Sorry if this seems like a poor question, I've not really worked in a text mode framework. How would one "hide" an element on the screen that I want to make visible later? I have a procedure that uses 3 lines of text to describe the current operations. At various points I would like to make the item 'invisible' but without setting the text blank for the label that it is associated with. Is there a concept for this or am I forced to clear the label to make it not visible? I did not see anything in the documentation for something like this.

**Comment by tig** [comment]
@BDisp just saw this. Nevermind my query on #839.
