### ISSUE TITLE
Top view is cut off when restarting terminal.gui.application

### ISSUE THREAD

**Issue by rueckertch58521** [migueldeicaza/gui.cs#851]
Hi,

I have a strange behavior in my Application where I use Terminal.Gui for two tasks. The first task is to do some inputs for variables.

![image](https://user-images.githubusercontent.com/34653494/89532090-895ec100-d7f1-11ea-8872-113f74c68526.png)

Everything works fine so far.

After the user has done his input he pushes the button "Apply" and that hits `Application.RequestStop()`. Afterward, a process is started and is visualized with another top view of Terminal.Gui. Here is the problem: For the second GUI I resize the Console-Window and also the top-view. But when the GUI starts part of the top-view is cut off.

![image](https://user-images.githubusercontent.com/34653494/89532448-199d0600-d7f2-11ea-9d99-7fb263c74948.png)

On a simpler code sample it works...

Do you guys have any idea why the top view is cut off?

Also, if I start the second Window on its own it is not cut off, only if I start it after the first one.

**Comment by rueckertch58521** [comment]
![image](https://user-images.githubusercontent.com/34653494/89533086-2110df00-d7f3-11ea-92cb-4b4aa06709fc.png)

This is how the second Window should look

**Comment by BDisp** [comment]
> For the second GUI I resize the Console-Window and also the top-view. But when the GUI starts part of the top-view is cut off.

How you are resizing the `GUI`? If it is by programmatically using `Console `class that could happen because the buffer length is changing by other class than the used by the `GUI`. If it isn't then it must something wrong with your code.

**Comment by rueckertch58521** [comment]
I resize the console `GUI` with the `Console `class. What is the "correct" way to resize the `GUI `?

**Comment by rueckertch58521** [comment]
So, I changed the order of resizing the console window and initializing Terminal.Gui.Application and it works. Thanks for your help =)

**Comment by BDisp** [comment]
@rueckertch58521, you welcome. Can you tell what the correct order for resizing the console please?

**Comment by rueckertch58521** [comment]
In my application I do it like this (solution):

1.  Resize console-window via `Console.WindowWidth` depending on content
2. Initialize `Terminal.Gui`
2. Create top-view and add content to it
3. Add top-view to `Terminal.Gui.Application`
4. Run `Terminal.Gui.Application`

When the error occurs I did it like this:
1. Initialize `Terminal.Gui`
2. Create top-view and add content to it, while adding content resize console-window depending on the 
content that needs to be shown
3. Add top-view to `Terminal.Gui.Application` 
4. Run `Terminal.Gui.Application`

On my first try, I thought it would be good to stick adding content to top-view and resize console window together. Now I have to calculate the size of the console-window before I add content to top-view.

**Comment by BDisp** [comment]
A little example would be most than good. I would like to add a method for resizing that would do that automatically and the developer only to call for example` Application.Resize (Cols, Rows)`.
