### ISSUE TITLE
ArgumentOutOfRangeException in FileDialog.cs/ExecutSelection() when changing directory

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#852]
Found this bug when using the OpenDialog for picking a directory. If I manually type in a path on a partition root, changing it from my current one, it will throw the listed exception. It seems that selection index is not checked for this method is called, as if there is nothing there (it hasn't loaded the files yet?) it will try to access an empty list.

![image](https://user-images.githubusercontent.com/2738836/89603026-5d5d3300-d825-11ea-9feb-a000a26b3bf5.png)

Here's video showing how to reproduce it
https://www.youtube.com/watch?v=mT5Ai1D2OrQ

This is based on latest code from master branch (so about 7 days old since last commit). This was a NAS drive that was connected but the file listing was not accessible. Windows does this thing where until you try to do an actual data access it won't spin drives up, so devices don't seem to think the drive actually is accessible (it causes all sorts of fun issues)

**Comment by Mgamerz** [comment]
This bug actually crops up in multiple areas: Pretty much anywhere `infos[selected]` is called, this bug seems to be able to occur in FileDialog.cs, if the directory currently specified is not valid, which happens a lot if I am typing in the path.

**Comment by BDisp** [comment]
Please test with my branch to check is everything alright.
