### ISSUE TITLE
Clicking cancel in OpenDialog returns FilePaths objects even if you press cancel

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#854]
Maybe I'm missing something in documentation (I looked through the OpenDialog pages), but if you press Cancel on an OpenDialog, the selected item is still returned. I'm not sure if I'm supposed to look at another variable to see if the dialog was accepted, but I guess I thought the values wouldn't be set if you pressed canceled (no selection/cancel).

How do I tell if the user canceled the OpenDialog?

**Comment by BDisp** [comment]
It's in the `demo.cs` at the `Open `method, there is a `Canceled `property.

```cs
public static void Open ()
{
	var d = new OpenDialog ("Open", "Open a file") { AllowsMultipleSelection = true };
	Application.Run (d);

	if (!d.Canceled)
		MessageBox.Query (50, 7, "Selected File", d.FilePaths.Count > 0 ? string.Join (", ", d.FilePaths) : d.FilePath, "Ok");
}
```

**Comment by Mgamerz** [comment]
Ah, did not see that. Might be good idea to also put this in documentation for OpenDialog.
