### ISSUE TITLE
Wrapping with a ListView ?

### ISSUE THREAD

**Issue by Ssiws** [migueldeicaza/gui.cs#860]
Hello,

Is it possible to disable the scrollbar on a ListView and wrap the overflow on a second column?

Here is a snippet of my code:
 ``` csharp
     FrameView frame = new FrameView() { Width = Dim.Percent(50), Height = Dim.Fill(), Title = root };
     lv = new ListView(Model.Data.GetData(root)) { Width = Dim.Fill(), Height=Dim.Fill() };
     frame.Add(lv);
```

Thanks !

**Comment by BDisp** [comment]
I didn't know that the ListView has a scrollbar. ???

**Comment by Ssiws** [comment]
Well, I checked again: there is no scrollbar, however, the content can scroll.
Do you know if it is possible to disable the scrolling, and wrap the content on another column ? I'm using the latest code in `master`

**Comment by BDisp** [comment]
No it doesn't have that feature.
