### ISSUE TITLE
RemoveAll() followed by adding content to the view causes weird rendering until console is resized

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#866]
This might be a misunderstanding by me of how to do this, however it seems to not do what is expected when clearing all views and adding new ones one after another. I build an interface based on some variables, and when some of those variables change (which would change a lot of items), I simply clear the interface and re-add the new updated elements rather than editing the existing ones. When I call RemovalAll(); followed by a method that adds the elements back to the interface, I get this weird corruption:

![2020-08-13_20h29_11](https://user-images.githubusercontent.com/2738836/90207635-036be880-dda4-11ea-864b-d5541e7566bf.gif)

This button's code is this:
```
Add(new Button("Reload UI")
            {
                X = Pos.Right(this) - 30,
                Y = Pos.Bottom(this) - 3,
                Height = 1,
                Clicked = () =>
                {
                    RemoveAll();
                    buildUI();
                    Application.Refresh();
                }
            });
```

and the buildUI() code is nothing special. It just adds objects to view.
![image](https://user-images.githubusercontent.com/2738836/90207802-6cebf700-dda4-11ea-8bb9-54b54d38d455.png)

The items can be tabbed through with the cursor and they all still work but the rendering doesn't seem to take place. If I remove the Application.Refresh() the old contents stay rendered and the new ones also render in the same top left glitchy look. I also tried SetNeedsDisplay() but it has the same result. I assume this would work if I somehow waited to add the controls back after the next refresh occurred, but I don't know if this is expected behavior.

![image](https://user-images.githubusercontent.com/2738836/90207901-b50b1980-dda4-11ea-8214-aa5d3986ca0d.png)

**Comment by BDisp** [comment]
`RemoveAll ()` only remove the views from the `SuperView `but the views are still with his value. Try use the `Dispose `method to remove them from memory or setting as null. Another solution is to reload the `Application.Top` again with the new views.

**Comment by Mgamerz** [comment]
Got it. Since this is a simple UI I just reloaded the whole uicontroller object's that I use and it works just fine. Thanks!
