### ISSUE TITLE
MenubarItem() Argument Exceptions

### ISSUE THREAD

**Issue by jowlsaw** [migueldeicaza/gui.cs#867]
I am trying to create a menubar with two menu items(without the sub menus) by modifying the demo [app](https://github.com/migueldeicaza/gui.cs/blob/master/StandaloneExample/Program.cs).

At first, I tried
```
		var menu = new MenuBar ( new MenuBarItem [] {
			new MenuBarItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }),
			new MenuBarItem ("_Settings", "",() => Settings ())
		});
```

when I build, I receive error CS1729: 'MenuBarItem' does not contain a constructor that takes 3 arguments

Then I tried, 
```
		var menu = new MenuBar ( new MenuBarItem [] {
			new MenuBarItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }, null),
			new MenuBarItem ("_Settings", "",() => Settings (), null)
		});

```
when I build, I receive error CS1729: 'MenuBarItem' does not contain a constructor that takes 4 arguments.

Not sure what I am doing wrong, I need help

**Comment by BDisp** [comment]
Try this
```cs

var menu = new MenuBar ( new MenuBarItem [] { new MenuItem [] { 
			new MenuItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }, null),
			new MenuItem ("_Settings", "",() => Settings (), null)
		}});

```

**Comment by jowlsaw** [comment]
i tried that already and I receive error CS0029: Cannot implicitly convert type 'Terminal.Gui.MenuItem[]' to 'Terminal.Gui.MenuBarItem'

**Comment by BDisp** [comment]
Sorry was wrong

```cs
menu = new MenuBar (new MenuBarItem [] {
			new MenuBarItem ("_File", new MenuItem [] {
				new MenuItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }, null),
				new MenuItem ("_Settings", "",() => Settings (), null)
			}});
```

**Comment by jowlsaw** [comment]
this creates a seperate file menu which is not what I want.
![Screenshot from 2020-08-14 23-04-24](https://user-images.githubusercontent.com/26406786/90292709-bf034a00-de82-11ea-82a9-39e053deed12.png)

I'd like it to be two items in the menubar so it looks like this and when I click them, their respective function is triggered instead of a dropdown menu:
![Screenshot from 2020-08-14 23-10-20](https://user-images.githubusercontent.com/26406786/90293000-5f596e80-de83-11ea-836a-b5ddfe6bb265.png)

**Comment by BDisp** [comment]
```cs
menu = new MenuBar (
                        new MenuBarItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }),
		        new MenuItem ("_Settings", "",() => Settings ())
			}});
```

**Comment by jowlsaw** [comment]
gives these two errors:

error CS1729: 'MenuBarItem' does not contain a constructor that takes 3 arguments
error CS1729: 'MenuBar' does not contain a constructor that takes 2 arguments

P.S - I sincerely appreciate your efforts to help me :)

**Comment by BDisp** [comment]
I'm doing without the IDE :-)

```cs
menu = new MenuBar (new MenuBarItem [] {
                        new MenuBarItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }),
		        new MenuBarItem ("_Settings", "",() => Settings ())
			});
```

**Comment by jowlsaw** [comment]
> I'm doing without the IDE :-)
> 
> ```cs
> menu = new MenuBar (new MenuBarItem [] {
>                         new MenuBarItem ("_Quit", "Quit the application", () => { if (Quit ()) top.Running = false; }),
> 		        new MenuBarItem ("_Settings", "",() => Settings ())
> 			});
> ```

this is same as my first code in the issue description, I tried it again now anyways and I get the same "'MenuBarItem' does not contain a constructor that takes 3 arguments" exception twice for each of the two menuBarItems - same as earlier.

**Comment by BDisp** [comment]
You are using the master GUI or nuget package?

**Comment by jowlsaw** [comment]
I am using nuget package Terminal.Gui --version 0.81.0

my dev environment is dotnet core with VS Code running in linux.

**Comment by BDisp** [comment]
I think the nuget package does not have these updates yet.

**Comment by jowlsaw** [comment]
:(  
I see [version 0.90.0 was going to be deployed to nuget last month](https://github.com/migueldeicaza/gui.cs/issues/792), but that item is still open(I can just wait for it), will Version 0.90.0 contain the updates?

**Comment by BDisp** [comment]
I think so. Everything already in the master should be published.

**Comment by jowlsaw** [comment]
thank you, 
I will try building the Master, otherwise I will just wait for new version.
