### ISSUE TITLE
Modifier key are not fully supported with CursesDriver

### ISSUE THREAD

**Issue by StefanHolst** [migueldeicaza/gui.cs#881]
It seems modifier key are not fully supported with CursesDriver.

Some examples: 
- `CTRL+1` not supported.
- `CTRL+SHIFT+S` not supported.
- `SHIFT+F5`. not supported.
- `CTRL+S` supported (with `ControlS` key).

However, most of these are supported with the WindowsDriver, except `CTRL+1`.

**Comment by tig** [comment]
We need to completely re-write the driver used on Linux. See https://github.com/migueldeicaza/gui.cs/issues/370.

I've added a link to this issue in that Issue so it can be referenced as we do this...
