### ISSUE TITLE
Funny behavior resizing and relaunching the app

### ISSUE THREAD

**Issue by gamosoft** [migueldeicaza/gui.cs#887]
Hi there, first of all thanks for putting this together it's very cool. :-)

Now, maybe you have already noticed this but there's a weird issue when resizing the window, other than the "glitch" already mentioned.

Here I have a very sample test app with the sample code from Scott Hanselmann's post (https://www.hanselman.com/blog/Its2020AndItIsTimeForTextModeWithGuics.aspx).

So I add the code and run it with `dotnet run` and shows nicely:

![original](https://user-images.githubusercontent.com/9968384/92094498-ce681a00-edd4-11ea-84ec-601746df27fb.png)

Now, if I resize the screen I notice the "glitch" others have talked about and the display stays the same, but if I exit the app and relaunch it, now the window looks all messed up:

![relaunched](https://user-images.githubusercontent.com/9968384/92094585-e93a8e80-edd4-11ea-9525-774af448eaf8.png)

sometimes it looks REALLY messed up:

![relaunched2](https://user-images.githubusercontent.com/9968384/92095053-77af1000-edd5-11ea-95a3-1b038ea10be0.png)

The app is fully functional, only the layout is ugly. I'm using Windows Terminal 1.2.2381.0 

I have tested in a plain command prompt and here the problem doesn't happen, but I noticed that if I resize the app while it's running, upon closing it the window goes back to the initial size.

Not sure if this has already been mentioned elsewhere but here it goes just in case. :-)

Thanks again!
Kind regards.

**Comment by BDisp** [comment]
`Windows Terminal` doesn't work well with `GUI`. It has to do with them himself and not with `GUI`, I think.

**Comment by BDisp** [comment]
Be sure you are using the latest `API `too.

**Comment by tig** [comment]
Windows Terminal does have bugs when resizing that we can't fix ourselves. However, they usually only occur WHILE resizing. I'm going to close this as 'wontfix'.
