### ISSUE TITLE
LINUX: Clicking menu item that is above listview item causes listview to be selected instead

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#892]
![image](https://user-images.githubusercontent.com/2738836/92332846-dbd40d00-f03d-11ea-9276-907edf13b6ae.png)

I thought I saw a commit for this recently, but couldn't find it. On Windows, if you click on a menu item that's over a listview (as shown on the right), it clicks the menu item. If you do the same thing on Linux (Ubuntu 20 in this case), it closes the menu and selects the listview (but not the item). This is through mouse interaction; with keyboard it works as expected.

**Comment by BDisp** [comment]
I think it's was PR #596.

**Comment by tig** [comment]
Does this still repro?

**Comment by tig** [comment]
@BDisp  any status?

**Comment by BDisp** [comment]
@tig that don't repro anymore.

**Comment by tig** [comment]
yay!
