### ISSUE TITLE
ScrollView Parameterless Constructor

### ISSUE THREAD

**Issue by mrzachhigginsofficial** [migueldeicaza/gui.cs#893]
Using Terminal.GUI 0.81, I am attempting to create a scroll view with computed positioning. The documentation states I should be able to initialize this by using the parameterless constructor: https://migueldeicaza.github.io/gui.cs/api/Terminal.Gui/Terminal.Gui.ScrollView.html

However, a parameterless constructor does not appear to exist.
![image](https://user-images.githubusercontent.com/53547287/92335342-34b69c00-f064-11ea-8fb5-a367b1656291.png)

How can a scrollview be created with computed positioning?

**Comment by Mgamerz** [comment]
The documentation is coded against the current codebase, as stated in the project's readme. The 0.81 code is significantly outdated right now.

**Comment by tig** [comment]
Closing as this is addressed in 0.90
