### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by inamvar** [migueldeicaza/gui.cs#894]
Is there any plan for RTL support?

**Comment by BDisp** [comment]
Do you meaning this https://en.wikipedia.org/wiki/Register_transfer_language?

**Comment by biohazard999** [comment]
@BDisp I think he means [RightToLeft support](https://en.wikipedia.org/wiki/Right-to-left)

**Comment by BDisp** [comment]
> 
> 
> @BDisp I think he means [RightToLeft support](https://en.wikipedia.org/wiki/Right-to-left)

Thanks @biohazard999, I didn't know that kind of encoding already existed for script :-)

**Comment by jmperricone** [comment]
Hi, #1195 will solve this.

**Comment by jmperricone** [comment]
@tig  This can be closed! Its Right To Left text direction.

**Comment by moohaad** [comment]
What about layout  mirroring  Right to Left flow

for example FrameView




[Windows Forms supported long ago](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/bi-directional-support-for-windows-forms-applications?view=netframeworkdesktop-4.8)
