### ISSUE TITLE
async issue?

### ISSUE THREAD

**Issue by jhgbrt** [migueldeicaza/gui.cs#895]
While experimenting with async in a Terminal.Gui app, I noticed that async calls were not completing, causing the app to hang. While narrowing down, I noticed that just calling Application.Init() in a console application prevents async calls from completing:
```
		static async Task Main (string [] args)
		{
			await Task.Delay (10);
			Console.WriteLine ("1");
			Application.Init ();
			await Task.Delay (10);
			Console.WriteLine ("2");
		}
```
This method hangs on the second Task.Delay.

**Comment by BDisp** [comment]
Since you call `Application.Init ()` you must also call `Application.Run ()` and invoke the async call which will call `Application.RequestStop ()` to exit the app.

```cs
static async Task Main (string [] args)
{
	await Task.Delay (10);
	Console.WriteLine ("1");
	Application.Init ();
	Application.MainLoop.Invoke (async () => {
		await Task.Delay (10);
		Console.WriteLine ("2");
		Application.RequestStop ();
	});
	Application.Run ();
}

```
