### ISSUE TITLE
Control: StatusBar/Function Bar

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/gui.cs#9]
This is the function bar at the bottom of the screen that provides a visual cue for the available commands.

**Comment by Slesa** [comment]
There are two possibilities here: just show a part (or all) of the available hotkeys, or show a short message. Or hide the hotkey content when a message is shown for a short time.

Should the StatusBar be multiline? Should it also handle the hotkeys or just display them? In the latter case, it only has to display a content with a color-switching character:
```
new StatusLine("~F1~ Help ~F2~ Save ~F3~ Load");
```
in the former it probably looks like
```
new StatusLine()
  .AddCommand( new Command("F1", "Help", () => Help() )
  .AddCommand( new Command("F2", "Save", () => Save(), () => CanSave() )
  .AddCommand( new Command("F3", "Load", () => Load(), () => CanLoad() );
```

**Comment by migueldeicaza** [comment]
Some other topics to ponder:

* Is the StatusBar the provider of the global accelerator, or just a useful display?   I think it should provide the accelerator, and respond to keyboard input
* I think that if we go with a global one, that we need a push/pop system, but perhaps the pushing/popping should be the job of running a new toplevel.

**Comment by tig** [comment]
`StatusBar` is in. Closing.
