### ISSUE TITLE
Status bar disappearing after resizing

### ISSUE THREAD

**Issue by abiratur** [migueldeicaza/gui.cs#901]
Steps to reproduce:
1. Run UICatalog
2. Maximize window
3. Decrease window size and watch the status bar disappears 

My guess is that the root cause is not related specifically to the status bar.
since this code also produces the same issue:
https://gist.github.com/abiratur/90dcf0517a60fbaaf2515a83d64284bb

(Possible duplicate of #698)

**Comment by tig** [comment]
Please be specific on what OS you are on and what console you are using.

**Comment by abiratur** [comment]
Windows, cmd

**Comment by tig** [comment]
> Windows 10, cmd

There is no API we can use in `cmd.exe` to know the window has been made smaller vertically. So this can't be fixed. 

Suggest you use a different terminal, such as ConEmu or Windows Terminal.
