### ISSUE TITLE
Cursor blinks on listviews etc...

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#905]
I do not think the cursor should blink on UI elements that already show selected status.

I thought this had been fixed/changed but it looks like a recent PR changed it back.

Does anyone disagree that the blinking cursor should only show in edit boxes?

**Comment by BDisp** [comment]
I agree but I think it isn't possible hiding the cursor but only hacking with the same background color.

**Comment by tig** [comment]
IIRC, there's a driver API to hide/show cursor...
