### ISSUE TITLE
Resizing not working in iTerm on macOS Catalina

### ISSUE THREAD

**Issue by TylerLeonhardt** [migueldeicaza/gui.cs#907]
Resizing doesn't appear to work on macOS Catalina (using iTerm2):

![image](https://user-images.githubusercontent.com/2644648/94349539-13f5bc80-fffa-11ea-8ac0-f9024f212f47.png)

using 0.84 of Terminal.Gui

**Comment by BDisp** [comment]
Using iTerm2 in Linux Ubuntu (WSL) does not fail to resize, but there are many gaps with printing the letters. Perhaps bad mapping related to unicode keys. It seems that some unicode characters aren't properly rendered his lenght in  that TERM.

![iterm2](https://user-images.githubusercontent.com/13117724/94360806-10207380-00a8-11eb-8fcb-bfab76b82ebd.gif)

**Comment by TylerLeonhardt** [comment]
I thought iterm2 was macOS only 🤔

**Comment by BDisp** [comment]
> 
> 
> I thought iterm2 was macOS only 🤔

I think it is but I did change the TERM to iTerm2 and got this ugly view :-)

**Comment by TylerLeonhardt** [comment]
Just tried this in Terminal.app (the default terminal in macOS and it has different behavior:

![image](https://user-images.githubusercontent.com/2644648/94371404-2a0f8580-00ab-11eb-8b17-6c8ef554e88f.png)

Here's terminus as well:
![image](https://user-images.githubusercontent.com/2644648/94371433-6511b900-00ab-11eb-8387-b8ccd264676f.png)

**Comment by BDisp** [comment]
Therefore, it should not be related to GUI problems.

**Comment by tig** [comment]
I don't have a mac. I believe this is fixed, right???

**Comment by BDisp** [comment]
I think this not repro anymore.
