### ISSUE TITLE
Turbo Vision (aka TVision) like controls?

### ISSUE THREAD

**Issue by rgl** [migueldeicaza/gui.cs#916]
Is there hope for a Turbo Vision (aka TVision) like controls?

I mean more than a [color scheme](https://github.com/migueldeicaza/gui.cs/issues/29), the full glory of tvision (like the window shadows and button half shadows) :-)

**Comment by tig** [comment]
See these (essentially) dupes #463 and #898.

**Comment by rgl** [comment]
Oh I see. I've subscribed to those, thx!
