### ISSUE TITLE
Window should support not having a frame/title

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#927]
`Window` is currently hard coded to have a frame (and title).

There are cases where this frame is un-wanted, especially in scenarios where the user wants max screen real estate.

Suggestion is to 

- Add a `bool HasFrame` property (default `true`). Can't be `Frame` because that's already a member.
- Logic throughout would need to change (see all places where `1 + ` exists).

if `padding = 0` and `HasFrame` is `false` then `X` and `Y` would be 0, 0.

If `padding =1` and `HasFrame` is `false` then `X` and `Y` would be 1, 1.

**Comment by tig** [comment]
I just realized this has an easy work around:

```csharp
            var win = new Window("title")
            {
                X = -1,
                Y = -1,
                Width = Dim.Fill(-1),
                Height = Dim.Fill(-1)
            };
```

Any reasons why this won't work? (I tested it and it seems fine).

**Comment by BDisp** [comment]
Only the line in the title is printed. Even using a empty string it also printed because the margin isn't handled for the top. So the top horizontal line is always printed. Maybe `if Y == -1 && title.IsEmpty` don't print the line.

**Comment by tig** [comment]
> Only the line in the title is printed. Even using a empty string it also printed because the margin isn't handled for the top. So the top horizontal line is always printed. Maybe `if Y == -1 && title.IsEmpty` don't print the line. And `if Y == -1 && !title.IsEmpty` only print the title and supress the line.

I'm not sure what you mean. In another test, I modified Generic to:

```csharp
class MyScenario : Scenario {
	public override void Setup ()
	{
		// Put your scenario code here, e.g.
		var button = new Button ("Press me!") {
			X = Pos.Center (),
			Y = Pos.Center (),
		};
		button.Clicked += () => MessageBox.Query (20, 7, "Hi", "Neat?", "Yes", "No");
		Win.X = -1;
		Win.Y = -1;
		Win.Height = Dim.Fill (-1);
		Win.Width = Dim.Fill (-1);
		Win.Add (button);
	}
}
```
![image](https://user-images.githubusercontent.com/585482/94623362-d6e33180-0268-11eb-9346-6ded2cb6becc.png)

So it seems to work fine. What am I missing?

**Comment by BDisp** [comment]
I tested in the Example project and since it have a MenuBar and a StatusBar the horizontal top line is printed.

**Comment by tig** [comment]
Closing. Won't fix.
