### ISSUE TITLE
Where the ShortCut should be reside?

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#928]
I will talk about three places where it will could belong according to my order of preference:

1. On the `TextFormatter `and in the `View`.
2. On the `View `only.
3. On the `Menu `(This going limit the use case of shortcuts than can be used on multiple views)

Please give me suggestions.

**Comment by BDisp** [comment]
On the `TextFormatter `there are no sense, sorry.

**Comment by tig** [comment]
Related: https://github.com/migueldeicaza/gui.cs/issues/944

Whatever you decide, we need to make sure this works. I'm not sure I have a strong opinion yet.

**Comment by BDisp** [comment]
I can guarantee to you it will work better than before, although in unix some combinations won't work at all, mainly Ctrl+Shift and some functions keystroke.

**Comment by tig** [comment]
> I can guarantee to you it will work better than before, although in unix some combinations won't work at all, mainly Ctrl+Shift and some functions keystroke.

Can you explain the technical reason Ctrl+Shift won't work via Curses? I'm curious to know.

**Comment by BDisp** [comment]
> Can you explain the technical reason Ctrl+Shift won't work via Curses? I'm curious to know.

Because the value is always the same no matter the shift key is pressed or not.

**Comment by tig** [comment]
> > Can you explain the technical reason Ctrl+Shift won't work via Curses? I'm curious to know.
> 
> Because the value is always the same no matter the shift key is pressed or not.

That's not a very technical description. What value? 

I can't tell if this is a limitation of Curses or an underlying Linux/mac issue. For example, is it possible that building a Linux/Mac `ConsoleDriver` with some other layer OTHER than Curses, could address this? If so, what are our options. 

Note, if you don't know that's ok. But we need to find someone who does because much like mouse not working in Windows Terminal, Terminal.Gui looks pretty silly if fundamental things like chorded-key-presses don't work on Linux/Mac.

**Comment by BDisp** [comment]
There may be new versions of ncurses that can better handle keyboard and mouse processing. Anyway, I can already process many key combinations in Linux. What is really bothering me is the fact that the mouse movement is no longer being detected in linux. That is why I suspect that there may be new features of libncurses that need to be explored but I confess that I am not a specialist in linux or mac. I can promise to try to search for solutions and find patience for it.

**Comment by BDisp** [comment]
> That's not a very technical description. What value?

For example, pressing `Ctrl+A `wch return 1 and pressing `Ctrl+Shift+A` wch also return 1. So we don't have another variable, unlike Windows which has the modifiers keys, to compare and distinguish the difference. The only certain we have is the code 1 really contains the Ctrl key but not the Shift key. Unfortunately it's not possible. See here https://invisible-island.net/ncurses/ncurses.faq.html#modified_keys. It could be possible with the `X11 `library which read the keys state, but go beyond the GUI objective as console and not as `Windows Forms`.
