### ISSUE TITLE
Associate arbitrary data with View

### ISSUE THREAD

**Issue by patriksvensson** [migueldeicaza/gui.cs#932]
It would be super convenient if it was possible to associate arbitrary data with a `View` object, just like I can with `Tag` in `TreeViewItem` in Windows Forms or `DataContext` in WPF.

Of course, I could always subclass all controls and implement it myself, but it would be very convenient if `View` contained a property `Data` or similar that could be used for this.

**Comment by tig** [comment]
Good suggestion. Please feel free to craft a PR. I assume this is as simple as adding this to `View`:

```csharp
/// <summary>
/// Arbitrary data. Not used internally. 
/// </summary>
public object Data { get; set; } ;
```

??

**Comment by BDisp** [comment]
Or maybe creating both. `Tag `to store simples information and `DataContext `is more related with relational data.

**Comment by patriksvensson** [comment]
@tig Happy to submit a PR for this.
