### ISSUE TITLE
Terminal.Gui apps under WSL don't get keystrokes when started as EXE

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#936]
Try running any standalone Terminal.gui app under under WSL. Arrow keys and other keys do not work. Some shortcut keys (e.g. CTRL Q don't).

- Setup WSL2 with Debian or Ubuntu (I've tried both). 
- Install .NET Core 5
- git clone https://github.com/migueldeicaza/gui.cs

```bash
cd gui.cs
dotnet build
./UICatalog/bin/Debug/net5.0/UICatalog.exe
```

Expected: 
Up/Down/Left/Right keys work.
Tab/CtrlQ work.

Result:
Only Tab/CtrlQ work.

Note that if you run the app with `dotnet` against the dll it works fine:

```bash
dotnet ./UICatalog/bin/Debug/net5.0/UICatalog.dll
```

**Comment by BDisp** [comment]
I don't have that issue.

**Comment by BDisp** [comment]
You'll see that the mouse is not working well because of the `WSL `display limitations. In this case you must test in a real or virtual complete `Linux OS`.

**Comment by tig** [comment]
Won't fix. Running .exe is not the right way to start  dotnet app in Linux. 

Use `./UICatalog/bin/Debug/net5.0/UICatalog` or `dotnet run --project UICatalog` instead.

**Comment by BDisp** [comment]
> Use `./UICatalog/bin/Debug/net5.0/UICatalog` or `dotnet run --project UICatalog` instead.

I use `dotnet ./UICatalog/bin/Debug/net5.0/UICatalog.dll`
