### ISSUE TITLE
Is it possible to have a Telnet window?

### ISSUE THREAD

**Issue by aswanevelder** [migueldeicaza/gui.cs#940]
Is it possible to have a frame/window that runs a separate Telnet session?

**Comment by tig** [comment]
> Is it possible to have a frame/window that runs a separate Telnet session?

Sure. 

You'll want to include something like https://github.com/migueldeicaza/XtermSharp/blob/master/GuiCsHost/TerminalView.cs

in your app. 

That code is a bit old, so some work will be required to get it all to work, but it's def possible.
