### ISSUE TITLE
StatusBar - SHIFT-CTRL-A shortcut not possible

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#944]
`new StatusItem(Key.ShiftMask | Key.CharMask | (Key)65, "~SHIFT-^A~ Select None", () => ...`

This does not work. 

Neither does `Key.ShiftMask | Key.ControlA` which is what I tried first,

Am I missing something or is this just broke?

**Comment by BDisp** [comment]
These combinations never worked all together before. I almost have all that ready but it will get some days to finish.

**Comment by tig** [comment]
> These combinations never worked all together before. I almost have all that ready but it will get some days to finish.

Sweet. Here's the use case: https://github.com/PowerShell/GraphicalTools/issues/120

**Comment by BDisp** [comment]
>On Windows/Linux ^A would be CTRL-A. On Mac it would be Command-A

Well the solution I'll going to submit will return a string like Ctrl+Alt+1 or whatever is choosed but if is the case of print the Ctrl with another name the developer will be deal with that.

**Comment by migueldeicaza** [comment]
While it might be possible to support this on Windows, it will not work on Unix, as there is no way of encoding "control" for uppercase/lowercase, there are only 26 or so control values available, and the kernel does not distinguish those, nor do terminal emulators.

**Comment by tig** [comment]
Won't fix.
