### ISSUE TITLE
MenuBar in Mvvm/ReactiveUI example

### ISSUE THREAD

**Issue by 9swampy** [migueldeicaza/gui.cs#948]
New to Terminal.Gui but liking the concepts generally; looks very promising... thanks for the effort put in already.

Coming from Mvvm/Wpf I've been trying to follow the great ReactiveUI example; keen to bind to testable Models/ViewModels I've been finding the MenuBar isn't refreshing correctly.

When MenuBar is added to a View I'm finding events to clear upon MouseLeave for example don't fire/don't cause the UI to clear properly.

Any chance of an example or any pointers on what needs to be wired up to relay appropriate events; I'd be happy to extend the sample and submit a pull request to add to the example if I get it to work - if that'd be welcomed.

**Comment by tig** [comment]
The ReactiveUI stuff is pretty new. I'm guessing you've found a bug. Could you please share your code with us?

**Comment by 9swampy** [comment]
Having come back to it to build a simple example to demonstrate the issues I've found it to be behaving more as expected. Perhaps a binary cache went wrong somewhere? I'll close and revert when (if) I'm able to replicate more specific repeatable scenarios.

**Comment by BDisp** [comment]
I can confirm that the UI has an unexpected behavior after quit a scenario through `Ctrl+Q` with the mouse being offscreen. That scenario should stay selected and only after some interaction with keyboard or mouse the event is finished. This bahavior doesn't happens with Windows but only with Linux and Mac. I don't know if it's related.
