### ISSUE TITLE
TextField: System.InvalidOperationException after delete/backspace

### ISSUE THREAD

**Issue by adamowski10** [migueldeicaza/gui.cs#95]
V: 0.10.0 from May 18, 2018
1) Type something in TextField
2) Try delete character using backspace/delete
3) System.InvalidOperationException: 
   w Terminal.Gui.TextField.RuneIndexToByteIndex(Int32 index)
   w Terminal.Gui.TextField.ProcessKey(KeyEvent kb)
   w Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   w Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   w Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   w Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   w Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   w Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke)
   w Terminal.Gui.WindowsDriver.Mono.Terminal.IMainLoopDriver.MainIteration()
   w Mono.Terminal.MainLoop.MainIteration()
   w Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   w Terminal.Gui.Application.Run(Toplevel view)
   w Terminal.Gui.Application.Run()
   w gui.Program.Main(String[] args)

**Comment by luetm** [comment]
Might be a side effect of something we are doing here https://github.com/migueldeicaza/gui.cs/issues/81 , but with 0.9.0 you should be fine.

**Comment by migueldeicaza** [comment]
Incoming fix, will be in the 0.11 release
