### ISSUE TITLE
Mouse click on Menu is not working on linux terminals

### ISSUE THREAD

**Issue by quentin-dev** [migueldeicaza/gui.cs#976]
I have tried running my program on Ubuntu 20.04 (WSL2) and the latest Arch Linux version, and on both machines, `MessageBox.Query` does not work. The expected message box never appears, do you know what could be done to fix this ?

**Comment by quentin-dev** [comment]
I should mention that the `MessageBox.Query` works fine when I run it on Windows

**Comment by tig** [comment]
Can you share the code you are using?

**Comment by quentin-dev** [comment]
Sure, here it is:

```C#
            Application.Init();

            var top = Application.Top;

            var window = new Window("sharpengine")
            {
                X = 0,
                Y = 1,

                Width = Dim.Fill(),
                Height = Dim.Fill() - 1
            };

            var menu = new MenuBar(new MenuBarItem[] {
                new MenuBarItem("_Help", new MenuItem[] {
                    new MenuItem("_About", string.Empty, () => {
                        MessageBox.Query("sharpengine", "A demo C# game engine for text-based adventure games.", "Close");
                    }),
                }),
            });

            top.Add(window, menu);

            Application.Run();
```

**Comment by tig** [comment]
FWIW, the UICatalog MessageBox sample creates a MessageBox on Linux (Debian) fine. And the About box works.  For me anyway.

Can you confirm UICatalog works for you?

**Comment by quentin-dev** [comment]
The MessageBox sample in UICatalog seems to work fine on my machine too

**Comment by quentin-dev** [comment]
The bug seems to be linked to selecting a `MenuItem` by clicking on it, as I cannot quit the UICatalog program simply by clicking the `Quit` `MenuItem` in the `File` `MenuBarItem`

**Comment by BDisp** [comment]
I tested with Ubuntu 20.04 (WSL2) and Ubuntu on the virtual machine and they work well. Only in Ubuntu 20.04 (WSL2) pressing ctrl together with the mouse appears as alt and pressing alt or shift together with the mouse is not detected. However, on Ubuntu installed on the virtual machine it works very well. Are you not using the latest version of the repository?

**Comment by quentin-dev** [comment]
It looks like I am, I'm using version 0.90.3 of `Terminal.Gui`

**Comment by quentin-dev** [comment]
On a possibly related note, running my program with `dotnet run` then quitting it with `ctrl+q`, and clicking the mouse once in my terminal leaves me with this
![2020-10-28-110341_1916x154_scrot](https://user-images.githubusercontent.com/20909347/97422010-81ed1680-190d-11eb-9772-9e008ecfaccc.png)

**Comment by BDisp** [comment]
> 
> 
> It looks like I am, I'm using version 0.90.3 of `Terminal.Gui`

Please try with the latest version and check if the same problem with the mouse still occurs when it is still inside the application.
This last problem that you reported actually exists because of `Net5.0` which is not properly restoring environment variables when exiting. With `netcoreapp3.1` this is no longer the case. There is a related issue here #931.

**Comment by quentin-dev** [comment]
Here is my `.csproj` file (after updating Terminal.Gui):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="1.0.0-pre.5" />
  </ItemGroup>

</Project>
```

but no behavior has changed

**Comment by BDisp** [comment]
Can you clone the gui.cs and add the `Terminal.Gu`i to your project? Here is the `Example.csproj`. Check if the terminal hangs after exit and clicking with the mouse causes prints sequence characters on the terminal.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NStack.Core" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Terminal.Gui\Terminal.Gui.csproj" />
  </ItemGroup>

</Project>

```

**Comment by quentin-dev** [comment]
Clicking the mouse still prints sequence characters on the terminal, and the screen is not fully cleared

**Comment by BDisp** [comment]
I will submit a PR that fix both issues but only work with `netcoreapp3.1` and not with `Net5.0`.
