### ISSUE TITLE
MessageBox & Dialog UI Scenarios are broken

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#979]
A recent change (perhaps #661 ?) broke UI Catalog's MessageBoxes and Dialogs scenarios.

![image](https://user-images.githubusercontent.com/585482/97316763-598aec80-1827-11eb-8ea5-5a74935ec023.png)

![image](https://user-images.githubusercontent.com/585482/97316800-627bbe00-1827-11eb-9ec2-79d44d8e42d8.png)

I don't have time to debug this morning, but it appears to be where setting `frame. Height` used to work:

```csharp
fame.Height = Dim.Height (widthEdit) + Dim.Height (heightEdit) + Dim.Height (titleEdit) + Dim.Height (messageEdit) 
				+ Dim.Height(numButtonsEdit) + Dim.Height (styleRadioGroup) + 2;
```

**Comment by tig** [comment]
@BDisp Can you please look at this? I think it is a regression caused by your recent changes to PosDim?

**Comment by BDisp** [comment]
Of course yes. It is a controlled regression that will require more care in creating new views.

**Comment by BDisp** [comment]
I could work around this problem by placing the frame `Height `into `Top.Ready` but the main problem is that `TextFormatter `is overwriting the dimension properties in the `public virtual ustring Text` of the `View `class, always considering `ustring.Empty` initially. I prefer to adapt the views to that detail than to get around. Working...

**Comment by BDisp** [comment]
@tig sometimes default constructors induce a very serious error. Test the following, please:

```
		[Fact]
		public void View_Rect__SetsValue ()
		{
			var view = new View ();
			Assert.True (view.Bounds.IsEmpty);

			view = new View () {
				X = 1,
				Y = 2,
				Width = 3,
				Height = 4
			};
			Assert.True (view.Frame.IsEmpty);
			Assert.True (view.Bounds.IsEmpty);

			view.LayoutSubviews ();

			Assert.False (view.Frame.IsEmpty);
			Assert.False (view.Bounds.IsEmpty);
		}

```
