### ISSUE TITLE
Menu does not seem to work in C# app in .Net 4.6.2. Escape-9 does not activate menu. Thoughts ?

### ISSUE THREAD

**Issue by richardschoen** [migueldeicaza/gui.cs#98]
Just tried your small samples from your blog site and the menu does not seem to work in C# app in .Net 4.6.2. Escape-9 does not activate menu either. I can tab through fields.

Is this supposed to work in standard .Net or Core only ?

You blog link: https://sirwan.info/archive/2018/05/02/Developing-Console-based-UI-in-C/

**Comment by migueldeicaza** [comment]
I clarified the use of ESC-9 as being a Unix-ism.
