### ISSUE TITLE
csproj issues?

### ISSUE THREAD

**Issue by damageboy** [migueldeicaza/gui.cs#99]
I'd like to contribute to gui.cs but have seeing some weird things which (I feel) need some explanation:

For example:

https://github.com/migueldeicaza/gui.cs/blob/829aae09c82f00942e944af67732a588e7ae224c/Terminal.Gui/Terminal.Gui.csproj#L54-L56

Except for looking really weird on public git project, this also looks completely superfluous as the whole thing builds without this reference?

Would you accept a PR on this?

**Comment by damageboy** [comment]
In addition there's an dangling `packages.config` inside Terminal.Gui which I assume no longer needs to be there?

**Comment by migueldeicaza** [comment]
Can you explain the problem?   I do not know how that ended up there, I am wondering what problem this causes, perhaps it is the reason on mac it fails by default without copying an additional file.

Packages.config - I dont know either how this got there honestly.   I just used a file new project and added nugets

**Comment by damageboy** [comment]
It's not a problem per-se, but when I edit the code with the Rider IDE (at least) it ends up automatically removing the weird references.
So I just wanted to preemptively remove them so they don't end up happening on their own on some other commit.

**Comment by tig** [comment]
This is ancient. closing. Please re-open if you still have this issue.
