### ISSUE TITLE
Moving the mouse after quitting an application causes text being typed into the terminal shell

### ISSUE THREAD

**Issue by ettolrach** [migueldeicaza/gui.cs#994]
Hello, I wanted to start using this toolkit and wrote out the example code provided in the [overview of the documentation](https://migueldeicaza.github.io/gui.cs/articles/overview.html). However, once quitting, for every mouse move, characters were typed into the terminal.

Terminal: zsh with [powerlevel10k](https://github.com/romkatv/powerlevel10k) on Arch Linux.
.NET: .NET Core 3.1.108

Steps to reproduce:
1. Create a new C# console program. (`mkdir testdir; cd testdir; dotnet new console`).
2. Edit `Program.cs` and create a simple program like the one below.
```csharp
using Terminal.Gui;
namespace gui_cs_test
{
    class Program
    {
        static void Main(string[] args)
        {
            Application.Init ();
            var n = MessageBox.Query (50, 7, "Question", "Do you like console apps?", "Yes", "No");
        }
    }
}
```
3. Run the application using `dotnet build; dotnet run`.
4. Quit the application (by either pressing Ctrl+Q or by clicking the yes or no buttons).
5. Move the mouse around the terminal.

You should see characters being entered into the terminal.

If necessary I can provide a video demonstrating what this looks like on my end.

**Comment by BDisp** [comment]
On `Linux `you have to call the `Application.Shutdown ()` to restore the Terminal. Otherwise it will trigger all the mouse keystrokes. Normally you will need to call `Application.Run` on a real application too.
