### ISSUE TITLE
Question: TextChanged Action

### ISSUE THREAD

**Issue by SemperFu** [migueldeicaza/gui.cs#998]
Good evening,

I am working on a console with this gui to edit configuration. I am having a really hard time controlling the TextField. In WPF this is really easy for me. I can filter and interact with the main sender and handle the event as well.

 ```
  private void TextboxTest_PreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            TextBox OS = (TextBox)sender;
            if (OS.Text.Length > 4) // Don't allow more than 4 digits
            {
                e.Handled = true;
                return;
            }
            e.Handled = Regex.IsMatch(e.Text, "[^0-9]+"); //Match Digits only
        }
```

On gui.cs I am using an action

```
Label LabelSSHPort = new Label(17, 1, "port: ");
            TextField TextFieldSSHPort = new TextField(24, 1, 5, MainConfig.LoginServersSSH.Qstr("port"));
            TextFieldSSHPort.TextChanged += UpdateSSHPort;

      private static void UpdateSSHPort(ustring e)
        {
            string PortString = e.ToString();
            string result = Regex.Replace(PortString, @"[^\d]", "");
           //Snipped
            if (Int32.TryParse(result, out ParsedPort))
            {
                MainConfig.LoginServersSSH["port"] = ParsedPort;
            }
        }

```

The first issue with the action is it isn't returning the changed text. It sends me the text of the field before the change has been processed. In this case I have a port number. Its port is 8889. If I type anything, The text changed will show me 8889 and not include what I just typed. So I don't know how to process and filter what has changed.

Also since the action is just the text, even if it was including the changed text. It doesn't include the sender like the events. My variables for the menus are not global so I don't have an easy way to access them in my function.

**Comment by BDisp** [comment]
It was decided to use only the `Action `event instead of the `EventHandler `event in this repo, because the `sender `object is rarely used and, if necessary, it is easily done. I will propose two ways to solve it depending on whether the edited `TextField `is focused or not.

If it's focused you can use this method:
```

			Label LabelSSHPort1 = new Label (17, 1, "port1: ");
			TextField TextFieldSSHPort1 = new TextField (24, 1, 5, "");
			TextFieldSSHPort1.TextChanged += UpdateSSHPort;
			
			Label LabelSSHPort2 = new Label (17, 2, "port2: ");
			TextField TextFieldSSHPort2 = new TextField (24, 2, 5, "");
			TextFieldSSHPort2.TextChanged += UpdateSSHPort;

		private static void UpdateSSHPort (ustring e)
		{
			TextField OS = (TextField)Application.Top.MostFocused;
			if (OS.Text.Length > 4 || Regex.IsMatch (OS.Text.ToString (), "[^0-9]+"))	// Don't allow more than 4 digits and
			{                                                                               //Match Digits only
				var cp = OS.CursorPosition;
				OS.Text = e;
				OS.CursorPosition = Math.Min (cp, OS.Text.RuneCount);
			}
		}

```			
If it isn't focused you can use this method:
```

			Label LabelSSHPort3 = new Label (17, 4, "port1: ");
			TextField TextFieldSSHPort3 = new TextField (24, 4, 5, "");
			TextFieldSSHPort3.TextChanged += (e) => HandleUpdateSSHPort2 (TextFieldSSHPort3, e);
			
			Label LabelSSHPort4 = new Label (17, 5, "port2: ");
			TextField TextFieldSSHPort4 = new TextField (24, 5, 5, "");
			TextFieldSSHPort4.TextChanged += (e) => HandleUpdateSSHPort2 (TextFieldSSHPort4, e);
			
		private static void HandleUpdateSSHPort2 (TextField OS, ustring e)
		{
			if (OS.Text.Length > 4 || Regex.IsMatch (OS.Text.ToString (), "[^0-9]+"))       // Don't allow more than 4 digits and
			{                                                                               //Match Digits only
				var cp = OS.CursorPosition;
				OS.Text = e;
				OS.CursorPosition = Math.Min (cp, OS.Text.RuneCount);
			}
		}

```

**Comment by SemperFu** [comment]
Thank you for the quick response, I didn't know you could pass the sender that easily. That worked great!

 I do think it would be nice to have a pre-changed event you could cancel the actual update as this calls the changed event a second time but this should let me get everything taken care of.  Thank you very much.

**Comment by BDisp** [comment]
Yes, you are right. It must have a `TextChanging `event with the option to cancel the update and avoiding recursive call. I'll do that soon.
